### ISSUE TITLE
skaffold fails to sync with helm

### ISSUE THREAD

**Issue by cflynn07** [GoogleContainerTools/skaffold#1691] opened 2019-02-23 05:21 UTC
### Expected behavior
static files sync to container without a rebuild when updated on disk

### Actual behavior
skaffold fails to sync files, prints warn log

### Information

- Skaffold version: v0.23.0
- Operating system: macOS 10.14 (18A391)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: cflynnus/blog
    context: .
    sync:
      '**/*.html': "/root"
      '**/*.md': "/root"
      '**/*.css': "/root"
      '**/*.png': "/root"
deploy:
  helm:
    releases:
      - name: "blog"
        chartPath: "helm"
```

- error message from skaffold dev -v debug:
```
INFO[0309] files modified: [templates/home.html]
DEBU[0310] Checking base image golang:1.11.5-alpine3.8 for ONBUILD triggers.
DEBU[0310] Checking base image alpine:latest for ONBUILD triggers.
DEBU[0310] Found dependencies for dockerfile: [.]
DEBU[0310] Skipping excluded path: node_modules
DEBU[0310] Skipping excluded path: README.md
DEBU[0310] Skipping excluded path: kubernetes
Syncing 1 files for cflynnus/blog:392e972d392cdd136404b52ae4e31ce490cabace4ade88c485dc2debc8dc9b9b
INFO[0310] Copying files: map[templates/home.html:/root/templates/home.html] to cflynnus/blog:392e972d392cdd136404b52ae4e31ce490cabace4ade88c485dc2debc8dc9b9b
WARN[0310] Skipping deploy due to sync error: copying files: didn't sync any files
Watching for changes every 1s...
```

- complete repository with helm chart/templates and skaffold.yaml
https://github.com/cflynn07/myblog/tree/dc5115181f030e769ae192f9ecf6aecb8dcec8d2

### Steps to reproduce the behavior

1. `skaffold dev -v debug`
2. update static template file `/templates/home.html` with trivial change

**Comment by laander** [comment] 2019-02-26 19:37
Might be a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/1668 although reports in the other issue doesn't mention any errors (`Skipping deploy due to sync error: copying files: didn't sync any files`)

**Comment by cflynn07** [comment] 2019-02-27 20:13
I'm able to use skaffold in the project by using kubectl instead of helm for local development

**Comment by priyawadhwa** [comment] 2019-03-01 23:11
Hey @cflynn07 I just merged #1709 which may have solved this problem -- could you see if you still get this error with the lastest released version [v0.24.0](https://github.com/GoogleContainerTools/skaffold/releases/tag/v0.24.0)?

**Comment by cflynn07** [comment] 2019-03-05 09:42
Still seeing the issue.
- checked out the code in my repo at `dc5115181f030e769ae192f9ecf6aecb8dcec8d2`
- ran `skaffold dev -v debug`
- Made a trivial change to a file
- Observed the error in my logs:

```
Syncing 1 files for cflynnus/blog:f9311c81defed5ed89a3ff07461d24cfd69c9ca1d5d9c7fd1373ed61e4cb5a30
INFO[0034] Copying files: map[templates/home.html:/root/templates/home.html] to cflynnus/blog:f9311c81defed5ed89a3ff07461d24cfd69c9ca1d5d9c7fd1373ed61e4cb5a30
WARN[0034] Skipping deploy due to sync error: copying files: didn't sync any files
```

**Comment by cflynn07** [comment] 2019-03-05 09:47
Still seeing an issue
- checked out the code in my repo at `dc5115181f030e769ae192f9ecf6aecb8dcec8d2`
- ran `skaffold dev`
- Made a trivial change to a file
- skaffold dev exited with an error

```
skaffold dev
WARN[0000] config version (skaffold/v1beta3) out of date: upgrading to latest (skaffold/v1beta6)
Generating Tag for [cflynnus/blog]...
Starting build...
Found [docker-for-desktop] context, using local docker daemon.
Building [cflynnus/blog]...
Sending build context to Docker daemon  34.31MB
Step 1/8 : FROM golang:1.11.5-alpine3.8 as builder
 ---> a0d0176aa927
Step 2/8 : WORKDIR /go/src/app
 ---> Using cache
 ---> 81e84baa853b
Step 3/8 : COPY . .
 ---> Using cache
 ---> 6d4ccbab1eaa
Step 4/8 : RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
 ---> Using cache
 ---> 51a8d3efe70a
Step 5/8 : FROM alpine:latest
 ---> 3f53bb00af94
Step 6/8 : WORKDIR /root
 ---> Using cache
 ---> a3d5f0e9cf0a
Step 7/8 : COPY --from=builder /go/src/app/ .
 ---> Using cache
 ---> a6c626e4a0ce
Step 8/8 : CMD ["./main"]
 ---> Using cache
 ---> bc3b2a672b4a
Successfully built bc3b2a672b4a
Successfully tagged cflynnus/blog:dc51151
Build complete in 1.086752908s
Starting test...
Test complete in 5.319µs
Starting deploy...
Error: release: "blog" not found
Helm release blog not installed. Installing...
No requirements found in helm/charts.
NAME:   blog
LAST DEPLOYED: Tue Mar  5 17:46:44 2019
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1/Service
NAME       TYPE          CLUSTER-IP      EXTERNAL-IP  PORT(S)       AGE
blog--app  LoadBalancer  10.103.104.183  localhost    80:32303/TCP  0s

==> v1/Deployment
NAME       DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
blog--app  1        1        1           0          0s

==> v1beta1/Ingress
NAME          HOSTS                      ADDRESS  PORTS  AGE
test-ingress  cflynn.us,cflynn-blog.com  80, 443  0s

==> v1/Pod(related)
NAME                        READY  STATUS    RESTARTS  AGE
blog--app-75dcf6dbd4-crf2w  0/1    Init:0/1  0         0s


Deploy complete in 660.121915ms
Watching for changes every 1s...
Cleaning up...
release "blog" deleted
Cleanup complete in 178.160281ms
FATA[0018] calling final callback: sync: retrieving working dir for cflynnus/blog:bc3b2a672b4a98b942d35a3fc32c24a5d8dee423b1f9f75c2a33e3bdda2193c1: retrieving remote config: MANIFEST_UNKNOWN: "manifest unknown"
```

**Comment by dee-me-tree-or-love** [comment] 2019-03-06 10:27
Same issue when using `kubectl` for deployment. 
Running `skaffold v0.24.0` with `minikube version: v0.33.1` with `--vm-driver kvm2`.  

- ran `skaffold dev -v debug`
- made a trivial change
- getting same error as @cflynn07  

```
...
Successfully built e10d8cf74849
Successfully tagged gcr.io/k8s-skaffold/lotr-quotes:14733c7-dirty
Build complete in 401.08347ms
...
Deploy complete in 1.225985329s
Watching for changes every 1s...
...
[lotr-quotes-6dcc8b6dfc-2qxgv lotr-quotes] > lotr-quotes@1.0.0 start /usr/src/app
[lotr-quotes-6dcc8b6dfc-2qxgv lotr-quotes] > nodemon index.js
[lotr-quotes-6dcc8b6dfc-2qxgv lotr-quotes] 
[lotr-quotes-6dcc8b6dfc-2qxgv lotr-quotes] [nodemon] 1.18.10
[lotr-quotes-6dcc8b6dfc-2qxgv lotr-quotes] [nodemon] to restart at any time, enter `rs`
[lotr-quotes-6dcc8b6dfc-2qxgv lotr-quotes] [nodemon] watching: *.*
[lotr-quotes-6dcc8b6dfc-2qxgv lotr-quotes] [nodemon] starting `node index.js`
[lotr-quotes-6dcc8b6dfc-2qxgv lotr-quotes] "lotr_quotes" listening on port 8080!
...
INFO[0026] files modified: [lotr-quotes/index.js]       
DEBU[0027] Checking base image node:10-alpine for ONBUILD triggers. 
DEBU[0027] Found dependencies for dockerfile: [package-lock.json package.json .] 
DEBU[0027] Skipping excluded path: node_modules         
DEBU[0030] Terminating port-forward lotr-quotes-6dcc8b6dfc-2qxgv/lotr-quotes:8080 
Cleaning up...
...
DEBU[0030] Running command: [kubectl --context minikube delete --ignore-not-found=true -f -] 
service "lotr-quotes" deleted
deployment.apps "lotr-quotes" deleted
Cleanup complete in 690.755178ms
FATA[0031] calling final callback: sync: retrieving working dir for gcr.io/k8s-skaffold/lotr-quotes:e10d8cf74849706c1aa4ae979e5c60aac96cff324d9674128b212c86f4a6aedc: retrieving remote config: MANIFEST_UNKNOWN: "Failed to fetch \"e10d8cf74849706c1aa4ae979e5c60aac96cff324d9674128b212c86f4a6aedc\" from request \"/v2/k8s-skaffold/lotr-quotes/manifests/e10d8cf74849706c1aa4ae979e5c60aac96cff324d9674128b212c86f4a6aedc\"."
```
--- 

My `skaffold.yaml`: 
```
apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/lotr-quotes
    context: ./lotr-quotes/
    sync:
      '**/*.js': .

deploy:
  kubectl:
    manifests:
    - ./lotr-quotes/k8s/*
```
The `lotr-quotes` manifest: 
```
apiVersion: v1
kind: Service
metadata:
  name: lotr-quotes
  labels: 
    app: lotr-quotes
spec:
  type: NodePort
  selector:
    app: lotr-quotes
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotr-quotes
  labels: 
    app: lotr-quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lotr-quotes
  template:
    metadata:
      labels:
        app: lotr-quotes
    spec:
      containers:
      - name: lotr-quotes
        image: gcr.io/k8s-skaffold/lotr-quotes
        ports:
        - containerPort: 8080
```

**Comment by dee-me-tree-or-love** [comment] 2019-03-06 13:42
In fact in my case reverting to `v0.23.0` solves the problem...

**Comment by dee-me-tree-or-love** [comment] 2019-03-07 14:14
Most likely is related to https://github.com/GoogleContainerTools/skaffold/issues/1734 
And hopefully is transitively fixed :+1:

**Comment by nkubala** [comment] 2019-03-07 18:46
@dee-me-tree-or-love any chance you could try building from HEAD and seeing if your issue is fixed?

**Comment by davidbancor** [comment] 2019-03-08 11:07
Using the latest build from https://storage.googleapis.com/skaffold/builds/latest/skaffold-darwin-amd64 solved this issue for me 👍

**Closed** 2019-03-18 21:58 UTC
Labels: area/sync, good first issue, helm
