### ISSUE TITLE
`defaultNamespace` value is not put in the `SKAFFOLD_NAMESPACES` environment variable for deploy hook usage

### ISSUE THREAD

**Issue by dallasvaughan** [GoogleContainerTools/skaffold#7995] opened 2022-10-27 16:15 UTC
### Expected behavior
If the `skaffold.yaml` `deploy.kubectl.defaultNamespace` element is set, this value is put into the `SKAFFOLD_NAMESPACES` list of namespaces and resolves to this value when the `$SKAFFOLD_NAMESPACES` is referenced in a host pre- or post-deploy hook command and a namespace is not provided in the `skaffold` command.

### Actual behavior
If the `skaffold.yaml` `deploy.kubectl.defaultNamespace` element is set, this value is not put into the `SKAFFOLD_NAMESPACES` list of namespaces and resolves to an empty string when referenced in a host pre- or post-deploy hook command.

This variable is only set when a namespace is passed in via the CLI `--namespace` argument, though I believe the intent of `defaultNamespace` is to provide the deploy namespace when the CLI option argument is not explicitly provided. It seems to reason that in both cases this variable should represent whatever namespace(s) skaffold is configured to deploy to.

### Information

- Skaffold version: v2.0.0
- Operating system: macOS 12.5.1
- Installed via: skaffold.dev
- Contents of skaffold.yaml:
```yaml
# any valid config
deploy:
  kubectl:
    defaultNamespace: testNS
    hooks:
      before:
        - host:
            command: [ "sh", "-c", "echo $SKAFFOLD_NAMESPACES" ]
      after:
        - host:
           command: [ "sh", "-c", "echo $SKAFFOLD_NAMESPACES" ]
```
### Steps to reproduce the behavior 

1. `skaffold dev` on valid project with `defaultNamespace` set and with `$SKAFFOLD_NAMESPACES` referenced in host hook command(s)
2. Empty strings are printed in the output before and after k8s resources are deployed to `testNS` namespace.

**Comment by RB14** [comment] 2022-11-21 21:29
Hi,

In our projects we were relying on this configuration option to set a dynamic namespace that includes the name of the user who runs `skaffold`. We couldn't think on any other **nice** and **clean** solution that plays well with the rest of our configurations (i.e. K8s configurations), so we chose to use this nice option. For context, we are using the [Cloud Code](https://plugins.jetbrains.com/plugin/8079-cloud-code) IntelliJ plugin to run Skaffold, and passing the `SKAFFOLD_NAMESPACE` as an environment variable there does not support dynamic values. This seems to be an unintentional breaking change, and I humbly think it should have higher priority. Would appreciate if you can reconsider and prioritize this (currently it broke all our Skaffold-based deployments, so we had to manually downgrade the *Cloud Code* plugin version we use).

P.S. There is a bigger context here, I didn't go into too much details.

**Comment by aaron-prindle** [comment] 2022-11-21 21:43
@dallasvaughan @RB14  - thank you for flagging this and bringing this to our intention.  @RB14 sorry for the breaking changes that were made, this was an unintentional regression.  I have added this to our current milestone (`v2.1.0` - expected release date ~Dec 7th 2022).  I will update the thread here with any information on the cause here, general investigation and ongoing fix

**Comment by RB14** [comment] 2022-11-21 22:19
@aaron-prindle Thanks so much for your prompt response! Looking forward for the fix! Will keep myself updated, thanks!

**Comment by aaron-prindle** [comment] 2022-11-28 21:43
This should be fixed now @ HEAD.  If someone here can confirm this fix is working, that would be great.  This will be out in our next Skaffold released scheduled for ~12/7/2022

**Closed** 2022-11-28 21:42 UTC
Labels: kind/bug, priority/p1, area/hooks, area/env-vars, area/namespaces

**Comment by dallasvaughan** [comment] 2022-12-01 19:38
Thanks so much @aaron-prindle! FYI, a co-worker attempted to use [templating](https://skaffold.dev/docs/environment/templating/) of an environment variable in `deploy.kubectl.defaultNamespace` and found that while the following example was working in 2.0.1, it does not work with a HEAD build (`v2.0.2-31-g4b9badab3`). Not sure if this change is the cause but thought I'd let you know.

```yaml
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: ["sh", "-c", "./predeploy.sh"]
    defaultNamespace: 'test-{{.HOST}}'```

**Comment by aaron-prindle** [comment] 2022-12-01 20:07
Np, thanks for flagging this @dallasvaughan.  I've created https://github.com/GoogleContainerTools/skaffold/issues/8183 to track what was mentioned above.

**Comment by RB14** [comment] 2022-12-04 15:15
Hi,

I also tested it, and I confirm the problem reported above. Templating doesn't seem to work with other variables as well.. Specifically, the following configuration doesn't work:

```
deploy:
  kubectl:
    defaultNamespace: "{{.USER}}-test"
```

Results in:

```
the namespace from the provided object "{{.USER}}-test" does not match the namespace "myuser-test". You must pass '--namespace={{.USER}}-test' to perform this operation.
```

**Comment by renzodavid9** [comment] 2022-12-05 19:30
Thanks @RB14 for the example to reproduce this, let's continue the conversation in #8183 to centralize the information
