### ISSUE TITLE
Logs from `skaffold dev` before container in the ready state

### ISSUE THREAD

**Issue by levibostian** [GoogleContainerTools/skaffold#4911] opened 2020-10-14 15:27 UTC
### Expected behavior

When I run `skaffold dev`, I expect STDOUT and STDERR logs from my container to be displayed *before* my container is in the ready state. 

### Actual behavior

I build expressjs nodejs apps that I deploy to k8s. The way that my application is setup is...
1. I have my k8s readiness and liveness checks setup to send a HTTP request to my nodejs application. Expect a 200 back from the request. 
2. When my application is started up, it will run a series of assertion checks before my expressjs HTTP web server starts up. These assertions are for me as the developer to feel more confident my application will work at runtime. So, I try to connect to my remote database, I try to authenticate with AWS, those sort of tasks. I run all of these assertions and if they all pass I then start my web server. 

This means that my web server does not start unless the assertions pass. The k8s readiness will not succeed unless my webs server is started. 

This means that there is a chance that my application will never start when using `skaffold dev`. Skaffold may never receive a readiness check successfully and therefore will automatically delete my resources and stop development. 

I have logs setup in my application during these assertion checks when the server starts up. I need to view these logs when my app starts up and before my web server gets started so I can see if my assertions are working. 

Here is where my issue comes in. When I use `skaffold dev`, it appears to me that STDOUT and STDERR from my docker container is not displayed to the terminal *until my container is in the ready state*.

* Run `skaffold dev`. Wait for my docker image to be built and is deployed to minikube. I see this output:
```
Listing files to watch...
 - app-image
Generating tags...
 - app-image -> app-image:f5e6a4e-dirty
Checking cache...
 - app-image: Found Locally
Tags used in deployment:
 - app-image -> app-image:75e02dde060810c0f586fe33c81696a8c2b13147e80c7d2b14d2965643ef6b07
Starting deploy...
 - deployment.apps/app-deployment created
 - service/app-service created
 - poddisruptionbudget.policy/app-pdb created
 - configmap/app-configmap created
 - ingress.extensions/app-ingress created
WARN[0001] image [app-image] is not used by the deployment
 - secret/app-config created
 - secret/dotenv created
Waiting for deployments to stabilize...
```
Where `Waiting for deployments to stabilize...` will be there for 15 seconds or so until my assertions pass. I will see this message for many minutes if my assertions fail and therefore my web server never starts. The only way to see what is wrong is to open another terminal window, `kubectl get pods` and then `kubectl logs <pod name>` to view the STDERR and STDOUT logs myself. 

If my application gets to a readiness state, then skaffold will dump all of the containers STDOUT and STDERR to me at that point all at once:
```
Deployments stabilized in 19.456625997s
Port forwarding service/app-service in namespace default, remote port 80 -> address 127.0.0.1 port 5000
Press Ctrl+C to exit
Watching for changes...
[app] [nodemon] 2.0.5
[app] [nodemon] to restart at any time, enter `rs`
[app] [nodemon] watching path(s): *.*
[app] [nodemon] watching extensions: js,mjs,json
[app] [nodemon] starting `node --enable-source-maps dist/app_startup.js`
[app] VERBOSE: Starting up job queue manager - Extra: (none)
[app] VERBOSE: Done starting up job queue manager - Extra: (none)
[app] VERBOSE: ============== STARTING UP SERVER ============== - Extra: (none)
[app] VERBOSE: X------ PROJECTS - Extra: (none)
[app] VERBOSE: X------ PROJECTS SUCCESS - Extra: (none)
[app] VERBOSE:         Projects loaded: expressjsblanky - Extra: (none)
[app] VERBOSE: -X----- INITIALIZE DATABASE - Extra: (none)
[app] VERBOSE: Authenticating database connection. - Extra: (none)
[app] Executing (default): SELECT 1+1 AS result
[app] VERBOSE: Database connection is setup successful - Extra: (none)
[app] VERBOSE: -X----- INITIALIZE DATABASE SUCCESS - Extra: (none)
```

When I run `skaffold dev`, I expect to see these logs from my container to be displayed *before* my container is in the ready state so I can have an easier development experience checking my assertions. 

### Information

- Skaffold version: version `v1.15.0`
- Operating system: macos 10.15.7
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
    - image: app-image
      context: .
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          ENV: development
      sync:
        infer:
        - 'dist/**/*.js'
        - 'app/**/*.ts'
        - 'dist/**/*.map'
  local: 
    push: false
deploy:
  kustomize: 
    paths: ["."]
  kubectl: 
    manifests:
      - "k8s/*.yaml"

# As long as you pass `--port-forward` to `skaffold dev/debug`, this maps local port 5000 to the node application
portForward:
- resourceType: service
  resourceName: app-service
  port: 80
  localPort: 5000
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project: https://github.com/levibostian/ExpressjsBlanky/tree/skaffold
2. `npm install && npm run dev:setup`

**Comment by MarlonGamez** [comment] 2020-10-21 21:28
Hi @levibostian! Thanks for opening up this issue. I'm trying to reproduce this following the steps you provided, however, I seem to be running into issues running `npm run dev:setup`. Not sure if I'm missing something simple or not.
Here's my output from running the command:
```
❯ npm run dev:setup

> ExpressjsBlanky@0.1.0 dev:setup /Users/marlongamez/Projects/ExpressjsBlanky
> ./bin/dev_setup.sh

##################################################################
#            Dev setup starting up...This script does:           #
# 1. Starts up a Postgres database                               #
# 2. Starts up a Redis database                                  #
# 3. Builds your application in a Docker container and deploys   #
#    it to your local minikube Kubernetes cluster.               #
#                                                                #
#     If you want to better understand what this script does,    #
#         read the docs/DEV.md document in this project.         #
##################################################################
Note: Server will be available at localhost:5000 once it is up!
Full script output located at /tmp/app_dev.log. In case of an error, check out that file.
Do you want to clear the current dev databases?
1) Yes
2) No
#? 1
Clearing postgres database...
Clearing redis database...
Databases cleared.

Starting up Postgres database...
Creating Postgres schema through database migration...
Postgres up successfully

Starting up Redis database...
npm ERR! code ELIFECYCLE
npm ERR! errno 125
npm ERR! ExpressjsBlanky@0.1.0 dev:setup: `./bin/dev_setup.sh`
npm ERR! Exit status 125
npm ERR!
npm ERR! Failed at the ExpressjsBlanky@0.1.0 dev:setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marlongamez/.npm/_logs/2020-10-21T21_18_51_975Z-debug.log
```

When running `cat` on the log file, here's what I see:
```
❯ cat /Users/marlongamez/.npm/_logs/2020-10-21T21_18_51_975Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/marlongamez/.nvm/versions/node/v12.19.0/bin/node',
1 verbose cli   '/Users/marlongamez/.nvm/versions/node/v12.19.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev:setup'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'predev:setup', 'dev:setup', 'postdev:setup' ]
5 info lifecycle ExpressjsBlanky@0.1.0~predev:setup: ExpressjsBlanky@0.1.0
6 info lifecycle ExpressjsBlanky@0.1.0~dev:setup: ExpressjsBlanky@0.1.0
7 verbose lifecycle ExpressjsBlanky@0.1.0~dev:setup: unsafe-perm in lifecycle true
8 verbose lifecycle ExpressjsBlanky@0.1.0~dev:setup: PATH: /Users/marlongamez/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/marlongamez/Projects/ExpressjsBlanky/node_modules/.bin:/Users/marlongamez/.nvm/versions/node/v12.19.0/bin:/Users/marlongamez/mdproxy/bin:/Users/marlongamez/google-cloud-sdk 2/bin:/Users/marlongamez/.sdkman/candidates/java/current/bin:/Users/marlongamez/go/bin:/Users/marlongamez/apache-maven-3.6.3/bin:/Users/marlongamez/.sdkman/candidates/java/11.0.7-amzn/bin:/usr/local/git/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin
9 verbose lifecycle ExpressjsBlanky@0.1.0~dev:setup: CWD: /Users/marlongamez/Projects/ExpressjsBlanky
10 silly lifecycle ExpressjsBlanky@0.1.0~dev:setup: Args: [ '-c', './bin/dev_setup.sh' ]
11 silly lifecycle ExpressjsBlanky@0.1.0~dev:setup: Returned: code: 125  signal: null
12 info lifecycle ExpressjsBlanky@0.1.0~dev:setup: Failed to exec dev:setup script
13 verbose stack Error: ExpressjsBlanky@0.1.0 dev:setup: `./bin/dev_setup.sh`
13 verbose stack Exit status 125
13 verbose stack     at EventEmitter.<anonymous> (/Users/marlongamez/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/marlongamez/.nvm/versions/node/v12.19.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid ExpressjsBlanky@0.1.0
15 verbose cwd /Users/marlongamez/Projects/ExpressjsBlanky
16 verbose Darwin 19.6.0
17 verbose argv "/Users/marlongamez/.nvm/versions/node/v12.19.0/bin/node" "/Users/marlongamez/.nvm/versions/node/v12.19.0/bin/npm" "run" "dev:setup"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 125
22 error ExpressjsBlanky@0.1.0 dev:setup: `./bin/dev_setup.sh`
22 error Exit status 125
23 error Failed at the ExpressjsBlanky@0.1.0 dev:setup script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 125, true ]
```

**Comment by levibostian** [comment] 2020-10-21 21:57
Hey there, @MarlonGamez. Thanks for checking it out!

`npm run dev:setup` will get databases up and running and then begin skaffold dev. 

It looks like skaffold dev didn't execute. Once it begins to execute, you are where I need you to be. `cat /tmp/app_dev.log`. That's where the dev setup script performs STDOUT and STDERR output to.

**Comment by taisph** [comment] 2020-10-26 09:25
I'd also expect to see the log even if a deployment fails using `skaffold dev`. It would save me from doing the same `kubectl get pods`, `kubectl logs <pod name>` dance whenever that happens.

**Comment by tejal29** [comment] 2020-10-26 19:51
@taisph I see a of FR here
1. Skaffold should stream logs for pods "not ready" as there could be interesting things to look at. 

We are looking into this. The only reason, we don't have it right now is because the statuscheck output and log output get interleaved. 

and a bug. 
1. If a pod did fail readiness check, skaffold should show failed logs. I feel status check phase has logic in place to grab logs.  I will confirm this.

**Comment by tejal29** [comment] 2021-06-04 20:03
Skaffold status check phase now stream logs if available from a failed container. 
If status check passes, then logs will streamed for all containers since before the deploy time.

Closing this issue now as we wont be able to support the Feature request.

**Closed by tejal29** 2021-06-04 20:03 UTC
Labels: area/deploy, area/ui, deploy-health-check, kind/friction
