### ISSUE TITLE
Modify the skaffold v2 render prompt behavior 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#6373] opened 2021-08-06 12:58 UTC
Per offline discussion with @briandealwis , this is what we believe the appropriate behavior when prompting a message in render.
- if the hydration dir exists and is empty => no prompt
- if the hydration dir exists and there is content but no Kptfile => exit: this doesn't look right
- if the hydration dir exists and there is content and Kptfile => prompt to remove ?

**Comment by yuwenma** [comment] 2021-08-06 12:58
cc @briandealwis

**Comment by tejal29** [comment] 2022-10-07 16:47
Render prompt will not feasible in cloud deploy scenario as well as cloud code.  Closing this for now.

**Closed by tejal29** 2022-10-07 16:47 UTC
Labels: kind/feature-request, priority/p2, planning/H1-2022

**Comment by tejal29** [comment] 2022-10-07 16:48
closing this as dupe of #7608
