### ISSUE TITLE
Don't see installers for any of the releases done on 3/2/22 (e.g. 1.36.1)

### ISSUE THREAD

**Issue by todd-andrew-procore** [GoogleContainerTools/skaffold#7158] opened 2022-03-03 20:27 UTC
### Expected behavior

Should see installers here: https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.36.1

### Actual behavior

- No installers exist.
- Also, the windows release example reads `https://storage.googleapis.com/skaffold/releases/v1.36.1skaffold-windows-amd64.exe` (missing a slash after 1.36.1)

### Information

N/A

### Steps to reproduce the behavior

N/A

**Comment by tejal29** [comment] 2022-03-22 19:51
Dupe of #7165

**Closed by tejal29** 2022-03-22 19:51 UTC
