### ISSUE TITLE
Allow logs to be excluded from skaffold dev output (by regexp or by pod)

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#1991] opened 2019-04-19 03:22 UTC
Is it possible to not stream logs from some pods in the `skaffold dev` output? I have an HA PostgreSQL in the cluster (Stolon) and its pods are constantly writing stuff to the log. When skaffold merges everything and outputs it to the terminal, there is so much scrolling stuff that it becomes pretty much unusable. I would like to exclude some pods from `skaffold dev` merged log output, if possible.

**Comment by balopat** [comment] 2019-04-19 17:22
Hi, thank you for filing this! @corneliusweig has design proposal outstanding for better log handling #1911. I'd expect that to solve your issue.

**Comment by corneliusweig** [comment] 2019-04-19 18:03
Indeed this is exactly the problem that #1911 addresses

**Comment by tstromberg** [comment] 2020-04-30 15:53
Decreasing the priority, as no one is currently working on this feature. If someone is interested in making this happen, we would be welcome to review a PR adding support for it.

**Comment by nkubala** [comment] 2020-04-30 16:16
to consolidate the conversation, i'm closing this as a dupe of https://github.com/GoogleContainerTools/skaffold/issues/588

**Closed by nkubala** 2020-04-30 16:16 UTC
Labels: area/logging, kind/feature-request, priority/p3
