### ISSUE TITLE
Support for GitHub Package repository (does not support pull by digest)

### ISSUE THREAD

**Issue by WilliamB17** [GoogleContainerTools/skaffold#4218] opened 2020-05-18 23:41 UTC
I use [Github Package](https://github.com/features/packages) as registry for Docker.

In the documentation of Github, [here](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages), it says:

> Note: You must push your image using IMAGE_NAME:VERSION and not using IMAGE_NAME:SHA.

and in the Skaffold documentation, [here](https://skaffold.dev/docs/pipeline-stages/taggers/), it says:

> When images are pushed, their immutable digest is available. Skaffold then references images both by tag and digest. Something like image:tag@sha256:abacabac.... Using both the tag and the digest seems superfluous but it guarantees immutability and helps users quickly see which version of the image is used.

> Skaffold never references images just by their tags because those tags are mutable and can lead to cases where Kubernetes will use an outdated version of the image.

I understand Skaffold's point of view, I don't think Github will solve this problem for a little while. Before I change the registry Docker is there a way around the problem?

**Comment by dgageot** [comment] 2020-05-19 06:18
@WilliamB17 did you have an issue with Github Package? Skaffold does push using `IMAGE_NAME:VERSION`. When it references those images in the Kubernetes yaml files, it uses the `IMAGE_NAME:VERSION@SHA` form though. Which should be totally ok.

**Comment by WilliamB17** [comment] 2020-05-19 08:24
@dgageot Yes, in Github's documentation it says that you can't push and pull with `SHA`. The image is pushed on the Github registry, however in my cluster k8s I can't pull the image. I've tried this locally and I can't pull an image with a digest.

**Comment by dgageot** [comment] 2020-05-19 08:58
@WilliamB17 Could you share the logs that make you think this is the issue? I have the feeling that the problem might be different. See https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry to understand how Kubernetes pulls images from private registries.

**Comment by WilliamB17** [comment] 2020-05-19 15:08
For give an example I use [this](https://github.com/WilliamB17/kuard).
the Docker image is pushed [here](https://github.com/WilliamB17/kuard/packages).

<img width="1273" alt="Screenshot 2020-05-19 at 16 54 30" src="https://user-images.githubusercontent.com/17731120/82342876-6f7fc000-99f2-11ea-850a-9d2c4fdde64f.png">
<img width="1262" alt="Screenshot 2020-05-19 at 16 54 09" src="https://user-images.githubusercontent.com/17731120/82342897-760e3780-99f2-11ea-923e-193a5e059c99.png">

If I add myself the tag only in the deployment description and I use `kubectl apply -f k8s/k8s-dep.yaml`  my pod is pull properly in k8s cluster.

**Comment by lucacasonato** [comment] 2020-05-20 18:36
I can reproduce this. You can not pull from GitHub Package Registry using a the `...@sha256...` syntax.

**Comment by chanseokoh** [comment] 2020-05-20 19:15
Not being able to pull using a digest is the [current limitation of GitHub Packages](https://github.community/t5/GitHub-API-Development-and/Cannot-pull-docker-image-from-Github-Package-Registry-by-digest/m-p/33018#M3127) that is giving hard time to many people.

**Comment by dgageot** [comment] 2020-05-20 19:32
That seems so unreal that they don't support that. It's a core feature of
Docker

**Comment by tstromberg** [comment] 2020-06-01 20:50
With discussed this issue offline today, and agree with @chanseokoh 's observation: the inability for the GitHub Package repository to reference images by digest is breaking many applications. It's not up to Skaffold to workaround this restriction.

We've had some similar conversations with other users to improve Skaffold integrating with tag-based workflows, so it may be possible that we accidentally resolve this incompatibility in the future. We just aren't planning on addressing this specifically for GitHub at this time.

That said, I'd be willing to review any PR's that make Skaffold function in environments which discourage tagging.

**Comment by StarpTech** [comment] 2020-06-24 17:03
Is it so hard to prepare a PR which address this limitation behind a flag? I will try to do it. Any @tstromberg hints?

**Comment by tstromberg** [comment] 2020-07-13 20:57
@StarpTech - As far as I know, changing Skaffold to pull based on tag rather than digest is not going to be a trivial change. @dgageot likely has a more authoritative opinion.

According to https://github.community/t/cannot-pull-docker-image-from-github-package-registry-by-digest/14342/9 this shortcoming will be fixed shortly on the GitHub side.

**Comment by StarpTech** [comment] 2020-07-13 21:04
@tstromberg thanks for the review.

**Comment by dgageot** [comment] 2020-07-15 09:10
It would clearly not be easy!

**Comment by iMerica** [comment] 2020-08-01 17:20
Does anyone have a fork of Skaffold that doesn't pull by digest? I'm completely blocked by this.

**Comment by gsquared94** [comment] 2020-08-05 16:44
@iMerica unfortunately this is not a straight-forward fix and I doubt any of the maintainers have a fork that does this.

**Comment by fewkz** [comment] 2022-09-28 06:28
Looks like this is fixed, GitHub now supports pulling by digest

**Closed** 2022-10-10 14:46 UTC
Labels: help wanted, kind/feature-request, priority/p3
