### ISSUE TITLE
Check why statuscheck is not interruptible. 

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#4599] opened 2020-07-30 18:58 UTC
When implementing status check, for subsequent following dev iterations, if a file change occurs the previous context in which status check runs got canceled. 
I had verified this on the [prototype](https://github.com/tejal29/skaffold/blob/prototype/pkg/skaffold/runner/dev.go) branch 

The reason for this is, 
- status check shares the same context as current dev iteration context.
- when a change is triggered, we cancel the previous context which should cause status check to interrupt. 

Verify if we still do this.

**Comment by dgageot** [comment] 2020-07-31 10:43
Duplicate of #3908

**Closed by dgageot** 2020-07-31 10:43 UTC
Labels: area/status-check, july-chill, priority/p2
