### ISSUE TITLE
[v2] Support multi-module

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#6374] opened 2021-08-06 14:47 UTC

**Comment by yuwenma** [comment] 2021-08-06 14:47
cc @gsquared94

**Comment by nkubala** [comment] 2021-11-15 18:41
@yuwenma can you elaborate a little more on what needs to be done here? does the current implementation not support passing multiple skaffold pipelines?

**Comment by aaron-prindle** [comment] 2022-06-15 19:04
Closing as a dupe of #7540

**Closed by aaron-prindle** 2022-06-15 19:04 UTC
Labels: kind/feature-request, priority/p1, 2.0.0, planning/H1-2022
