### ISSUE TITLE
feature request: use different build image name

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#4444] opened 2020-07-06 09:06 UTC
Hi,

we use for kaniko in skaffold.yaml 
```yaml
build: 
artifacts: 
- image: <registry-push/imagename>
```

but in deployment.yaml
```yaml
containers:
      - name: containername
        image: registry/imagename
```
error in our case

```bash
getting image: GET https://registry-push.<domain>/v2/: unsupported status code 403; body: <html>
```

is it possible or would it make sense to support such approach?

kind regards
Marco

**Comment by briandealwis** [comment] 2020-07-07 02:04
The build-image is the link between the artifacts that are built and the k8s manifests.  Skaffold rewrites the image references to the tagged images before deploying the manifests.  If we don't use the build-image, we'd need some other way to link the uses of an image with its corresponding artifacts.

That said, we have some support for placing the image elsewhere, like `--default-repo`, and we plan to introduce another variant too #4321.

**Comment by MarcoSchaar** [comment] 2020-07-07 07:05
Thanks for reply.
another question ...
is there any other option to use "--destination" inside the kaniko pod instead of artifact image name?

**Comment by briandealwis** [comment] 2020-07-31 03:35
@MarcoSchaar the Kaniko `--destination` will be the artifact-image modulo the `--default-repo`.  

That said, wWe are looking to simplify the `--default-repo` experience and would appreciate any input you may have either on this issue here or on #4321.

**Comment by briandealwis** [comment] 2020-09-03 15:55
Closing as this is working as intended.

**Closed by briandealwis** 2020-09-03 15:55 UTC
Labels: kind/question
