### ISSUE TITLE
Unsigned Windows binary skaffold-windows-amd64.exe

### ISSUE THREAD

**Issue by scscgit** [GoogleContainerTools/skaffold#6580] opened 2021-09-09 12:26 UTC
### Expected behavior

Skaffold is an officially supported project of Google, so I'd assume that it intends to follow best practices and common sense from security standpoint, including signing the built binaries for Windows using a valid certificate, or even cooperating with Microsoft's SmartScreen process to ensure that users aren't forced to completely discard all their security practices. Alternatively there should be a well-documented reasoning behind why this isn't a correct approach, along with an alternative process that goes beyond just "trusting both GitHub's HTTPS and the [.sha256 file](https://github.com/GoogleContainerTools/skaffold/releases/download/v1.31.0/skaffold-windows-amd64.exe.sha256) being uploaded securely". We're supposed to auto-update software on regular basis, so a forward-looking security requires the option of not trusting any intermediaries.

### Actual behavior

Not only isn't the binary signed via any certificate ([StackOverflow](https://stackoverflow.com/q/252226)), it also lacks any additional metadata (making it difficult to consistently keep track of, validate, or otherwise automate the installation process or archive older installers - or binaries in general, as skaffold is incapable of installing itself to the PATH automatically for an unknown reason).

![image](https://user-images.githubusercontent.com/3118390/132682685-befb85dd-7510-402b-ac0e-2a694506449a.png)

Microsoft Defender SmartScreen also doesn't trust the build ([StackOverflow](https://stackoverflow.com/q/48946680)) (and doesn't this occur each time skaffold gets auto-updated?)

![image](https://user-images.githubusercontent.com/3118390/132679477-5b559d28-fa93-463d-8c6a-24d19a79a505.png)

Obviously, we cannot simply ignore the direct approach and use Chocolatey if it has open issues that haven't been fixed, as mentioned by https://skaffold.dev/docs/install/#chocolatey, and also because it isn't officially supported (if there is no way to assert that the downloaded binary is correct). This makes it very difficult to provide skaffold as an (automatically downloadable) dependency of our project, so we have no way to safely onboard new developers.

### Information

- Skaffold version: 1.31.0
- Operating system: Windows 10 Enterprise

Related issues: https://github.com/kubernetes/minikube/issues/4841

**Comment by briandealwis** [comment] 2021-10-01 20:58
Duplicate of #2154

**Closed by briandealwis** 2021-10-01 20:58 UTC
Labels: meta/release, priority/p2, platform/windows
