### ISSUE TITLE
sha256 tagpolicy uses `latest` as tag

### ISSUE THREAD

**Issue by tdickman** [GoogleContainerTools/skaffold#1884] opened 2019-03-27 16:19 UTC
### Expected behavior
Image is tagged with sha256 hash causing the deployment to create new pods when changes are made.

### Actual behavior
Image is tagged with `latest`, so new pods are not created when changes occur.

### Information

- Skaffold version: v0.25.0
- Operating system: ubuntu
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: localhost:32000/us.gcr.io/test-registry/name
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: name
        chartPath: infrastructure/kube
        namespace: name
        values:
          image: localhost:32000/us.gcr.io/test-registry/name
        imageStrategy:
          helm: {}
        valuesFiles:
          - infrastructure/kube/values.yaml
          - infrastructure/kube/values-lcl.yaml
```

### Steps to reproduce the behavior

1. Create a project that uses helm for k8s templates
2. Run `skaffold run`

**Comment by corneliusweig** [comment] 2019-03-27 21:39
While it is odd that the image is tagged as `latest`, there must be a misunderstanding about `skaffold run`.
The `run` command builds, tests, and deploys, then exits. There is no file watching. On the other hand, the `dev` command, watches for file changes and re-deploys. Can you try if this solves your problem?

**Comment by tdickman** [comment] 2019-03-27 21:55
Sorry if the OP was confusing. I tried using both the `dev` and `run` commands. The OP was specifically speaking about the workflow:

* Run `skaffold run`
* Make code changes
* Run `skaffold run` again

When I do this, the second `skaffold run` doesn't trigger new pods to be created since the deployment has the same docker tag (`latest`). Another user on slack mentioned running into the same issue and posted a workaround [here](https://kubernetes.slack.com/messages/CABQMSZA6/convo/CABQMSZA6-1553706952.095700/).

**Comment by corneliusweig** [comment] 2019-03-28 22:19
So I just tried this, but I cannot reproduce the bug. Unfortunately, the current helm examples are not very useful to try this out, but could you give #1891 a try?
Take the updated _helm-deployment_ example, do `skaffold run`, make some code changes to the static assets, and run `skaffold run` again. For me, the second `run` _does_ deploy updated containers. Can you confirm that?

Note: to check out this PR, do `git fetch origin pull/1891/head:helm-example; git checkout helm-example`.

**Comment by mdujmovits** [comment] 2019-04-12 12:32
You have to use the sha256 digest of the container like this, it's not a tag like 'latest', it's a docker feature:
```
values:
  image: '{{.IMAGE_NAME}}@sha256:{{.DIGEST_HEX}}'
```

**Comment by dgageot** [comment] 2019-06-21 13:18
Closing as a duplicate of #2290

**Closed by dgageot** 2019-06-21 13:18 UTC
Labels: area/tag, deploy/helm, kind/bug, tagger/sha256
