### ISSUE TITLE
Ambiguous warning :  "WARN[0064] image [gcr.io/wired-benefit-XXXXX/demoapp] is not used by the deployment"

### ISSUE THREAD

**Issue by DhruboB** [GoogleContainerTools/skaffold#4942] opened 2020-10-25 07:42 UTC
### Expected behavior
Stated warning should be NOT be displayed.
### Actual behavior

Every time I make a change and trigger a re-deployment, I get an error like:

> WARN[0064] image [gcr.io/wired-benefit-XXXXX/demoapp] is not used by the deployment

Yet the image is modified with the updated change, so I'm not sure what the error is indicating,

### Information

- Skaffold version: version... v1.15.0
- Operating system: ... MacOS Catilina 10.15.16
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: demoapp
build:
  artifacts:
  - image: gcr.io/wired-benefit-293406/demoapp
deploy:
  kubectl:
    manifests:
    - k8*.yml
```
Content of K8s manifests :

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
  name: demoapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: gcr.io/wired-benefit-293406/demoapp
        imagePullPolicy: IfNotPresent
        name: demoapp
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp
  name: demoapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: demoapp
  type: LoadBalancer
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demoapp
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demoapp
  targetCPUUtilizationPercentage: 80
```

### Steps to reproduce the behavior

1. a very basic starter demo app
2. `skaffold dev`
3. Any change ... docker build is successful by skaffold and even pushing to registry

But, changes are not being reflected. Could be tag related problem. When I manually set the image name to latest for the deployment, then app change works.

**Comment by tejal29** [comment] 2020-10-27 23:15
I can reproduce this on my end by using the k8 manifest you have. 
Looks like there is an issue where we replace Manifests for yaml containing multiple manifests. 

Reproduction Steps:
1. Replace the manifest in examples/getting-started/k8s-pods.yaml with the one in the bug. (use your own gcr project)

/cc @IsaacPD

**Comment by IsaacPD** [comment] 2020-11-03 19:17
@DhruboB Do you have a tag present in the image used in your K8s manifest? I was able to reproduce the behavior exactly as described by doing the following with one of the example projects.

1. cd examples/getting-started && skaffold render --output=k8s-pod.yaml
2. skaffold dev
-- Warning shows up
3. Make change to main.go
-- Re build/deploy happens but changes are not reflected

**Comment by DhruboB** [comment] 2020-11-04 05:22
No my K8s manifest does not have any tag/version present ... as given in the issue description.

Note, I do not have the issue anymore, when I use multiple k8s manifest files for each section i.e. deployment , service and hpa without using ---. You can also try once from your end to verify.

**Comment by IsaacPD** [comment] 2020-11-05 21:06
Turns out that I am unable to reproduce this in the way you described so it would be helpful if you could provide some more details on how you encountered this issue. Like what git tagger you used? or maybe could you try reproducing it again?

**Comment by briandealwis** [comment] 2020-12-16 20:52
I too am unable to reproduce this.

@DhruboB is it possible that you have some of your manifests in a file that isn't matched by `k8*.yml`?  Could you include the logs of running Skaffold with `-vdebug` and verify that the rendered manifests look as you expect?

**Comment by briandealwis** [comment] 2021-05-03 20:26
Closing since even @DhruboB can no longer reproduce.

**Closed by briandealwis** 2021-05-03 20:26 UTC
Labels: kind/bug, kind/question, priority/awaiting-more-evidence
