### ISSUE TITLE
Private Azure Container Registry: unauthorized: authentication required

### ISSUE THREAD

**Issue by renatodelgaudio** [GoogleContainerTools/skaffold#3479] opened 2020-01-07 16:58 UTC
Hi,
I am trying to use skaffold to showcase the typical developer experience by deploying the local change to a remote Kubernetes cluster and a private docker registry.
In this PoC, I am using Azure Contaner Registry and AKS.

Althought I run skaffold from a terminal session, after a successfull login to my private Azure Container Registry, skaffold cannot authenticate to the registry and hence it fails to push the image.

I can push docker image to my private registry from standalone command line but not within skaffold loop.

### Expected behavior
While running the developer loop, the container is built and pushed to remote private Azure Container Registry

### Actual behavior
Skaffold dev detects the changes and trigger the build of the new container but it fails while pushing it to Azure Container Registry due authentication issue

[rpc error: code = Unknown desc = Error response from daemon: manifest for csskaffold.azurecr.io/skaffold-example/skaffold-a:20427eea7498fabd666292085953aeaf1bfd15441db2e363cd997739e79e97a0 not found: manifest unknown: manifest unknown, rpc error: code = Unknown desc = Error response from daemon: Get https://csskaffold.azurecr.io/v2/skaffold-example/skaffold-a/manifests/20427eea7498fabd666292085953aeaf1bfd15441db2e363cd997739e79e97a0: unauthorized: authentication required]

### Information

- Skaffold version: version: v1.1.0
- Operating system: Windows 10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: csskaffold.azurecr.io/skaffold-example/skaffold-a
deploy:
  kubectl:
    manifests:
      - kubernetes/k8s-*
```

### Steps to reproduce the behavior

1. Clone the example repo: https://github.com/renatodelgaudio/skaffold-a
2. docker login to private Docker Registry from a command line
After successful docker login, my docker config file looks as follows:

~/.docker/config.json

```json
{
	"auths": {
		"csskaffold.azurecr.io": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.5 (windows)"
	},
	"credsStore": "desktop",
	"stackOrchestrator": "swarm"
}
```
3. skaffold dev

**Comment by balopat** [comment] 2020-01-14 23:59
Thank you @renatodelgaudio for opening! 
I don't have too much experience with Azure. 
We will have to sit down and reproduce this with Skaffold. 
In the meantime can you try to use `useDockerCLI: true` (see https://skaffold.dev/docs/pipeline-stages/builders/docker/)  if it works as a workaround?

**Comment by chulkilee** [comment] 2020-01-23 07:43
~/.docker/config.json is for docker CLI, not for docker daemon, I believe - so the default behavior (using docker engine api) cannot use it, unless skaffold reads the config and mimic the behavior of docker CLI (e.g. supporting different credsStore..)

**Comment by tstromberg** [comment] 2020-04-30 16:37
Has anyone figured out how to feed Azure credentials into skaffold?

**Comment by rudolphjacksonm** [comment] 2020-05-21 14:02
I'm running into the same issue on my end. I can push images to ACR fine oddly enough, and that's after logging in to the container registry using the Azure CLI:
```
az login
az acr login --name registry
```
What I can't do for some reason is pull images from ACR. Running Skaffold in debug mode doesn't tell me much more about why the credentials aren't working:
```
exiting dev mode because first build failed: couldn't build "xxx.azurecr.io/skaffold-project/skaffold-web-test": unable to stream build output: Get https://xxx.azurecr.io/v2/dependency-build/manifests/node14-1.0: unauthorized: authentication required
```

**Comment by chanseokoh** [comment] 2020-05-21 22:24
Can't reproduce. I'm using the latest `skaffold` and `az` on Linux. I logged in using `az`, and Docker CLI and Skaffold work as expected. Nothing special needed to make Skaffold work.
```
az login
az acr login --name francium25
```
However, unlike the original comment, I'm not using a credential helper (i.e., no `credHelpers` or `credsStore` in `~/docker/config.json`).
```
    "auths": {
        ...
        "francium25.azurecr.io": {
            "auth": " ... ",
            "identitytoken": " ... <ACR identity token> ..."
        },
```

I am deploying to OpenShift (CodeReady Containers) which pulls in images from ACR built and pushed by Skaffold. I tested both `Dockerfile` and the Jib builder. Rebuilding and pushing after detecting changes also work.

`skaffold.yaml`:
```yaml
apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: demo-springboot
build:
  artifacts:
  - image: francium25.azurecr.io/test
deploy:
  kubectl:
    manifests:
    - deployment.yaml
```

<details>
<summary><code>deployment.yaml</code> (click to expand)</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
    spec:
      containers:
      - image: francium25.azurecr.io/test
        name: test
        resources: {}
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: demo
  name: demo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  type: ClusterIP
status:
  loadBalancer: {}
```
</details>

<details>
<summary>logs (click to expand)</summary>

```
$ skaffold dev --port-forward                              
Listing files to watch...                                                                         
 - francium25.azurecr.io/test      
Generating tags...                 
 - francium25.azurecr.io/test -> francium25.azurecr.io/test:latest
Some taggers failed. Rerun with -vdebug for errors.
Checking cache...                  
 - francium25.azurecr.io/test: Not found. Building
Building [francium25.azurecr.io/test]...
Sending build context to Docker daemon  2.048kB                                                                                                                                                      
Step 1/2 : FROM francium25.azurecr.io/base
latest: Pulling from base                                                                                                                                                                            
24f0c933cbef: Already exists 
69e2f037cdb3: Already exists   
3e010093287c: Already exists 
54b6e68178ac: Pull complete            
541d10d17ef0: Pull complete                                                                                                                                                                          
ddf5d65a30f8: Pull complete          
1345dc7c0145: Pull complete           
Digest: sha256:5c0892cf0e62eb3fb2bf2e348bbcf3e19af2db7d33d4929e6c68d0a4d4322ac5                                                                                                                      
Status: Downloaded newer image for francium25.azurecr.io/base:latest
 ---> 4caeee7e6e84     
Step 2/2 : ENV FOO=foo       
 ---> Running in 00abcd0d2af5                                                                     
 ---> 46f5a68261ff                                                                                
Successfully built 46f5a68261ff                                                                   
Successfully tagged francium25.azurecr.io/test:latest                  
The push refers to repository [francium25.azurecr.io/test]            
e36580f00059: Layer already exists                                                                
2f149da86288: Layer already exists                                                                
f5cea98a3c91: Layer already exists 
7aeb35e851c4: Layer already exists                                                                                                                                                                   6189abe095d5: Layer already exists 
f47163e8de57: Layer already exists                                                                                                                                                                   
42a3027eaac1: Layer already exists                                                                                                                                                                   
latest: digest: sha256:0932a8703655401fcfb5a67837987e7a17cb193a7a38e5d2dd65f166c222a2b6 size: 1787                                                     
Tags used in deployment:                                                                                                                                                                             
 - francium25.azurecr.io/test -> francium25.azurecr.io/test:latest@sha256:0932a8703655401fcfb5a67837987e7a17cb193a7a38e5d2dd65f166c222a2b6                                      
Starting deploy...                                                                                                                                                                                   
 - deployment.apps/demo created                                                                                                                                                                      
 - service/demo created                                                                                                                                                                              
Waiting for deployments to stabilize...                                                                                                                                                              
 - chanseok:deployment/demo: waiting for rollout to finish: 0 of 1 updated replicas are available...
 - chanseok:deployment/demo is ready.
Deployments stabilized in 5.466025087s
Port forwarding service/demo in namespace chanseok, remote port 8080 -> address 127.0.0.1 port 8080
Press Ctrl+C to exit
Watching for changes...
[demo-69f9f75574-rgslz test] 
[demo-69f9f75574-rgslz test]   .   ____          _            __ _ _
[demo-69f9f75574-rgslz test]  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[demo-69f9f75574-rgslz test] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[demo-69f9f75574-rgslz test]  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[demo-69f9f75574-rgslz test]   '  |____| .__|_| |_|_| |_\__, | / / / /
[demo-69f9f75574-rgslz test]  =========|_|==============|___/=/_/_/_/
[demo-69f9f75574-rgslz test]  :: Spring Boot ::             (v2.3.0.M1)
[demo-69f9f75574-rgslz test] 
...
Generating tags...                                                                                                                                                                                   
 - francium25.azurecr.io/test -> francium25.azurecr.io/test:latest                                                                                                                                   
Some taggers failed. Rerun with -vdebug for errors.
Checking cache...
 - francium25.azurecr.io/test: Not found. Building
Building [francium25.azurecr.io/test]...
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM francium25.azurecr.io/base
 ---> 4caeee7e6e84
Step 2/3 : ENV FOO=foo
 ---> Using cache
 ---> 46f5a68261ff
Step 3/3 : ENV BAR=bar
 ---> Running in bd4b799e3311
 ---> bfbcd7e6dc13
Successfully built bfbcd7e6dc13
Successfully tagged francium25.azurecr.io/test:latest
The push refers to repository [francium25.azurecr.io/test]
e36580f00059: Layer already exists 
2f149da86288: Layer already exists 
f5cea98a3c91: Layer already exists 
7aeb35e851c4: Layer already exists 
6189abe095d5: Layer already exists 
f47163e8de57: Layer already exists 
42a3027eaac1: Layer already exists 
latest: digest: sha256:fe787426f4e3acd8d07959e1178899928db1e695ff639a9e5685a715d508cbf4 size: 1787 
Tags used in deployment:
 - francium25.azurecr.io/test -> francium25.azurecr.io/test:latest@sha256:fe787426f4e3acd8d07959e1178899928db1e695ff639a9e5685a715d508cbf4
Starting deploy...
 - deployment.apps/demo configured
Waiting for deployments to stabilize...
 - chanseok:deployment/demo: waiting for rollout to finish: 1 old replicas are pending termination...
 - chanseok:deployment/demo is ready.
Deployments stabilized in 4.119519666s
Watching for changes...
Port forwarding service/demo in namespace chanseok, remote port 8080 -> address 127.0.0.1 port 8080
[demo-6d744d7688-b2c2n test] 
[demo-6d744d7688-b2c2n test]   .   ____          _            __ _ _
[demo-6d744d7688-b2c2n test]  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[demo-6d744d7688-b2c2n test] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[demo-6d744d7688-b2c2n test]  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[demo-6d744d7688-b2c2n test]   '  |____| .__|_| |_|_| |_\__, | / / / /
[demo-6d744d7688-b2c2n test]  =========|_|==============|___/=/_/_/_/
[demo-6d744d7688-b2c2n test]  :: Spring Boot ::             (v2.3.0.M1)
[demo-6d744d7688-b2c2n test] 
```
</details>

**Comment by rudolphjacksonm** [comment] 2020-05-22 07:33
Oddly enough the issue disappeared on my end. I'm still getting an error regarding gcloud creds at the beginning of the pipeline, but otherwise this seems to be behaving 🤷

**Comment by nkubala** [comment] 2020-06-15 20:57
I'm going to close this since it sounds like the issue may have disappeared, and we weren't able to repro it on our end. if anyone is still encountering this with newer versions of skaffold please feel free and reopen.

**Closed by nkubala** 2020-06-15 20:57 UTC
Labels: area/auth, area/private-registry, build/docker, kind/bug, needs-reproduction, platform/azure, priority/awaiting-more-evidence

**Comment by zubinchopra** [comment] 2020-07-08 00:38
This resolved the error for me

[https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration#configure-acr-integration-for-existing-aks-clusters](https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration#configure-acr-integration-for-existing-aks-clusters)

**Comment by scheung38** [comment] 2022-06-30 21:44
Still getting this from Skaffold to AKS after successful az acr login:

![Screenshot 2022-06-30 at 22 42 16](https://user-images.githubusercontent.com/1273014/176783841-497dc624-4622-44d0-8991-530e87025e6d.png)

![Screenshot 2022-06-30 at 22 44 00](https://user-images.githubusercontent.com/1273014/176784056-55b9147e-5647-45ba-902a-c37e4e603629.png)
![Screenshot 2022-06-30 at 22 44 25](https://user-images.githubusercontent.com/1273014/176784113-a6904a6e-cfc7-4b5b-a9a0-341c45b00972.png)

kompose version                                         
1.26.0 (40646f47)

**Comment by goonerify** [comment] 2022-08-16 22:57
I was able to pull images from ACR by doing the following

1. [Authenticate to my private ACR](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-docker-cli?tabs=azure-cli#log-in-to-a-registry)
2. [Create a service principal](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes#create-a-service-principal)
3. [Login to docker using the service principal username & password](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-service-principal#use-with-docker-login)
4. [Create an image pull secret](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes#create-an-image-pull-secret)
5. [Use the image pull secret](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes#use-the-image-pull-secret)

Finally, ensure that your images are properly tagged with existing tags in your registry
