### ISSUE TITLE
support skaffold init for helm apps.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#3768] opened 2020-03-02 23:28 UTC
This is a tracking issues to support `skaffold init` for helm apps.

Add a flag like `skaffold init --helm`. Try to parse the helm charts, and
1. Suggest the correct key for `image` value used in helm templates deployment.yaml. 
   e.g. in the skaffold helm example, the image key is `Values.image` [0](https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold-helm/templates/deployment.yaml#L24)
   This should be set in skaffold.yaml
```

apiVersion: skaffold/v2alpha4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: skaffold-helm
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: skaffold-helm
      values:
        image: skaffold-helm
```

2. Retry cleaning using `--no-hooks` if `helm delete failed` for charts with hooks.
3. For all hooks, identify the artifacts and create a corresponding entry in `skaffold.build` config.
    - changes to hooks code should also re-install the chart by listing source code in hooks as source dependency. (not sure how to wire that up)

**Comment by as3445** [comment] 2020-05-08 14:53
Is there a temporary workaround for this until the feature is built out? I'd love to try skaffold!

**Comment by nkubala** [comment] 2020-05-08 17:26
@as3445 this feature would theoretically generate a skaffold.yaml based on your helm project configuration. but you can always write the skaffold.yaml yourself :) in fact, based on some of the experimentation I've done, this is actually a much harder problem than it seems on the surface, so I'd recommend taking a stab at setting up skaffold with your project! I put together a small guide on how to set up helm projects with skaffold: https://skaffold.dev/docs/pipeline-stages/deployers/helm/

**Comment by as3445** [comment] 2020-05-08 17:35
@nkubala cool! I did come across that page, and the requirement of needing to update the underlying charts would be too much of an overhead for the project I am currently working on unfortunately. :( Would be nice if it could hook into an existing namespace/charts and handle things from there. I can appreciate the difficulty of doing that though!

**Comment by nkubala** [comment] 2020-05-08 17:41
ah I'm sorry to hear that :( we recognize that this is definitely a limitation of using skaffold with helm. can I ask why it's too much overhead for you? do you have a lot of charts? or are they too big? just trying to understand use cases!

**Comment by as3445** [comment] 2020-05-08 18:00
It is indeed an overhead that there are a lot of charts. More importantly these charts are used by a build process to create new environments constantly, so having to change the template file poses a certain level of risk come time to merge these changes.

**Comment by tstromberg** [comment] 2020-05-11 22:11
Is this a dupe of https://github.com/GoogleContainerTools/skaffold/issues/1726 ?

**Comment by nkubala** [comment] 2020-07-06 22:49
after investigating what would go into supporting this, at the moment it doesn't look like it's technically feasible in a way that would provide any value given the current support for helm applications in skaffold. i'm going to close it for now, but we can revisit if we ever make big changes to the way we configure and deploy helm apps.

**Closed by nkubala** 2020-07-06 22:49 UTC
Labels: area/init, dogfood/helm, kind/feature-request, priority/p1
