### ISSUE TITLE
Images are not loaded into k3d cluster

### ISSUE THREAD

**Issue by mattupstate** [GoogleContainerTools/skaffold#8024] opened 2022-11-02 15:48 UTC
### Expected behavior

Images are loaded into local k3d cluster when using helm manifests and `skaffold [dev|run|deploy]`

### Actual behavior

Skaffold incorrectly reports images as being loaded into k3d cluster when using helm manifests and  `skaffold [dev|run|deploy]`

### Information

- Skaffold version: v2.0.1
- Operating system: macOS 12.6.1
- Installed via: Homebrew
- Local Cluster: Rancher Desktop + k3d
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v3
kind: Config
metadata:
  name: noteable
build:
  artifacts:
    - image: <REDACTED>
      context: ../<REDACTED>
      docker:
        dockerfile: Dockerfile
    - image: <REDACTED>
      context: ../<REDACTED>
      docker:
        dockerfile: Dockerfile
  local:
    useDockerCLI: true
    useBuildkit: true
    concurrency: 3
manifests:
  helm:
    releases:
      - name: <REDACTED>
        chartPath: ../<REDACTED>/helm
      - name: <REDACTED>
        chartPath: ../<REDACTED>/helm
deploy:
  helm: {}
```

### Steps to reproduce the behavior

1. `skaffold run`

Logs:

![image](https://user-images.githubusercontent.com/166176/199535938-528c3c64-1d06-4ccc-9990-40821b668857.png)

Notice the `Images loaded in 42ns` line. If it's not obvious, that's far too quick and indicates something is being skipped over. Otherwise, you'll have to take my word for the fact that images aren't found in the cluster when pods that use the image(s) are created.

**Comment by ericzzzzzzz** [comment] 2022-11-02 17:53
may be the same cause as #7992

**Comment by aaron-prindle** [comment] 2022-11-07 18:53
Thanks for bringing this to our attention, I believe this is a dupe of #7992 (same root issue causing kind and k3d regression here).  Follow along there for more information.  This should be fixed now @ HEAD via https://github.com/GoogleContainerTools/skaffold/pull/8007.  Our next release will have this fix

**Closed by aaron-prindle** 2022-11-07 18:53 UTC
Labels: area/build, priority/p1, platform/k3d, area/local
