### ISSUE TITLE
Docker registries with different local path than remote.

### ISSUE THREAD

**Issue by glennpratt** [GoogleContainerTools/skaffold#5721] opened 2021-04-23 22:01 UTC
### Expected behavior

I can use microk8s local registry within a multipass VM where it's address is localhost but on my host OS the the address is the IP of the VM.

### Actual behavior

Pods have ErrImagePull

### Information

- Skaffold version: v1.22.0
- Operating system: macOS
- Installed via: Homebrew
- Contents of skaffold.yaml:

https://github.com/GoogleContainerTools/skaffold/blob/master/examples/getting-started/skaffold.yaml

### Steps to reproduce the behavior

- Install microk8s in a multipass VM.
- Enable microk8s local registry.
- `multipass list` to get VM IP address
- `skaffold config set default-repo 192.168.64.2:32000`
- `skaffold config set insecure-registries 192.168.64.2:32000`
- Review pod: `ErrImagePull`

### Workarounds

- `kubectl port-forward -n container-registry svc/registry 32000:5000`
    - (portForwards in skaffold.yaml does not appear to work)

**Comment by glennpratt** [comment] 2021-04-23 22:08
If portForwards were active during the build phase, that would be fine.

**Comment by briandealwis** [comment] 2021-04-24 01:24
Duplicate of #3461

The port-forwards won't work because the underlying pods aren't starting.

**Closed by briandealwis** 2021-04-24 01:24 UTC

**Comment by glennpratt** [comment] 2021-04-24 05:35
@briandealwis a port forward to the registry service already running does work, that's my current work around. I gather that's probably not what the skaffold  feature was intended for.

**Comment by glennpratt** [comment] 2021-04-24 05:37
Also, thanks for linking the dupe, I searched and didn't see it.

**Comment by briandealwis** [comment] 2021-04-24 15:28
Oh I misunderstood!  Your port-forward is a nice workaround so that the host:port registry portion matches up  👍
