### ISSUE TITLE
Feature Request: expanded glob support for sync

### ISSUE THREAD

**Issue by bryanlarsen** [GoogleContainerTools/skaffold#1222] opened 2018-10-30 14:05 UTC
AFAICT, the cool new sync feature uses path/filepath#Glob for it's globbing.    That function is very limited: no support for matching the separator (aka recursive matching), no support for 0 or 1 matches, et cetera.   Would it be possible to use a more featureful globbing package?

**Comment by r2d4** [comment] 2018-10-30 16:14
The sync feature should respect the same exact syntax as the Dockerfile I think.

We already parse the dockerfile COPY and ADD glob patterns in https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/docker/parse.go#L213-L257

I'm pretty sure applying that code to the sync patterns should work.

Somewhere along the lines util.ExpandPathsGlob was used there, but we should have one central glob matcher (for kubectl manifest list, sync list, and Dockerfile COPY/ADD parsing)

**Comment by r2d4** [comment] 2018-10-30 16:14
That would give us https://docs.docker.com/engine/reference/builder/#copy style matching.

**Comment by bryanlarsen** [comment] 2018-10-30 16:29
According to your linked docs, that's also only filepath.Match.   I've currently got ten subdirectories in my source directory, so to synchronize both .ts & .tsx from those 10 and the root I'd need 22 rules, afaict.  https://github.com/GoogleContainerTools/skaffold/issues/1161 is limiting my testing of that.    That's not a huge deal, but if anybody creates a new directory and forgets to add that to skaffold.yaml, they might be confused for a while...

**Comment by pehlert** [comment] 2018-11-11 16:07
This might be a slightly different approach to it, but I think it's the only feasible approach for deeply nested projects. What do you think? https://github.com/GoogleContainerTools/skaffold/pull/1266

**Comment by balopat** [comment] 2018-11-13 23:33
> The sync feature should respect the same exact syntax as the Dockerfile I think.
@r2d4 can you elaborate why is this?

**Comment by priyawadhwa** [comment] 2018-11-27 23:07
Fixed by #1266

**Closed by priyawadhwa** 2018-11-27 23:07 UTC
Labels: area/sync, feature-request

**Comment by jsdevtom** [comment] 2019-04-29 15:44
@radityasurya

> so it is not possible to pass multiple patterns?

I believe the cause of this is this function: https://github.com/GoogleContainerTools/skaffold/blob/0bd43a4dc36da9f2cc34dc6f31f714dcc76c6b19/pkg/skaffold/sync/sync.go#L178-L189

Notice how it returns only one `tripleStarPattern`. @priyawadhwa Shouldn't it be possible to determine multiple `tripleStartPattern`s? Like this:

```
build:
  local:
    push: false
  artifacts:
    - image: image_name
      context: .
      docker:
        dockerfile: ./client/Dockerfile.dev
      sync:
        '***/*.ts': .
        '***/*.scss': .
        '***/*.html': .
```

**Comment by jsdevtom** [comment] 2019-04-29 16:05
For anyone else strugling with this issue, this work around (syncing all the things) works for me:
```
      sync:
        '***/*': .
```

**Comment by priyawadhwa** [comment] 2019-04-29 18:00
Hey @jsdevtom I wasn't able to reproduce this bug, could you provide the repo you're using, or a sample repo? For me, multiple triple star patterns are working as expected, and from the code it looks like multiple triple star patterns can be added to the map.

**Comment by jsdevtom** [comment] 2019-04-30 10:15
@priyawadhwa This is definitely reproducible on a project I am working on (but am not willing to share). But when I try it with the [react-reload example project](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/react-reload), I am unable to reproduce, I will see if I can narrow the problem down on the project I am working on.

**Comment by jsdevtom** [comment] 2019-04-30 10:17
please feel free to close until I am able to reproduce
