### ISSUE TITLE
Skaffold not able to parse image name from git commit when commit is numeric.

### ISSUE THREAD

**Issue by thejasn** [GoogleContainerTools/skaffold#1992] opened 2019-04-19 06:13 UTC
### Expected behavior

Should parse git commit (8202758) as string and not as a numeric constant.

### Actual behavior

Failed to apply default image tag "docker08.helpchat.in:5000/nuclei-billpayment-forward:8.202758e+06": couldn't parse image reference "docker08.helpchat.in:5000/nuclei-billpayment-forward:8.202758e+06": invalid reference format

### Information

- Skaffold version: version: v0.23.0
- Operating system: macOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
  - image: <image-name>
    context: <some-context>
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
deploy:
  kubectl:
    manifests:
      - k8s-*
profiles:
- name: dev
  build:
    tagPolicy:
      gitCommit: {}
  deploy:
    helm:
      releases:
      - name: <image-name>
        chartPath: <chart-path>
        imageStrategy:
          helm: {}
        version: "dev"
        valuesFiles:
          - <some-files>
          - <some-files>
        values:
          image: <image-name>

```

### Steps to reproduce the behavior

1. Make sure your git commit hash has only numbers.
2. skaffold deploy

**Comment by dgageot** [comment] 2019-04-23 07:44
@thejasn I'm not sure I understand how to reproduce this issue. I have a few questions for you:
 + Is the profile needed to reproduce?
 + Where does `VERSION` come from? Is it an env variable? What's its value?

**Comment by nkubala** [comment] 2019-04-24 22:51
@thejasn `docker08.helpchat.in:5000/nuclei-billpayment-forward:8.202758e+06` is getting rejected because `8.202758e+06` is not a valid docker image tag (`+` is an illegal character). this tag is likely not being generated by skaffold, it looks like something you're passing in to the `{{.VERSION}}` field in your env template. can you double check this?

**Comment by thejasn** [comment] 2019-04-26 18:23
@nkubala The `VERSION` comes from the git commit hash, as mentioned in the tag policy. So once in a while whenever the entire commit hash is only numerical it gets converted to the scientific notation and this introduces the `+` character.

**Comment by tejal29** [comment] 2019-04-30 22:49
interesting, skaffold uses the following command:
```
git rev-list -1 HEAD
```

Can you print the output of this command ?

**Comment by dgageot** [comment] 2019-06-20 07:28
I'm going to close this issue since it can't be reproduced. @thejasn if you are still facing this issue, it would be useful to have the smallest possible `skaffold.yaml` that shows the bug. Right now, the config contains two profiles so we don't know if it's the git tagger or the env tagger that's used. For what it's worth, the git tagger doesn't seem to have the bug and the env tagger was completely rewritten since `v1beta5`.

**Comment by santigarcor** [comment] 2019-07-24 15:50
@dgageot I can confirm it, i'm having the same issue, the problem si related with helm, because https://github.com/helm/helm/issues/1707 if you pass `--set tag=20161216` it will convert it to scientific notation, it's better to use `--set-string`

**Closed** 2019-12-18 15:37 UTC
Labels: area/tag, kind/bug, needs-reproduction, priority/p2
