### ISSUE TITLE
Use container-runtime info from minikube node for image loading strategy

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3711] opened 2020-02-20 18:49 UTC
`kubectl describe node` contains the Container Runtime Version: 
```
  Container Runtime Version:  docker://18.9.7
```

We should use this info to determine whether to build a docker image directly against the internal docker daemon determined by docker-env or by using `minikube cache add` (similar to `kind load`)

**Comment by dgageot** [comment] 2020-07-01 12:39
@balopat @tstromberg could you tell us how `minikube cache add` would be required or better?

**Comment by tejal29** [comment] 2021-07-01 20:10
dupe of #5773

**Closed by tejal29** 2021-07-01 20:10 UTC
Labels: area/deploy, kind/feature-request, platform/minikube, priority/awaiting-more-evidence
