### ISSUE TITLE
sync to compeleted job fails, terminating the rest of the sync

### ISSUE THREAD

**Issue by MarkBennett** [GoogleContainerTools/skaffold#2360] opened 2019-06-27 03:23 UTC
### Expected behavior

Given I've got a few pods running in my cluster and using the same build (such as Rails webserver, worker, and rspec job), then when I make a change to synced file skaffold to restart the job rather than try to sync files to a completed/terminated pod. Alternatively, as a less ideal outcome skaffold could ignore the completed job and not do anything.

### Actual behavior

Currently, if I make a change to a synced file then skaffold will try to sync it to all pods using the build, including jobs which have completed. When trying to exec into a completed pod this error is generated:

```
WARN[2020] Skipping deploy due to sync error: copying files: Running [kubectl exec dev-run-specs-kfqfs --namespace default -c run-specs -i -- tar xmf - -C / --no-same-owner]: stdout , stderr: error: canno
t exec into a container in a completed pod; current phase is Succeeded
, err: exit status 1: exit status 1
```

### Information

- Skaffold version: v0.31.0
- Operating system: Mac OS 10.14.5
- Cluster: Minikube v1.1.1
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image:  gcr.io/litdistco-pro/litdistco-rails
      docker:
        cacheFrom:
          - gcr.io/litdistco-pro/litdistco-rails 
  googleCloudBuild:
    projectId: litdistco-pro
deploy:
  kustomize:
    path: k8s/overlays/production
profiles:
  - name: dev
    build:
      artifacts:
      - image:  gcr.io/litdistco-pro/litdistco-rails
        docker:
          target: developer
        sync:
          manual:
            - src: 'app/**'
              dest: /project
      local: {}
    deploy:
      kustomize:
        path: k8s/overlays/development
    activation:
      - command: dev
  - name: staging
    build:
      artifacts:
      - image:  gcr.io/litdistco-pro/litdistco-rails
        docker:
          target: developer
      local: {}
    deploy:
      kustomize:
        path: k8s/overlays/staging
```

### Steps to reproduce the behavior

1. Create `skaffold.yaml` which uses `build.artificats.sync` and deploys to both a pod and a job.
2. Start development with `skaffold dev`
3. Change a synced file.
4. `skaffold dev` fails to sync changed files to pods as running `exec` in the terminated job seems to abort the entire sync.

Note, I realize I'm running the previous version of `skaffold` but I've got a multistage build and can't build on v0.32.0 until #2340 is merged into the latest version.

**Comment by seblegall** [comment] 2019-06-28 05:29
@MarkBennett I'm not sure to understand the expected behavior.

```
when I make a change to synced file skaffold to restart the job rather than try to sync files to a completed/terminated pod.
```
Do you mean : 
apply the change to the files in the container (sync) and then restart the worker (pod) ?
or just restart the worker (pod) ?

**Comment by MarkBennett** [comment] 2019-06-28 16:41
@seblegall I think I'd want sync to update running pods without restarting, however in the case of finished jobs it should update the image and then restart them.

**Comment by seblegall** [comment] 2019-07-04 05:39
Hello again @MarkBennett .

I've looked for a way to deal with jobs/workers container and I have a few questions.

From what I understand of your issue, you are using the same artifact / container in different deployments/pod? Where each is running a different command?

There is 2 things we could do : 

1. Check the status of the pod and skip pods which are in a non-running state in order to avoid sync troubles.
2. Force the artifact rebuild if at least one of the pods running the container is in a non-running state.

I feel option 1 is a better approach. When working on a job, a worker or a command I feel it's more natural to make updates on the code and then run `skaffold run` because, anyway, you will need to restart the job and wait of it to complete to check if your changes are working as expected.

But Option 2 has an advantage : it covers the case of application that have crashed. It also means in your case, the artifact will always be rebuilt as soon as your job is complete.

**Comment by MarkBennett** [comment] 2019-07-04 12:41
Bonjour @seblegall!

My sense is that option 1, skipping pods in a non-running state, is the best option for now. It maintains the existing behaviour with respect to crashed pods so users would know what to expect but also ensures that the sync failing for one pod won't impact the success of the sync for another.

Merci! :)

**Comment by dgageot** [comment] 2019-07-05 13:03
Fixed with https://github.com/GoogleContainerTools/skaffold/pull/2403

**Closed by dgageot** 2019-07-05 13:03 UTC
Labels: area/sync, help wanted, kind/bug
