### ISSUE TITLE
Feature: Support custom deploy scripts

### ISSUE THREAD

**Issue by mattcopas** [GoogleContainerTools/skaffold#5030] opened 2020-11-16 11:08 UTC
It would be quite useful to allow "custom" deploy scripts (instead of limiting to kubectl/helm/kustomize)

My use case:

I want to use Skaffold for a [Knative](https://knative.dev/) setup.

Currently I have to work out the yaml for whatever Knative component I want to use - that works but is slightly cumbersome.

It would be nicer to allow custom deploy scripts (similar to custom build scripts), so I could do something like:

`kn service delete ... && kn service create ...`

This'd be useful for other mechanisms too (Kubeless, for example) that have their own CLI for abstracting away deployment of services.

**Comment by MarlonGamez** [comment] 2020-11-16 18:34
Hi @mattcopas, thanks for opening this issue :) It looks like this is a dupe of #2277, so I'm going to close this in favor of it.
Please feel free to share your use case in comments of that issue, or reopen this issue if you feel that there is enough of a difference in the request to justify it being on its own

**Closed by MarlonGamez** 2020-11-16 18:34 UTC
