### ISSUE TITLE
x509: certificate signed by unknown authority when using Jib (MacOS)

### ISSUE THREAD

**Issue by slowr** [GoogleContainerTools/skaffold#3116] opened 2019-10-23 08:31 UTC
Most of the issues that talked about this error was using kaniko, so I decided to make a separate one for Jib.

While the certificate is loaded on Java (for Jib) and OS's CA I still get x509 certificate error after Jib build. Seems that the error comes when skaffold tries to pull the image from the registry after jib has successfully pull, build and push the image.

```
Containerizing application to xxx/dev/yyy...
Base image 'xxx/dev/tomcat:7.0.96-jdk8-adoptopenjdk-hotspot' does not use a specific image digest - build may not be reproducible
Retrieving registry credentials for xxx...
Getting manifest for base image xxx/dev/tomcat:7.0.96-jdk8-adoptopenjdk-hotspot...
Building dependencies layer...
Building resources layer...
Building classes layer...
Building extra files layer...
The base image requires auth. Trying again for xxx/dev/tomcat:7.0.96-jdk8-adoptopenjdk-hotspot...
Retrieving registry credentials for xxx...
Using base image with digest: sha256:8a83f6b072f390810ee7b28b55ab781cabacb583dbf6ee523a648ae1c066b399

Container entrypoint set to [/bin/bash] (inherited from base image)

Built and pushed image as xxx/dev/yyy

BUILD SUCCESSFUL in 9s
```

I already tried some workarounds that I saw on different issues with no luck like creating my own .cert, .pem, .key and providing them with `DOCKER_TLS`, `DOCKER_CERT_PATH` and `DOCKER_HOST` but had no luck.

### Expected behavior
Use the certificate from operating system's certificate authority and pull the image.

### Actual behavior
Getting x509 error when at `build artifact` step. Logs do not provide much information about the failing buid. This is right after the successful build with debug verbosity.

```
FATA[0036] failed to build: build failed: build failed: building [xxx/dev/yyy]: build artifact: getting image: Get https://xxx/v2/: x509: certificate signed by unknown authority
```

### Information

- Skaffold version: v0.40.0
- Operating system: MacOS Sierra
- Docker: Non installed
- Registry: Harbor
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta16
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: xxx/dev/yyy
      jib:
        project: yyy
        args:
          - --no-scan
deploy:
  helm:
    releases:
      - name: release
        chartPath: helm-chart
        values:
          apps.yyy.image: xxx/dev/yyy
        valuesFiles:
          - values-dev.yaml
```

### Steps to reproduce the behavior

1. Have a registry with self-signed certificate 
2. Load it to Java and OS's CA and build with Jib normally
3. Try to pull/push with HTTPS on skaffold

**Comment by chanseokoh** [comment] 2019-10-23 12:36
I think this is it: https://github.com/GoogleContainerTools/skaffold/issues/1961

It is recently fixed. I am not sure if Skaffold made a release after the fix, but you can try the bleeding edge binary as mentioned in that issue.

**Comment by slowr** [comment] 2019-10-23 13:18
This issue seems to be more `kaniko` oriented. 

I tried with the bleeding edge binary with providing the certificates
```
DOCKER_HOST=tcp://xxx:443 DOCKER_CERT_PATH=~/.docker DOCKER_TLS=1 skaffold run
```
and without and did not have any success. Insecure registries will not work in my case as HTTPS is forced and `SkipTLS` is only an option in `kaniko` builder.

**Comment by slowr** [comment] 2019-10-23 14:24
Seems that the issue is limited to MacOS since I got it working correctly on CentOS 7:
1. Copy cert to `/etc/pki/ca-trust/source/anchors/`
2. Run update-ca-trust
3. Import certificate on Java with `keytool -importcert -file $PEM_PATH -keystore $JAVA_HOME/lib/security/cacerts -alias "sscert" -storepass changeit`

Anyway to debug further the MacOS installation?

**Comment by chanseokoh** [comment] 2019-10-23 16:48
Ah, sorry. I thought your registry is insecure and jumped to the conclusion too early by just looking at the issue title. I see Skaffold should verify the server in this case.

**Comment by balchua** [comment] 2019-10-24 12:57
@slowr what if you create an environment variable `SSL_CERT_FILE=<your ca cert>` then try again.

**Comment by slowr** [comment] 2019-10-24 15:40
> @slowr what if you create an environment variable `SSL_CERT_FILE=<your ca cert>` then try again.

Unfortunately it doesn't seem to work

**Comment by balchua** [comment] 2019-10-24 21:38
@slowr thats a bummer.  This symptom is very similar to what I've been seeing with kaniko builder.  The image is successfully pushed to the registry and yet towards the end skaffold fails.
What im doing now is ignoring this error.  So i do 2 command instead of 1.

```
skaffold build
skaffold deploy
```

**Comment by balopat** [comment] 2019-10-24 23:05
@slowr As a workaround - can you try if `--cache-artifacts=false` helps with the post-failure - I think that is code path that is trying to get the remote config from the registry and fails...

**Comment by slowr** [comment] 2019-10-25 09:13
> @slowr thats a bummer. This symptom is very similar to what I've been seeing with kaniko builder. The image is successfully pushed to the registry and yet towards the end skaffold fails.
> What im doing now is ignoring this error. So i do 2 command instead of 1.
> 
> ```
> skaffold build
> skaffold deploy
> ```

The problem with this approach is that you loose the tag. Do you have this issue on MacOS as well or different OS? Because for me it seems that MacOS (Sierra) is the only setup I have issues with (tried with Centos and Ubuntu successfully).

> @slowr As a workaround - can you try if `--cache-artifacts=false` helps with the post-failure - I think that is code path that is trying to get the remote config from the registry and fails...

Same error, maybe it doesn't load the MacOS keychain correctly?

**Comment by balchua** [comment] 2019-10-25 10:16
@slowr i have this issue on a rhel. I dont have a mac to test with.   With regards to the tag, i use the tagger envTemplate.

**Comment by whodevil** [comment] 2020-02-14 21:56
any updates on this? I'm still having this issue

**Comment by jason155392** [comment] 2020-02-20 06:56
I fixed this issue followed by 
https://docs.docker.com/ee/dtr/user/access-dtr/

Windows
In your browser navigate to https://<dtr-url>/ca to download the TLS certificate used by DTR. Open Windows Explorer, right-click the file you’ve downloaded, and choose Install certificate.

Then, select the following options:

Store location: local machine
Check place all certificates in the following store
Click Browser, and select Trusted Root Certificate Authorities
Click Finish

**Comment by tstromberg** [comment] 2020-04-15 17:01
Is this a dupe of #3039 ?

**Comment by chanseokoh** [comment] 2020-04-15 17:44
I don't think it is a dupe. #3039 is when Docker CLI accesses a repository whereas I *think* this issue is when Skaffold accesses a repository. However, [this comment](https://github.com/GoogleContainerTools/skaffold/issues/3039#issuecomment-608546305) in #3039 seems to touch both Docker CLI and Skaffold.

**Comment by chanseokoh** [comment] 2020-04-15 17:45
Oh, and this issue may apply only to MacOS: https://github.com/GoogleContainerTools/skaffold/issues/3116#issuecomment-545469321

**Comment by briandealwis** [comment] 2020-04-24 19:18
Docker has the following page to add certificates for Docker for Mac:

https://docs.docker.com/docker-for-mac/#add-tls-certificates

Could you please retry with this approach?

**Comment by tstromberg** [comment] 2020-05-20 17:24
Has anyone seen this recently? 

I can't determine if this is a bug -- in that Skaffold doesn't read certificates from Jib -- or a documentation issue, where we need to provide clearer docs as to how to plumb custom certificates into Skaffold.

**Comment by dsb012** [comment] 2020-06-01 16:46
Yes, I am still seeing this. This is using Jib in Ubuntu. My base image is successfully pulled by Jib from my private repo as I've added it's cert to cacerts. The skaffold built image is built and pushed successfully.  The Maven build is successful but is then followed by a fatal error from skaffold:
FATA[0016] failed to build: build failed: building [.........]: build artifact: getting image: Get "https://........": x509: certificate signed by unknown authority

**Comment by dsb012** [comment] 2020-06-03 14:22
Disregard my comment above setting SSL_CERT_FILE addresses this.

**Comment by nkubala** [comment] 2021-03-19 19:09
seems like setting the `SSL_CERT_FILE` variable provides a workaround for this, so i'll close due to inactivity.

**Closed by nkubala** 2021-03-19 19:09 UTC
Labels: build/jib, kind/documentation, needs-actionable-error, priority/p3
