### ISSUE TITLE
Could not get docker context

### ISSUE THREAD

**Issue by userbradley** [GoogleContainerTools/skaffold#9121] opened 2023-10-08 23:09 UTC
When using skaffold to render and deploy helm charts, and docker is not installed, when running `skaffold -p dev deploy` I get the below error

```
➜ skaffold -p dev deploy
WARN[0000] Could not get docker context: starting command docker context inspect --format {{.Endpoints.docker.Host}}: exec: "docker": executable file not found in $PATH, falling back to the default docker host  subtask=-1 task=DevLoop
Starting deploy...
Error: UPGRADE FAILED: error while running post render on files: error while running command /opt/homebrew/bin/skaffold. error output:
time="2023-10-08T23:59:24+01:00" level=warning msg="Could not get docker context: starting command docker context inspect --format {{.Endpoints.docker.Host}}: exec: \"docker\": executable file not found in $PATH, falling back to the default docker host" subtask=-1 task=DevLoop
missing Resource metadata
: exit status 1
deploying "data-portal": install: exit status 1

```

### Expected behavior

Skaffold continues as usual and doesnt care that docker isnt installed

### Actual behavior

Skaffold throws a fit

### Information

- Skaffold version: v2.8.0
- Operating system: `Darwin l 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64
`
- Installed via: Homebrew 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: redacted
profiles:
  - name: dev
    deploy:
      kubeContext: prd
      helm:
        releases:
          - name: redacted
            namespace: redacted-dev
           # remoteChart: redacted/redacted
            chartPath: ../../helm-charts/redacted/chart
            version: 0.3.0
            upgradeOnChange: true
            setValues:
              redacted:
                mountGcs: false
                image:
                  tag: dev
              env: dev
            setValueTemplates:
              redacted:
                config:
                  auth:
                    clientSecret: "{{.AZURE_CLIENT_SECRET}}"
  - name: test
    deploy:
      kubeContext: prd
      helm:
        releases:
          - name: redacted
            namespace: redacted-test
            remoteChart: redacted/redacted
            version: 0.3.0
            upgradeOnChange: true
            setValues:
              redacted:
                mountGcs: false
                image:
                  tag: dev
              env: dev
            setValueTemplates:
              redacted:
                config:
                  auth:
                    clientSecret: "{{.AZURE_CLIENT_SECRET}}"
  - name: prd
    deploy:
      kubeContext: prd
      helm:
        releases:
          - name: redacted
            namespace: redacted-prd
            remoteChart: redacted/redacted
            version: 0.3.0
            upgradeOnChange: true
            setValues:
              redacted:
                mountGcs: false
                image:
                  tag: 9d0e698
              env: dev
            setValueTemplates:
              redacted:
                config:
                  auth:
                    clientSecret: "{{.AZURE_CLIENT_SECRET}}"

```

### Steps to reproduce the behavior

1. Install podman
2. Install skaffold version 2.8
3. Run skaffold -p dev deploy

**Comment by userbradley** [comment] 2023-10-08 23:11
Not to be _that guy_ but this is blocking stuff my end, so let me know what you want and I am happy to provide

**Comment by renzodavid9** [comment] 2023-10-11 19:59
Hey @userbradley, thanks for opening this issue. I haven't been able to reproduce the issue from my end, is it possible for you to attach a reproducible project/repo? Also, if you try running the command with the `-v DEBUG` flag we might find more information about what's happening, it will be `skaffold -p dev deploy -v DEBUG`. Thanks!

**Comment by userbradley** [comment] 2023-10-11 20:08
Hey @renzodavid9 i can't reproduce it my side either.

I do still get the weird docker context issue 

> WARN[0000] Could not get docker context:

I am on a Mac with Podman

**Comment by renzodavid9** [comment] 2023-10-11 20:37
Yeap, it is a Warning message, it shouldn't be reporting an error, is more to inform something important is happening, in this case is Skaffold doing a fallback for a value due to there is no docker installation.

So, from your previous comment, does that mean that you were able to make your config work?

**Comment by userbradley** [comment] 2023-10-11 20:39
Correct it's working now.

Is there anyway I can prevent that warning? There's nothing in the config that uses local docker?

---

This issue can be closed as the original issue was resolved my side

**Comment by renzodavid9** [comment] 2023-10-12 20:50
Hey @userbradley, looks like we don't have a config in place to help us prevent the warning message/validation, the option I can think of is maybe playing with the [log levels](https://github.com/sirupsen/logrus#level-logging), something like `skaffold deploy -p dev -v error`, but this might hide some other messages that can be helpful for you.

Cool! I'm going to close this issue then, if you find the same problem again please feel free to re open it or open another issue. Thanks!

**Closed by renzodavid9** 2023-10-12 20:50 UTC
Labels: needs-reproduction
