### ISSUE TITLE
Notify trigger does not detect changes until file is closed

### ISSUE THREAD

**Issue by petr-buchin** [GoogleContainerTools/skaffold#3429] opened 2019-12-23 10:59 UTC
### Expected behavior
I watch some directory with Skaffold manual sync rule and `notify` trigger.
I expect Skaffold to detect file changes as they being changed and changes were written to disk.
### Actual behavior
Skaffold does not detect any file changes until file is closed.
### Information

- Skaffold version: master
- Operating system: MacOs Catalina
- Contents of skaffold.yaml:
**not relevant here, just any manual sync rule.**

### Steps to reproduce the behavior

1. Configure manual sync rule to watch files in some dir.
2. Run `skaffold dev`
3. Open file using any programming language. I will use python for this example:

```python
f = open('my-watched-dir/somefile', 'a')
f.write('anything')
f.flush() # Ensure that changes were actually written to disk, not buffered
```
4. Check Skaffold output - you will not see any file changes.
5. Close file:

```python
f.close()
```
6. Check Skaffold output - file change is detected.

Note also, that I've tried to change file mtime before closing the file, and still changes are not detected until file is closed.

**Comment by petr-buchin** [comment] 2020-01-05 22:29
Could I get some answer for this please?
I'd be happy to make a PR and fix that behavior, but I would like to get some information about where to start.
Thanks in advance!

**Comment by nkubala** [comment] 2020-01-08 19:05
hey @petr-buchin, thanks for the issue.

using skaffold version 1.1.0 on Debian 5.2.17, I ran `skaffold dev` on the `getting-started` example in the repo. then I opened a python interpreter and ran the following commands, based on the example you provided:

```python
f = open('main.go', 'a')
f.write('foo.bar')
f.flush()
```
with no `f.close()`. I then saw skaffold retrigger the build, as expected:

```
[getting-started] Hello world!
Generating tags...
 - gcr.io/k8s-skaffold/skaffold-example -> gcr.io/nkubala-demo/gcr.io/k8s-skaffold/skaffold-example:v1.1.0-65-g19a4dec1b-dirty
Checking cache...
 - gcr.io/k8s-skaffold/skaffold-example: Not found. Building
Building [gcr.io/k8s-skaffold/skaffold-example]...
Sending build context to Docker daemon  3.072kB
Step 1/6 : FROM golang:1.12.9-alpine3.10 as builder
 ---> e0d646523991
Step 2/6 : COPY main.go .
 ---> efca48fc776f
Step 3/6 : RUN go build -o /app main.go
 ---> Running in 1cabb8aa8ab3
# command-line-arguments
./main.go:15:1: syntax error: non-declaration statement outside function body
WARN[0058] Skipping deploy due to error: build failed: build failed: building [gcr.io/k8s-skaffold/skaffold-example]: build artifact: unable to stream build output: The command '/bin/sh -c go build -o /app main.go' returned a non-zero code: 2 
```

so I'm unable to reproduce the behavior you're seeing on Linux. 

**HOWEVER**, doing the same thing on OS X, I do have to issue a `f.close()` to get skaffold to see the changes. so this issue is specific to OS X.

we're using ['fsnotify'](https://github.com/fsnotify/fsnotify) to handle the watching of file changes, none of this is actually handled by skaffold directly. I don't know that there's anything we can do to address this in skaffold, so you'll probably want to take this up on their repo. I'll close this issue for now.

**Closed by nkubala** 2020-01-08 19:05 UTC
