### ISSUE TITLE
skaffold deploy does not honour --default-repo flag

### ISSUE THREAD

**Issue by dan-j** [GoogleContainerTools/skaffold#5341] opened 2021-02-03 16:35 UTC
### Expected behavior

I've upgraded to v1.19, I'm not 100% which version from and running into the following issue:

```
skaffold deploy -p profile --default-repo eu.gcr.io/my-registry --images my-image:v1.0.0
```

I expect the image to be deployed be `eu.gcr.io/my-registry/my-image:v1.0.0`

### Actual behavior

The image deployed is `my-image:v1.0.0`

### Information

I've verified this working as expected on v1.17.0, but not sure which exact release it was last functioning.

- Skaffold version: v1.19.0
- Operating system: tested on both MacOS and Ubuntu

### Steps to reproduce the behavior

Will attach a link to a repo asap, sorry!

**Comment by dan-j** [comment] 2021-02-03 16:36
I've never contributed to this project before but love it. If somebody can point me in the right direction I don't mind looking at fixing it

**Comment by gsquared94** [comment] 2021-02-11 20:19
Thanks for opening this issue. This seems to be a case where our documentation doesn't match the behavior so I'll take that as a bug. The `--images` flag is setting [this](https://github.com/GoogleContainerTools/skaffold/blob/d956d4465c2eacf6a75e85f964363d1533ecff30/cmd/skaffold/app/cmd/deploy.go#L33) variable. If you navigate to its usage it's being merged with the list of skaffold built artifacts [here](https://github.com/GoogleContainerTools/skaffold/blob/d956d4465c2eacf6a75e85f964363d1533ecff30/cmd/skaffold/app/cmd/util.go#L29). You can apply the transformation [`ApplyDefaultRepo`](https://github.com/GoogleContainerTools/skaffold/blob/d956d4465c2eacf6a75e85f964363d1533ecff30/pkg/skaffold/deploy/util/util.go#L27) here prior to this merge to fix this issue.

**Comment by gsquared94** [comment] 2021-02-11 20:23
I misdiagnosed this issue. Adding `needs-reproduction` back

**Comment by dan-j** [comment] 2021-02-13 20:53
https://github.com/dan-j/skaffold-issue-5341

**Closed** 2021-03-10 02:38 UTC
Labels: area/default-repo, kind/bug, priority/p2
