### ISSUE TITLE
Go app buildpack failure: can't load package

### ISSUE THREAD

**Issue by etanshaul** [GoogleContainerTools/skaffold#4180] opened 2020-05-14 14:30 UTC
Not sure if I'm misconfiguring buildpacks here..

skaffold `1.9.1`

Using the Go Cloud Code hello-world sample: https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/master/golang/go-hello-world

skaffold.yaml (identical to the sample, with extra buildpack config):
```
apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: .
    image: go-hello-world
    buildpack:
      builder: "gcr.io/buildpacks/builder"
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/**
```

Running `skaffold dev` or `skaffold debug`
-> Build failure

`Failure: can't load package: package hello-world: unknown import path "hello-world": cannot find module providing package hello-world`

```
Building [go-hello-world]...
latest: Pulling from buildpacks/builder
Digest: sha256:99b3920db578ebdb80fa664702eee78fff6ad2e2aa37b219a301ab73b314b5ba
Status: Image is up to date for gcr.io/buildpacks/builder:latest
latest: Pulling from buildpacks/gcp/run
Digest: sha256:4e049217d386a4ffea60e0055df10a5e3bcff1300437400eca3c614e05f38052
Status: Image is up to date for gcr.io/buildpacks/gcp/run:latest
===> DETECTING
[detector] 2 of 5 buildpacks participating
[detector] google.go.runtime 0.9.0
[detector] google.go.build   0.9.0
===> ANALYZING
===> RESTORING
===> BUILDING
[builder] === Go - Runtime (google.go.runtime@0.9.0) ===
[builder] Using runtime version from go.mod: 1.12
[builder] Installing Go v1.12
[builder] === Go - Build (google.go.build@0.9.0) ===
[builder] ————————————————————————————————————————————————————————————————————————————————
[builder] Running "go build -o /layers/google.go.build/bin/main . (GOCACHE=/layers/google.go.build/gocache)"
[builder] can't load package: package hello-world: unknown import path "hello-world": cannot find module providing package hello-world
[builder] Done "go build -o /layers/google.go.build/bin/main . (GOCACHE=/lay..." (31.6396ms)
[builder] Failure: can't load package: package hello-world: unknown import path "hello-world": cannot find module providing package hello-world
[builder] ————————————————————————————————————————————————————————————————————————————————
[builder] Sorry your project couldn't be built.
[builder] Our documentation explains ways to configure Buildpacks to better recognise your project:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/blob/master/README.md
[builder] If you think you've found an issue, please report it:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
[builder] ————————————————————————————————————————————————————————————————————————————————
[builder] ERROR: failed to build: exit status 1
time="2020-05-14T10:28:24-04:00" level=fatal msg="exiting dev mode because first build failed: build failed: building [go-hello-world]: build artifact: failed with status code: 7"
```

The application builds fine with Docker.

**Comment by etanshaul** [comment] 2020-05-14 14:33
@dgageot @briandealwis fyi. Am I doing something silly here?

**Comment by dgageot** [comment] 2020-05-14 15:19
I think the problem is twofold. Nothing serious:
 + Buildpacks can't build your app, the same way `go build .` can't. You have to say in which package your entrypoint is since it's not in the root package. This is done with `GOOGLE_BUILDABLE=cmd/hello-world/main.go` envvar. 
+ If the sample was using go 1.14, you'd have a clearer message. Something like:
```
[builder] Running "go build -o /layers/google.go.build/bin/main . (GOCACHE=/layers/google.go.build/gocache)"
[builder] can't load package: package .: no Go files in /workspace
[builder] Done "go build -o /layers/google.go.build/bin/main . (GOCACHE=/lay..." (24.077964ms)
[builder] Tip: "GOOGLE_BUILDABLE" env var configures which Go package is built. Default is '.'
```
With older versions of Go, we get a different error message from Go that's less clear, so Buildpacks can't guess the solution to your issue.

We could improve the Go Build buildpack so that they give a better error message for every version of Go. We could also improve it so that it automatically selects the proper entrypoint if there's only one. It's the .go file on package `main`, with `func main()` function.

**Comment by briandealwis** [comment] 2020-05-14 15:24
We could even check if there are any .go files in `GOOGLE_BUILDABLE` and warn, can't we?

**Comment by dgageot** [comment] 2020-05-14 15:27
Yes.

**Comment by dgageot** [comment] 2020-05-18 16:23
I'm going to close this issue here. I've opened two issues on the buildpacks themselves:
https://github.com/GoogleCloudPlatform/buildpacks/issues/29 and https://github.com/GoogleCloudPlatform/buildpacks/issues/30

**Closed by dgageot** 2020-05-18 16:23 UTC
