### ISSUE TITLE
Website says: "fl Search this site..."

### ISSUE THREAD

**Issue by steren** [GoogleContainerTools/skaffold#4993] opened 2020-11-03 18:11 UTC
![image](https://user-images.githubusercontent.com/360895/98024037-98d3b300-1dbc-11eb-8377-3cdac7ebe702.png)

I guess "fl" is a typo?

**Comment by tejal29** [comment] 2020-11-03 18:20
Thanks @steren definitely a typo

**Comment by tejal29** [comment] 2020-11-03 18:22
Can you please mention which page you see this ?
i don't see it on skaffold.dev 
![image](https://user-images.githubusercontent.com/1534539/98025425-80fd2e80-1dbe-11eb-9c52-20579293d80b.png)

**Comment by chanseokoh** [comment] 2020-11-03 19:10
![image](https://user-images.githubusercontent.com/10523105/98028953-d0525780-1ddc-11eb-878e-7229f669830d.png)

Every page. It's from these `&#xf002` which is supposed to be a magnifying glass icon.

![image](https://user-images.githubusercontent.com/10523105/98028628-60dc6800-1ddc-11eb-95b5-20886447d826.png)

Note two instances of `placeholder="&#xf002 Search this site…"` below: 

```html
<input type="search" class="form-control td-search-input" placeholder="&#xf002 Search this site…" aria-label="Search this site…" autocomplete="off">
  </div>
  ...
  <div id="td-sidebar-menu" class="td-sidebar__inner">
  <form class="td-sidebar__search d-flex align-items-center">

  <input type="search" class="form-control td-search-input" placeholder="&#xf002 Search this site…" aria-label="Search this site…" autocomplete="off">
```

I think this is when [using a wrong font](https://stackoverflow.com/q/34823883/1701388). For example, removing the Awesome font from [this example](https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-search) will render "fl" instead of the icon.

**Comment by IsaacPD** [comment] 2020-11-03 19:23
I believe you are correct, I had not even noticed that there was supposed to be a search icon there. Some browsers seem to render it differently as for me on Chrome it only shows a blank space. And on Safari the magnifying glass is there. Which browser are you using?

**Comment by chanseokoh** [comment] 2020-11-03 19:29
I an using Chrome on my corp laptop (Linux). Honestly I've seen this "fl" for maybe more than a year, but I was too lazy to report before @steren did.

**Comment by tejal29** [comment] 2020-11-06 20:29
> I an using Chrome on my corp laptop (Linux). Honestly I've seen this "fl" for maybe more than a year, but I was too lazy to report before @steren did.

:) no worries @chanseokoh. you forced me to log into corp laptop. But yes now i can see the "fi"

![image](https://user-images.githubusercontent.com/1534539/98411862-ab075880-202b-11eb-9429-e8ddb503c49d.png)

**Comment by IsaacPD** [comment] 2020-11-10 15:53
Oddly I noticed that the magnifying glass does initially appear for me on Chrome/Firefox on Mac for a split second before it goes back to an empty space/"fl". By continuously refreshing it was easier to notice it appearing and then disappearing.

**Comment by IsaacPD** [comment] 2020-11-10 23:37
I managed to make the magnifying glass appear within my browser by changing the font used for that element from "font awesome 5 free" to "FontAwesome"

https://github.com/GoogleContainerTools/skaffold/blob/29d522ff1895036793245cb439246b56e4e64f05/docs/layouts/partials/navbar.html#L36

The code that is responsible for the search bar is that above but I cannot find this "search-input.html" partial file that describes it, I have a feeling that's the key but i'm not sure.

Also closing since this issue is a duplicate of #4903

<img width="1792" alt="Screen Shot 2020-11-10 at 6 31 19 PM" src="https://user-images.githubusercontent.com/12650821/98746243-14b49900-2383-11eb-986b-9099721225dc.png">

**Closed by IsaacPD** 2020-11-10 23:37 UTC
Labels: kind/documentation, platform/linux
