### ISSUE TITLE
'skaffold debug' should support build triggers

### ISSUE THREAD

**Issue by bmcustodio** [GoogleContainerTools/skaffold#3272] opened 2019-11-19 15:16 UTC
`skaffold debug` is awesome, but as far as I understand it doesn't support "redeploy-on-change"—meaning that to debug a change one has to stop and restart `skaffold debug`, which may be a bit awkward. It would be great if `skaffold debug` would behave a bit more like `skaffold dev`. Thoughts?

**Comment by bmcstdio** [comment] 2019-11-19 15:17
BTW, I am not sure whether this is this a duplicate of #2351 or not—sorry if it is indeed.

**Comment by balopat** [comment] 2019-11-20 17:31
Hi @bmcstdio - thanks for opening this!

Yes, this was intentional from the get-go because we didn't have a clean separation between file sync and debug, and the whole filewatcher is turned off for debug:  
https://github.com/GoogleContainerTools/skaffold/blob/master/cmd/skaffold/app/cmd/debug.go#L39
@briandealwis can share a bit more about the plans, but I think this should be possible.

**Comment by briandealwis** [comment] 2019-11-20 18:44
Hi @bmcstdio.  `debug` disables the file watcher because it's really awkward have a process call stack in the debugger be torn down because you saved a change (triggering a rebuild and redeploy, causing the container and process being killed).

`debug` should use the newer mechanisms to disable the auto build so that it can be overridden or triggered externally though.  I'll repurpose this bug for that.

**Comment by tstromberg** [comment] 2020-04-30 16:44
@briandealwis - are you aware of any progress on this?

**Comment by briandealwis** [comment] 2020-04-30 16:54
Yeah, I have to write a test.  In progress.

**Closed** 2020-06-19 09:54 UTC
Labels: area/debug, kind/feature-request, priority/awaiting-more-evidence
