### ISSUE TITLE
Skaffold should work with kubernetes server version 1.12

### ISSUE THREAD

**Issue by corneliusweig** [GoogleContainerTools/skaffold#1181] opened 2018-10-19 14:53 UTC
### Expected behavior
Skaffold should also work with kubernetes server version 1.12.
### Actual behavior
When using skaffold with a kubernetes server version 1.12, it deploys the resources, immediately deletes them, and dies with the following fatal error:

```
...
Successfully built 45531af8a373
Successfully tagged 6b984cdaed22d38bc96a6aef2b4d34b0:latest
Build complete in 386.173648ms
Starting test...
Test complete in 37.307µs
Starting deploy...
kubectl client version: 1.12
pod/node created
pod/python created
Deploy complete in 383.298556ms
Cleaning up...
pod "node" deleted
pod "python" deleted
Cleanup complete in 12.55336228s
FATA[0013] starting logger: initializing pod watcher: unknown (get pods)
```

### Information

- Skaffold version: 0.16.0
- Operating system: Linux
- Kubernetes version: 1.12
- Contents of skaffold.yaml: one of the skaffold examples, e.g. `examples/hot-reload/skaffold.yaml`

### Steps to reproduce the behavior
0. `kubectl version`
    ```
    Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", 
    GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"archive", BuildDate:"2018-10-04T12:02:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", 
    GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
    ```
1. `cd examples/hot-reload`
2. `skaffold dev`

### Remarks
When starting skaffold with the following flags, no PodWatcher is set up and skaffold works as desired:
```
skaffold  dev --tail=false --port-forward=false
```
My debugging has shown that `pkg/skaffold/kubernetes/watcher.go` tries to set up a watcher in
```go
return client.Pods("").Watch(meta_v1.ListOptions{
	IncludeUninitialized: true,
	TimeoutSeconds:       &forever,
})
```
which produces an unhandled error, resulting in the fatal error as shown above.

The output of `dep status` shows that the k8s client library is still using version kubernetes-1.11.0, which most likely causes the issue:
```
k8s.io/api                                        kubernetes-1.11.0    kubernetes-1.11.0  072894a                    29  
k8s.io/apimachinery                               kubernetes-1.11.0    kubernetes-1.11.0  103fd09                    38  
k8s.io/client-go                                  kubernetes-1.11.0    kubernetes-1.11.0  7d04d0e                    92
```

**Comment by michaelfig** [comment] 2019-01-15 18:56
I'm getting the same error with 1.13.  Is there anything I can do?  I really want to run skaffold in my on-prem cluster, but this issue is really biting me.

**Comment by michaelfig** [comment] 2019-01-15 19:02
I can confirm that upgrading the client libraries to 1.12.0 does *not* fix the issue.

**Comment by michaelfig** [comment] 2019-01-15 20:12
I found this issue was caused by my user not having permission to list pods at the cluster scope.

A working, but incomplete fix, is found at #1473.

**Comment by dgageot** [comment] 2019-01-19 23:22
@michaelfig Could you create a new ticket that describes the issue? and close this one?

**Comment by michaelfig** [comment] 2019-01-23 20:00
Created #1521.  Thank you, @corneliusweig for finding that the problem was with the Pod watcher.

I can confirm that skaffold works fine with kubernetes 1.13 with the PR mentioned in the new issue.

**Comment by dgageot** [comment] 2019-01-24 05:45
Thanks a lot!

**Closed by dgageot** 2019-01-24 05:45 UTC
Labels: bug, priority/p0, question
