### ISSUE TITLE
Investigate skaffold debug failures for deploy healthcheck.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#2373] opened 2019-06-28 20:35 UTC
### Expected behavior
Skaffold debug integration tests are failing on my PR #2359 
Raw log : https://api.travis-ci.org/v3/job/551517933/log.txt

However, when i run `skaffold debug` on the integration/testdata/debug, it executes correctly.

```
tejaldesai~integration/testdata/debug: (add_healthcheck)$ ../../../out/skaffold debug
Generating tags...
 - gcr.io/k8s-skaffold/skaffold-debug-jib -> gcr.io/k8s-skaffold/skaffold-debug-jib:v0.29.0-496-g34cdd619
 - gcr.io/k8s-skaffold/skaffold-debug-npm -> gcr.io/k8s-skaffold/skaffold-debug-npm:v0.29.0-496-g34cdd619
 - gcr.io/k8s-skaffold/skaffold-debug-nodejs -> gcr.io/k8s-skaffold/skaffold-debug-nodejs:v0.29.0-496-g34cdd619
 - gcr.io/k8s-skaffold/skaffold-debug-python3 -> gcr.io/k8s-skaffold/skaffold-debug-python3:v0.29.0-496-g34cdd619
Tags generated in 37.868139ms
Starting build...
Building [gcr.io/k8s-skaffold/skaffold-debug-jib]...
Building [gcr.io/k8s-skaffold/skaffold-debug-npm]...
Sending build context to Docker daemon  102.4kB
...
Build complete in 39.404677632s
Starting test...
Test complete in 4.226µs
Starting deploy...
kubectl client version: 1.11+
kubectl version 1.12.0 or greater is recommended for use with Skaffold
deployment.apps/jib created
pod/nodejs created
pod/npm created
pod/python3 created
Deploy complete in 1.934511688s
Waiting for deployments to stabilize

Deployments stabilized.
Watching for changes every 1s...

[jib-7659fccd9c-66sd2 web] Picked up JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
[nodejs web] Debugger listening on ws://127.0.0.1:9229/ee8d54be-9534-4320-9b6c-958d8360caaf
[nodejs web] For help see https://nodejs.org/en/docs/inspector
[nodejs web] Example app listening on port 3000!
[jib-7659fccd9c-66sd2 web] 
[jib-7659fccd9c-66sd2 web]   .   ____          _            __ _ _
[jib-7659fccd9c-66sd2 web]  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[jib-7659fccd9c-66sd2 web] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[jib-7659fccd9c-66sd2 web]  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[jib-7659fccd9c-66sd2 web]   '  |____| .__|_| |_|_| |_\__, | / / / /
[jib-7659fccd9c-66sd2 web]  =========|_|==============|___/=/_/_/_/
[jib-7659fccd9c-66sd2 web]  :: Spring Boot ::        (v2.0.5.RELEASE)
[jib-7659fccd9c-66sd2 web] 

ngine  : Starting Servlet Engine: Apache Tomcat/8.5.34
...
[jib-7659fccd9c-66sd2 web] 2019-06-28 19:49:09.269  INFO 1 --- [           main] hello.Application                        : Started Application in 10.757 seconds (JVM running for 12.443)


^CPruning images...
untagged image gcr.io/k8s-skaffold/skaffold-debug-npm:v0.29.0-496-g34cdd619
untagged image gcr.io/k8s-skaffold/skaffold-debug-
...
Image prune complete in 111.930801ms
Cleaning up...
deployment.apps "jib" deleted
pod "nodejs" deleted
pod "npm" deleted
pod "python3" deleted
Cleanup complete in 4.555856342s
tejaldesai~integration/testdata/debug: (add_healthcheck)$ echo $?
0
```
### Actual behavior

Not sure, which i am not able to reproduce this. Looking at the tests log here:
https://gist.github.com/tejal29/1550ec08a8e9b976082143e48521d12e and we might need to bring WaitForDeployments back in the flow.

### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by dgageot** [comment] 2019-07-05 12:17
Closing as a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/2398

**Closed by dgageot** 2019-07-05 12:17 UTC
Labels: meta/testing
