### ISSUE TITLE
Support kube.config and kube.context for specifying alternative Kubernetes config file or context

### ISSUE THREAD

**Issue by braderhart** [GoogleContainerTools/skaffold#2325] opened 2019-06-24 05:30 UTC
### Expected behavior
Allow setting an alternative kube.config file for an alternative Kubernetes config file and kube.context for specifying context without having to modify global flags for every step or setting manually

### Actual behavior
Currently have to add global flags for everything or manually set context or rename config file before running skaffold

### Information

- Skaffold version: 0.32.0
- Operating system: Arch 5.1.14-arch1-1-ARCH
- Contents of skaffold.yaml (example):

```yaml
apiVersion: skaffold/v1beta11
kind: Config

kube:
  config: ~/.kube/alternative_config
  context: kube-context

deploy:
  kustomize:
    path: kustomize/overlays/prod

profiles:
- name: dev
  kube:
    config: ~/.kube/minikube
    context: minikube
```

**Comment by seblegall** [comment] 2019-06-24 13:52
Why would you like to specify both a kubectl config file and un context?

In my understanding, kubectl config file may be managed with 2 strategy  :
* One big config file with multiple context and a default context set
* One config file by context

The ability to specify a file (where a default context is set) should be enough, right?

**Comment by braderhart** [comment] 2019-06-25 22:00
@seblegall I personally don't have a use for that currently, but I could see how other users may have multiple config files with multiple contexts for let's say home and work accounts. Maybe they are using separate profiles in Minikube, or have multiple clusters setup for work and then a different .kubeconfig for a personal GKE cluster and Minikube.

**Comment by seblegall** [comment] 2019-06-27 07:40
@braderhart I see. It seems to me that the use case of having multiple config files and multiple context in each is a little bit particular.

Maybe we could start by taking in consideration a specified config file as a first step and see later if there is a need for specifying a context.

Then, you've suggested to add this feature in the configuration file `skaffold.yml`. But kube config files and contexts can be named differently depending of the developer configuration. And since the `skaffold.yml` file is supposed to be versioned with your project, how would you do for different people working on the same team, on the same project but using different config for their local kubectl?

In my point of view, the kube config file (or the context) is something that vary depending on the user running skaffold, not depending on the project built with skaffold.

In this case, don't you think it should be a CLI flag?

**Comment by braderhart** [comment] 2019-06-28 05:48
I did realize later on that specifying the `KUBECONFIG` environment variable should work for kubectl and Helm. Specifying the `KUBECONFIG` environment variable requires that you either export it (not ideal when switching between configs frequently), or set it on the CLI for each command, or create a wrapper script and likely lose access to bash completion. This is also an extra step for the CI/CD process and can get confusing when managing everything in multiple places, as opposed to having a YAML file that they can go look at to see how things are setup and run everything as expected with a single command.

However, I do see an issue with the proposal, and that is that you probably don't want 20+ different `skaffold.yaml` files all specifying the same thing, especially if those values change later on as you suggested. I would like to see the option to specify it in the `skaffold config`, but with some of the profile logic in the config as well, so a user can run `skaffold build -p dev` and have it automatically switch to their preferred context and Kubernetes config. It is very plausible that a team may have a different config file for each DC, and different contexts within that.

An additional helpful feature would be to specify the default profile to use. One last feature could be to look in the current and parent directories for a `skaffold(_|.)config` and use the first one it finds as overrides. That way variables like `default-repo` can be set for a single project or multiple projects within a limited scope, or users can specify the profile context or config (e.g. `region/asia/skaffold.config`). Sorry, I'm probably blabbering by now but hopefully you see where I'm going with this and I'm not making it too complicated.

**Comment by balopat** [comment] 2019-08-16 23:56
Hi @braderhart - do you mind writing this up as a design proposal? It sounds like a larger effort that needs some thought.

**Comment by tejal29** [comment] 2019-08-21 17:26
@corneliusweig I remember your design proposal https://github.com/GoogleContainerTools/skaffold/pull/2384 addresses this?

**Comment by corneliusweig** [comment] 2019-08-22 08:27
Hey @tejal29, thanks for highlighting this for me.

So to summarize the ideas listed here:
1. add CLI option to configure the kube-context
2. add CLI option to configure the kubeconfig file
3. add Skaffold config option to configure the kube-context per project
4. add Skaffold config option to configure the default profile per project
5. add skaffold.yaml config to configure the kube-context
6. add skaffold.yaml config to configure the kubeconfig file

@seblegall @braderhart Please let me know if I missed something.

---

Out of those items, 1), 3) and 5) are addressed by design proposal #2384. It's also implemented, though not merged yet.

@braderhart @seblegall You are encouraged to take a look at this and let me know if this is sufficient for your use-cases.

---
As to 2) and 6), I'm totally with @seblegall:

>In my point of view, the kube config file (or the context) is something that vary depending on the user running skaffold, not depending on the project built with skaffold.

I think it does not make sense to configure a kube-config file in `skaffold.yaml`, as the file location varies too wildly for different users. We even had the same discussion for kubecontext which has the same issue but for the config file location it's even worse.

Also, I'm currently -1 for adding another CLI flag for the kubeconfig location. Skaffold already has a lot of CLI options, including 2 flags for configs (skaffold.yaml + skaffold config). Adding a third config file flag will cause massive confusion. Besides, the `KUBECONFIG` env variable should already be fully supported (can you confirm that @braderhart?).

---

As to item 4) "configure a default profile for a given Skaffold project"

I think it's worth investigating. At the moment, I don't fully understand the use-case, though. In essence, this config permanently changes the main profile to a given profile (in particular, the main profile won't be accessible anymore). However, this effect can be attained in a much cleaner way by restructuring the `skaffold.yaml` file, so that the default profile configuration is applied to the main profile.

Do you agree @braderhart?

**Comment by woodcockjosh** [comment] 2019-09-10 19:55
Just accidentally wiped out my shared dev environment with skaffold because I forgot to update the kube context. Would love this feature to be completed soon.

**Comment by corneliusweig** [comment] 2019-09-10 22:26
@woodcockjosh I presume you are referring to the context via `skaffold.yaml` or global config feature?

**Comment by woodcockjosh** [comment] 2019-09-11 00:27
@corneliusweig I'm referring to the kube context. eg `kube config set-context mycontext`

**Comment by balopat** [comment] 2019-09-20 23:14
Kubecontext can be passed already as a command line flag.
Setting kubecontext in skaffold.yaml is being worked on and soon will be merged. Follow https://github.com/GoogleContainerTools/skaffold/pull/2510 for updates.
For kubeconfig you can follow https://github.com/GoogleContainerTools/skaffold/issues/2699.

**Comment by balopat** [comment] 2019-11-15 00:23
This should doable now in the next release (v1.1.0 that will come next week) or the bleeding edge https://skaffold.dev/docs/install/, please open an issue if you find an issue

**Closed by balopat** 2019-11-15 00:23 UTC
Labels: area/deploy, area/global-config, kind/feature-request, priority/p1
