### ISSUE TITLE
Getting started with Docker does not work

### ISSUE THREAD

**Issue by adrienDog** [GoogleContainerTools/skaffold#2134] opened 2019-05-16 10:28 UTC
### Expected behavior
Following the tutorial [Getting Started](https://skaffold.dev/docs/getting-started/) with Docker:
```
docker run gcr.io/k8s-skaffold/skaffold:latest skaffold run
```
Should have the same behaviour as `skaffold run`

### Actual behavior
**ERROR**
```
time="2019-05-16T10:15:04Z" level=fatal msg="creating runner: parsing skaffold config: read skaffold config: open skaffold.yaml: no such file or directory"
```

### Information

- Skaffold version: 0.29.0 (latest)
- Operating system: linux
- Contents of skaffold.yaml: not relevant

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. Run `docker run gcr.io/k8s-skaffold/skaffold:latest skaffold run` as explained in the Getting Started

### Why do I need this?
Running skaffold on the CI

**Comment by nkubala** [comment] 2019-05-16 19:12
hey @adrienDog. just running `docker run gcr.io/k8s-skaffold/skaffold:latest skaffold run` won't work for a few reasons:

1) there's no skaffold.yaml or project in the provided skaffold image. the image we provide is for use in CI pipelines, so the smaller the better. we don't bundle in any of our examples because they would add extra size to the image. you'll need to mount in your project into the container before running it: something like 
`docker run -v /host/skaffold/project:/skaffold gcr.io/k8s-skaffold/skaffold:latest skaffold run -f /skaffold/skaffold.yaml`
should work.

2) our provided skaffold image doesn't have docker installed in it. this is where you'll want to think about what you're actually trying to do by running skaffold in a container - if you're trying to just run skaffold in container-based CI, then you could consider mounting in /var/run/docker.sock (though I personally don't recommend doing this). you could also consider using kaniko, which is a good alternative for building containers with "docker" outside of your host.

hope this helps!

**Comment by dgageot** [comment] 2019-05-17 09:36
I'm going to close this one as it's not a bug in Skaffold

**Closed by dgageot** 2019-05-17 09:36 UTC

**Comment by adrienDog** [comment] 2019-05-18 09:11
Thank you very much for the explanations!

I am trying to use skadfold from a CI (GitLab) yes so I will explore Kaniko :)
