### ISSUE TITLE
skaffold init: how to process after choosing the Dockerfiles?

### ISSUE THREAD

**Issue by brightzheng100** [GoogleContainerTools/skaffold#5114] opened 2020-12-06 04:39 UTC
### Expected behavior

Choose the right Dockerfile(s) and proceed to generate the initial `skaffold.yaml` file.

### Actual behavior

After choosing the Dockerfile(s), I don't have a way to proceed.

### Information

- Skaffold version: `v1.7.1`
- Operating system: Mac
- Contents of skaffold.yaml: N/A

### Steps to reproduce the behavior

1. In an existing `kubebuilder` project, issue `skaffold init`;

2. In the prompt, choose some Dockerfile(s);

```sh
$ skaffold init
? Choose the builder to build image controller  [Use arrows to move, enter to select, type to filter]
  Docker (Dockerfile)
> Docker (_output/release/manager.dockerbuild/Dockerfile)
  Docker (_output/release/syncer.dockerbuild/Dockerfile)
  Docker (_output/release/agent.dockerbuild/Dockerfile)
  None (image not built from these sources)
```

3. After choosing some Dockerfiles, don't know how to proceed:

```sh
$ skaffold init
? Choose the builder to build image controller Docker (_output/release/manager.dockerbuild/Dockerfile)
? Choose the builder to build image gcr.io/kubebuilder/kube-rbac-proxy Docker (_output/release/syncer.dockerbuild/Dockerfile)
? Choose the builder to build image image_url Docker (_output/release/agent.dockerbuild/Dockerfile)
? Choose the builder to build image xxxx/manager-amd64  [Use arrows to move, enter to select, type to filter]
  Docker (Dockerfile)
> None (image not built from these sources)
```

4. Keep typing Enter, the CLI will just clash:

```
? Choose the builder to build image virtualcluster/coredns None (image not built from these sources)
? Choose the builder to build image virtualcluster/etcd-v3.4.0 None (image not built from these sources)
? Choose the builder to build image virtualcluster/manager-amd64 None (image not built from these sources)
? Choose the builder to build image virtualcluster/sample-controller-amd64 None (image not built from these sources)
? Choose the builder to build image virtualcluster/syncer-amd64 None (image not built from these sources)
? Choose the builder to build image virtualcluster/agent-amd64 None (image not built from these sources)
using non standard workspace: _output/release/manager.dockerbuild
using non standard workspace: _output/release/syncer.dockerbuild
using non standard workspace: _output/release/agent.dockerbuild
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x60e54b3]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer/build.Artifacts(0xc000184f00, 0x5, 0x8, 0x0, 0x0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/pkg/skaffold/initializer/build/util.go:72 +0x133
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer/build.(*defaultBuildInitializer).BuildConfig(0xc0003d3110, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/skaffold-20201202-19997-11jo8qd/pkg/skaffold/initializer/build/init.go:57 +0x8b
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.generateSkaffoldConfig(0x68c5860, 0xc0003d3110, 0x68c59a0, 0xc000498ea0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/pkg/skaffold/initializer/config.go:57 +0x3d5
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.Initialize(0x6881dc0, 0xc000b95f10, 0x6630a6a, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/skaffold-20201202-19997-11jo8qd/pkg/skaffold/initializer/init.go:101 +0x5ca
github.com/GoogleContainerTools/skaffold/pkg/skaffold/initializer.DoInit(0x68c5520, 0xc000798240, 0x6881dc0, 0xc000b95f10, 0x6630a6a, 0x1c, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/skaffold-20201202-19997-11jo8qd/pkg/skaffold/initializer/init.go:49 +0x213
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doInit(0x68c5520, 0xc000798240, 0x6881dc0, 0xc000b95f10, 0x0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/cmd/skaffold/app/cmd/init.go:84 +0x258
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc000465b80, 0x75d4060, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/cmd/skaffold/app/cmd/commands.go:111 +0xd5
github.com/spf13/cobra.(*Command).execute(0xc000465b80, 0x75d4060, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/vendor/github.com/spf13/cobra/command.go:850 +0xb70
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004642c0, 0xc000465b80, 0x0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/vendor/github.com/spf13/cobra/command.go:958 +0x768
github.com/spf13/cobra.(*Command).Execute(0xc0004642c0, 0x0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/vendor/github.com/spf13/cobra/command.go:895 +0x3b
github.com/spf13/cobra.(*Command).ExecuteContext(0xc0004642c0, 0x68c5520, 0xc000798240, 0x0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/vendor/github.com/spf13/cobra/command.go:888 +0x6a
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x68811a0, 0xc000010018, 0x68811a0, 0xc000010020, 0x0, 0x0)
	/private/tmp/skaffold-20201202-19997-11jo8qd/cmd/skaffold/app/skaffold.go:47 +0x552
main.main()
	/private/tmp/skaffold-20201202-19997-11jo8qd/cmd/skaffold/skaffold.go:35 +0x65
```

**Comment by tejal29** [comment] 2020-12-08 19:46
@marlon-gamez since he has touched the code recently

**Comment by MarlonGamez** [comment] 2020-12-08 19:52
Hi @brightzheng100, thanks for opening this. I'll try to see what's going on here asap

**Comment by MarlonGamez** [comment] 2020-12-08 20:22
@brightzheng100 do you know how many images skaffold asked you to select a builder for?

**Comment by brightzheng100** [comment] 2020-12-09 02:55
There is one that I'm trying.

You may easily reproduce it by going through these steps:

```sh
git clone https://github.com/kubernetes-sigs/multi-tenancy.git
cd multi-tenancy/incubator/virtualcluster

make build-images
skaffold init
```

**Comment by MarlonGamez** [comment] 2020-12-09 18:43
Awesome, thanks for sharing this. I was able to reproduce it. It looks like the issue is coming from hitting enter after typing to filter. I'll try to work on a fix for this asap.

In the meantime, are you basically trying to end the process after you select those three dockerfiles? We don't have a way to support that, so I believe you'd have to choose the "None" option for the remaining images.

**Closed** 2020-12-09 21:13 UTC
Labels: area/init, kind/bug, priority/p2
