### ISSUE TITLE
kpt deployer fails when there's no kustomization.yaml

### ISSUE THREAD

**Issue by halvards** [GoogleContainerTools/skaffold#5580] opened 2021-03-19 08:14 UTC
### Expected behavior

The kpt deployer can be used with `skaffold` dev/run without requiring a `kustomization.yaml` file in the kpt directory.

### Actual behavior

If the kpt directory (as configured in `skaffold.yaml`) doesn't contain a kustomization.yaml file, this is the output of `skaffold run`:

```
DEBU[0005] Running command: [kpt live apply .kpt-hydrated]
error: can't find scope for resource ResourceList.config.kubernetes.io
exit status 1
```

When there's no `kustomization.yaml` file, the `.kpt-hydrated/resources.yaml` file contains a ResourceList, and `kpt live apply` [doesn't accept a ResourceList](https://github.com/GoogleContainerTools/kpt/issues/574).

With a `kustomization.yaml` file present, `resources.yaml` contains a list of yaml objects, and kpt applies this successfully.

### Information

- Skaffold version: v1.21.0 (also v1.20.0)
- kpt version: v0.38.1 (also v0.37.1)
- kustomize version: v4.0.5 (also v3.6.1)
- Operating system: macOS 11.2.3
- Installed via: binary download
- Contents of skaffold.yaml: see steps to reproduce below

### Steps to reproduce the behavior

This works:

1. `git clone https://github.com/google/k8s-digester.git`
2. `skaffold run` (or you can run `skaffold render` and see that it outputs a list of yaml objects)

This fails:

1. `git clone https://github.com/google/k8s-digester.git`
2. `sed -i~ 's/dir: "\."/dir: manifests/' skaffold.yaml`
3. `skaffold run` (or you can run `skaffold render` and see that it outputs a ResourceList)

**Comment by nkubala** [comment] 2021-04-01 22:09
hmm, is this a bug in `kpt`? i'm not totally familiar with the way this should work but i think the `resources.yaml` file is being constructed by `kpt` itself.

cc @yuwenma

**Comment by yuwenma** [comment] 2021-04-02 01:21
@halvards Thanks for filing the issue (and the details are really helpful especially for the reproducing steps). This is a bug in skaffold kpt deployer (my bad) which does not handle the mingled usage of kpt and kustomize well. Basically kustomize is a standalone process from kpt and some resource transformation is needed when embeding the kustomization into kpt render pipeline. Here, some risk condition handling is missing. I'll upload the fix soon. 

The good news is that kustomize is going to be a kpt fn image in skaffold and the problem should be resolved from the root.

**Comment by yuwenma** [comment] 2021-04-02 21:04
@halvards Actually, I noticed some kpt version differences between 0.34.0 (when the kpt deployer is implemented) and 0.38.0 (current latest), this explains why the expected behavior used to work (in 0.34.0) but not now. AFAIK, some major changes are happening in kpt (for its GA) and the current workaround in skaffold may be deprecated as well. 

Thus, we wouldn't provide a solid solution to the root cause (restructure the kpt config pipeline in skaffold) but I'm going to upload a patch to make it work for your specific use case.

**Comment by yuwenma** [comment] 2021-04-02 21:47
@halvards Just FYI, once the fix is in, you also need to remove the [inventory-template.yaml](https://github.com/google/k8s-digester/blob/main/manifests/inventory-template.yaml) to run in non-kustomize mode (I manually tested it against your example and it works).

`kpt` does not accept multiple inventory info and you have already provided the inventory in `skaffold.yaml`.

**Closed** 2021-04-08 20:29 UTC
Labels: area/deploy, deploy/kpt, kind/bug, priority/p2

**Comment by halvards** [comment] 2021-04-09 00:40
Thanks @yuwenma !
