### ISSUE TITLE
.Values.imageKey is rendered differently in helm template

### ISSUE THREAD

**Issue by letmutx** [GoogleContainerTools/skaffold#7967] opened 2022-10-21 18:52 UTC
### Expected behavior
Using `{{ .Values.imageKey }}` resolves to the same values when used everywhere in the template with helm release.

```
$ skaffold run
$ kubectl get deployment test -o yaml | rg -aF binaries
          value: binaries:2001d978bc5729c0bfc3c5f9a1a3499c7afdeb3f45e4c785711f58d644a3aa2e
        image: binaries:2001d978bc5729c0bfc3c5f9a1a3499c7afdeb3f45e4c785711f58d644a3aa2e 
```

### Actual behavior
With v2.0.0, it when using the `{{ .Values.imageKey }}` in a k8s deployment template in `env` block and setting it in container `image` results in different values. 

```
$ skaffold run
$ kubectl get deployment test -o yaml | rg -aF binaries
          value: binaries
        image: binaries:2001d978bc5729c0bfc3c5f9a1a3499c7afdeb3f45e4c785711f58d644a3aa2e 
```

This was not the case in v1.34.1 

### Information

- Skaffold version: `v2.0.0`
- Operating system: Linux, Pop!_OS 22.04
- Installed via: skaffold.dev
- Contents of skaffold.yaml: Attached a minimal reproducible example to the PR

### Steps to reproduce the behavior

1. [sample skaffold project](https://github.com/letmutx/skaffold-bug-report/)
2. Steps here: https://github.com/letmutx/skaffold-bug-report/blob/main/README.md

logs: https://github.com/letmutx/skaffold-bug-report/blob/main/run-2.0.0.log

**Comment by iosifnicolae2** [comment] 2022-10-31 11:31
We're encountering something similar in https://github.com/GoogleContainerTools/skaffold/issues/8008

**Comment by sanketsudake** [comment] 2022-11-21 17:36
Facing similar issue https://github.com/fission/fission, unable to migrate to scaffold v2 because of the bug.

**Comment by aaron-prindle** [comment] 2022-11-23 23:08
@letmutx thank you for flagging this and posting the github repo for reproduction.  As you noted,  there is currently an issue where when using `setValues`, only the `image:` field of a deployment is modified, not all instances of {{ Values.imageKey }}.  Currently in the code `setValues` uses two passes, one to rewrite the values with the <artifact-name> (my-image-name)  (via `helm template` essentially) and another to convert them to the "fully-qualified-name" (gcr.io/my-image-name:tag@sha256:<sha256-value>) (via `--post-renderer=/path/to/skaffold`).  The solution here is to instead use:
`setValueTemplates` as these template values are properly updated in the first pass.  I have submitted:
https://github.com/GoogleContainerTools/skaffold/pull/8147

and plan on updating our docs to have this be the preferred method of passing skaffold images to helm rendererd manifests // helm deployments.  

In the short term, you can change your current yamls to use `setValueTemplates` instead of `setValues` but currently w/o the above PR the env vars to use is confusing if used with multiple images:
https://skaffold.dev/docs/environment/templating/

relevant snippet:
![image](https://user-images.githubusercontent.com/1951658/203661242-faaa9af9-b17b-471b-839a-9a141b10fe6e.png)

**Comment by aaron-prindle** [comment] 2022-11-23 23:11
For the sample repo you posted, the short term fix will be like:
```apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: inference-engine
build:
  artifacts:
  - image: binaries
  local:
    useBuildkit: true
    concurrency: 0
manifests:
  helm:
    releases:
    - name: inference-engine
      chartPath: infra/app/
      namespace: default
      setValueTemplates:
        imageKey: '{{.DIGEST}}' // <---difficult if other images though w/o the above PR as this becomes .DIGEST2 ....DIGESTN
deploy:
  helm: {}
```

and once the above PR is merged:
```
apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: inference-engine
build:
  artifacts:
  - image: binaries
  local:
    useBuildkit: true
    concurrency: 0
manifests:
  helm:
    releases:
    - name: inference-engine
      chartPath: infra/app/
      namespace: default
      setValueTemplates:
        imageKey: '{{.DIGEST_binaries}}' // <---exact naming may change but will be similar
deploy:
  helm: {}
```


I also am changing the auto updating in the above PR from v2beta29 -> v3alpha1 to use this format so this will be done automatically assuming you call `skaffold <cmd>` from a `v2beta29` yaml

**Comment by aaron-prindle** [comment] 2022-11-23 23:13
@sanketsudake I've added some information above on the short term and long term fix here.  I plan on fixing this and making this work be default in our next release as well updating our docs here.  Sorry for the inconvience, thanks for flagging

**Closed** 2022-11-29 20:43 UTC
Labels: kind/bug, deploy/helm, area/env-vars

**Comment by aaron-prindle** [comment] 2022-11-30 04:05
This has been added at how now, the format is:
`IMAGE_[NAME|TAG|REPO|DOMAIN|REPO_NO_DOMAIN]_<artifact-name>`
