### ISSUE TITLE
[BUG] nil pointer dereference from k8s oidc provider

### ISSUE THREAD

**Issue by ddlees** [GoogleContainerTools/skaffold#4301] opened 2020-06-08 19:19 UTC
### Expected behavior

When invoking `skaffold run` against a target cluster protected by the OIDC protocol I would expect a clearer error message when the id token in my KUBECONFIG for that cluster has expired.

### Actual behavior

`skaffold run` consistently returns this stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x50e0e1a]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*oidcAuthProvider).idToken(0xc000b55140, 0x0, 0x0, 0x0, 0x0)
        /skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:281 +0x6fa
k8s.io/client-go/plugin/pkg/client/auth/oidc.(*roundTripper).RoundTrip(0xc0009ec9c0, 0xc000832700, 0x574f15b, 0xa, 0xc000a09c20)
        /skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:199 +0x7c
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0009ec9e0, 0xc000832600, 0xc0009ec9e0, 0xbfafbdd9d45f2a08, 0x7daf5a6da)
        /skaffold/vendor/k8s.io/client-go/transport/round_trippers.go:159 +0x1c0
net/http.send(0xc000832500, 0x5a71fe0, 0xc0009ec9e0, 0xbfafbdd9d45f2a08, 0x7daf5a6da, 0x68f44a0, 0xc000560688, 0xbfafbdd9d45f2a08, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:252 +0x43e
net/http.(*Client).send(0xc0008147e0, 0xc000832500, 0xbfafbdd9d45f2a08, 0x7daf5a6da, 0x68f44a0, 0xc000560688, 0x0, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:176 +0xfa
net/http.(*Client).do(0xc0008147e0, 0xc000832500, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:699 +0x44a
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:567
k8s.io/client-go/rest.(*Request).request(0xc000a76a50, 0xc0007292b0, 0x0, 0x0)
        /skaffold/vendor/k8s.io/client-go/rest/request.go:801 +0x3e9
k8s.io/client-go/rest.(*Request).Do(0xc000a76a50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /skaffold/vendor/k8s.io/client-go/rest/request.go:873 +0xd8
k8s.io/client-go/discovery.(*DiscoveryClient).ServerVersion(0xc0009eca40, 0x5ad0080, 0xc0009eca40, 0x0)
        /skaffold/vendor/k8s.io/client-go/discovery/discovery_client.go:408 +0xa9
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.failIfClusterIsNotReachable(0x5a72580, 0xc0001a4008)
        /skaffold/pkg/skaffold/runner/deploy.go:95 +0x7a
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Deploy(0xc00082c000, 0x5ab5440, 0xc0001b67c0, 0x5a72580, 0xc0001a4008, 0xc000d2a780, 0x2, 0x2, 0x2, 0x0)
        /skaffold/pkg/skaffold/runner/deploy.go:55 +0x26b
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).DeployAndLog(0xc00082c000, 0x5ab5440, 0xc0001b67c0, 0x5a72580, 0xc0001a4008, 0xc000d2a780, 0x2, 0x2, 0x0, 0x0)
        /skaffold/pkg/skaffold/runner/build_deploy.go:104 +0x1f5
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doRun.func1(0x5ad4da0, 0xc00082c000, 0xc00016be60, 0x0, 0x100000001)
        /skaffold/cmd/skaffold/app/cmd/run.go:49 +0x1b5
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x5ab5440, 0xc0001b67c0, 0xc000c0fb28, 0xc00093fb50, 0x41e9022)
        /skaffold/cmd/skaffold/app/cmd/runner.go:47 +0xb4
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doRun(0x5ab5440, 0xc0001b67c0, 0x5a72580, 0xc0001a4008, 0xc0001a4008, 0xc0001af980)
        /skaffold/cmd/skaffold/app/cmd/run.go:43 +0x83
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc00035a2c0, 0xc00000e700, 0x0, 0x2, 0x0, 0x0)
        /skaffold/cmd/skaffold/app/cmd/commands.go:99 +0xbb
github.com/spf13/cobra.(*Command).execute(0xc00035a2c0, 0xc00000e6e0, 0x2, 0x2, 0xc00035a2c0, 0xc00000e6e0)
        /skaffold/vendor/github.com/spf13/cobra/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00035a000, 0xc0001a4008, 0x5a72580, 0xc0001a4010)
        /skaffold/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /skaffold/vendor/github.com/spf13/cobra/command.go:887
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /skaffold/vendor/github.com/spf13/cobra/command.go:880
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x5a72580, 0xc0001a4008, 0x5a72580, 0xc0001a4010, 0x0, 0x0)
        /skaffold/cmd/skaffold/app/skaffold.go:33 +0xde
main.main()
        /skaffold/cmd/skaffold/skaffold.go:31 +0x4e
```

### Information

- Skaffold version: v1.10.1
- Operating system: macOS
- Contents of skaffold.yaml: Not disclosable 

### Steps to reproduce the behavior

1. Set context to a cluster that uses oidc for authentication
2. Modify KUBECONFIG such that the `id-token` or for that cluster's user defintion is invalid.

E.g.

``` yaml
users:
- name: user@domain.com
  user:
    auth-provider:
      config:
        id-token: imabadidtoken
        ...
      name: oidc
```

3. Execute `skaffold run` on any deployable profile that uses helm

### Additional Notes

For the sake of others running into a similar stack trace, try refreshing your cluster credentials; that's how I got around this problem. It does seem like the client here tries to check if the token is expired so I am unsure if that is the root cause. In case that isn't the root cause you can inspect a scrubbed version of the JWT payload below if that provides any insight. FWIW the k8s cluster I'm using is hosted on IBM Cloud which offers a Free plan if it comes to that for debugging.

``` json
{
  "iam_id": "",
  "iss": "",
  "sub": "",
  "aud": "",
  "given_name": "",
  "family_name": "",
  "name": "",
  "email": "",
  "exp": 1591643667,
  "scope": "ibm openid containers-kubernetes",
  "iat": 1591640067,
  "sub_60d74e319e72c2c58c02b8c2d18c41bc": "",
  "iam_id_60d74e319e72c2c58c02b8c2d18c41bc": "",
  "realmed_sub_60d74e319e72c2c58c02b8c2d18c41bc": "",
  "groups_60d74e319e72c2c58c02b8c2d18c41bc": [
  ]
}
```

**Comment by nkubala** [comment] 2020-06-15 19:59
hmm, strange that client-go is panicing here but this is a pretty bad error message either way. funny that this is happening because we're trying to validate the auth before attempting the deploy so we can surface a better error message 😄

**Comment by nkubala** [comment] 2020-06-15 20:58
this error also looks suspiciously like the one from https://github.com/GoogleContainerTools/skaffold/issues/3047

**Comment by dgageot** [comment] 2020-06-29 07:34
Duplicate of #3047

**Closed by dgageot** 2020-06-29 07:34 UTC
Labels: area/auth, kind/bug, needs-actionable-error, needs-reproduction, priority/p2
