### ISSUE TITLE
avoid to push image

### ISSUE THREAD

**Issue by jeusdi** [GoogleContainerTools/skaffold#6997] opened 2022-01-07 22:13 UTC
Here my `skaffold.yaml`:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: hes-mpi-fhir-mongodb
build:
  artifacts:
  - image: fhir-mongo
    custom:
      buildCommand: |-
        mvn clean package spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE
        echo $PUSH_IMAGE
        if [ $PUSH_IMAGE ]; then
          docker push $IMAGE
        fi
      dependencies:
        paths:
          - src
          - pom.xml
  local:
    push: false
```

I'm facing two problems:

1. I'm setting that image have to not be push up to registry.
2. I don't quite figure out why is trying to push up to docker.io. Shouldn't it be created on local repository as `fhir-mongo:tag`?

**Comment by gsquared94** [comment] 2022-01-10 13:04
what value are you getting for `$PUSH_IMAGE`?

**Comment by gsquared94** [comment] 2022-01-11 16:06
I'm not able to repro this either on release/v1.35.1 nor on main. Can you please share the ouput of running:
```
skaffold build --cache-artifacts=false -v DEBUG
```

**Comment by tejal29** [comment] 2022-01-26 16:13
@jeusdi friendly ping. Closing this issue as unable to reproduce. Please comment to re-open

**Closed by tejal29** 2022-01-26 16:13 UTC
Labels: kind/bug, needs-reproduction, build/custom
