### ISSUE TITLE
Options `deploy.kubeContext` or `--kube-context` not behaving as expected.

### ISSUE THREAD

**Issue by rsylthe** [GoogleContainerTools/skaffold#5863] opened 2021-05-19 13:14 UTC
### Expected behavior
I expect that when setting any of these kube context options to a local cluster that it overrides the current context found in kube config. Since Skaffold detects if a cluster is local based on context name, I also expect that it does not attempt to push images to a remote registry and instead uses the image from the docker daemon.
```yaml
deploy:
  kubeContext: kind-kind
```
```sh
skaffold dev --kube-context kind-kind
```

### Actual behavior
Regardless of the context provided to the aforementioned kube context options, it still seems like Skaffold is detecting the cluster as remote based on current context in `.kube/config`, and as such instructing Jib to attempt pushing to a remote registry I don't have permission to push to, failing the build.

### Information

- Skaffold version: v1.24.1
- Operating system: Windows 10 Pro v2004 and Ubuntu 20.04.2
- Installed via: skaffold.dev
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta16
kind: Config
build:
  artifacts:
    - image: input-api
      jib:
        project: input-api

deploy:
  kubeContext: kind-kind
  helm:
    releases:
      - name: input-api
        chartPath: igc-component
        valuesFiles:
          - input-api/values.yml
        artifactOverrides:
          image: input-api
```

<details>
<summary>Log from <code>skaffold dev ... -vdebug</code></summary>

```zsh
$ skaffold dev --kube-context kind-kind -vdebug
INFO[0000] starting gRPC server on port 50051           
INFO[0000] starting gRPC HTTP server on port 50052      
INFO[0000] Skaffold &{Version:v1.24.1 ConfigVersion:skaffold/v2beta16 GitVersion: GitCommit:c44d98a365e26a091cf2cde5a2378054d2d345b2 BuildDate:2021-05-17T23:45:24Z GoVersion:go1.14.14 Compiler:gc Platform:linux/amd64 User:} 
INFO[0000] Loaded Skaffold defaults from "/home/rsylthe/.skaffold/config" 
DEBU[0000] parsed 1 configs from configuration file /home/rsylthe/repos/igc-project/skaffold.yaml 
DEBU[0000] Defaulting build type to local build         
INFO[0000] Activated kube-context "kind-kind"           
INFO[0000] Using kubectl context: kind-kind             
DEBU[0000] Running command: [minikube version --output=json] 
DEBU[0000] setting Docker user agent to skaffold-v1.24.1 
DEBU[0000] Using builder: local                         
DEBU[0000] push value not present in NewBuilder, defaulting to true because cluster.PushImages is true 
INFO[0000] build concurrency first set to 1 parsed from *local.Builder[0] 
INFO[0000] final build concurrency value is 1           
DEBU[0000] Running command: [helm version --client]     
DEBU[0000] Command output: [version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
] 
Listing files to watch...
 - input-api
DEBU[0000] Running command: [java -version]             
DEBU[0000] could not parse date ""                      
DEBU[0000] Using wrapper for gradlew: gradle            
DEBU[0000] Running command: [/home/rsylthe/repos/igc-project/gradlew _skaffoldFailIfJibOutOfDate -Djib.requiredVersion=1.4.0 :input-api:_jibSkaffoldFilesV2 -q --console=plain] 
DEBU[0002] Command output: [
BEGIN JIB JSON
{"build":["/home/rsylthe/repos/igc-project/build.gradle.kts","/home/rsylthe/repos/igc-project/input-api/build.gradle.kts"],"inputs":["/home/rsylthe/repos/igc-project/input-api/src/main/kotlin"],"ignore":[]}
] 
DEBU[0002] Found dependencies for jib-gradle artifact: [build.gradle.kts input-api/build.gradle.kts input-api/src/main/kotlin/com/sardine/igc-project/inputapi/Main.kt] 
INFO[0002] List generated in 2.03 seconds               
Generating tags...
 - input-api -> DEBU[0002] Running command: [git describe --tags --always] 
DEBU[0002] Command output: [0ada439
]                   
DEBU[0002] Running command: [git status . --porcelain]  
DEBU[0002] Command output: [ M skaffold.yaml
]          
input-api:0ada439-dirty
INFO[0002] Tags generated in 3.841711ms                 
Checking cache...
DEBU[0002] Could not import artifact from Docker, building instead (import of missing images disabled) 
 - input-api: Not found. Building
INFO[0002] Cache check completed in 451.413µs           
Starting build...
Building [input-api]...
DEBU[0002] Using wrapper for gradlew: gradle            
INFO[0002] Building .: /home/rsylthe/repos/igc-project/gradlew, [/home/rsylthe/repos/igc-project/gradlew -Djib.console=plain _skaffoldFailIfJibOutOfDate -Djib.requiredVersion=1.4.0 :input-api:jib --image=input-api:0ada439-dirty] 
DEBU[0002] Running command: [/home/rsylthe/repos/igc-project/gradlew -Djib.console=plain _skaffoldFailIfJibOutOfDate -Djib.requiredVersion=1.4.0 :input-api:jib --image=input-api:0ada439-dirty] 
> Task :input-api:_skaffoldFailIfJibOutOfDate
> Task :input-api:compileKotlin UP-TO-DATE
> Task :input-api:compileJava NO-SOURCE
> Task :input-api:processResources NO-SOURCE
> Task :input-api:classes UP-TO-DATE
> Task :input-api:jib
Containerizing application to input-api:0ada439-dirty...
Base image 'amazoncorretto:11.0.11-alpine' does not use a specific image digest - build may not be reproducible
Getting manifest for base image amazoncorretto:11.0.11-alpine...
Building classes layer...
Building dependencies layer...
The base image requires auth. Trying again for amazoncorretto:11.0.11-alpine...
Using base image with digest: sha256:35e8797e008eac2e05264c8a3894767b8cd4661ddca0837db1df7795d142ed1b
> Task :input-api:jib FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':input-api:jib'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed, perhaps you should make sure your credentials for 'registry-1.docker.io/library/input-api' are set up correctly. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 5s
5 actionable tasks: 4 executed, 1 up-to-date
DEBU[0008] Running command: [tput colors]               
DEBU[0008] Command output: [256
]                       
gradle build failed: exit status 1. See the build transcript for suggestions..
DEBU[0008] exporting metrics                            
DEBU[0008] metrics uploading complete in 810.616335ms
```

</details>

**Comment by tejal29** [comment] 2021-05-20 15:53
@rsylthe Thanks for the issues. The team is aware of this issue and is planning to address it in June end release v1.27.0

Dupe of #4347

**Closed by tejal29** 2021-05-20 15:53 UTC
