### ISSUE TITLE
Multi stage build error

### ISSUE THREAD

**Issue by raphaelvigee** [GoogleContainerTools/skaffold#1783] opened 2019-03-12 05:14 UTC
### Expected behavior

Build the image

### Actual behavior

Fails with:

    FATA[0001] build failed: building [containers.XXX.com/YYY/frontend]: build artifact: An image does not exist locally with the tag: containers.XXX.com/YYY/frontend

### Information

- Skaffold version: 0.24.0
- Operating system: MacOS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
    - image: containers.XXX.com/YYY/frontend
      context: ..
      docker:
        dockerfile: ./frontend/Dockerfile
  tagPolicy:
    sha256: {}
```

- Dockerfile
```
FROM node:10-jessie AS build

...

FROM nginx:1.15.9

COPY --from=build /app/frontend/build /usr/share/nginx/html
COPY /app/frontend/nginx.conf /etc/nginx/conf.d/default.conf

```

- Full log
```
INFO[0000] Skaffold &{Version:v0.24.0 ConfigVersion:skaffold/v1beta6 GitVersion: GitCommit:6a829c4b29e3a102b0b14c4584cd174f780402e9 GitTreeState:clean BuildDate:2019-03-01T20:36:32Z GoVersion:go1.12 Compiler:gc Platform:darwin/amd64}
DEBU[0000] Defaulting build type to local build
DEBU[0000] Defaulting deploy type to kubectl
INFO[0000] no kubectl context currently set, using global values
INFO[0000] Using kubectl context:
INFO[0000] no kubectl context currently set, using global values
DEBU[0000] Using builder: local
DEBU[0000] setting Docker user agent to skaffold-v0.24.0
INFO[0000] no kubectl context currently set, using global values
DEBU[0000] push value not present, defaulting to true because localCluster is false
Generating Tag for [containers.XXX.com/YYY/frontend]...
DEBU[0000] Tag for containers.XXX.com/YYY/frontend: containers.XXX.com/YYY/frontend:latest
Starting build...
Building [containers.XXX.com/YYY/frontend]...
DEBU[0000] Running docker build: context: .., dockerfile: ./frontend/Dockerfile
DEBU[0001] Checking base image node:10-jessie for ONBUILD triggers.
DEBU[0001] Checking base image nginx:1.15.9 for ONBUILD triggers.
Sending build context to Docker daemon

DEBU[0001] Skipping credential configuration because registry is not gcr.
The push refers to repository [containers.XXX.com/YYY/frontend]
FATA[0001] build failed: building [containers.XXX.com/YYY/frontend]: build artifact: An image does not exist locally with the tag: containers.XXX.com/YYY/frontend

```

### Steps to reproduce the behavior

If you do not attempt to COPY from the `build` stage, the build is successful. The error seems to be created by attempting to COPY from the previous stage.

**Comment by dgageot** [comment] 2019-06-27 09:10
Let's close this one because it was never reproduced. If the problem is still there, please reopen

**Closed by dgageot** 2019-06-27 09:10 UTC
Labels: area/tag, kind/bug, tagger/sha256
