### ISSUE TITLE
feat: Adding configuration field for image default repository on skaffold yaml

### ISSUE THREAD

**Issue by irvifa** [GoogleContainerTools/skaffold#6129] opened 2021-07-05 10:42 UTC
**Kind**
This is a feature request.

**Background**
As of now, image repository handling support [default-registry](https://skaffold.dev/docs/environment/image-registries/) that can be used in three ways:

- Using the `--default-repo` flag
- Setting SKAFFOLD_DEFAULT_REPO environment variable
- Using global config `skaffold config set default-repo <myrepo>`

As user, I think it'll be good to provide a field similar to [`defaultNamespace`](https://skaffold.dev/docs/references/yaml/#deploy-kustomize-defaultNamespace) in Skaffold which can be overridden using availble profiles.

**Comment by briandealwis** [comment] 2021-07-05 20:56
Duplicate of #2317

We do intend to fix this.

**Closed by briandealwis** 2021-07-05 20:56 UTC
