### ISSUE TITLE
Updates of workloads due to ConfigMap changes

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/skaffold#97] opened 2018-02-22 00:02 UTC
When a ConfigMap manifest is updated, users may want that to automatically update the workload that it references. Unfortunately the deployment will only update if the configmap name or any other field changes in the spec.

**Comment by lucperkins** [comment] 2018-08-31 19:51
Having changes to a config file trigger changes to the appropriate ConfigMap, Deployment, etc. would be fantastic, but probably difficult to implement and more suited for a release further down the line. In the short term, however, I think it would be extremely helpful to be able to define configs even *without* auto-updating. Something like this:

```yaml
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    sha256: {}
  local: {}
  artifacts:
  - imageName: my-app
    bazel:
      target: //:my-app.tar
  configs:
  - name: prometheus-config
    file: config/prometheus.yml
  - name: nginx-config
    file: config/nginx.conf
```

**Comment by demisx** [comment] 2019-05-24 16:32
Currently, if I change a value in a config map, skaffold (v0.30) does neither rebuild/apply the updated value. I have to restart it manually for new values to take effect. Is this related to this issue  (or https://github.com/kubernetes/kubernetes/issues/22368) or is there something wrong with my skaffold configuration? I've confirmed that I am not manually syncing my `k8s/` folder.

**Comment by lucperkins** [comment] 2019-05-24 19:05
@demisx The issue is still open. Skaffold does not yet support this desired behavior.

**Comment by demisx** [comment] 2019-05-24 19:14
@lucperkins Got it. Sorry, I wasn't sure if this was the issue I was experiencing or not. I'll be watching!

**Comment by vaidik** [comment] 2019-06-25 16:24
Configmaps get updated but not the deployments referencing them.

**Comment by tstromberg** [comment] 2020-04-20 23:50
I'm closing this issue as it hasn't seen activity in awhile, and if it does still exist, it doesn't seem to be getting any traction at the moment. If this issue appears in the most recent release of Skaffold, please feel free to add a follow-up comment and we will see about getting it prioritized appropriately.

If someone sees a similar issue to this one, please create a new issue, but do include a link to this issue if possible. 

Thank you for sharing this issue with us!

**Closed by tstromberg** 2020-04-20 23:50 UTC
Labels: area/deploy, kind/feature-request, priority/p3

**Comment by JasonMan34** [comment] 2022-12-25 13:18
This is quite a hassle when working with many services locally  
I'm working on a repo with 55 deployments, having to re-launch all of them because I changed the configmap of one is.. less than optimal
