### ISSUE TITLE
skaffold example fails on start

### ISSUE THREAD

**Issue by arashbi** [GoogleContainerTools/skaffold#3117] opened 2019-10-23 16:39 UTC
When I try to run the example, I get an error. The `skaffold dev` command doesn't work.

### Expected behavior
I expect the behavior to be like described in https://skaffold.dev/docs/getting-started/

### Actual behavior
~/s/s/e/getting-started ❯❯❯ skaffold dev                                        ✘ 127 master ◼
Listing files to watch...
 - gcr.io/k8s-skaffold/skaffold-example
FATA[0000] watching files for artifact gcr.io/k8s-skaffold/skaffold-example: listing files: listing files: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (golang:1.12.9-alpine3.10) for ONBUILD triggers: getting remote config: getting image: Get https://auth.docker.io/token?scope=repository%3Alibrary%2Fgolang%3Apull&service=registry.docker.io: invoking docker-credential-desktop: exit status 1; output: No stored credential for https://index.docker.io
### Information

- Skaffold version: v0.40.0
- Operating system: Mac OS
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta16
kind: Config
build:
  artifacts:
  - image: gcr.io/k8s-skaffold/skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*

```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold dev`
3. ...

**Comment by balopat** [comment] 2019-10-24 22:44
Hi @arashbi - can you try running `docker build .` in that same folder?

**Comment by dgageot** [comment] 2019-11-07 14:54
Hi @arashbi, any chance you had time to try `docker build .`?
If we can't reproduce the issue, we can't fix it.

**Comment by wstrange** [comment] 2019-11-12 17:29
I am running into a related issue pulling images from a public gcr.io registry.

I get:
`FATA[0000] watching files for artifact am: listing files: listing files: expanding ONBUILD instructions: parsing ONBUILD instructions: processing base image (gcr.io/forgerock-io/openam:6.5.2) for ONBUILD triggers: getting remote config: getting image: error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: `

I can `docker build` from that directory just fine - without the gcloud credential helper (which should not be needed for public repos).

I also tried `useDockerCLI: true`  and `push: false` options as well - and they did not help

**Comment by wstrange** [comment] 2019-11-12 17:42
Ahh -OK - I think I have a hunch on what is happening. This might be pilot error.

If I edit my docker/config.json  to remove the requirement for the `gcloud` credential helper- it works .

So (speculating...) I suppose if your docker config has at one time authenticated use the cred helper - you must continue to use it - unless you blow away your docker config again. 

The user who reported this to me must have at one point in time had the cred helper installed, but subsequently removed the gcloud SDK?

Confusing - but I think I understand the issue now

**Comment by dgageot** [comment] 2019-11-13 08:15
@wstrange Are you ok if we close this issue since the problem comes from the content of `docker/config.json`? Or maybe you expect Skaffold to do something different?

**Comment by wstrange** [comment] 2019-11-13 13:04
Hi @dgageot 

I did not open the issue - but I suspect it is the same problem that I ran into. I agree it makes sense to close it now because it is not something skaffold can solve.

**Comment by dgageot** [comment] 2019-11-27 17:11
OK. I'm going to close the issue. Feel free to reopen if you think Skaffold can do something about it

**Closed by dgageot** 2019-11-27 17:11 UTC
Labels: area/build, kind/bug, priority/awaiting-more-evidence
