### ISSUE TITLE
Skaffold Dev Mode sync appears broken in v1.28.0

### ISSUE THREAD

**Issue by DGollings** [GoogleContainerTools/skaffold#6219] opened 2021-07-15 12:50 UTC
### Expected behavior

Edit a file, file gets synced

### Actual behavior

Very little, simply doesnt sync. Verbose didn't help
`Skipping deploy due to sync error: copying files: didn't sync any files `
(nothing to do with namespaces as mentioned in other issues)

(a hint, although I assume DEVMODE should handle that: manual kubectl cp fails with a permission denied as buildpacks are afaik read only)

### Information

- Skaffold version:v1.28.0
- Operating system: PopOS 21.04
- Installed via: curl

### Steps to reproduce the behavior

I assume try using devmode in v1.28.0 vs v1.27.0

### Workound
Downgrade to v1.27.0

**Comment by erulabs** [comment] 2021-07-16 22:49
Same situation - both sync and log tailing appears broken in 1.28.0

For example, the config:
```
apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    - image: erulabs/example
      context: .
      sync:
        manual:
          - src: "**/*"
            dest: .
      docker:
        target: development
deploy:
  kustomize:
    paths:
      - k8s/dev
portForward:
  - resourceType: Service
    resourceName: api
    port: 443
    localPort: 4000
    address: 0.0.0.0
```

works fine in 1.27, but broken in 1.28 (same config except schema version changed to skaffold/v2beta19 when using 1.28). Both log tailing and file synching.

**Comment by nkubala** [comment] 2021-07-16 23:00
@DGollings thanks for opening, I'm able to reproduce this using our `getting-started-kustomize` example. investigating now, for now I'd suggest downgrading to `v1.27.0` until we can fix the issue and get a hotfix out.

**Comment by nkubala** [comment] 2021-07-17 00:12
another update: this issue is being caused by https://github.com/GoogleContainerTools/skaffold/pull/6170, which changed the way we aggregate namespaces during a dev run. the effect here is that it's causing `""` to be ignored as a namespace, which is valid in kubernetes land and translates to `default`. so until we get a fix out there are two options:
1) specify a **non-default** namespace to deploy to in your kubernetes manifests. this cannot be specified over the CLI - any namespaces passed via the `--namespace` flag are currently being ignored
2) downgrade to `v1.27.0` or another previous version

really sorry for the inconvenience here folks, we'll get a fix out ASAP.

**Comment by nkubala** [comment] 2021-07-19 17:50
I'm going to close this issue to consolidate related issues and track in https://github.com/GoogleContainerTools/skaffold/issues/6242 - please tune in there for updates!

**Closed by nkubala** 2021-07-19 17:50 UTC
Labels: area/dev, kind/bug, priority/p0
