### ISSUE TITLE
changing default minikube context

### ISSUE THREAD

**Issue by kameshsampath** [GoogleContainerTools/skaffold#1217] opened 2018-10-28 10:30 UTC
/kind quesiton

Is it possible to set `localCluster` via config ? I want to set that to make avoid pushing done for my local cluster.

**Comment by balopat** [comment] 2018-10-29 18:56
I think this is a dupe of https://github.com/GoogleContainerTools/skaffold/issues/1205. 
This is not possible yet, but should be very doable. PRs always welcome :)

**Comment by nkubala** [comment] 2018-11-30 22:49
This will also be possible once we support push configuration in the global config.

**Comment by balopat** [comment] 2019-08-20 21:41
This is possible now with the local cluster on [global config](https://skaffold.dev/docs/concepts/#global-configuration-skaffold-config)!

**Closed by balopat** 2019-08-20 21:41 UTC
Labels: kind/question, platform/minikube
