### ISSUE TITLE
[FR] CompositeTagger TagPolicy

### ISSUE THREAD

**Issue by jonjohnsonjr** [GoogleContainerTools/skaffold#622] opened 2018-05-31 04:53 UTC
I'm interested in using multiple tag policies together as a poor man's https://grafeas.io.

Any plans for something like this? Open to a PR?

**Comment by r2d4** [comment] 2018-05-31 18:35
+1 for me. Not sure if the model should be

1. (no config change) just specify multiple taggers and each one will be applied. Can't specify multiple of the same type (mostly make sense, except envTaggers can be different)
2. (config changE) a list of taggers with types that get applied, can have multiple of the same type

**Comment by radityasurya** [comment] 2018-10-17 07:53
+1

**Comment by btardell** [comment] 2019-07-25 21:14
I'm interested in being able to apply multiple tags too for tracking deployments. Putting everything in a single tag for traceability is not pretty. Individual tags will make this cleaner.

**Comment by balopat** [comment] 2019-07-25 23:32
Also, as @btardell mentioned in https://github.com/GoogleContainerTools/skaffold/issues/2534, supporting this as flags would be interesting.

**Comment by tejal29** [comment] 2019-09-19 21:38
This is dupe of #1269

**Closed by tejal29** 2019-09-19 21:38 UTC
Labels: area/tag, help wanted, kind/feature-request
