### ISSUE TITLE
error adding label to runtime object: patching resource: deployments.apps not found

### ISSUE THREAD

**Issue by r0bj** [GoogleContainerTools/skaffold#1405] opened 2018-12-20 11:39 UTC
### Expected behavior

skaffold properly deploys workload (and add labels) without warning.

### Actual behavior

skaffold deploys workload with warning and without adding labels.

### Information

- Skaffold version: v0.19.0
- Operating system: macOS 10.14.2
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta1
kind: Config
deploy:
  kubectl:
    manifests:
    - ./test.yaml
```

- Contents of test.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: prod
spec:
  selector:
    matchLabels:
      app: nginx-test
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx
```

Note: namespace `prod` is used in this manifest.

### Steps to reproduce the behavior

1. set current kubectl context to use other namespace than `prod`

2. run skaffold
```
$ skaffold run
[...]
WARN[0003] error adding label to runtime object: patching resource /nginx-test: deployments.apps "nginx-test" not found
```

Warning is generated.

3. set current kubectl context to use `prod` namespace:
```
$ skaffold run
Starting build...
Build complete in 331.055µs
Starting test...
Test complete in 8.884µs
Starting deploy...
kubectl client version: 1.13
deployment.apps/nginx-test unchanged
Deploy complete in 658.545266ms
```

Skaffold runs without warnings.

**Comment by r2d4** [comment] 2018-12-20 16:55
There was an issue where labeling was not namespace aware. I'm not sure if I've upstreamed the patch

**Comment by pscarey** [comment] 2019-01-17 02:18
Experiencing a similar issue:

```
...
WARN[0029] error adding label to runtime object: patching resource default/istio-security-post-install-role-binding-istio-system: the server could not find the requested resource
...
```

Lots of other similar errors when installing Istio. We have a helm chart which installs our apps in the `default` namespace, and Istio installs in `istio-system`, under the same chart.

For our case, I believe this is caused by lines 150-155 of `pkg/skaffold/deploy/label.go`:

```
	var namespace string
	if accessor.GetNamespace() != "" {
		namespace = accessor.GetNamespace()
	} else {
		namespace = res.Namespace
	}
```

I believe the logic should be the other way round, i.e. use the `res.Namespace`, and fall back to the `accessor.GetNamespace()`. For us, `accessor` must be in `default`, but `res` should be in `istio-system` for the `istio` components.

I'll be making & testing changes locally, but we need to run them on top of other changes I've made (which there are pull requests for). Wanted to raise this here so that we dont bounce between breaking things for different scenarios.

**Comment by corneliusweig** [comment] 2019-02-05 22:08
Seems to be fixed in master. Release 0.22.0 still has the issue, though.

**Comment by dgageot** [comment] 2019-07-05 13:04
I'm going to close this issue since it seems to be fixed in master

**Comment by lduparc** [comment] 2019-07-31 10:28
Using skaffold 0.34.1, issue still exist, it is not fixed.

**Comment by corneliusweig** [comment] 2019-07-31 12:08
@lduparc Can you provide an example? This issue was closed, because it could not be reproduced.

**Comment by NotSoShaby** [comment] 2019-11-11 10:00
I just had this issue when trying to play with skaffold (v1.0):

skaffold.yaml:

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.BASE_TAG}}"
  artifacts:
  - imageName: <ECR>/<IMAGE_NAME>
    workspace: ..
    docker:
      dockerfilePath: ./Dockerfile
  local:
deploy:
  kubectl:
    manifests:
      - k8s-*
```

k8s-celery-pod.yaml:

```
apiVersion: v1
kind: Pod
metadata:
  name: celery
spec:
  containers:
  - name: celery
    image: <ECR>/<IMAGE_NAME>:<IMAGE_TAG>
    command: "pipenv run celery worker -c 4 -l INFO -A celery.core.celery"
```

Error:

```
Starting deploy...
Cleaning up...
WARN[0001] deployer cleanup: reading manifests: kubectl create: Running [kubectl --context  create --dry-run -oyaml -f l/Desktop/code/romee/k8s/k8s-celery-pod.yaml]: stdout , stderr: Error from server (NotFound): the server could not find the requested resource
, err: exit status 1: exit status 1
FATA[0001] exiting dev mode because first deploy failed: reading manifests: kubectl create: Running [kubectl --context  create --dry-run -oyaml -f /Desktop/code/romee/k8s/k8s-celery-pod.yaml]: stdout , stderr: Error from server (NotFound): the server could not find the requested resource
, err: exit status 1: exit status 1
```

**Comment by corneliusweig** [comment] 2019-11-11 19:25
@NotSoShaby Does your pod manifest really name an image with tag? In that case, Skaffold will just deploy the manifest, but not update the image. Can you try removing the image tag?

**Comment by fredleger** [comment] 2020-06-04 14:50
Just run into the same issue today. So far it seems related to the fact you have transient workload like an init job or a test job (which is now created by default with helm create) that is triggered through helm hooks and deleted **before** skaffold run finish.

Does that make any sense to you ?

**Comment by gsquared94** [comment] 2020-06-08 20:16
Reopening the issue

**Comment by briandealwis** [comment] 2020-08-24 21:27
@NotSoShaby @fredleger could you provide some more details on your reproduction cases?  It sounds like you might have a nice small test case?

**Comment by fredleger** [comment] 2020-09-01 09:59
Hello @briandealwis,

You can find a testbed to reproduce the issue here : https://github.com/fredleger/skaffold-issue-1405

# Steps

## create namespace

```sh
kubectl create ns 1405
kubens 1405
```

## check infos of test case

```sh
kubectl version --short
Client Version: v1.17.9
Server Version: v1.17.4+k3s1
```

```sh
skaffold version
v1.13.2 # also tested with 1.9.1 and 1.10.0
```

## deploy with skaffold helm strategy

```sh
skaffold run
```

# Results

```sh
<SNIP>
WARN[0014] error adding label to runtime object: patching resource 1405/"test-1405-mariadb-test-b7fmj": pods "test-1405-mariadb-test-b7fmj" not found 
WARN[0015] error adding label to runtime object: patching resource 1405/"test-1405-1405-issue-test-connection": pods "test-1405-1405-issue-test-connection" not found
<SNIP>
```

**Comment by briandealwis** [comment] 2020-09-08 14:13
Our Helm deployer currently labels resources as a separate step after deploy.  Short-lived containers may have exited by the time our labeller starts to work.  It's a race condition and there is nothing we can do with our current labelling approach.

**Closed by briandealwis** 2020-09-08 14:13 UTC
Labels: area/labels, deploy/helm, help wanted, kind/bug, priority/p2
