### ISSUE TITLE
Skaffold dev - don't exit if deployment is broken

### ISSUE THREAD

**Issue by HariSekhon** [GoogleContainerTools/skaffold#6205] opened 2021-07-14 09:23 UTC
### Expected behavior

Expect the dev mode watcher to stay running while I fix manifests until the deployment stays working.

### Actual behavior

Skaffold exits out if the deployment fails to pass the container status / health check.

This means I have to continually re-run `skaffold dev` each time I change the manifests until I get it working, somewhat defeating the purpose of the dev mode, as it's then not much different to running `kubectl apply` myself each time, which loses the aspect of automatic Continuous Development.

### Information

- Skaffold version: v1.27.0
- Operating system: macOS
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta18
kind: Config
metadata:
  name: www
deploy:
  statusCheckDeadlineSeconds: 500  # app takes ages to pre-load cache and pass healthcheck
  kubeContext: mycontext
  kustomize:
    paths:
      - ../base
      - .
```

### Steps to reproduce the behavior

With a deployment that fails to bring up its pods, and results in say CrashLoopBackoff, Skaffolds exits out.

```
$ skaffold dev --cleanup=false
....
 - mynamespace:deployment/www failed. Error: container blah terminated with exit code 1.
1/1 deployment(s) failed
$ (exited)
```
or
```
 - mynamespace:deployment/www failed. Error: container blah is backing off waiting to restart.
1/1 deployment(s) failed
$ (exited)
```

**Comment by MarlonGamez** [comment] 2021-07-26 20:34
hey @HariSekhon, hopping in here to say that this is something we'd like to work on soon. We can't give a delivery date right now but we just wanted to give that update

**Comment by tejal29** [comment] 2021-08-09 18:05
related issue  #4158

**Comment by aaron-prindle** [comment] 2022-11-26 20:14
Dupe of #4158 which has recently been re-prioritized.  Closing this issue and tracking the issue/progress in #4158

**Closed by aaron-prindle** 2022-11-26 20:14 UTC
Labels: help wanted, kind/feature-request, priority/p2, area/dev, kind/todo, kind/friction
