### ISSUE TITLE
Skaffold namespace from environment

### ISSUE THREAD

**Issue by TheYkk** [GoogleContainerTools/skaffold#5339] opened 2021-02-03 11:05 UTC
### Expected behavior
Skaffold should get namespace from environment

### Actual behavior
```log
exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User "system:serviceaccount:kaank:kaank" cannot list resource "deployments" in API group "apps" in the namespace "{{.NAMESPACE}}"
```

I was using skaffold v1.17.2 and I upgraded v1.19.0 then skaffold is not worked.
I used `skaffold fix`
### Information

- Skaffold version: v1.19.0
- Operating system: ubuntu:20.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: project
build:
  artifacts:
    - image: myimage
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: project-dev
        chartPath: project
        artifactOverrides:
          image: myimage
        namespace: "{{ .NAMESPACE}}"
        wait: true
    flags:
      install:
        - --timeout=3m
        - --debug
      upgrade:
        - --timeout=3m
        - --install
        - --debug
```

### Steps to reproduce the behavior

1. skaffold fix
2. skaffold dev

**Comment by MarlonGamez** [comment] 2021-02-05 19:59
Hey @TheYkk, thanks for opening this issue :) Could you please post the rest of your output from skaffold as well? It will help pintpoint where the error is coming from

**Comment by TheYkk** [comment] 2021-02-05 20:06
```log
ubuntu@dh22-3p-kaank:~/projects/api$ skaffold dev
Building [api]...
Sending build context to Docker daemon  2.148MB
latest: digest: sha256:613a82cd8835249c6b93cd7da4eaafbbd2114d92620c0c58e6aa0a20790bbeab size: 6602
Tags used in deployment:
 - api -> api:latest@sha256:613a82cd8835249c6b93cd7da4eaafbbd2114d92620c0c58e6aa0a20790bbeab
Starting deploy...
Helm release api not installed. Installing...
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/ubuntu/projects/api/api
client.go:122: [debug] creating 4 resource(s)
wait.go:53: [debug] beginning wait for 4 resources with timeout of 3m0s
wait.go:225: [debug] Deployment is not ready: 3p-kaank/api. 0 out of 1 expected pods are ready
wait.go:225: [debug] Deployment is not ready: 3p-kaank/api. 0 out of 1 expected pods are ready
NAME: api
LAST DEPLOYED: Fri Feb  5 12:02:06 2021
NAMESPACE: 3p-kaank
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
image: api:latest@sha256:613a82cd8835249c6b93cd7da4eaafbbd2114d92620c0c58e6aa0a20790bbeab
persistent:
  enabled: false

COMPUTED VALUES:
affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ""
image: api:latest@sha256:613a82cd8835249c6b93cd7da4eaafbbd2114d92620c0c58e6aa0a20790bbeab
imagePullSecrets:
- name: regcred
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
pullPolicy: IfNotPresent
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  type: ClusterIP
tolerations: []

HOOKS:
MANIFEST:
---
# Source: api/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
---
# Source: api/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    helm.sh/chart: api-0.1.0
    app.kubernetes.io/name: api
    app.kubernetes.io/instance: api
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: api
    spec:
      imagePullSecrets:
        - name: regcred
      securityContext:
        {}
      volumes:
        - name: api-persistent
          emptyDir: {}
        - name: dot-env
          secret:
            secretName: api-secrets
      containers:
        - name: api          
          securityContext:
            {}
          image: "api:latest@sha256:613a82cd8835249c6b93cd7da4eaafbbd2114d92620c0c58e6aa0a20790bbeab"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: api-persistent
              mountPath: /var/www/html/storage
            - name: dot-env
              mountPath: /var/www/html/.env
              subPath: .env
          resources:
            {}
NOTES:
1. Get the application URL by running these commands:
Waiting for deployments to stabilize...
Cleaning up...
release "api" uninstalled
exiting dev mode because first deploy failed: could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User "system:serviceaccount:3p-kaank:3p-kaank" cannot list resource "deployments" in API group "apps" in the namespace "{{ .NAMESPACE}}"
```

**Comment by MarlonGamez** [comment] 2021-02-18 19:05
Thanks for that! I've made the team aware of the issue and I'll update this as we get a fix

**Comment by MarlonGamez** [comment] 2021-05-17 22:14
hi @TheYkk , are you still seeing this issue? I'm unable to repro this locally on v1.24.0

**Comment by netaskd** [comment] 2021-05-27 11:18
@MarlonGamez seems the bug is still here.
```
$ skaffold version
v1.24.1
```
```
$ skaffold run
....
Waiting for deployments to stabilize...
could not fetch deployments: could not fetch deployments: deployments.apps is forbidden: User "username" cannot list resource "deployments" in API group "apps" in the namespace "{{.NAMESPACE}}"
```

**Comment by alewis001** [comment] 2021-05-27 11:18
Hi, I'm using 1.24.1 and I believe I'm seeing both this issue and one related. I can at least reproduce the error message as describe in this issue. 

The environment in which I'm seeing this issue is within Gitlab Pipelines. When it runs the `skaffold deploy` command as part of the pipeline, it's doing so using a Kubernetes Service Account that is restricted to a specific namespace. That namespace is being passed to the `deploy` command as a `-n` parameter (`skaffold deploy -p <profile> -n $KUBE_NAMESPACE ...`) 

The deploy part works fine; however, when the deploy command comes to do a status check it fails, but it fails because it tries to check against the namespace defined in the `deploy` section of `skaffold.yaml`, not the namespace defined by the `-n` argument.

Consequently, I tried the approach described in this issue by using `namespace: "{{ .NAMESPACE}}"`; however, I then run in to this exact issue where the NAMESPACE property is not being substituted. In my case, I was hoping that it would be substituted by whatever value is used in the `-n` argument.

**Comment by briandealwis** [comment] 2021-05-30 01:43
It looks like Helm `Deploy()` isn't treating the Helm release's namespace field as templated.
https://github.com/GoogleContainerTools/skaffold/blob/054953092f59bfa3c126e4f8623d7282c1f711b4/pkg/skaffold/deploy/helm/deploy.go#L142-L147

It should be using [`releaseNamespace()`](https://github.com/GoogleContainerTools/skaffold/blob/054953092f59bfa3c126e4f8623d7282c1f711b4/pkg/skaffold/deploy/helm/util.go#L156-L167) to reference the namespace

**Comment by briandealwis** [comment] 2021-05-30 03:53
I tried to reproduce this issue using the Skaffold [`example/helm-deployment`](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/helm-deployment) example with the following patch:
```diff
--- examples/helm-deployment/skaffold.yaml
+++ examples/helm-deployment/skaffold.yaml
@@ -10,3 +10,5 @@ deploy:
       chartPath: charts
       artifactOverrides:
         image: skaffold-helm
+      namespace: "{{ .NAMESPACE}}"
```

But it all seemed to work fine for me.  @netaskd @TheYkk @alewis001 can you please try reproducing with the newly released Skaffold v1.25.0 and include the results of logging with `-v debug`?

**Comment by briandealwis** [comment] 2021-05-31 18:21
I suspect this was fixed with #5723 (released in v1.23.0) which simplified checking the deployment.

**Comment by alewis001** [comment] 2021-06-01 11:17
Thanks, I'll try to get this tested with 1.25.0 today.

Which bit was fixed in 1.23.0 as both of the issues I ran into (this one and -n appears to not be passed down to the helm status check after deploy) were seen with 1.24.1?

**Comment by alewis001** [comment] 2021-06-01 13:27
Attached is a run where there is only a namespace set in the default `deploy` section of skaffold.yaml and `-n targetnamespace` on the deploy command line. As the `-n` works for the actual deployment part of the `deploy` command I would have expected the status check to work but that's where it fails with the error message:

`could not fetch deployments: deployments.apps is forbidden: User "system:serviceaccount:myproject-mycomponent:-123456-staging:myproject-mycomponent-123456-staging-service-account" cannot list resource "deployments" in API group "apps" in the namespace "myproject"` where `myproject` is the value in the default deploy section of the skaffold.yaml rather than the value given with `-n`. 

As this is in a corporate environment I had to remove some of the lines and switch out sensitive info. Where I removed a line/content I have put `***REMOVED***`.

I'll repeat the build with the build with the skaffold structure as suggested by this issue.

[skaffold-1.25.0-ns-command-line.txt](https://github.com/GoogleContainerTools/skaffold/files/6576548/skaffold-1.25.0-ns-command-line.txt)

**Comment by alewis001** [comment] 2021-06-01 13:50
Here's the output with `{{.NAMESPACE}}` in the skaffold.yaml; same behaviour. 

[skaffold-1.25.0-ns-command-line-NAMESPACE_VAR.txt](https://github.com/GoogleContainerTools/skaffold/files/6576679/skaffold-1.25.0-ns-command-line-NAMESPACE_VAR.txt)

**Comment by briandealwis** [comment] 2021-10-04 15:01
I tested this with Skaffold at HEAD (v1.33.0) and this all seems to work fine.

**Closed by briandealwis** 2021-10-04 15:01 UTC
Labels: kind/bug, deploy/helm, priority/p2, needs-reproduction, area/status-check
