### ISSUE TITLE
Is it possible to run a custom script before a kaniko image build?

### ISSUE THREAD

**Issue by bitsofinfo** [GoogleContainerTools/skaffold#3681] opened 2020-02-12 20:55 UTC
Is it possible to run a custom script before a kaniko image build?

I have need to generate a Dockerfile right before kaniko runs

**Comment by bitsofinfo** [comment] 2020-02-14 20:19
https://kubernetes.slack.com/archives/CABQMSZA6/p1581538776128400

**Comment by dgageot** [comment] 2020-02-20 09:36
Closing as a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/1441

**Closed by dgageot** 2020-02-20 09:36 UTC
