### ISSUE TITLE
Helm [UPDATED] docs only partially?

### ISSUE THREAD

**Issue by falcorocks** [GoogleContainerTools/skaffold#8048] opened 2022-11-07 09:59 UTC
Hey all,

I'm trying to use v2 with helm, but I can't get the image tagging to override as intended. I may be missing something, but It looks like the docs were updated only partially:

section title at https://skaffold.dev/docs/pipeline-stages/deployers/helm/#configuring-your-helm-project-with-skaffold says 
```
No more `artifactsOverride`
Skaffold no longer requires the intricate configuring of artifactsOverride and image naming strategies.
```

but then the immediately following subsection https://skaffold.dev/docs/pipeline-stages/deployers/helm/#image-configuration gives an example using `artifactsOverride`, which skaffold v2 is not happy with!

So without a working example in the docs, how do I configure helm and images overrides in v2?

**Comment by johnnyhuy** [comment] 2022-11-07 11:57
Used `setValuesTemplates` instead based on this [document](https://skaffold.dev/docs/environment/templating/)

```yaml
---
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: example
build:
  artifacts:
    - image: examplecr
deploy:
  helm:
    releases:
      - name: example
        chartPath: charts/example

        # this
        setValueTemplates:
          image: '{{.IMAGE_REPO}}:{{.IMAGE_TAG}}'
```

Not sure if this is expected to be the official solution 🤔

**Comment by renzodavid9** [comment] 2022-11-07 16:06
Related with #8002

**Comment by aaron-prindle** [comment] 2022-11-07 18:10
Thanks for pointing this out, we are currently working on updating this.  If you use `skaffold fix` this should update your skaffold.yaml value to have the appropriate `setValues` or `setValueTemplates` stanza (from the now removed `artifactOverrides`).  Closing as dupe of #8002, follow along there for updates here.

**Closed by aaron-prindle** 2022-11-07 18:10 UTC
