### ISSUE TITLE
SIGSEV if invalid chartPath in Helm deployment

### ISSUE THREAD

**Issue by stevesea** [GoogleContainerTools/skaffold#1243] opened 2018-11-06 21:12 UTC
### Expected behavior

`skaffold dev` builds via jib-maven and autodeploys via helm

### Actual behavior

`skaffold dev` crashes with SIGSEV

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1d563e1]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).Dependencies.func1(0xc420040390, 0x10, 0x0, 0x0, 0x223e460, 0xc420322600, 0x20, 0x1fc3900)
        /go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/helm.go:88 +0x41
path/filepath.Walk(0xc420040390, 0x10, 0xc420638480, 0xc4206569e0, 0x17)
        /usr/local/go/src/path/filepath/path.go:401 +0x6c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).Dependencies(0xc42004c280, 0x30, 0xc4203225a0, 0x0, 0xc4204ea000, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/helm.go:87 +0x8d
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Dev.func6(0xc4203225a0, 0x10, 0x10, 0xc4205a4550, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/runner.go:354 +0x33
github.com/GoogleContainerTools/skaffold/pkg/skaffold/watch.Stat(0xc4205a4570, 0xc4200d0188, 0x1, 0x1)
        /go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/watch/changes.go:36 +0x4a
github.com/GoogleContainerTools/skaffold/pkg/skaffold/watch.(*watchList).Register(0xc420588140, 0xc4205a4570, 0xc4205a4580, 0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/watch/watch.go:50 +0x2f
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Dev(0xc420200240, 0x22595e0, 0xc4203a5f00, 0x223e420, 0xc4200d0008, 0xc420476038, 0x1, 0x1, 0xc420386b00, 0xc4204d5c80, ...)
        /go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/runner.go:353 +0x79f
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.dev(0x223e420, 0xc4200d0008, 0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:73 +0x16a
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.NewCmdDev.func1(0xc4202f1400, 0x2ba1ac8, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:36 +0x33
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202f1400, 0x2ba1ac8, 0x0, 0x0, 0xc4202f1400, 0x2ba1ac8)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:762 +0x468
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2b6e140, 0xc4202f1400, 0xc4202f1180, 0xc4202f0f00)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).Execute(0x2b6e140, 0xc4200d0008, 0x223e420)
        /go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x0, 0x0)
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:27 +0x58
main.main()
        /go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:26 +0x22
```

### Information

- Skaffold version: v0.17.0
- Operating system: mac osx
- Contents of skaffold.yaml:

```yaml
---
apiVersion: skaffold/v1alpha5
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: svc
      context: .
      jibMaven: {}
deploy:
  helm:
    releases:
      - name: svc-rel
        chartPath: charts/svc
        namespace: default
        values:
          imageName: svc
```

after a little digging, realized that my chartPath is invalid -- i should have used `chart/svc` rather than `charts/svc`

### Steps to reproduce the behavior

1. create a skaffold.yaml with a bad path to the helm charts
2. run `skaffold dev`

**Comment by balopat** [comment] 2018-11-08 21:09
Thank you, for filing this, yes, we should fail more gracefully in this case instead of panic.

**Comment by balopat** [comment] 2018-11-13 23:14
This is a dupe of #1215.

**Closed by balopat** 2018-11-13 23:14 UTC
Labels: bug, good first issue, helm
