### ISSUE TITLE
skaffold build throws error : applying default repo to "test-api:test-api:0.1.0-d69db0d": invalid reference format

### ISSUE THREAD

**Issue by Snehil03** [GoogleContainerTools/skaffold#5980] opened 2021-06-08 21:12 UTC

**Comment by Snehil03** [comment] 2021-06-08 21:17
```
+ skaffold build -p $TARGET -vdebug --default-repo $DOCKER_REGISTRY --file-output ./dist/artifacts.json
time="2021-06-08T20:52:35Z" level=info msg="Skaffold &{Version:v1.25.0 ConfigVersion:skaffold/v2beta16 GitVersion: GitCommit:c788c2b15fc3b3a002edcff25b5ef33563d5bb9c BuildDate:2021-05-26T03:29:00Z GoVersion:go1.14.14 Compiler:gc Platform:linux/amd64 User:}"
time="2021-06-08T20:52:35Z" level=info msg="Loaded Skaffold defaults from \"/root/.skaffold/config\""
time="2021-06-08T20:52:35Z" level=debug msg="config version out of date: upgrading to latest \"skaffold/v2beta16\""
time="2021-06-08T20:52:35Z" level=debug msg="parsed 1 configs from configuration file /opt/atlassian/pipelines/agent/build/skaffold.yaml"
time="2021-06-08T20:52:35Z" level=info msg="applying profile: tagged"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field Build"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field artifacts"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field insecureRegistries"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field tagPolicy"
time="2021-06-08T20:52:35Z" level=info msg="no values found in profile for field TagPolicy, using original config values"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field BuildType"
time="2021-06-08T20:52:35Z" level=info msg="no values found in profile for field BuildType, using original config values"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field Test"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field Deploy"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field DeployType"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field helm"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field kpt"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field kubectl"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field kustomize"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field statusCheck"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field statusCheckDeadlineSeconds"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field kubeContext"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field logs"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field prefix"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field PortForward"
time="2021-06-08T20:52:35Z" level=info msg="applying profile: azure-develop"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field Build"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field artifacts"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field insecureRegistries"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field tagPolicy"
time="2021-06-08T20:52:35Z" level=info msg="no values found in profile for field TagPolicy, using original config values"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field BuildType"
time="2021-06-08T20:52:35Z" level=info msg="no values found in profile for field BuildType, using original config values"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field Test"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field Deploy"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field DeployType"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field helm"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field kpt"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field kubectl"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field kustomize"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field statusCheck"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field statusCheckDeadlineSeconds"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field kubeContext"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field logs"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field prefix"
time="2021-06-08T20:52:35Z" level=debug msg="overlaying profile on config for field PortForward"
time="2021-06-08T20:52:35Z" level=info msg="Using kubectl context: "
time="2021-06-08T20:52:35Z" level=debug msg="Running command: [minikube version --output=json]"
time="2021-06-08T20:52:35Z" level=debug msg="setting Docker user agent to skaffold-v1.25.0"
time="2021-06-08T20:52:35Z" level=debug msg="Using builder: local"
time="2021-06-08T20:52:35Z" level=debug msg="push value not present in NewBuilder, defaulting to true because cluster.PushImages is true"
time="2021-06-08T20:52:35Z" level=info msg="build concurrency first set to 1 parsed from *local.Builder[0]"
time="2021-06-08T20:52:35Z" level=info msg="final build concurrency value is 1"
time="2021-06-08T20:52:35Z" level=debug msg="Running command: [helm version --client]"
time="2021-06-08T20:52:35Z" level=debug msg="Command output: [version.BuildInfo{Version:\"v3.2.0\", GitCommit:\"e11b7ce3b12db2941e90399e874513fbd24bcb71\", GitTreeState:\"clean\", GoVersion:\"go1.13.10\"}\n]"
Generating tags...
time="2021-06-08T20:52:35Z" level=debug msg="Running command: [tput colors]"
time="2021-06-08T20:52:35Z" level=debug msg="error checking for color support: checking terminal colors: starting command tput colors: exec: \"tput\": executable file not found in $PATH"
invalid reference format
2021-06-08T20:52:35.481574326Z stdout P  - test-api -> 
```

**Comment by tejal29** [comment] 2021-06-09 00:06
@Snehil03 closing this as dupe of #5979.

**Closed by tejal29** 2021-06-09 00:06 UTC
Labels: area/default-repo, needs-actionable-error, priority/p2
