### ISSUE TITLE
only one element in set deploy can be set

### ISSUE THREAD

**Issue by dkirrane** [GoogleContainerTools/skaffold#2334] opened 2019-06-25 15:47 UTC
### Expected behavior
This worked in previous versions I believe. And it is a good feature.

I was using it do deploy extra yaml not included in Helm Chart. In my case I'm using kubectl to add a Istio VirtualService yaml for keycloak since its not in Helm chart.

### Actual behavior 
```
$ skaffold deploy
time="2019-06-25T16:41:53+01:00" level=fatal msg="creating runner: invalid skaffold config: only one element in set deploy can be set. got HelmDeploy and KubectlDeploy"
```

### Information

- Skaffold version: version. v0.32.0
- Operating system: windows
Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
deploy:

  helm:
    releases:
      - name: keycloak
        chartPath: codecentric/keycloak
        skipBuildDependencies: true

  kubectl:
    manifests:
      - other/*.yaml
```

### Steps to reproduce the behavior

1. skaffold deploy

**Comment by seblegall** [comment] 2019-06-28 05:56
@dkirrane just to be sure, have you seen it works yourself in previous version? 

Because the code of the first config seems to says it as always been only on of possible deploy type : 
https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/schema/v1alpha1/config.go#L75

How should this work? Deployment should be done iteratively in the order they are declared in the  config file?

If we change the behavior here, we would also need to change it in the `profile` section which let you override the deploy section.

**Comment by dkirrane** [comment] 2019-07-16 21:42
@seblegall  yes it think  deploy in order they appear in the skaffold would be enough.

**Comment by ccll** [comment] 2019-08-21 08:41
I think this is a valid use case, in my setup I'd like to deploy MySQL or other 3rdparty/standard components through helm as there are already plenty charts around, for my own code container I'd like to deploy them through kubectl as this is quicker and easier (avoid writing my own helm chart files).

Unfortunately we can't mix multiple deployers now.

**Comment by balopat** [comment] 2019-09-20 23:45
I am going  to close this as a dupe of https://github.com/GoogleContainerTools/skaffold/issues/528 where we will track this feature request. Thank you! Please put thumbs up there :)

**Closed** 2019-09-20 23:45 UTC
Labels: area/deploy, kind/feature-request, priority/p2
