### ISSUE TITLE
Docker images with Java 17 JDK

### ISSUE THREAD

**Issue by MaxGrosshandler** [GoogleContainerTools/skaffold#7076] opened 2022-02-03 15:49 UTC
### Expected behavior
I would like to be able to select a Docker image of Skaffold, example: v1.35.2 with Java 17 JDK as there is a potential need to use the latest LTS version of Java for a project I'm working on

### Actual behavior
The image only works with JDK 11 currently. Would it be possibly to have images made with Java 17 JDK?
### Information

- Skaffold version: v1.35.2
- Operating system: Linux

**Comment by aaron-prindle** [comment] 2022-02-22 05:22
The JDK 11 import comes from this line here in the skaffold image Dockerfile:
https://github.com/GoogleContainerTools/skaffold/blob/main/deploy/skaffold/Dockerfile.deps#L154

As a potential workaround in the short-term, you could build your own image from skaffold source modifying the line above and then using the `release-build` Makefile rule to build the image locally (https://github.com/GoogleContainerTools/skaffold/blob/main/Makefile#L155-L162):
```
~/skaffold $ make release-build
```

**Comment by aaron-prindle** [comment] 2022-02-22 05:22
I've added this issue for discussion in our team's weekly meeting, I will update the thread here to see if updating our image to JDK 17 or possibly adding an additional image might make sense here to support use cases like yours

**Comment by aaron-prindle** [comment] 2022-02-28 19:24
Closing this as it is a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/6012.  The suggestion there that resolved the issue was a user creating their own image - https://github.com/GoogleContainerTools/skaffold/issues/6012#issuecomment-865253244

> Many newer Maven plugins no longer work with JDK 8. Our gcr.io/k8s-skaffold/skaffold image is already too hefty.
> 
> I can think of a few alternatives:
> 
> You could create your own image using gcr.io/k8s-skaffold/skaffold as a base image and install a Java 8 JDK and configure toolchains.
> You could create your own image using your JDK of choice and install Skaffold there. The latest release can be obtained from https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64

**Comment by calebdelnay** [comment] 2022-02-28 19:34
@aaron-prindle Not really sure I understand this choice. Is there no desire to provide both a JDK 11 container image and JDK 17 container image as two separate choices? If not, then when does the singular Skaffold image move from JDK 11 to JDK 17 as the default? Why even provide an image with any JDK at all?

**Comment by aaron-prindle** [comment] 2022-03-09 22:49
@calebdelnay sorry for the delay on the response here.  From the similar issue linked  - https://github.com/GoogleContainerTools/skaffold/issues/6012 the precendent here is that user's can build their own image that includes JDK 17.  Currently

**Comment by s-aliasgar** [comment] 2022-09-13 09:26
Hi @aaron-prindle ,
Any updates on this feature?
Additionally, can you share some documentation to be followed for creating our own skaffold image with a different JDK

**Comment by akshay26031996** [comment] 2022-09-14 09:58
> The JDK 11 import comes from this line here in the skaffold image Dockerfile: https://github.com/GoogleContainerTools/skaffold/blob/main/deploy/skaffold/Dockerfile.deps#L154
> 
> As a potential workaround in the short-term, you could build your own image from skaffold source modifying the line above and then using the `release-build` Makefile rule to build the image locally (https://github.com/GoogleContainerTools/skaffold/blob/main/Makefile#L155-L162):
> 
> ```
> ~/skaffold $ make release-build
> ```

We were able to build Java 17 project using skaffold. Additionally, we did the following things:
1. After changing in Dockerfile.deps, we need to build the image. To locally build the image
```
cd skaffold
docker build \
	-f deploy/skaffold/Dockerfile.deps \
	-t build_deps:v1 .
```

2. After that, we need to reference this image in Dockerfile
```
vim deploy/skaffold/Dockerfile
```
Change base image to reference to the newly created deps image
```
FROM build_deps:v1 as build
...
```
3. Finally run `make release-build`

**Comment by aaron-prindle** [comment] 2022-11-01 19:28
Thanks for the patience here everyone, I have added this work to our current milestone and we plan on keeping this up to date with the latest LTS release of the JDK in the future

**Comment by aaron-prindle** [comment] 2022-11-22 00:28
The skaffold image has been updated to use JDK 17.  Currentlyt this is only available in our `edge` CI/CD builds available at - `gcr.io/k8s-skaffold/skaffold:edge`:
```
aprindle@aprindle-ssd ~/skaffold  [fix-7995]$ docker run -it --entrypoint=/bin/sh gcr.io/k8s-skaffold/skaffold:edge
# java --version
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing)
```

The next release - `v2.1.0` and future releases will have this image available then.  Marking closed (fixed)

**Closed by aaron-prindle** 2022-11-22 00:28 UTC
Labels: kind/feature-request, area/build, priority/p2, java, area/ci-cd, release/new-feature
