### ISSUE TITLE
artifacts.hook.after and before doesn't login to container registry on host

### ISSUE THREAD

**Issue by rstoermer** [GoogleContainerTools/skaffold#7469] opened 2022-06-01 06:18 UTC
### Expected behavior
I am executing a hook to login to our container registry. The login should work

### Actual behavior
I am not logged in and have to do it manually:
build [XXXXX.azurecr.io/orchestrator] failed: getting image: POST https://XXXXX.azurecr.io/oauth2/token: unexpected status code 401 Unauthorized

### Information

- Skaffold version: v1.38.0
- Operating system: OS X most current
- Installed via: Homebrew
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
      push: false
      useDockerCLI: true
      useBuildkit: true
  artifacts:
      - image: XXXXXXX.azurecr.io/orchestrator
        hooks:
          after:
          - command: ["az", "acr", "login", "-n", "nextordev"]
            os: [darwin]
        context: .
        docker:
            dockerfile: Dockerfile
            target: local
            buildArgs:
                NPM_TOKEN: "{{ .NPM_TOKEN }}"
        sync:
            manual:
                # Sync all folders relevant for application development
                - src: "src/**"
                  dest: .
```

before also doesn't work

**Comment by gsquared94** [comment] 2022-08-14 19:03
can you provide the output of running with the `-v DEBUG` flag, after redacting sensitive info? Does the `az acr login` command succeed when run as a hook?

**Comment by ericzzzzzzz** [comment] 2023-09-26 20:34
This is probably caused by Skaffold didn't respect docker context, if DOCKER_SOCKET is not set. The current behavior is that DOCKER_SOCKET is not set skaffold will try to use the socket defined for the current context. I'm closing this. If the issue still exists, please leave a comment. I'll re-open it :)

**Closed by ericzzzzzzz** 2023-09-26 20:34 UTC
Labels: kind/bug, priority/p2, area/registry
