### ISSUE TITLE
Wrong error: "error deleting inventory object configmaps 'inventory-XXX' not found" 

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#4985] opened 2020-11-02 09:46 UTC
skaffold cleanup should check the existence of the inventory in the cluster before the deletion.

This error is a no-op but causes user confusions.
### Information

- Skaffold version: v1.15.0+

**Comment by tejal29** [comment] 2020-11-02 17:51
closing this as dupe of #4984

**Closed by tejal29** 2020-11-02 17:51 UTC
Labels: deploy/kpt, kind/bug
