### ISSUE TITLE
skaffold init for Java applications

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/skaffold#1264] opened 2018-11-09 18:51 UTC
### Expected behavior
`skaffold init` on a Java project (with Maven or Gradle) will produce the default `skaffold.yaml` with the  corresponding Jib builder configuration.

### Actual behavior
`skaffold init` requires Dockerfile to be present and fails with:
`FATA[0001] one or more valid Dockerfiles must be present to run skaffold; please provide at least one Dockerfile and try again `

However, Dockerfile is not needed for Jib.

### Information

- Skaffold version: 0.17
- Operating system: OSX

### Steps to reproduce the behavior

1. Create a new Java project that uses either Maven or Gradle.
1. Run `skaffold init`

**Comment by dgageot** [comment] 2018-11-09 18:55
That's a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/1093 but I'm going to keep your ticket because it's more detailed :-)

**Comment by coollog** [comment] 2018-11-09 22:11
Some options for when there might be a mix of Dockerfiles and Maven/Gradle.

- default to Dockerfile if present, choose between Dockerfiles if multiple
- default to Maven/Gradle if `pom.xml/mvnw`/`build.gradle/gradlew` detected, choose between Maven/Gradle if both present
- survey with choices for use Dockerfile, jibGradle, or jibMaven

I think we should go with the survey with all the choices since otherwise, it would be hard to differentiate which artifact should use which.

**Comment by loosebazooka** [comment] 2018-11-09 22:15
I like the survey idea.

Is skaffold init designed to only work for single artifacts at the moment? I imagine it would get pretty complex pretty fast if it started searching for one or more artifacts to configure.

**Comment by dgageot** [comment] 2019-11-07 14:42
This can be close, we are waiting for https://github.com/GoogleContainerTools/skaffold/issues/2842 to make this feature active.

**Closed by dgageot** 2019-11-07 14:42 UTC
Labels: area/init, build/jib, kind/feature-request, priority/p1
