### ISSUE TITLE
Generated schemas have 'http://json-schema-org' instead of 'http://json-schema.org'

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6482] opened 2021-08-20 17:40 UTC
Reported from `@seankhliao` on the #skaffold Kubernetes channel
> should this line be json-schema.org instead of json-schema-org? https://github.com/GoogleContainerTools/skaffold/blob/7363674d131daa16b0af81bebf2ae83620b980fd/hack/schemas/main.go#L41

All of our generated Skaffold schemas have this schema reference.  For example:
https://github.com/GoogleContainerTools/skaffold/blob/7363674d131daa16b0af81bebf2ae83620b980fd/docs/content/en/schemas/v2beta8.json#L8

Marking as low priority as there's no clear impact as the validators seem to have no issue accepting this schema value.

**Comment by tejal29** [comment] 2022-05-09 19:05
close dupe of #7298

**Closed by tejal29** 2022-05-09 19:05 UTC
Labels: kind/bug, priority/p3, area/schemas
