### ISSUE TITLE
support for helm oci

### ISSUE THREAD

**Issue by MarcoSchaar** [GoogleContainerTools/skaffold#5418] opened 2021-02-19 15:58 UTC
Hi 
is there something planned to implement support for

https://helm.sh/docs/topics/registries/#enabling-oci-support 

that a given helm chart is pulled from e.g. registry before deployment?
cheers
Marco

**Comment by tejal29** [comment] 2021-02-24 01:49
We are thinking of revamping helm support for skaffold.  We could definitely explore this.

We are tracking all helm support requests here #5442
/cc @nkubala

**Comment by havenotfear** [comment] 2021-04-12 21:10
This would be great. 👍

**Comment by eshepelyuk** [comment] 2021-10-30 07:02
It would be also great to allow pushing charts to OCI registries during the build, as for container images.

**Comment by CrystalMethod** [comment] 2022-01-31 09:27
With Helm 3.8 OCI support has become generally available.

https://github.com/helm/helm/releases/tag/v3.8.0

**Comment by tejal29** [comment] 2022-02-28 22:44
duplicate of #7127

**Closed by tejal29** 2022-02-28 22:44 UTC
Labels: kind/feature-request, area/deploy, deploy/helm, priority/p2
