### ISSUE TITLE
kubectl deployer should not replace fully qualified image names

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#565] opened 2018-05-18 05:00 UTC
Currently, the `kubectl` deployer scans all k8s manifests for images names and replace those that are listed in the artifacts section with a fully qualified name, ignoring any tag that might be specified.

I believe we should only replace images names without tag or with tag `latest`.

Skaffold is building the artifacts and removes from me the need to edit all the manifests each time. It should still let me use an older, properly tagged, fully qualified image. That's currently not possible.

**Comment by jonjohnsonjr** [comment] 2018-05-18 05:12
I'm not 100% familiar with the implementation, so my suggestion might be stupid, but I'm generally -1 on anything that has different semantics based on the tag name. Kubernetes does this with "latest" and it's a huge source of headaches. See https://github.com/google/go-containerregistry/issues/143#issuecomment-389521793 for a recent example of this, but I see people trip over the "latest" tag magic constantly.

Again, I lack context for what you're doing here, but perhaps you can apply this heuristic to images that are referenced by digest instead? (Perhaps you already do?) Using a digest is a pretty strong signal that the user wants to pin that exact image version, so it seems to align well with your goal.

**Comment by jonjohnsonjr** [comment] 2018-05-18 05:41
My problem with this is that in most contexts, unqualified image references are implicitly tagged with "latest", i.e. for basically every tool that currently exists, these are equivalent:
* `ubuntu`
* `ubuntu:latest`

This change would add another exception to my mental model of image references, and that list of exceptions is already quite long :-/

> Images with fully qualified names (tag or digest) should be left untouched. The user clearly indicated that they want to use a very specific version of the image. That's what need to be fixed

I don't 100% agree with you here. Perhaps they are just using known-good tags as a starting point, but would like skaffold to replace them when they are iterating on their project. Also, since tags are mutable, I don't think referencing a specific tag necessarily indicates that they want to use a *very* specific version. They would be using a digest in that case :)

Thinking out loud, how would you feel about a tool that "freezes" image references by resolving tags to digests? We could do a similar pass over the k8s manifests and just replace any tags with digests. Then for the images that they *do* want to be skaffoldized, users can just truncate the reference to the unqualified image name.

I'm a lot more comfortable with "we won't replace digests, here's a tool for resolving tags to digests" than skaffold-unique heuristics re: tag names. 

> Replace it because the user basically said they want the freshest image

I don't think that's necessarily the case. The "latest" tag is only "latest" by convention, and usually only with inexperienced docker users -- I think this is the most commonly hit footgun that ships with docker.

> Leave it untouched and have the user suffer a bit then realize that latest is evil.

Of these two options, and given my previous sentence, I think I'm okay with "punishing" people for intentionally using "latest", since they should know better :^) we could also print some warning here because it might not be expected behavior.

**Comment by dgageot** [comment] 2018-05-18 05:48
Just for the record: My proposal would treat `ubuntu` and `ubuntu:latest` the same way. No additional exception to be added to your mental model!

I like what you are saying about still replacing tagged images with their latest digest. Tags can be moved, skaffold could try to detect that and update the manifests accordingly.
It's not what we are doing right now. We are replacing tagged images with the digest of `latest`. This is VERY wrong.

My proposal of not replacing tagged image names would not meet your expectations but would be more correct than what we do now.

**Comment by jonjohnsonjr** [comment] 2018-05-18 05:53
Sure -- I think this option breaks my model the least :) you are still breaking my mental model where "latest" is just a normal tag, like any other.

> It's not what we are doing right now. We are replacing tagged images with the digest of latest. This is VERY wrong.

Oh! This is terrible! :) Why?

I think this is a step in the right direction, then. I don't want the perfect to be the enemy of the good, so I won't try to block it (as if I could :P), but we should definitely keep pushing this forward.

**Comment by dgageot** [comment] 2018-05-18 06:01
Yes, what we do with tags is terrible right now!

I don't understand how this proposal treats "`latest` as a normal tag". I think we are on the same line but my explanation must be flawed...

I'd like to:
 + Treat `ubuntu` and `ubuntu:latest` equally by replacing them both with the fully qualified name of the image that Skaffold just built.
 + Partially unbreak the behavior for other fully qualified name by NOT replacing them with the fully qualified name of the image that Skaffold just built.

**Comment by jonjohnsonjr** [comment] 2018-05-18 06:16
Sorry, I was not very clear. I think doing this consistently is impossible due to two things:

1. `ubuntu` == `ubuntu:latest`
2. `latest` is just a tag, like any other.

Images are not automatically tagged with `latest` when you push them _unless_  you omit the tag when you push it. If you're using the docker client, then if you do something like:

`docker push my-namespace/my-image`

you are implicitly doing this:

`docker push my-namespace/my-image:latest`.

From the registry's perspective, there is no special handling of "latest" tags.

Thus:
* If you replace only "untagged" images, you are violating [1] by not treating an "untagged" image as implicitly `latest`.
* If you replace both "untagged" images and `latest` images, you are violating [2] by treating `latest` tags differently from other tags.

Which is why I'm proposing only skipping images that are referenced by digest. There is a precedent for digests having different behavior in both docker and kubernetes already, so this would keep me happy.

**Closed** 2018-05-21 16:32 UTC
Labels: area/deploy, bug, kubectl
