### ISSUE TITLE
skaffold.yaml

### ISSUE THREAD

**Issue by lucasmaj** [GoogleContainerTools/skaffold#4615] opened 2020-08-03 03:00 UTC
### Expected behavior
https://skaffold.dev/docs/references/yaml/ has content describing all the options for skaffold.yaml
### Actual behavior
https://skaffold.dev/docs/references/yaml/ is devoid of any information describing skaffold.yaml

**Comment by jelleklaver** [comment] 2020-08-03 14:44
Hi, I just noticed that it doesn't work too.

I suppose it is due to the following JS error:

```js
main.js:83 Uncaught (in promise) TypeError: Cannot read property 'properties' of undefined
    at template (main.js:83)
    at template.next (<anonymous>)
    at NodePart.__commitIterable (parts.ts:305)
    at NodePart.commit (parts.ts:222)
    at TemplateInstance.update (template-instance.ts:53)
    at NodePart.__commitTemplateResult (parts.ts:277)
    at NodePart.commit (parts.ts:218)
    at NodePart.__commitIterable (parts.ts:320)
    at NodePart.commit (parts.ts:222)
    at TemplateInstance.update (template-instance.ts:53)
```

Which points to the following code:
```js
...
81    // Check if the referenced description is a final one
82    const refName = definition.$ref.replace('#/definitions/', '');
83    if (!definitions[refName].properties && !definitions[refName].anyOf) {
84        value = '{}';
85    }
...
```

Haven't really looked into it and don't know the source of the variables, but it might be fixed by first checking if `definitions[refName]` exists?

**Comment by nkubala** [comment] 2020-08-03 20:21
closing as a dupe of #4614, thanks for the info though! fix coming soon.

**Closed by nkubala** 2020-08-03 20:21 UTC
