### ISSUE TITLE
Google Cloud Build logging options

### ISSUE THREAD

**Issue by giladsh1** [GoogleContainerTools/skaffold#2637] opened 2019-08-12 19:18 UTC
It seems like Skaffold is hammering the 
when running with google cloud build builder, I got the following error message - 
```
FATA[0476] failed to build: build failed: building [eu.gcr.io/riscale/http]: getting build status: googleapi: Error 429: Quota exceeded for quota metric 'cloudbuild.googleapis.com/get_requests' and limit 'GetRequestsPerMinutePerProject' of service 'cloudbuild.googleapis.com' for consumer 'project_number:<project number>'., 
rateLimitExceeded
```

### Expected behavior
implement a proper backoff when using google cloud build API.
Also, allow additional options for google cloud build logging such as -
```
options:
  logging: GCS_ONLY
  logStreamingOption: STREAM_ON
```
 
### Actual behavior
the build crashes
### Information

- Skaffold version: v0.35.0
- Operating system: MacOS
- Contents of skaffold.yaml:

**Comment by balopat** [comment] 2019-08-13 16:56
Thank you for opening this!

Regarding the rate limit backoff request, that is a dupe of #https://github.com/GoogleContainerTools/skaffold/issues/1589, so I'll reopen #1589 to track that work. 

I'll keep this issue as a feature request for GCB logging options.

**Closed** 2020-04-29 08:33 UTC
Labels: area/build, build/gcb, kind/feature-request, platform/gcp, priority/p1
