### ISSUE TITLE
post helm deploy: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bitsofinfo** [GoogleContainerTools/skaffold#3689] opened 2020-02-14 22:12 UTC
### Expected behavior

After helm deploy completes, I don't get some cli error

### Actual behavior

Go panic

```
....
WARN[0079] image [dockerhub.mydomain.com/hhd/my-app:4f205e7-dirty@sha256:67285744c3d0e23e95bc318869f538794a73891cc0b4335b5a5ea6670b042fc5] is not used. 
WARN[0079] image [dockerhub.mydomain.com/hhd/my-app] is used instead. 
WARN[0079] See helm sample for how to replace image names with their actual tags: https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4f36310]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).storeTokenInCfg(0xc0007394c0, 0xc000111600, 0xd, 0xc000111600)
        vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:276 +0x390
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureTokenSource).Token(0xc0007394c0, 0x0, 0x0, 0x0)
        vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:194 +0x42b
k8s.io/client-go/plugin/pkg/client/auth/azure.(*azureRoundTripper).RoundTrip(0xc0007d0040, 0xc0000e8800, 0x5588f2f, 0xa, 0xc000429ac0)
        vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:125 +0x81
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc0007d0060, 0xc0000e8700, 0xc0007d0060, 0xbf89e44d6a593f60, 0x1a0c03bbe9)
        vendor/k8s.io/client-go/transport/round_trippers.go:167 +0x1c0
net/http.send(0xc0000e8600, 0x5852dc0, 0xc0007d0060, 0xbf89e44d6a593f60, 0x1a0c03bbe9, 0x6566b20, 0xc0005283d8, 0xbf89e44d6a593f60, 0x1, 0x0)
        /usr/local/Cellar/go/1.13.7/libexec/src/net/http/client.go:250 +0x443
net/http.(*Client).send(0xc0007c0090, 0xc0000e8600, 0xbf89e44d6a593f60, 0x1a0c03bbe9, 0x6566b20, 0xc0005283d8, 0x0, 0x1, 0x400ddc6)
        /usr/local/Cellar/go/1.13.7/libexec/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc0007c0090, 0xc0000e8600, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.13.7/libexec/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(0xc0007c0090, 0xc0000e8600, 0x0, 0x5894b00, 0xc00076d2c0)
        /usr/local/Cellar/go/1.13.7/libexec/src/net/http/client.go:509 +0x35
k8s.io/client-go/rest.(*Request).request(0xc0004c0d80, 0xc000838690, 0x0, 0x0)
        vendor/k8s.io/client-go/rest/request.go:737 +0x367
k8s.io/client-go/rest.(*Request).Do(0xc0004c0d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        vendor/k8s.io/client-go/rest/request.go:809 +0xc5
k8s.io/client-go/discovery.(*DiscoveryClient).ServerResourcesForGroupVersion(0xc0007d00e0, 0xc000531138, 0x8, 0x5580516, 0x1, 0xc00071aa4e)
        vendor/k8s.io/client-go/discovery/discovery_client.go:199 +0x1c0
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.groupVersionResource(0x58b37e0, 0xc0007d00e0, 0xc00071aa48, 0x5, 0xc00071aa4e, 0x2, 0xc00071aa50, 0x3, 0x0, 0x0, ...)
        pkg/skaffold/deploy/labels.go:168 +0xde
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.updateRuntimeObject(0x58529e0, 0xc00011a4e8, 0x58b37e0, 0xc0007d00e0, 0xc00072de30, 0x5864540, 0xc0007b6900, 0xc00057a320, 0x8, 0x4, ...)
        pkg/skaffold/deploy/labels.go:119 +0x2bc
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.labelDeployResults(0xc00072de30, 0xc0003fb100, 0x8, 0x8)
        pkg/skaffold/deploy/labels.go:85 +0x1b4
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).Deploy(0xc0005682c0, 0x5894a80, 0xc000568a80, 0x58533c0, 0xc000010018, 0xc00074cc40, 0x1, 0x1, 0xc000568300, 0x4, ...)
        pkg/skaffold/deploy/helm.go:116 +0x2f4
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.withTimings.Deploy(0x58800c0, 0xc0004926c0, 0x5868ec0, 0xc000568280, 0x589bcc0, 0xc0005682c0, 0x1, 0x5894a80, 0xc000568a80, 0x58533c0, ...)
        pkg/skaffold/runner/timings.go:89 +0x15f
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Deploy(0xc00002bb00, 0x5894a80, 0xc000568a80, 0x58533c0, 0xc000010018, 0xc00074cc40, 0x1, 0x1, 0x0, 0x0)
        pkg/skaffold/runner/deploy.go:55 +0x32e
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).DeployAndLog(0xc00002bb00, 0x5894a80, 0xc000568a80, 0x58533c0, 0xc000010018, 0xc00074cc40, 0x1, 0x1, 0x0, 0x0)
        pkg/skaffold/runner/build_deploy.go:81 +0x64c
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doRun.func1(0x58b6960, 0xc00002bb00, 0xc0001a0b40, 0x0, 0x10001000001)
        cmd/skaffold/app/cmd/run.go:49 +0x126
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x5894a80, 0xc000568a80, 0xc00067fbf8, 0xc00053eae0, 0x5869c00)
        cmd/skaffold/app/cmd/runner.go:48 +0xa7
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doRun(0x5894a80, 0xc000568a80, 0x58533c0, 0xc000010018, 0xc000491690, 0x1d)
        cmd/skaffold/app/cmd/run.go:43 +0x83
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x58533c0, 0xc000010018, 0x0, 0x0)
        cmd/skaffold/app/cmd/signals.go:33 +0xe1
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc00013c780, 0x6584c90, 0x0, 0x0, 0x0, 0x0)
        cmd/skaffold/app/cmd/commands.go:96 +0x6a
github.com/spf13/cobra.(*Command).execute(0xc00013c780, 0x6584c90, 0x0, 0x0, 0xc00013c780, 0x6584c90)
        vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00013c500, 0xc000010018, 0x58533c0, 0xc000010020)
        vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:864
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x58533c0, 0xc000010018, 0x58533c0, 0xc000010020, 0xc000645f50, 0x400762f)
        cmd/skaffold/app/skaffold.go:27 +0x57
main.main()
        cmd/skaffold/skaffold.go:30 +0x4e
```

### Information

```
skaffold version
v1.3.1
```
os-x

**Comment by merkushin** [comment] 2020-02-18 07:46
Same problem here:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4f5173b]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc.(*oidcAuthProvider).idToken(0xc0018ee6f0, 0x0, 0x0, 0x0, 0x0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:281 +0x6fb
github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc.(*roundTripper).RoundTrip(0xc00071f680, 0xc004a7a300, 0x5585acd, 0xa, 0xc0023900a0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go:199 +0x7c
github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc00071f6a0, 0xc004a7a200, 0xc00071f6a0, 0xbf8ad5eae4943e18, 0x470e8390c6)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/transport/round_trippers.go:167 +0x1c0
net/http.send(0xc004a7a100, 0x584c800, 0xc00071f6a0, 0xbf8ad5eae4943e18, 0x470e8390c6, 0x6700ac0, 0xc0018f8478, 0xbf8ad5eae4943e18, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:250 +0x443
net/http.(*Client).send(0xc001968150, 0xc004a7a100, 0xbf8ad5eae4943e18, 0x470e8390c6, 0x6700ac0, 0xc0018f8478, 0x0, 0x1, 0x400e646)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc001968150, 0xc004a7a100, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x3ce
net/http.(*Client).Do(0xc001968150, 0xc004a7a100, 0x0, 0x5892dc0, 0xc0000b5c80)
	/usr/local/go/src/net/http/client.go:509 +0x35
github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/rest.(*Request).request(0xc004b3f500, 0xc004a00818, 0x0, 0x0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/rest/request.go:737 +0x367
github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/rest.(*Request).Do(0xc004b3f500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/rest/request.go:809 +0xc5
github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/discovery.(*DiscoveryClient).ServerResourcesForGroupVersion(0xc00071f720, 0xc000a11e70, 0x2, 0x7ae4208, 0x5328501, 0x10100c001968d50)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/k8s.io/client-go/discovery/discovery_client.go:199 +0x1c0
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.groupVersionResource(0x58ae360, 0xc00071f720, 0x0, 0x0, 0xc000a11e70, 0x2, 0xc000a11ed4, 0x6, 0x0, 0x0, ...)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/labels.go:168 +0xde
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.updateRuntimeObject(0x584c420, 0xc0018f8150, 0x58ae360, 0xc00071f720, 0xc0018e9e90, 0x5870e00, 0xc000294000, 0x7ffeefbff678, 0x10, 0x4, ...)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/labels.go:119 +0x2bc
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.labelDeployResults(0xc0018e9e90, 0xc004bafe00, 0x9, 0xc)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/labels.go:85 +0x1b4
github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy.(*HelmDeployer).Deploy(0xc0000de240, 0x5892d40, 0xc0003cc940, 0x584cf20, 0xc0000ce008, 0xc0026ccc80, 0x2, 0x2, 0xc0000de2c0, 0x4, ...)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/deploy/helm.go:116 +0x2f4
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.withTimings.Deploy(0x587b140, 0xc0000b4240, 0x5874ac0, 0xc0000de200, 0x5899180, 0xc0000de240, 0x1, 0x5892d40, 0xc0003cc940, 0x584cf20, ...)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/timings.go:89 +0x15f
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Deploy(0xc0006a4240, 0x5892d40, 0xc0003cc940, 0x584cf20, 0xc0000ce008, 0xc0026ccc80, 0x2, 0x2, 0xc0026ccc40, 0x2)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/deploy.go:55 +0x31c
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*SkaffoldRunner).Dev(0xc0006a4240, 0x5892d40, 0xc0003cc940, 0x584cf20, 0xc0000ce008, 0xc0006b3f60, 0x2, 0x4, 0x0, 0x0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/dev.go:199 +0x9bf
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doDev.func5(0x58b18c0, 0xc0006a4240, 0xc0006b67e0, 0x0, 0x101010001000001)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:72 +0xad
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner(0x5892d40, 0xc0003cc940, 0xc000835be8, 0xc0005483a8, 0x60)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/runner.go:48 +0xa7
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doDev(0x5892d40, 0xc0003cc940, 0x584cf20, 0xc0000ce008, 0x0, 0x0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:71 +0x15f
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x584cf20, 0xc0000ce008, 0x0, 0x0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/signals.go:33 +0xe1
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.(*builder).NoArgs.func1(0xc00041a500, 0xc000538d60, 0x0, 0x2, 0x0, 0x0)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/commands.go:96 +0x6a
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).execute(0xc00041a500, 0xc000538d20, 0x2, 0x2, 0xc00041a500, 0xc000538d20)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:826 +0x460
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00041a000, 0xc0000ce008, 0x584cf20, 0xc0000ce010)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:864
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x584cf20, 0xc0000ce008, 0x584cf20, 0xc0000ce010, 0xc00060bf50, 0x4007eaf)
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:27 +0x57
main.main()
	/ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:30 +0x4e
```

Versions:
```
skaffold v1.2.0
helm v2.14.1
macOS 10.15.3
```

**Comment by dgageot** [comment] 2020-02-20 09:33
Duplicate of https://github.com/GoogleContainerTools/skaffold/issues/3293

**Closed by dgageot** 2020-02-20 09:33 UTC
