### ISSUE TITLE
Verify Control API Devloop intent

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#6710] opened 2021-10-08 22:16 UTC
In #6636, I added a devloop intent,  to only have 1 devloop task per request.

@emmanuelbaah when testing pointed out, they are still seeing multiple `devloop` task.

Here is the event API V2 events: https://paste.googleplex.com/5373493047721984
Search for `taskEvent":{"id":"Devloop-` and you shd see 3 instances of 2. 

Steps to reproduce:
1. skaffold dev --auto-build=false --auto-deploy=false --auto-sync=false -d <> --rpc-http-port=50052
1. Change a build dependency and a deploy dependency
1. Send a devloop request 
```
 curl -i localhost:50052/v1/execute -X POST -d '{
  "devloop": true
}'

```
1. Get event API v2 log `curl localhost:50052/v2/events`

Here is a screencast (sorry could not attach this on github)
https://drive.google.com/file/d/1krU7Bcyqtdkl1LY4TIJSSKPDNij3Bv6k/view?usp=sharing&resourcekey=0-zVh6bQMDf2Wcz8vmPk26RA

**Comment by tejal29** [comment] 2021-10-08 22:22
Note: I was not able to reproduce it if i change just 1 files in each artifact per deviteration. So please try changing multiple files  across artifacts.

**Comment by MarlonGamez** [comment] 2021-11-03 18:14
@emmanuelbaah have you been able to find anything here?

**Comment by emmanuelbaah** [comment] 2021-11-03 18:18
yes, sorry for the delay, when i tested it out i was still seeing the issue. So i'm getting another set of eyes from my team to verify. It very well could be an issue on my end. Hoping to resolve this by EOD

**Comment by MarlonGamez** [comment] 2021-11-03 18:26
Feel free to schedule something on my calendar if you'd like to run through this together! I'm assuming that there's some form of miscommunication/misunderstanding on our end

**Comment by emmanuelbaah** [comment] 2021-11-04 02:50
After syncing with @MarlonGamez I realized that there indeed was a gap in my understanding. I didn't realize that a new function, `setDevloop`, was created to solve this issue. After testing with the new function, I can confirm that the issue is no longer occurring. Thanks @MarlonGamez for helping get to the bottom of it!

**Comment by MarlonGamez** [comment] 2021-11-04 16:48
closing since Emmanuel and I have confirmed this is working as intended ✅

**Closed by MarlonGamez** 2021-11-04 16:48 UTC
Labels: kind/bug, priority/p2, area/api, source/partnerships, planning/Q4-21
