### ISSUE TITLE
skaffold build fails in specific Linux box with - copying sources: uploading build context:

### ISSUE THREAD

**Issue by pagmoro** [GoogleContainerTools/skaffold#4846] opened 2020-10-01 19:05 UTC
This issue seems very similar to issue [3944](https://github.com/GoogleContainerTools/skaffold/issues/3944) , but doesn't help. It appears that any additional logging that was added as part of [3944](https://github.com/GoogleContainerTools/skaffold/issues/3944) does not cover my scenario.
Note that the same build works on windows and some other Linux machines (with same os version), but fails on this particular one.

    $ cat /etc/redhat-release
    Red Hat Enterprise Linux Server release 7.7 (Maipo)

Here's my test Dockerfile
    
    #Redhat Linux base image
    FROM mycontainerregistry-############redhat7:latest
    RUN yum install -y wget

### Expected behavior
skaffold build should succeed. Even if it fails there should be a descriptive error. The issue seems machine specific so adding more logs would help in pin-pointing the real issue.

### Actual behavior
skaffold build fails with *"copying sources: uploading build context:"*

    $ skaffold build -p local --verbosity=debug
    INFO[0000] Skaffold &{Version:v1.14.0 ConfigVersion:skaffold/v2beta7 GitVersion: GitCommit:4b3ca59af505c4ab5d5b6960a194e1f6887018f8 GitTreeState:clean BuildDate:2020-09-02T19:38:54Z GoVersion:go1.14.2 Compiler:gc Platform:linux/amd64}
    DEBU[0000] config version "skaffold/v2beta5" out of date: upgrading to latest "skaffold/v2beta7"
    INFO[0000] Loaded Skaffold defaults from "/home/#####/.skaffold/config"
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    INFO[0000] applying profile: local
    DEBU[0000] overlaying profile on config for field Build
    DEBU[0000] overlaying profile on config for field artifacts
    DEBU[0000] overlaying profile on config for field insecureRegistries
    DEBU[0000] overlaying profile on config for field tagPolicy
    INFO[0000] no values found in profile for field TagPolicy, using original config values
    DEBU[0000] overlaying profile on config for field BuildType
    INFO[0000] no values found in profile for field BuildType, using original config values
    DEBU[0000] overlaying profile on config for field Test
    DEBU[0000] overlaying profile on config for field Deploy
    DEBU[0000] overlaying profile on config for field DeployType
    DEBU[0000] overlaying profile on config for field helm
    DEBU[0000] overlaying profile on config for field kpt
    DEBU[0000] overlaying profile on config for field kubectl
    DEBU[0000] overlaying profile on config for field kustomize
    DEBU[0000] overlaying profile on config for field statusCheckDeadlineSeconds
    DEBU[0000] overlaying profile on config for field kubeContext
    DEBU[0000] overlaying profile on config for field logs
    DEBU[0000] overlaying profile on config for field prefix
    DEBU[0000] overlaying profile on config for field PortForward
    DEBU[0000] Defaulting deploy type to kubectl
    INFO[0000] Using kubectl context: ########################@##########################
    DEBU[0000] Using builder: cluster
    DEBU[0000] setting Docker user agent to skaffold-v1.14.0
    Generating tags...
     - mycontainerregistry-##########/############/############myimage -> mycontainerregistry-##########/#############/#############myimage:latest
    INFO[0000] Tags generated in 71.597µs
    Creating docker config secret [build-secret]...
    DEBU[0000] getting client config for kubeContext: ``
    DEBU[0000] No docker config specified. Checking for one in the cluster.
    Building [mycontainerregistry-##########/#############/###########myimage]...
    DEBU[0000] getting client config for kubeContext: ``
    INFO[0000] Waiting for kaniko-wgzp9 to be initialized
    DEBU[0005] Running command: [kubectl --context ########################@########################## exec -i kaniko-wgzp9 -c kaniko-init-container -n build-dev -- tar -xf - -C /kaniko/buildcontext]
    DEBU[0005] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
    couldn't build "mycontainerregistry-##########/#############/##########myimage": copying sources: uploading build context:
    
    
### Information

- Skaffold version: v1.14.0
- Operating system: Red Hat Enterprise Linux Server release 7.7 (Maipo)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: mycontainerregistry-##########/############/##########myimage
      kaniko:
        initImage: mycontainerregistry-##########/############/##################redhat:7-stable
        image: mycontainerregistry-##########/############/##################/kaniko-executor:latest
  tagPolicy:
    sha256: {}

  cluster:
    namespace: build-dev
profiles:
  - name: local
    patches:
      - op: add
        path: /build/cluster/dockerConfig
        value: {secretName: "build-secret"}

```

Multiple people have independently looked into it and found no obvious issue with the environment , so any additional logs when the build fails would be helpful. The behavior is same for 1.10.1 version as well.

**Comment by briandealwis** [comment] 2020-10-08 22:28
Are you sure your cluster has access to your registry?

**Comment by briandealwis** [comment] 2020-10-09 02:10
Any ideas @tejal29?

**Comment by pagmoro** [comment] 2020-10-15 15:15
> 
> 
> Are you sure your cluster has access to your registry?

@briandealwis  - Yes , same build with same credentials on same cluster works from windows box. So far it is not reproducible on other Linux boxes. The error seems very abrupt and not helpful.

**Comment by briandealwis** [comment] 2020-10-15 20:19
Huh, this sounds like it might be a line-ending issue.  There are a number of tools that fail to handle carriage returns.  [We hit such an error recently](https://github.com/GoogleCloudPlatform/buildpacks/issues/56) ([fix](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/371/files)), which was baffling!

Can you please check that your files have expected line endings?

**Comment by pagmoro** [comment] 2020-10-16 16:18
> Can you please check that your files have expected line endings?

Thanks - seemed promising but did not help. The only 2 files I have are the Dockerfile and skaffold.yaml. Removed extra line from the end and checked for any special characters. One thing I should mention is /tmp on the box is non-executable. Would that make a difference? I also tried pointing TMPDIR and TMP variables to a different dir in my home. No difference.

**Comment by briandealwis** [comment] 2020-10-19 21:46
I took a deeper look…

```
INFO[0000] Waiting for kaniko-wgzp9 to be initialized
DEBU[0005] Running command: [kubectl --context ########################@########################## exec -i kaniko-wgzp9 -c kaniko-init-container -n build-dev -- tar -xf - -C /kaniko/buildcontext]
DEBU[0005] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
couldn't build "mycontainerregistry-##########/#############/##########myimage": copying sources: uploading build context:
```

The `DEBU[0005] Running command: [kubectl` and `uploading build context` is coming from Skaffold and corresponds to the following code:
https://github.com/GoogleContainerTools/skaffold/blob/a549c7a1dd25fb9e75ef1dd8b59dce940f33f944/pkg/skaffold/build/cluster/kaniko.go#L103-L105

From the `uploading build context: ` error string, `kubectl exec` is failing, but this output should include the stdout and stderr from the kubectl command.  So this `exec` command is failing, but we're not getting any output as to why.

The `FIXME: Got an status-code` comment comes from Docker helper code:
https://github.com/GoogleContainerTools/skaffold/blob/a549c7a1dd25fb9e75ef1dd8b59dce940f33f944/vendor/github.com/docker/docker/errdefs/http_helpers.go#L103-L106

I'd almost think this `FIXME` was coming from `kubectl` *except* that the counter `DEBU[0005]` matches the Skaffold line above it.  Totally baffling.

Would you be able to apply the following modification:
```
diff --git vendor/github.com/docker/docker/errdefs/http_helpers.go vendor/github.com/docker/docker/errdefs/http_helpers.go
index 07552f1cc..7c4c672f6 100644
--- vendor/github.com/docker/docker/errdefs/http_helpers.go
+++ vendor/github.com/docker/docker/errdefs/http_helpers.go
@@ -104,6 +104,7 @@ func FromStatusCode(err error, statusCode int) error {
 			"module":      "api",
 			"status_code": fmt.Sprintf("%d", statusCode),
 		}).Debugf("FIXME: Got an status-code for which error does not match any expected type!!!: %d", statusCode)
+		panic("FIXME: time to panic")
 
 		switch {
 		case statusCode >= 200 && statusCode < 400:
```

And rebuild Skaffold with: `go build -mod=vendor ./cmd/skaffold` and try again?

**Comment by pagmoro** [comment] 2020-10-21 14:02
Here's what I get:

> INFO[0000] Waiting for kaniko-fskxx to be initialized
DEBU[0002] Running command: [kubectl --context ################@##################### exec -i kaniko-fskxx -c kaniko-init-container -n build-dev -- tar -xf - -C /kaniko/buildcontext]
DEBU[0002] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
panic: FIXME: time to panic

>goroutine 82 [running]:
github.com/docker/docker/errdefs.FromStatusCode(0x20beb80, 0xc0009fc380, 0xffffffffffffffff, 0xc0005a6500, 0x0)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/docker/docker/errdefs/http_helpers.go:107 +0x679
github.com/docker/docker/client.(*Client).sendRequest(0xc000482300, 0x2106780, 0xc000056098, 0x1dd2069, 0x3, 0xc000061020, 0x55, 0x0, 0x0, 0x0, ...)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/docker/docker/client/request.go:115 +0x193
github.com/docker/docker/client.(*Client).get(...)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/docker/docker/client/request.go:37
github.com/docker/docker/client.(*Client).ImageInspectWithRaw(0xc000482300, 0x2106780, 0xc000056098, 0xc00098c375, 0x48, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/docker/docker/client/image_inspect.go:17 +0x167
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.(*localDaemon).ConfigFile(0xc00041f360, 0x2106780, 0xc000056098, 0xc00098c375, 0x48, 0x0, 0x0, 0x0)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker/image.go:145 +0x152
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.retrieveImage(0xc00098c375, 0x48, 0x2106c00, 0xc0006f1600, 0xc0003a1840, 0x1, 0x1)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker/parse.go:390 +0x115
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.parseOnbuild(0xc00098c375, 0x48, 0x2106c00, 0xc0006f1600, 0x30fc6a0, 0x0, 0x2, 0x1, 0x28)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker/parse.go:340 +0xf3
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.expandOnbuildInstructions(0xc0009fc2a0, 0x2, 0x2, 0x2106c00, 0xc0006f1600, 0x0, 0x0, 0xc00033dee0, 0xc0005a55f0, 0x26)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker/parse.go:318 +0x556
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.readCopyCmdsFromDockerfile(0x0, 0xc0005a55f0, 0x26, 0x1dd1a55, 0x1, 0x0, 0x2106c00, 0xc0006f1600, 0x0, 0x0, ...)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker/parse.go:84 +0x33b
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.GetDependencies(0x2106740, 0xc00013ec80, 0x1dd1a55, 0x1, 0x1ddab3f, 0xa, 0x0, 0x2106c00, 0xc0006f1600, 0x40e788, ...)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker/dependencies.go:61 +0x259
github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker.CreateDockerTarContext(0x2106740, 0xc00013ec80, 0x20bd520, 0xc000010ff0, 0x1dd1a55, 0x1, 0xc00006d738, 0x2106c00, 0xc0006f1600, 0xc0002b27b0, ...)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/docker/context.go:30 +0xa3
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).copyKanikoBuildContext.func1(0x2106740, 0xc00013ec80, 0xc000010ff0, 0x1dd1a55, 0x1, 0xc00015d4a0, 0xc0008008d0)
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster/kaniko.go:89 +0x12c
created by github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster.(*Builder).copyKanikoBuildContext
        /home/o705858/go_projects/src/github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cluster/kaniko.go:88 +0x29c

**Comment by tejal29** [comment] 2020-10-26 19:42
@pagmoro Thanks for the sending the detailed report. 
I do have a AI to #4929 which will should help bring forward, 
- pod events, 
- pod failures
etc. 
I will try to reproduce this scenario locally.

**Comment by briandealwis** [comment] 2020-11-30 22:34
@pagmoro I'm sorry, I missed this.  If you're willing to try another patch:

```diff
diff --git vendor/github.com/docker/docker/client/request.go vendor/github.com/docker/docker/client/request.go
index ee15a46ed..830a19b78 100644
--- vendor/github.com/docker/docker/client/request.go
+++ vendor/github.com/docker/docker/client/request.go
@@ -112,6 +112,7 @@ func (cli *Client) sendRequest(ctx context.Context, method, path string, query u
        }
        resp, err := cli.doRequest(ctx, req)
        if err != nil {
+               fmt.Printf(">> error from %+v to %+v: %+v\n", resp, req, err)
                return resp, errdefs.FromStatusCode(err, resp.statusCode)
        }
        err = cli.checkResponseErr(resp)
```

**Comment by pagmoro** [comment] 2020-12-13 19:14
Looks like I missed your comment too - let me try this and revert back

**Comment by briandealwis** [comment] 2020-12-17 22:00
Any luck @pagmoro ?

**Comment by pagmoro** [comment] 2020-12-18 04:29
Here you go .. I was waiting to see if I could figure this out with my collegues. Looks like its still expecting docker daemon in local box ?


     $ ./ske1 build -p local
    Generating tags...

    containerregistry-#########/container-sandbox/####/#####-container-lab-1 -> containerregistry-#########/container- 
    sandbox/####/######-container-lab-1:latest
    Creating docker config secret [build-secret]...
    Building [containerregistry-#########/container-sandbox/####/#####-container-lab-1]...
    >> error from {body:<nil> header:map[] statusCode:-1 reqURL:0xc0006af600}
    to &

    {Method:GET URL:http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/containerregistry-#########/container- 
    release/######/red-hat7:latest/json Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:<nil> GetBody:<nil> 
    ContentLength:0 TransferEncoding:[] Close:false Host:docker Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] 
    RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc00019e000}
    : Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    copying sources: uploading build context:

**Comment by pagmoro** [comment] 2020-12-18 04:58
Posting the latest skaffold.yaml as a refresher - Also confirmed I'm connected to remote cluster

    apiVersion: skaffold/v2beta5
    kind: Config
    build:
       artifacts:
         - image: containerregistry-#########/container-sandbox/####/#####-container-lab-1
           kaniko:
             initImage: containerregistry-#########/container-release/managedbaseimages/lrh/targz:7-stable
             image:  containerregistry-#########/container-release/kube/gkp/kaniko-executor:latest
       tagPolicy:
         sha256: {}

       cluster:
         namespace: ####-#####-build-dev
     profiles:
       - name: local
         patches:
           - op: add
             path: /build/cluster/dockerConfig
             value: {secretName: "build-secret"}

**Comment by briandealwis** [comment] 2020-12-20 04:17
@pagmoro is there any chance you could try this on Skaffold v1.17.2?  I've been unable to reproduce as I think this codepath was made more robust with #4896.

**Comment by pagmoro** [comment] 2020-12-21 15:07
I'll update on this in the new year (the people involved are on vacation) - hopefully that version fixes this issue.

**Comment by pagmoro** [comment] 2021-01-08 22:48
I am unfortunately getting the same error with v1.17.2


>> error from {body:<nil> header:map[] statusCode:-1 reqURL:0xc000e98200} to &{Method:GET URL:http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/###########/container-release/#####/redhat7:latest/json Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[] Body:<nil> GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:docker Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> ctx:0xc0000b6000}: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
DEBU[0004] FIXME: Got an status-code for which error does not match any expected type!!!: -1  module=api status_code=-1
copying sources: uploading build context:

**Comment by pagmoro** [comment] 2021-01-20 17:10
Hi @briandealwis - just checking if you got a chance to take a look?

**Comment by gsquared94** [comment] 2021-04-14 02:22
sorry @pagmoro we didn't respond sooner. Skaffold has progressed by a few more releases in the meantime and I was wondering if you could try the latest version again to see if this issue still reproduces?

**Comment by aaron-prindle** [comment] 2021-06-21 18:28
@pagmoro friendly ping.  Were you able to try to latest skaffold release and verify if this issue is still occuring?

**Comment by MarlonGamez** [comment] 2021-11-01 18:21
hi @pagmoro, I'm going to close this issue for now as we haven't had any updates on it in a while. Please feel free to reopen if it's still affecting you

**Closed by MarlonGamez** 2021-11-01 18:21 UTC
Labels: kind/bug, area/build, priority/p3, build/kaniko, needs-reproduction
