### ISSUE TITLE
helm deploys before kubectl

### ISSUE THREAD

**Issue by imerkle** [GoogleContainerTools/skaffold#5362] opened 2021-02-07 15:45 UTC
### Expected behavior

```
  deploy:
    kubectl:
      manifests:
        - ./namespace.yaml   
    helm:
      releases:
      - name: drone
        chartPath: drone/drone
        remote: true
        valuesFiles: 
          - drone-values.yaml
        namespace: mynamespace 
```
`kubectl` should run first then `helm`. i.e whichever is first and not alphabetically asc
### Actual behavior
`helm` runs first so `mynamespace` doesn't exists therefore fails

### Information

- Skaffold version: 1.19.x
- Operating system: ubuntu
- Contents of skaffold.yaml:

above

### Steps to reproduce the behavior

above

**Comment by nkubala** [comment] 2021-02-10 03:01
@imerkle thanks for the issue, this is a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/3905. we're definitely aware of the friction this is causing, and are working on some proposals on how to address it. stay tuned for updates!

**Closed by nkubala** 2021-02-10 03:01 UTC
