### ISSUE TITLE
skaffold requires kustomize on path

### ISSUE THREAD

**Issue by base698** [GoogleContainerTools/skaffold#3693] opened 2020-02-16 15:18 UTC
### Expected behavior

`skaffold dev` to work without installing kustomize.  `kubectl kustomize` has been available since `kubectl` version 1.14.

### Actual behavior
```
FATA[0040] exiting dev mode because first deploy failed: reading manifests: kustomize build: starting command kustomize build .: exec: "kustomize": executable file not found in $PATH
```

### Information

- Skaffold version: v1.3.1
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1
kind: Config
deploy:
  kustomize:
    path: "."
```

### Steps to reproduce the behavior

1. any
2. `skaffold dev`

**Comment by corneliusweig** [comment] 2020-02-19 10:35
Thanks for reporting. This is mentioned on https://skaffold.dev/docs/pipeline-stages/deployers/ at the bottom of the page. Where would you have looked for this information?

https://skaffold.dev/docs/install/ seems to be a natural place and it's missing there.

---

For completeness: This applies to all third-party tools used by Skaffold. This includes `helm`, `kustomize`, `kubectl`, and `docker`.

**Comment by base698** [comment] 2020-02-19 11:58
@corneliusweig I'm saying that it should not require `kustomize`.  Why would kustomize need to be on path if `kubectl` is already there?

**Comment by corneliusweig** [comment] 2020-02-19 12:47
This is also tracked by https://github.com/GoogleContainerTools/skaffold/issues/1781.

There are some tradeoffs though. The version bundled with `kubectl` is a bit outdated and does not come with all the features you find on the kustomize homepage. For the time being, the standalone `kustomize` seems the safer option to me.

**Comment by dgageot** [comment] 2020-02-20 09:30
I'm going to close this issue as a duplicate of #1781. I think supporting both the standalone and the built-in version would be nice.

**Closed by dgageot** 2020-02-20 09:30 UTC
