### ISSUE TITLE
Microk8s connection issue

### ISSUE THREAD

**Issue by soullivaneuh** [GoogleContainerTools/skaffold#1651] opened 2019-02-14 15:47 UTC
I'm trying Skaffold but I'm stuck at the beginning, it does not seem to detect my microk8s instance

Maybe some configuration is required but I can't found anything on the documentation about this.

### Expected behavior

```bash
skaffold init
# Should create my configs files
```

### Actual behavior

```bash
$ skaffold init
FATA[0000] one or more valid kubernetes manifests is required to run skaffold 
```

### Information

- Skaffold version: v0.22.0
- Operating system: `Linux sweetnexy 4.18.0-15-generic #16-Ubuntu SMP Thu Feb 7 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
$ kubectl config current-context
microk8s
```

### Steps to reproduce the behavior

1. Install microk8s with snap
2. Install Skaffold
3. Run `skaffold init`

**Comment by Soullivaneuh** [comment] 2019-02-14 15:53
Right, it does not seem to be a microk8s connectivity issue as it works with a manual file creation.

Then, I don't understand the error message. :smile:

**Comment by balopat** [comment] 2019-02-14 22:14
Hey @Soullivaneuh, thanks for opening this issue. 
The `skaffold init` command doesn't generate yet kubernetes manifests - although it probably will in the future. The error you're getting shows that there are no K8s manifest files, currently you'll have to manually create them: see for example the k8s-pod.yaml in the [getting-started](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/getting-started)

**Comment by Soullivaneuh** [comment] 2019-02-14 23:54
Hi @balopat, thanks for the answer! :-)

I'm not sure what is the goal of the `k8s-pod.yaml` file here.

Before testing Skaffold, I just setup a helm chart project and it worked fine without it.

BTW, I did manually setup the skaffold configuration file:

```yaml
apiVersion: skaffold/v1beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: localhost:32000/sweetforeign_web
deploy:
  helm:
    releases:
      - name: sweetforeign
        chartPath: .
```

And it works fine, except the `ADD` directive of my `Dockerfile` being not updated, but I think it's an another configuration issue...

**Comment by balopat** [comment] 2019-02-15 20:08
Ah I see, I understand the problem better. 
This might be a bug with `skaffold init` not handling helm charts. Can you create a small reproduction that we can try out?

**Comment by Soullivaneuh** [comment] 2019-02-16 00:02
@balopat Here you go: https://github.com/Soullivaneuh/skaffold-issues/tree/issue-1651

Just clone this branch and run `skaffold init`.

**Comment by tejal29** [comment] 2019-03-01 22:30
running skaffold init with debug options reveals, that helm config files are not supported yet and interpreted as normal k8 config files

```

INFO[0000] Skaffold &{Version:latest-release GitVersion: GitCommit:0f99b31ce724e971af347e9a6f9582f68b9ac250 GitTreeState:clean BuildDate:2018-09-22T18:32:25Z GoVersion:go1.10.4 Compiler:gc Platform:linux/amd64} 
INFO[0000] update check failed: parsing current semver, skipping update check: parsing semver: No Major.Minor.Patch elements found 
INFO[0000] existing dockerfile found: Dockerfile        
DEBU[0000] Chart.yaml is not a valid skaffold configuration: continuing 
INFO[0000] invalid k8s yaml Chart.yaml: decoding kubernetes yaml: Object 'Kind' is missing in 'apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: sweetforeign
version: 0.1.0
' 
DEBU[0000] templates/deployment.yaml is not a valid skaffold configuration: continuing 
INFO[0000] invalid k8s yaml templates/deployment.yaml: decoding kubernetes yaml: yaml: line 38: did not find expected node content 
DEBU[0000] templates/ingress.yaml is not a valid skaffold configuration: continuing 
INFO[0000] invalid k8s yaml templates/ingress.yaml: decoding kubernetes yaml: couldn't get version/kind; json parse error: invalid character '{' looking for beginning of object key string 
DEBU[0000] templates/service.yaml is not a valid skaffold configuration: continuing 
INFO[0000] invalid k8s yaml templates/service.yaml: decoding kubernetes yaml: yaml: invalid map key: map[interface {}]interface {}{"include \"..fullname\" .":interface {}(nil)} 
DEBU[0000] templates/tests/test-connection.yaml is not a valid skaffold configuration: continuing 
INFO[0000] invalid k8s yaml templates/tests/test-connection.yaml: decoding kubernetes yaml: yaml: line 3: did not find expected key 
DEBU[0000] values.yaml is not a valid skaffold configuration: continuing 
INFO[0000] invalid k8s yaml values.yaml: decoding kubernetes yaml: Object 'Kind' is missing in 'replicaCount: 1

image:
  repository: localhost:32000/sweetforeign_web
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
' 
FATA[0000] one or more valid kubernetes manifests is required to run skaffold 
```

**Comment by tejal29** [comment] 2019-03-05 00:19
Proposal to support helm and other supported deploy tools added herehttps://github.com/GoogleContainerTools/skaffold/issues/1726

**Comment by priyawadhwa** [comment] 2019-09-24 22:32
Closing as a dupe of https://github.com/GoogleContainerTools/skaffold/issues/1726, please follow there for more information about this feature.

**Closed by priyawadhwa** 2019-09-24 22:32 UTC
Labels: area/init, deploy/helm, good first issue, kind/feature-request
