### ISSUE TITLE
Building a base image artifact

### ISSUE THREAD

**Issue by KhaledSakr** [GoogleContainerTools/skaffold#3451] opened 2019-12-26 09:37 UTC
I'm using skaffold to build and deploy multiple artifacts, but each of them are based on a base image that should be built and pushed first.

This is for example doable with docker-compose in the following way:
```yaml
services:
  base:
    build:
      context: ../base
    image: base
  users:
    build:
      context: ../users
```
And then the dockerfile for the `users` image:
```dockerfile
FROM base
...
```

This workflow is currently not supported in skaffold as far as I understand.

### Expected behavior
Should be able to build base artifacts and then pass the created tag to other artifacts.

### Actual behavior
Currently there's no way no pass the tags to other artifacts.

### Information

- Skaffold version: v1.1.0
- Operating system: Ubuntu 19.04

**Comment by balopat** [comment] 2020-01-16 16:21
Thanks @KhaledSakr for opening this - this seems reasonable to me. A design doc would be the first step for this kind of feature. We currently don't have the bandwidth to dig into it, but we could start on this by reviewing community designs. Would you be interested to dig deeper into this?

**Comment by KhaledSakr** [comment] 2020-01-16 16:41
Fair enough. Let me work on a proposal over the next few days.

Thanks for the suggestion. Unfortunately, it doesn't fit our use case. For now we build the base image in a seperate step before skaffold and then pass the tag to skaffold to be passed in turn to the artifacts as a buildArg. It's not pretty but it does the job.

**Comment by no1melman** [comment] 2020-03-05 15:56
Could you elaborate on this @balopat maybe show a sample skaffold.yaml

> In the meantime - my (imperfect) solution would be in case of Dockerfiles to use a multistage dockerfile and use target in the artifact definitions.

**Comment by asavpatel92** [comment] 2020-03-24 20:46
> Could you elaborate on this @balopat maybe show a sample skaffold.yaml
> 
> > In the meantime - my (imperfect) solution would be in case of Dockerfiles to use a multistage dockerfile and use target in the artifact definitions.

yes I would second that, I tried scavenging through examples but couldn't find an example for this one.

**Comment by no1melman** [comment] 2020-03-31 08:43
Actually funnily enough I did come across it

https://github.com/GoogleContainerTools/skaffold/issues/3831

**Comment by briandealwis** [comment] 2020-09-22 15:39
Duplicate of #889 (closing)

Design proposed in #4794

**Closed by briandealwis** 2020-09-22 15:39 UTC
Labels: area/artifact-dependencies, area/build, area/modules, kind/feature-request, priority/p3
