### ISSUE TITLE
imageStrategy Helm broken since v0.38, possibly v0.37

### ISSUE THREAD

**Issue by MisterTimn** [GoogleContainerTools/skaffold#2902] opened 2019-09-18 13:56 UTC
### Expected behavior
Skaffold dev or run resulting in deployed and running pods

### Actual behavior
InvalidImageName errors on pods because the imageStrategy: helm option on skaffold config isnt respected
Actual image name becomes: `imageName:imageName` instead of `imageName:tag`

Tested on multiple of my projects. I then reverted to 0.36 because I knew this was the last version on which my deployments worked, and there I had no issues. (Yes I ran skaffold fix --overwrite true before I ran skaffold dev/run)

### Information

- Skaffold version: version 0.38
- Operating system: Manjaro Arch
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v1beta14
kind: Config
build:
  artifacts:
  - image: gitlab.ilabt.imec.be:4567/dyversify/demo-controller
    context: .
    jib: {}
deploy:
  helm:
    releases:
    - name: skaffold-demo-controller
      chartPath: helm/demo-controller
      valuesFiles:
      - helm/dyversify-values.yaml
      values:
        image: gitlab.ilabt.imec.be:4567/dyversify/demo-controller
      namespace: default
      recreatePods: true
      imageStrategy:
        helm: {}
profiles:
- name: obelisk-staging
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: helm/obelisk-staging-values.yaml
  activation:
  - kubeContext: obelisk-staging
- name: dyversify
  patches:
  - op: replace
    path: /deploy/helm/releases/0/valuesFiles/0
    value: helm/dyversify-values.yaml
  activation:
  - kubeContext: dyversify
```

### Steps to reproduce the behavior

Cant expose my codebase, but basically run any project which uses the default Helm config 
```yaml
containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
```

And use in your skaffold.yaml
```yaml
 deploy:
  helm:
      imageStrategy:
        helm: {}
```
and it will give you the double imageNames resulting in an error.

**Comment by forgo** [comment] 2019-09-18 17:52
My team is also experiencing this issue.

**Comment by dmmatson** [comment] 2019-09-18 18:30
Can confirm that rolling back from 0.38.0 to 0.37.1 fixes this issue for me.

**Comment by tejal29** [comment] 2019-09-18 21:33
Thanks @forgo and @dmmatson for confirming the issue. The team will look in to this soon. For now, please revert to 0.37.1

**Comment by tejal29** [comment] 2019-09-18 21:38
I was able to reproduce this bug on my end. Will work on a fix.

**Comment by tejal29** [comment] 2019-09-18 21:49
#2887 fixes this issue. I am going to add this to our integration test suite.

**Comment by georgekarrv** [comment] 2019-09-19 12:47
I had to go all the way back to 0.35.0 to get correct imagenames

**Comment by MisterTimn** [comment] 2019-09-19 12:56
Might be unrelated/other issue then? I can also confirm that 0.37.1 works for me. Using it right now until next release.

Do you get the double name same as I had or other image names?

**Comment by georgekarrv** [comment] 2019-09-19 14:19
well i checked out master and applied the diff of the above pr and it works for me so that's what I'll stick with until an actual release

**Comment by tejal29** [comment] 2019-09-19 18:30
Thanks @georgekarrv, Just an update, i am working with @michaelbeaumont to get his PR merged in soon.

**Closed** 2019-09-24 21:10 UTC
Labels: area/deploy, deploy/helm, kind/bug, priority/p1
