### ISSUE TITLE
DOCKER_HOST env var is not recognized and skaffold build fails with error.

### ISSUE THREAD

**Issue by cheburakshu** [GoogleContainerTools/skaffold#8454] opened 2023-02-21 03:38 UTC
Skaffold fails when DOCKER_HOST env var is used. `docker build` command works fine.

```
⟩ skaffold version
v2.0.4

⟩ docker context ls

NAME            DESCRIPTION                               DOCKER ENDPOINT                                          KUBERNETES ENDPOINT                                     ORCHESTRATOR
default *       Current DOCKER_HOST based configuration   ssh://root@my-redacted-host.com                https://my-redacted-host.com:6443 (default)   swarm
```

```
⟩ skaffold build
Generating tags...
 - hello-go -> hello-go:latest
 - hello-java -> hello-java:latest
 - hello-python -> hello-python:latest
Checking cache...
 - hello-go: Not found. Building
 - hello-java: Not found. Building
 - hello-python: Not found. Building
Starting build...
Building [hello-python]...
Building [hello-go]...
Build [hello-go] was canceled
Building [hello-java]...
Build [hello-java] was canceled
error during connect: Get "http://root%my-redacted-host.com/v1.24/version": dial tcp: lookup root@my-redacted-host.com: no such host
```

**Comment by cheburakshu** [comment] 2023-02-21 16:26
I got over this by just specifying the tcp url instead of ssh. 
Now I am facing a different issue.

The debugger doesn't attach and gives this error. For both java and python. The same setup works for a local kubernetes cluster. I am not using GCP/GCE, using my own remote vm.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/27330002/220402316-16e9efd6-7865-4806-a30e-874e93005579.png">

**Comment by cheburakshu** [comment] 2023-02-21 16:30
```[Cloud Code]: Validating deployment settings...
[Cloud Code]: Checking kubectl, skaffold dependencies...
[Cloud Code]: Checking kubectl current context...
[Cloud Code]: Waiting for user input...
[Cloud Code]: Checking active context...
[Cloud Code]: Checking additional dependencies gcloud and docker...
[Cloud Code]: Setting up image registry...
[Cloud Code]: Setting up build environment...
[Cloud Code]: Checking skaffold profile...
[Cloud Code]: Checking logged-in status for the user...
[Cloud Code]: Running: skaffold debug -v info --port-forward --rpc-http-port 54719 --filename /Users/x/src/envy/envy-hello/hello/skaffold.yaml --wait-for-deletions-max 2m0s --wait-for-connection
starting gRPC server on port 54720
starting gRPC HTTP server on port 54719 (proxying to 54720)
Skaffold &{Version:v2.1.0 ConfigVersion:skaffold/v4beta2 GitVersion: GitCommit:c037d6f51276e178a2c05c1c59665956ff34aa4c BuildDate:2023-01-23T09:58:07Z GoVersion:go1.19.1 Compiler:gc Platform:darwin/amd64 User:}
Loaded Skaffold defaults from "/Users/x/.skaffold/config"
map entry found when executing locate for &{hello-go ../../../ <nil> {0xc000cd6000 <nil> <nil> <nil> <nil> <nil> <nil>} [] {[] []} [] } of type *latest.Artifact and pointer: 824645796464
map entry found when executing locate for &{hello-java ../../../ <nil> {0xc000cd60b0 <nil> <nil> <nil> <nil> <nil> <nil>} [] {[] []} [] } of type *latest.Artifact and pointer: 824645796672
map entry found when executing locate for &{hello-python ../../../ <nil> {0xc000cd6420 <nil> <nil> <nil> <nil> <nil> <nil>} [] {[] []} [] } of type *latest.Artifact and pointer: 824645796880
Using kubectl context: default
no kpt renderer or deployer found, skipping hydrated-dir creation
build concurrency first set to 1 parsed from *local.Builder[0]
final build concurrency value is 1
Generating tags...
 - hello-go -> hello-go:latest
 - hello-java -> hello-java:latest
 - hello-python -> hello-python:latest
Tags generated in 1.057427ms
Checking cache...
 - hello-go: Found Locally
 - hello-java: Found Locally
 - hello-python: Not found. Building
Cache check completed in 404.482225ms
Starting build...
Building [hello-python]...
Target platforms: [linux/amd64]
Build [hello-python] succeeded
Build completed in 833.492287ms
Starting render...
starting render process
Render completed in 5.806918ms
Tags used in deployment:
 - hello-go -> hello-go:ca82b4688d06fc6e2e26ac8e1b98cb303f05ce057a8ed1cf84c0e4557b4a1264
 - hello-java -> hello-java:42d1220309435ecdb482e8f464df1bed2f78cd0e1bde3d15e2c0dd1fd7f4266a
 - hello-python -> hello-python:8f0cca2030a4461307d2f4afcd7e2da1a4a69adf18e65439e1900ad6769c2977
Starting deploy...
Image "hello-go" not configured for debugging: unable to determine runtime for ""
Configuring "" for JVM debugging
Configuring "" for python debugging
"hello-python" requires debugging support image "python"
Configuring installation of debugging support files
 - persistentvolumeclaim/envy-pv-claim created
 - deployment.apps/hello-go created
 - service/hello-go created
 - ingress.networking.k8s.io/hello-go-ingress created
 - deployment.apps/hello-java created
 - service/hello-java created
 - ingress.networking.k8s.io/hello-java-ingress created
 - deployment.apps/hello-python created
 - service/hello-python created
 - ingress.networking.k8s.io/hello-python-ingress created
 - persistentvolume/envy-pv-volume configured
Waiting for deployments to stabilize...
 - envy-hello:deployment/hello-go is ready. [2/3 deployment(s) still pending]
 - envy-hello:pod/hello-java-7f9b9d7c7-zq6lt: creating container hello-java
 - envy-hello:pod/hello-python-6c994f8d74-456mk: waiting for init container install-python-debug-support to start
 - envy-hello:pod/hello-java-7f9b9d7c7-zq6lt: running.
 - envy-hello:deployment/hello-java is ready. [1/3 deployment(s) still pending]
 - envy-hello:deployment/hello-python: waiting for init container install-python-debug-support to start
    - envy-hello:pod/hello-python-6c994f8d74-456mk: waiting for init container install-python-debug-support to start
 - envy-hello:pod/hello-python-6c994f8d74-456mk: running.
 - envy-hello:deployment/hello-python is ready.
Deployments stabilized in 13.414 seconds
Deploy completed in 18.967 seconds
Port forwarding service/hello-go in namespace envy-hello, remote port 8081 -> http://127.0.0.1:8081
Port forwarding service/hello-python in namespace envy-hello, remote port 8082 -> http://127.0.0.1:8082
Port forwarding service/hello-java in namespace envy-hello, remote port 8080 -> http://127.0.0.1:8080
Listing files to watch...
 - hello-go
 - hello-java
 - hello-python
List generated in 657.83µs
Press Ctrl+C to exit
Streaming logs from pod: hello-java-7f9b9d7c7-zq6lt container: hello-java
Streaming logs from pod: hello-python-6c994f8d74-456mk container: hello-python
Streaming logs from pod: hello-python-6c994f8d74-456mk container: install-python-debug-support
Streaming logs from pod: hello-go-84dd8b5545-jqnvd container: hello-go
Not watching for changes...
[hello-java]Picked up JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
[hello-java]
[hello-java]  .   ____          _            __ _ _
[hello-java]Picked up JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
[hello-java]
[hello-java]  .   ____          _            __ _ _
[hello-java] /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[hello-java]( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[hello-java] \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[hello-java]  '  |____| .__|_| |_|_| |_\__, | / / / /
[hello-java] =========|_|==============|___/=/_/_/_/
[hello-java] :: Spring Boot ::                (v3.0.2)
[hello-java]
[hello-java]2023-02-21T16:24:13.986Z  INFO 1 --- [           main] com.example.hello.HelloApplication       : Starting HelloApplication v0.0.1-SNAPSHOT using Java 18.0.2.1 with PID 1 (/app/hello/java/target/hello-0.0.1-SNAPSHOT.jar started by root in /)
[hello-java]2023-02-21T16:24:14.006Z  INFO 1 --- [           main] com.example.hello.HelloApplication       : No active profile set, falling back to 1 default profile: "default"
[hello-java]2023-02-21T16:24:18.371Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
[hello-java]2023-02-21T16:24:18.386Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
[hello-java]2023-02-21T16:24:18.386Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.5]
[hello-java]2023-02-21T16:24:18.798Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
[hello-java]2023-02-21T16:24:18.814Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4464 ms
[hello-java]2023-02-21T16:24:20.677Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
[hello-java]2023-02-21T16:24:20.724Z  INFO 1 --- [           main] com.example.hello.HelloApplication       : Started HelloApplication in 9.884 seconds (process running for 13.84)
[hello-java] /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[hello-java]( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[hello-java] \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[hello-java]  '  |____| .__|_| |_|_| |_\__, | / / / /
[hello-java] =========|_|==============|___/=/_/_/_/
[hello-java] :: Spring Boot ::                (v3.0.2)
[hello-java]
[hello-java]2023-02-21T16:24:13.986Z  INFO 1 --- [           main] com.example.hello.HelloApplication       : Starting HelloApplication v0.0.1-SNAPSHOT using Java 18.0.2.1 with PID 1 (/app/hello/java/target/hello-0.0.1-SNAPSHOT.jar started by root in /)
[hello-java]2023-02-21T16:24:14.006Z  INFO 1 --- [           main] com.example.hello.HelloApplication       : No active profile set, falling back to 1 default profile: "default"
[hello-java]2023-02-21T16:24:18.371Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
[hello-java]2023-02-21T16:24:18.386Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
[hello-java]2023-02-21T16:24:18.386Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.5]
[hello-java]2023-02-21T16:24:18.798Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
[hello-java]2023-02-21T16:24:18.814Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4464 ms
[hello-java]2023-02-21T16:24:20.677Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
[hello-java]2023-02-21T16:24:20.724Z  INFO 1 --- [           main] com.example.hello.HelloApplication       : Started HelloApplication in 9.884 seconds (process running for 13.84)
[install-python-debug-support]Installing runtime debugging support files in /dbg
[install-python-debug-support]Installation complete
[install-python-debug-support]Installing runtime debugging support files in /dbg
[install-python-debug-support]Installation complete
[hello-python] * Serving Flask app 'run'
[hello-python] * Debug mode: off
[hello-python][31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
[hello-python] * Running on all addresses (0.0.0.0)
[hello-python] * Running on http://127.0.0.1:8082
[hello-python] * Running on http://10.42.0.81:8082
[hello-python][33mPress CTRL+C to quit[0m
[hello-python] * Serving Flask app 'run'
[hello-python] * Debug mode: off
[hello-python][31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
[hello-python] * Running on all addresses (0.0.0.0)
[hello-python] * Running on http://127.0.0.1:8082
[hello-python] * Running on http://10.42.0.81:8082
[hello-python][33mPress CTRL+C to quit[0m
Port forwarding pod/hello-java-7f9b9d7c7-zq6lt in namespace envy-hello, remote port 5005 -> http://127.0.0.1:5005
Port forwarding pod/hello-python-6c994f8d74-456mk in namespace envy-hello, remote port 5678 -> http://127.0.0.1:5678
[hello-go]Server running (port=8081), route: http://localhost:8081/
[hello-go]Server running (port=8081), route: http://localhost:8081/
```

**Comment by ericzzzzzzz** [comment] 2023-02-23 12:35
Hi @cheburakshu thank you for filing this issue. Looks like the original issue has been resolved, I'm going to close this one. If you are facing a different issue, please create a new issue. Although debugger cannot attach is very likely to be a skaffold problem, I'd file an issue with the maintainers of the tool integrates with skaffold first if the issue occurs when using their tools, in your case, could-code vs code maintainers or code-code-intellij maintainers. If you cannot attach debugger when using skaffold alone, could you please open another issue and provide reproducible steps? We're happy to help!

**Comment by cheburakshu** [comment] 2023-02-28 17:25
> If you cannot attach debugger when using skaffold alone
How would I test this? Is there any documentation for this? I am willing to test this flow, if there are any good examples for python/java, it would be helpful. Thank you!

**Comment by ericzzzzzzz** [comment] 2023-02-28 21:01
Hi @cheburakshu  here are some examples projects for playing around ``skaffold debug`` https://github.com/GoogleContainerTools/skaffold/tree/main/integration/testdata/debug 

and here is related doc https://skaffold.dev/docs/workflows/debug/

**Closed** 2023-03-13 18:57 UTC
