### ISSUE TITLE
Use Docker Base Image Without Pushing to Registry

### ISSUE THREAD

**Issue by jklaw90** [GoogleContainerTools/skaffold#6816] opened 2021-11-09 06:53 UTC
### Expected behavior
I'd expect to be able to use base images without pushing them up to the registry.
ideally we could define that like we can with `noPush: false` like we can with kaniko
My base image really just adds the source go code and gets the dependencies shared between multiple of my artifacts. 
```
  - image: registry123xyz/cc-cli
    docker:
      dockerfile: cmd/cli/Dockerfile
    requires:
      - image: registry123xyz/base-builder
        alias: BASE_BUILDER
  - image: registry123xyz/base-builder
    docker:
      dockerfile: cmd/Dockerfile
```
### Actual behavior
I have to push the base image to the registry.

### Information

- Skaffold version: v1.33.0
- Operating system: linux
- Installed via: 
- Contents of skaffold.yaml:

**Comment by MarlonGamez** [comment] 2021-11-09 18:12
Hi @jklaw90 , thanks for opening this issue. It looks like this is actually a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/5243, so I'm going to be closing this one.

In that issue, there's a comment with a solution that involves modifying your skaffold config a bit to use multiple configs/modules: https://github.com/GoogleContainerTools/skaffold/issues/5243#issuecomment-823670290

**Closed by MarlonGamez** 2021-11-09 18:12 UTC
