### ISSUE TITLE
`--enable-rpc` should have option to block until connection

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#5850] opened 2021-05-14 21:07 UTC
When using `skaffold xxx --enable-rpc`, it possible for Skaffold to exit before an observer is able to connect to the RPC endpoint.  It would be useful to have an option to block execution until a client has managed to connect.

**Comment by gsquared94** [comment] 2021-05-14 21:11
possible dupe of https://github.com/GoogleContainerTools/skaffold/issues/5835 ?

**Comment by tejal29** [comment] 2021-05-17 19:58
closing as dupe

**Closed by tejal29** 2021-05-17 19:58 UTC
Labels: area/api, kind/feature-request, source/partnerships
