### ISSUE TITLE
Images not loaded into kind?

### ISSUE THREAD

**Issue by justinsb** [GoogleContainerTools/skaffold#8039] opened 2022-11-04 13:16 UTC
I'm using kind + kubectl + ko.  When I try to `skaffold run`, kind does not find the image.

Although there is a `Loading images into kind cluster nodes..` phase, nothing happens during this phase.

The reason seems to be that `imagesToLoad(localImages, deployerImages, images []graph.Artifact)` is called with an empty deployerImages list.  Walking back the callsites, it appears that comes from `originalImages` in `kubectl.Deployer`.  The `originalImages` field does not appear ever to be set.

Hacking imagesToLoad to always try loading everything gets past this problem.

Based on #8038, I believe kind loading probably does not have test coverage.

**Comment by aaron-prindle** [comment] 2022-11-07 18:31
Thanks for flagging this, there is a dupe of this issue here https://github.com/GoogleContainerTools/skaffold/issues/7992 so we can close this and track this there. Currently fix PR out https://github.com/GoogleContainerTools/skaffold/pull/8007 that should make it into our next release

kind loading does not currently have any integration test coverage.  Added https://github.com/GoogleContainerTools/skaffold/issues/8049 to track this

**Closed by aaron-prindle** 2022-11-07 18:31 UTC
Labels: kind/bug, priority/p2, platform/kind, area/local

**Comment by arikkfir** [comment] 2023-01-08 21:31
FYI this still happens with Skaffold v2.0.4 (which I think should include #8007 iianm)
Only adding `--load-images=true` fixes it for now.
