### ISSUE TITLE
No logs from container when using "skaffold dev --kubeconfig k8sconfig"

### ISSUE THREAD

**Issue by Exchizz** [GoogleContainerTools/skaffold#4925] opened 2020-10-19 21:37 UTC
### Expected behavior
Skaffold deploys pod and shows stdout from the container

### Actual behavior
Skaffold deploys the pod but does _not_ show stdout from the cont
### Information

- Skaffold version: v1.15.0-22-ga549c7a1d-dirty
- Operating system: Ubuntu 18.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta8
kind: Config
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

1. Clone skaffold repository
2. Create "k8sconfig"-file containing cluster different from what you have in ~/.kube/config
2. Run example "getting-started" using "skaffold dev --kubeconfig k8sconfig"
3. Note how the image is build and deployed but no output from the container
4. mv ~/.kube/config ~/.kube/config_bk
5. mv k8sconfig ~/.kube/config
6. Run "skaffold dev" and you should get output from the container

From --help:
```
    --kubeconfig='': Path to the kubeconfig file to use for CLI requests."
```

So it says --kubeconfig is used when deploying, but I would assume it is also used for getting output from containers ?

I discovered this by inserting the following at pkg/skaffold/kubernetes/watcher.go:79 and noticed it wasn't listing pods from my k8sconfig cluster by from the cluster defined in ~/.kube/config.

```go
pods, _ := kubeclient.CoreV1().Pods("default").List(metav1.ListOptions{
    TimeoutSeconds: &forever,
})
for _, pod := range pods.Items {
    fmt.Println(pod.Name)
}
```

**Comment by tejal29** [comment] 2020-10-27 18:54
@Exchizz for the investigation. 
You could be right.
We have noticed that that `--kubecontext` flag is not respected in #4477

**Comment by briandealwis** [comment] 2020-11-13 16:55
Our local cluster detection doesn't respect `--kubeconfig` either but this is #4347.

@tejal29 #4477 is different in that we're not validating the provided kube-context and as `''` is not matched as a local cluster then builds are happening in the local docker daemon rather than the minikube hosted daemon.  In this case, we seem to have code invoking subcommands with `--context` but not also passing along `--kubeconfig`.

**Comment by briandealwis** [comment] 2020-11-13 18:37
Duplicate of #4347 — we do invoke `kubectl` with the configured kube config files, but our update-check is causing our kubernetes configuration to be initialized too early.

**Closed by briandealwis** 2020-11-13 18:37 UTC
Labels: area/logging, kind/bug, priority/p1
