### ISSUE TITLE
Port Forwarding ignores namespace constraints

### ISSUE THREAD

**Issue by jehowell** [GoogleContainerTools/skaffold#2643] opened 2019-08-14 07:47 UTC
Start the same deployment in 2 different namespaces on 2 different machines
skaffold dev --port-forward --namespace ns1
skaffold dev --port-forward --namespace ns2

### Expected behavior
skaffold dev --port-forward --namespace=<ns> should only forward ports related to the deployment and the namespace.

### Actual behavior
The second skaffold call with forward ports from both ns1 and ns2

Currently, this makes skaffold not useable for development teams to share a k8s cluster.

This is due to the port forwarder doing a label selection on all pods with the managed by skaffold label.

### Information

- Skaffold version: version... 0.35
- Operating system: ...OSX
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```
 
### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project (used the nodejs example)
2. `skaffold dev --port-forward --namespace ns1` one machine 1
3. `skaffold dev --port-forward --namespace ns2' one machine 2
output:

Port forwarding service/node in namespace ns1, remote port 3000 -> local port 3000
Port forwarding service/node in namespace ns2, remote port 3000 -> local port 3001

**Comment by balopat** [comment] 2019-08-14 15:17
Same root cause as #2599.

**Comment by balopat** [comment] 2019-08-22 18:52
This should be fixed now, please let me know if it doesn't work!

**Closed by balopat** 2019-08-22 18:52 UTC
Labels: area/portforward, kind/bug, priority/p1
