### ISSUE TITLE
GCP cloud build quota

### ISSUE THREAD

**Issue by albertkang** [GoogleContainerTools/skaffold#1589] opened 2019-02-02 14:38 UTC
### Expected behavior
We should be able to execute multiple pipelines in our CI.

### Actual behavior
We have 8 services in our skaffold file and the images are built using Google Cloud Build. However, when we have concurrent jobs in our pipeline we are getting `Error 429: Quota exceeded for quota metric 'cloudbuild.googleapis.com/get_requests' and limit 'GetRequestsPerMinutePerProject' of service 'cloudbuild.googleapis.com' `. I know that GCP limits concurrent builds to 10 and if you exceed that limit they will queue the jobs but this error seems to imply something different?

### Information

- Skaffold version: version 0.20
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: gcr.io/some-project/service1
      context: ./services/service1
    - image: gcr.io/some-project/service2
      context: ./services/service2
    - image: gcr.io/some-project/service3
      context: ./services/service3
    - image: gcr.io/some-project/service4
      context: ./services/service4
    - image: gcr.io/some-project/service5
      context: ./services/service5
    - image: gcr.io/some-project/service6
      context: ./services/service6
    - image: gcr.io/some-project/service7
      context: ./services/service7
    - image: gcr.io/some-project/service8
      context: ./services/service8
deploy:
  kubectl:
    manifests:
      - ./manifests/*
profiles:
  - name: gcb-ci
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.SOME_TAG}}"
      googleCloudBuild:
        projectId: xxxx

```

**Comment by briandealwis** [comment] 2019-02-07 19:41
It looks like the GCB `RetryDelay` is set to 1 second:

https://github.com/GoogleContainerTools/skaffold/blob/5c835ed66deaa94795ce6dff635f5ffb2db9c1d6/pkg/skaffold/build/gcb/types.go#L51-L52

**Comment by nkubala** [comment] 2019-03-19 22:29
hey @albertkang, thanks for the issue. I want to try and reproduce this issue, but before I do could you tell me what the quota is set to on your project? navigate to `console.cloud.google.com`, go to the `IAM -> Quotas` page, check out the Cloud Build API section and find `Build and Operation Get requests`. since the quota you're hitting is on a per minute (not per second) basis I suspect you might be hitting this when you have lots of skaffold jobs running simultaneously.

**Comment by priyawadhwa** [comment] 2019-07-09 22:47
Hey @albertkang are you still facing this issue?

**Comment by balopat** [comment] 2019-07-23 22:43
Friendly ping @albertkang is this still an issue? 
I would like to close this for now assuming that users can workaround by increasing the GCP quotas - which should be free AFAIK. If people are really interested in throttling builds in skaffold, please reopen this issue!

**Comment by balopat** [comment] 2019-08-13 16:58
Reopening. 
The issue is at https://github.com/GoogleContainerTools/skaffold/blob/e80a637800d14f8ece314f63d8eca54515753463/pkg/skaffold/build/gcb/cloud_build.go#L118 where we should implement a proper error handling and back-off strategy.

**Closed** 2019-08-22 19:21 UTC
Labels: area/build, build/gcb, help wanted, kind/bug, priority/p1
