### ISSUE TITLE
skaffold does not recover from mismatching image names in yaml

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3910] opened 2020-04-02 17:58 UTC
1. use the microservices example
2. break it: update one of the deployment.yaml's to point to a different image name than the artifact name - e.g. leeroy-app1
3. run skaffold dev -- we don't get any error messages, skaffold just hangs, kubectl get pods shows ImagePullBackOff
4. fix it: change the yaml back to the correct image name 
5. skaffold doesn't recover, it has now two broken pods: 

```
NAME                          READY   STATUS         RESTARTS   AGE
leeroy-app-5b5bdbd465-vw49v   1/1     Running        0          3m24s
leeroy-web-799f5f9f89-b544k   0/1     ErrImagePull   0          3m25s
leeroy-web-854f6888dd-w5fws   0/1     ErrImagePull   0          3m15s
```

**Comment by dgageot** [comment] 2020-04-16 15:54
@balopat I couldn't reproduce.

When I change the name in one of the deployment.yamls, I get a warning saying that one of the images is not used. And then, when I change the name back, it works.

**Comment by briandealwis** [comment] 2020-06-08 20:17
@balopat could you try reproducing again?

**Comment by dgageot** [comment] 2020-06-19 09:34
I'm going to close this one because we can't reproduce

**Closed by dgageot** 2020-06-19 09:34 UTC
Labels: area/build, area/deploy, area/dev, area/status-check, cmd/dev, kind/bug, needs-reproduction, priority/p3
