### ISSUE TITLE
skaffold.yaml UX makes it hard to locate full path to YAML key

### ISSUE THREAD

**Issue by guitarmanvt** [GoogleContainerTools/skaffold#7929] opened 2022-10-09 20:50 UTC
I'm new to Skaffold, so I'm unfamiliar with where different keys belong in context. For example `portForwards` is listed twice, and it's hard to figure out what parent key each one goes under.

https://skaffold.dev/docs/references/yaml/

### Expected behavior

I looked for a collapsible widget, like a tree or code block, so I could easily find the parent this key belongs under. Altenatively, a hover-over with the parent and/or full-path to the key would work.

### Actual behavior

The page only scrolls vertically. When there are a lot of other entries between a key and its parent, it's not easy to locate the parent just by scrolling. Also, this is exacerbated by having only 2 spaces for YAML indentation, with no visual indicators of keys being at the same level (siblings), like in a tree-view.

### Information

- Skaffold version: `v2beta29`
- Operating system: `macOS Big Sur`
- Installed via: `not applicable`
- Contents of skaffold.yaml: `not applicable`

### Steps to reproduce the behavior

1. Browse to https://skaffold.dev/docs/references/yaml/
2. Find a key, for example `portForwards`
3. Try to find its parent (assuming no knowledge of Skaffold YAML structure).

**Comment by aaron-prindle** [comment] 2022-12-19 19:29
Thanks for the issue here, I believe this is a dupe of:
https://github.com/GoogleContainerTools/skaffold/issues/4502

Which suggests adding collapsibility/enhanced-nesting to our doc site's yaml reference to make it easier to determine:
(i) an element's parent, and (ii) whether sub-options may actually be sibling options

**Comment by aaron-prindle** [comment] 2022-12-19 19:32
Closing this as a dupe of #4502, feel free to continue the conversation here in that issue, thanks

**Closed by aaron-prindle** 2022-12-19 19:32 UTC
Labels: area/docs, kind/friction
