### ISSUE TITLE
Skaffold dev not smart enough to deploy just helm chart that changed

### ISSUE THREAD

**Issue by felipem1210** [GoogleContainerTools/skaffold#7297] opened 2022-04-12 22:38 UTC
### Expected behavior

When running `skaffold dev` with a skaffold file that have multiple artifacts deployed with helm I want skaffold to be smart enough to trigger the deploy process just for the artifacts that have changed using the automatic sync mode.

### Actual behavior

Actually, when change occurs in just one artifact, helm chart deploy process is run for all the artifacts

### Information

- Skaffold version: `v1.37.0`
- Operating system: `Ubuntu 20.04`
- Installed via: `skaffold.dev`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta22
kind: Config
build:
  local:
    push: false      
  artifacts:
    - image: myservice
      context: microservice/myservice
    - image: myservice2
      context: microservice/myservice2

deploy:
  kubeContext: kind-example
  helm:
    releases:
      - name: myservice
        chartPath: ./helm/charts/myservice
        namespace: microservices
        createNamespace: true
        valuesFiles:
          - "./helm/dev/microservices/myservice/values.yaml"
        artifactOverrides:
          global.image: myservice
        imageStrategy:
          helm: {}

      - name: myservice2
        chartPath: ./helm/charts/myservice2
        namespace: microservices
        createNamespace: false
        valuesFiles:
          - "./helm/dev/microservices/myservice2/values.yaml" 
        artifactOverrides:
          global.image: myservice2
        imageStrategy:
          helm: {} 
```

### Steps to reproduce the behavior
Run skaffold dev, make changes of code in just `myservice2`. `Skaffold dev` default is to rerun the deployment for both.

**Comment by ericzzzzzzz** [comment] 2022-05-10 16:30
hi @felipem1210  I did some experiments about multiple artifact deployments with ``skaffold dev`` on v1.37.2 using [this example](https://github.com/GoogleContainerTools/skaffold/tree/main/examples/docker-deploy) , when I change one dependent file for one artifact, it only trigger that artifact rebuild/deploy, not all of them. I haven't tried to do it with helm yet, but I'm going to do it. I'll get this back to you soon after I verify the reported behavior also happens on my end.

**Comment by ericzzzzzzz** [comment] 2022-05-12 17:03
hi @felipem1210 , sorry.. I cannot reproduce the issue with v1.37.0, when I changed a file for one artifact.. only that artifact is rebuild/re-deployed.. but there is a strange thing about the REVISION of helm release, when I change one file for one artifact.. all release REVISION upgraded as well, is this the one causing confusion? let me sync this with my team to see if this is expected

**Comment by felipem1210** [comment] 2022-05-12 21:03
Exactly, that's the behave I'm having with the helm deployments. I think is desirable to just upgrade the REVISION of the helm chart affected by some change I make on it.

**Comment by ericzzzzzzz** [comment] 2022-05-12 22:00
Hi @felipem1210 Thank you for the feedback, we will work on a fix for this one

**Comment by felipem1210** [comment] 2022-05-26 19:01
Hi @ericzzzzzzz any update of in which version will be the fix?

**Comment by ericzzzzzzz** [comment] 2022-05-26 19:49
Hi @felipem1210  we don't have a specific date for this change for now. This feature request has already been tracked here https://github.com/GoogleContainerTools/skaffold/issues/5406. I'll work with team to see if we can prioritize this.

**Comment by gsquared94** [comment] 2022-12-05 19:39
Closing this in favor of https://github.com/GoogleContainerTools/skaffold/issues/5406 which will fix this issue.

**Closed by gsquared94** 2022-12-05 19:39 UTC
Labels: priority/p2, area/dev, kind/friction
