### ISSUE TITLE
skaffold spring boot minikube Windows - hot reload/watch not happening

### ISSUE THREAD

**Issue by jvaidyan** [GoogleContainerTools/skaffold#6773] opened 2021-10-27 17:32 UTC
I am trying skaffold to build and deploy a springboot app (has Dockerfile) to minikube. The OS is Windows. First time build and deployment goes fine. But changes are not being detected and reloaded.
With jib maven, the watch works as expected.
Problem occurs when I use Docker file option.

### Expected behavior
Watch should be working upon change of source code.

### Actual behavior
-vdebug shows that change is being detected. But image rebuild and deploy is not happening.

### Information

- Skaffold version: v1.33.1
- Operating system: Windows 10
- Installed via: skaffold.dev 
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: todo
build:
  artifacts:
  - image: skaffold-todo-java
    #jib: {}
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
```
```
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
```
### Steps to reproduce the behavior

1. a regular springboot api with h2 in memory db.
2. `skaffold dev --port-forward -vdebug

```
time="2021-10-27T13:29:27-04:00" level=debug msg="getting client config for kubeContext: `minikube`" subtask=-1 task=DevLoop
time="2021-10-27T13:29:27-04:00" level=debug msg="Forwarding service todo-api-service/8080 to pod todo-api-fc475777-9j4xh/8080" subtask=service/todo-api-service task=PortForward
time="2021-10-27T13:29:27-04:00" level=debug msg="Running command: [kubectl --context minikube port-forward --pod-running-timeout 1s --namespace default pod/todo-api-fc475777-9j4xh 8080:8080]" subtask=service/todo-api-service task=PortForward
Port forwarding service/todo-api-service in namespace default, remote port 8080 -> http://127.0.0.1:8080
time="2021-10-27T13:29:28-04:00" level=debug msg="getting client config for kubeContext: `minikube`" subtask=-1 task=DevLoop
Press Ctrl+C to exit
time="2021-10-27T13:29:28-04:00" level=debug msg="Change detected<nil>" subtask=-1 task=DevLoop
Watching for changes...
time="2021-10-27T13:29:28-04:00" level=info msg="Streaming logs from pod: todo-api-fc475777-9j4xh container: todo-api" subtask=-1 task=DevLoop
time="2021-10-27T13:29:28-04:00" level=debug msg="Running command: [kubectl --context minikube logs --since=5s -f todo-api-fc475777-9j4xh -c todo-api --namespace default]" subtask=-1 task=DevLoop
[todo-api]
[todo-api]   .   ____          _            __ _ _
[todo-api]  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
[todo-api] ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
[todo-api]  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
[todo-api]   '  |____| .__|_| |_|_| |_\__, | / / / /
[todo-api]  =========|_|==============|___/=/_/_/_/
[todo-api]  :: Spring Boot ::                (v2.5.4)
[todo-api]
[todo-api] 2021-10-27 17:29:28.115  INFO 1 --- [           main] com.devexp.todo.TodoApplication          : Starting TodoApplication v0.0.1-SNAPSHOT using Java 1.8.0_212 on todo-api-fc475777-9j4xh with PID 1 (/app.jar started by root in /)
[todo-api] 2021-10-27 17:29:28.118  INFO 1 --- [           main] com.devexp.todo.TodoApplication          : No active profile set, falling back to default profiles: default
[todo-api] 2021-10-27 17:29:29.550  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
[todo-api] 2021-10-27 17:29:29.650  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 63 ms. Found 1 JPA repository interfaces.
time="2021-10-27T13:29:29-04:00" level=debug msg="Found dependencies for dockerfile: [{target\\todo-0.0.1-SNAPSHOT.jar /app.jar false}]" subtask=-1 task=DevLoop
[todo-api] 2021-10-27 17:29:30.569  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
[todo-api] 2021-10-27 17:29:30.594  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
[todo-api] 2021-10-27 17:29:30.598  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.52]
[todo-api] 2021-10-27 17:29:30.727  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
[todo-api] 2021-10-27 17:29:30.731  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2531 ms
[todo-api] 2021-10-27 17:29:30.837  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
[todo-api] 2021-10-27 17:29:31.280  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
[todo-api] 2021-10-27 17:29:31.292  INFO 1 --- [           main] o.s.b.a.h2.H2ConsoleAutoConfiguration    : H2 console available at '/h2'. Database available at 'jdbc:h2:file:~/db'
[todo-api] 2021-10-27 17:29:31.842  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
[todo-api] 2021-10-27 17:29:31.908  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.32.Final
[todo-api] 2021-10-27 17:29:32.082  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
[todo-api] 2021-10-27 17:29:32.218  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
[todo-api] 2021-10-27 17:29:32.952  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
[todo-api] 2021-10-27 17:29:32.966  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
[todo-api] 2021-10-27 17:29:33.888  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
[todo-api] 2021-10-27 17:29:34.790  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
[todo-api] 2021-10-27 17:29:35.188  INFO 1 --- [           main] com.devexp.todo.TodoApplication          : Started TodoApplication in 7.808 seconds (JVM running for 8.508)
```

### Upon change:
```
[todo-api] 2021-10-27 17:29:35.188  INFO 1 --- [           main] com.devexp.todo.TodoApplication          : Started TodoApplication in 7.808 seconds (JVM running for 8.508)
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Create: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\src\\main\\java\\com\\devexp\\todo\\controller\\TodoController.java___jb_tmp___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Write: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\src\\main\\java\\com\\devexp\\todo\\controller\\TodoController.java___jb_tmp___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Rename: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\src\\main\\java\\com\\devexp\\todo\\controller\\TodoController.java___jb_old___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Rename: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\src\\main\\java\\com\\devexp\\todo\\controller\\TodoController.java\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Rename: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\src\\main\\java\\com\\devexp\\todo\\controller\\TodoController.java\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Rename: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\src\\main\\java\\com\\devexp\\todo\\controller\\TodoController.java___jb_tmp___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Write: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\src\\main\\java\\com\\devexp\\todo\\controller\\TodoController.java\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Remove: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\src\\main\\java\\com\\devexp\\todo\\controller\\TodoController.java___jb_old___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Create: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\.idea\\workspace.xml___jb_tmp___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Write: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\.idea\\workspace.xml___jb_tmp___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Rename: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\.idea\\workspace.xml___jb_old___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Rename: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\.idea\\workspace.xml\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Rename: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\.idea\\workspace.xml\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Rename: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\.idea\\workspace.xml___jb_tmp___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Write: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\.idea\\workspace.xml\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:11-04:00" level=debug msg="Change detectednotify.Remove: \"C:\\projects\\DeveloperExperiance\\skaffold\\Java\\todo\\.idea\\workspace.xml___jb_old___\"" subtask=-1 task=DevLoop
time="2021-10-27T13:30:12-04:00" level=debug msg="Found dependencies for dockerfile: [{target\\todo-0.0.1-SNAPSHOT.jar /app.jar false}]" subtask=-1 task=DevLoop

```

**Comment by briandealwis** [comment] 2021-11-09 04:38
Skaffold's file-watcher traces through the ADD/COPY statements in your Dockerfile to identify the files that are actually used in the build, and hence should be watched.

Your Dockerfile is looking for a single .jar to be found in `target`, and so doesn't actually do a build in the container.  So I'm guessing you're expecting your IDE (IntelliJ, from the looks of it) to build the .jar file.  Which should work fine, but from the detected file changes, IntelliJ isn't actually regenerating the jar file.  If you can get IntelliJ to build the jar then this should work as you expect.

**Comment by briandealwis** [comment] 2021-11-09 04:42
Closing as I believe this is working as intended.

**Closed** 2021-11-09 04:41 UTC
Labels: kind/question, area/watch, platform/windows, platform/minikube
