### ISSUE TITLE
Profile with Empty Section {} is not removing previous

### ISSUE THREAD

**Issue by dhodun** [GoogleContainerTools/skaffold#5639] opened 2021-04-07 17:43 UTC
Initially I tried to remove a section from base config using a profile and an empty section, i.e. build: {} but this didn't work. Ultimately found the "proper" was to do this with a patch and remove op, but still curious if this intended behavior, maybe a JSON thing.

### Expected behavior

```yaml
apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: redis
deploy:
  kustomize:
    paths:
    - ./kustomize/minikube
profiles:
- name: dev
  deploy: {}
```
Should essentially override and remove the deploy section, I think?

### Actual behavior

The base profile is deployed as if profile not applied.

Ultimately fixed this with:

```yaml
profiles:
- name: dev
   patches:
      -op: remove
      -patch: /deploy
```

### Information

- Skaffold version: v1.21.0
- Operating system: macos
- Installed via: Homebrew

**Comment by dhodun** [comment] 2021-04-07 17:43
@dgageot - related to https://github.com/GoogleContainerTools/skaffold/issues/3044

**Comment by tejal29** [comment] 2021-04-07 18:45
Thanks @dhodun for investigating this and also listing the workaround.  I am not very well versed with this code.

**Comment by briandealwis** [comment] 2021-05-23 03:36
Duplicate of #5639 (code and doc refs are there)

**Closed by briandealwis** 2021-05-23 03:36 UTC
Labels: area/profiles, has-workaround, help wanted, kind/bug, priority/p3
