### ISSUE TITLE
Permission denied when pushing to ECR using skaffold (ecr credential helper works)

### ISSUE THREAD

**Issue by NotSoShaby** [GoogleContainerTools/skaffold#3218] opened 2019-11-11 10:31 UTC
Trying to use ECR as a repo i followed the directions [here](https://github.com/awslabs/amazon-ecr-credential-helper) for credentials helper. I tested it and it works from terminal using a simple `docker push <ECR REGISTRY>/<IMAGE_NAME>:<TAG> . but using skaffold, the push fails on auth issue

### Expected behavior
skaffold will be able to push as long as `amazon-ecr-credential-helper` is configured properly

### Actual behavior
`docker push` works, but skaffold fails pushing

### Information

- Skaffold version: 1.0
- Operating system: macOS Mojave
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.BASE_TAG}}"
  artifacts:
  - imageName: <ECR REGISTRY>/<IMAGE_NAME>
    workspace: ..
    docker:
      dockerfilePath: ./BaseDockerfile
  local:
deploy:
  kubectl:
    manifests:
      - k8s-*
```

### Steps to reproduce the behavior

k8s-celery-pod.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: celery
spec:
  containers:
  - name: celery
    image: <ECR REGISTRY>/<IMAGE_NAME>:<BASE_TAG>  
    command: "pipenv run celery worker -c 4 -l INFO -A autoai.celery.core.celery"
```

Error i get:

`FATA[0011] exiting dev mode because first build failed: pushing image: denied: requested access to the resource is denied`

`docker push <ECR REGISTRY>/<IMAGE_NAME>:<BASE_TAG>` in the same environment works fine

**Comment by adamgajzlerowicz** [comment] 2019-11-12 09:26
I am getting the same error on ubuntu. Pushing to docker hub works fine, but running `scaffold dev` fails with the above error.

I am just getting started with scaffold. Could it be that it is trying to push to a wrong registry, or uses different context than my workstation? 

Thanks.

**Comment by alex-roman** [comment] 2020-02-16 15:21
Having the same issue with skaffold+ECR. Tried both `aws ecr get-login --no-include-email` and ecr-credential-helper - both ignored by skaffold.

**Comment by chanseokoh** [comment] 2020-03-18 21:25
It works for me. I just copy-pasted the login command from the ECR page, and Skaffold does push my image to ECR.

```
aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <my account id>.dkr.ecr.us-east-1.amazonaws.com/francium25/test
```

Note that the command above put a short-lived credential into my `~/.docker/config.json`.

```
    "auths": {
        "<my account id>.dkr.ecr.us-east-1.amazonaws.com": {
            "auth": "QVdTOmV5SndZWGxzYjJG..."
```

Skaffold does pick up this credential and pushes an image.

![Screenshot from 2020-03-18 17-12-42](https://user-images.githubusercontent.com/10523105/77008316-4f714900-693c-11ea-8ca1-cd6b668924b0.png)

Using the credential helper `docker-credential-ecr-login` also works.

```
    "credHelpers": {
        "<my account id>.dkr.ecr.us-east-1.amazonaws.com": "ecr-login",
        "asia.gcr.io": "gcloud",
```

Of course, if I remove both `auths` and `credHelpers`, Skaffold fails to push the image.

```
Checking cache...
 - <my account id>.dkr.ecr.us-east-1.amazonaws.com/francium25/test: Found. Pushing
The push refers to repository [<my account id>.dkr.ecr.us-east-1.amazonaws.com/francium25/test]
f2cb0ecef392: Preparing 
FATA[0000] exiting dev mode because first build failed: pushing image: no basic auth credentials 
```

**Comment by chanseokoh** [comment] 2020-03-18 21:27
Googling the error message `denied: requested access to the resource is denied` makes me believe that the error message is coming from Docker Hub, not AWS ECR. It's possible that @NotSoShaby used a wrong image reference (`<ECR REGISTRY>/<IMAGE_NAME>` does look suspiciously a Docker Hub image) pointing to Docker Hub.

**Comment by briandealwis** [comment] 2020-04-20 21:21
If you're experiencing this issue, could you please attach a debug log with running `skaffold ... -v debug`.

**Comment by briandealwis** [comment] 2020-06-08 20:24
Closing.  Will re-open if new information provided.

**Closed by briandealwis** 2020-06-08 20:24 UTC
Labels: area/build, kind/documentation, needs-reproduction, platform/aws

**Comment by treyhyde** [comment] 2021-01-26 04:22
i just ran into this after update to .19.

There is some app that continually adds gcr entries in my .docker/config.json... I don't have the gcr helper..
Got some warning from skaffold that it was skipping my helpers because the google cloud helper wasn't on my path.  I don't care much about that since I use ECR.   Deleted gcr entries from the config and skaffold works fine again to pull ECR images with the ECR helper.
So for me, delete gcr entries or I would have suspected that installing the google cloud helper would have allowed my ECR helper to work.   So... overly aggressive preconditions on helper usage.

**Comment by OpenAIMP** [comment] 2022-12-23 11:37
Hi, Is there a solution for this problem?

We are deploying images to AWS/ECR and the push fails stating that the repo not found whereas the repo exists and images can be pushed via Docker.
The issue is that the image can be pushed as long as it is formatted with colon (:) "repo-name:image-name" as opposed to slash (/) "repo-name/image-name".
The below build works for [gcr.io](http://gcr.io/) but not for 1234567890.dkr.ecr.us-east-2.amazonaws.com/repo-name
  build:
    artifacts:
      - image: frontend
        context: ./frontend/
      - image: backend
        context: ./backend/
The skaffold run command is executed with default-repo flag.
The image to be pushed to AWS/ECR has to be in this format:
1234567890.[dkr.ecr.us-east-2.amazonaws.com/repo-name:frontend](http://dkr.ecr.us-east-2.amazonaws.com/repo-name:frontend)
1234567890.[dkr.ecr.us-east-2.amazonaws.com/repo-name:backend](http://dkr.ecr.us-east-2.amazonaws.com/repo-name:backend)
How can we append the image-name with ":" at the end of the repo? Is there any image tag policy that will allow this?
I've already reviewed this link but this was not of much help - https://skaffold.dev/docs/environment/image-registries/
