### ISSUE TITLE
Deployment status-check is misleading on our pod-only getting-started

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#4283] opened 2020-06-01 16:54 UTC
We have only a **pod** in our getting-started example. This can cause some oddness with status-check which only looks at **Deployments**: the deployment seems to succeed even if the pod is pending! It looks like logging is broken, until user runs `kubectl get pods`. 

Repro in minikube  

1. `kubectl taint nodes minikube key=value:NoSchedule`
1. `skaffold dev` on the getting-started example 

The output is from Tejal's PR https://github.com/GoogleContainerTools/skaffold/pull/4223 which is better than master but still not sufficient: 

```
...

Successfully tagged gcr.io/balintp-gcp-lab/skaffold-example:v1.10.0-47-g0bec3d0e7
Tags used in deployment:
 - skaffold-example -> gcr.io/balintp-gcp-lab/skaffold-example:2d2c5bd5243ac8274bf2d6eccb52208c0a08136990eb69735e2886b8a447deee
Starting deploy...
 - pod/getting-started created
Waiting for deployments to stabilize...
Deployments stabilized in 15.01709ms
Press Ctrl+C to exit
Watching for changes...
^CCleaning up...
 - pod "getting-started" deleted
There is a new version (1.10.1) of Skaffold available. Download it from:
```

While `kubectl describe pod` shows the events 
```
...
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) had taint {key: value}, that the pod didn't tolerate.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/1 nodes are available: 1 node(s) had taint {key: value}, that the pod didn't tolerate.
```

**Comment by briandealwis** [comment] 2021-08-22 15:50
This is still an issue.

**Comment by briandealwis** [comment] 2021-10-04 14:52
Duplicate of #5529 

(Although this is earlier, work is being tracked in #5529.)

**Closed by briandealwis** 2021-10-04 14:52 UTC
Labels: kind/bug, priority/p2, area/status-check
