### ISSUE TITLE
Helm deployment with image name not at top level of the values structure.

### ISSUE THREAD

**Issue by lboclboc** [GoogleContainerTools/skaffold#3652] opened 2020-02-06 17:05 UTC
When trying to deploy jenkins via skaffold and helm I get this go-error:
```
Starting deploy...
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc0006b0ee0, 0xc0004fff20, 0xc00061f898, 0x6)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:211 +0xdea
helm.sh/helm/v3/pkg/strvals.(*parser).key(0xc0006b0ee0, 0xc0006d61e0, 0x1535b1d, 0x17d2ce0)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:215 +0x1ad
helm.sh/helm/v3/pkg/strvals.(*parser).parse(0xc0006b0ee0, 0xc0006d61e0, 0x1)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:133 +0x38
helm.sh/helm/v3/pkg/strvals.ParseIntoString(0x7ffed9fd0eec, 0xc1, 0xc0006d61e0, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/strvals/parser.go:93 +0xbe
helm.sh/helm/v3/pkg/cli/values.(*Options).MergeValues(0xc000642ae0, 0xc0006b0840, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/circleci/helm.sh/helm/pkg/cli/values/options.go:69 +0x2ac
main.newUpgradeCmd.func1(0xc0004e6780, 0xc0005bac30, 0x2, 0xf, 0x0, 0x0)
	/home/circleci/helm.sh/helm/cmd/helm/upgrade.go:81 +0x1f7
github.com/spf13/cobra.(*Command).execute(0xc0004e6780, 0xc0005bab40, 0xf, 0xf, 0xc0004e6780, 0xc0005bab40)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003ce280, 0x1bc61c0, 0xc00044c0b0, 0x7ffed9fd0ed4)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:74 +0x1e2
FATA[0000] deploying ssvjenkins-playground: exit status 2 
```

I am trying to deploy jenkins with helm and it has its image specified as key master.image, like:
```
      values:
        master.image: registry2:443/atlas-ssvjenkins
      imageStrategy:
        helm: {}
```
### Expected behavior
If should deploy helm with proper image tags.

### Actual behavior
It deploys the jenkins helm with double tags on the image.

### Information

- Skaffold version 7b4da99.
- Ubuntu 18.04
- Contents of skaffold.yaml:
```
apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: ssv-jenkins

build:
  artifacts:
  - image: registry2:443/atlas-ssvjenkins
    docker:
      dockerfile: Dockerfile

deploy:
  helm:
    releases:
    - name: ssvjenkins-playground
      chartPath: stable/jenkins
      version: 1.9.16
      remote: true
      valuesFiles: 
      - ssv_jenkins_values
      namespace: playground
      values:
        master.image: registry2:443/atlas-ssvjenkins
      imageStrategy:
        helm: {} 
      setValues:
        master.nodePort: "32334"
    flags: { upgrade: [--install] }

```
### Steps to reproduce the behavior

1.skaffold run
2. kubectl get pod -> Shows pods can not start due to illegal image.

**Comment by TBBle** [comment] 2020-03-06 12:16
The problem is that the Jenkins chart sets up image with two [adjacent fields in values.yaml, `image` and `tag`](https://github.com/helm/charts/blob/094ca1ff07ed460b937c6e5c70f2d849dc41ede2/stable/jenkins/values.yaml#L68).

Skaffold's `imageStrategy` doesn't support that layout. I listed the layouts that are currently supported [in a different ticket](https://github.com/helm/helm/issues/7517#issuecomment-593106258).

Your current config will try to set `master.image.repository` and `master.image.tag`, and the [Jenkins Master Deployment](https://github.com/helm/charts/blob/094ca1ff07ed460b937c6e5c70f2d849dc41ede2/stable/jenkins/templates/jenkins-master-deployment.yaml#L95) expects `master.image` to be a string.

So you have a few ways forward:
* Raise a ticket with the Jenkins chart to support either `master.image.repository` + `master.image.tag`, or `master.repository` + `master.tag`.
* Raise a ticket with the Jenkins chart to align their image configuration strategy with other charts in the [Helm Charts repo](https://github.com/helm/charts/). That might be the above, or it might be the three-way `registry`/`repository`/`tag` split (which is the most-flexible strategy Helm supports).
* Raise a feature request with Skaffold to support this layout as another image strategy.
* Raise a feature request with Skaffold to implement a generalised imageStrategy that lets you specify how to apply the components of the generated image location as Helm values.

That last one would be interesting as it would also support, e.g., Agones, which uses `registry` and `tag`.

This config option is already a little messy as it assumes every chart in your release uses the same image strategy. So there are possibly even grander feature requests that could be raised from this.

**Comment by nkubala** [comment] 2020-04-24 19:09
@lboclboc thanks for opening, and @TBBle thanks for the detailed explanation. indeed there are only a limited number of image configurations supported for helm in skaffold at the moment, and this is something we're actively considering changing. however, this would require a significant rework of helm support in skaffold so it's something we need to be careful doing. we all agree that it would be nice to have more flexible image configuration support in skaffold, but it's unclear exactly how that would happen in skaffold.

i'm going to close this issue for now, as I think the direct question has been answered and we're tracking helm improvements in other open issues.

**Closed by nkubala** 2020-04-24 19:09 UTC
Labels: area/deploy, deploy/helm, help wanted, kind/bug, needs-reproduction, priority/p3
