### ISSUE TITLE
[DOCS]: Release notes for `v2.13.0` _Full Changelog_ link is wrong

### ISSUE THREAD

**Issue by wallind** [GoogleContainerTools/skaffold#9477] opened 2024-07-18 13:25 UTC
# Summary

Not a problem with the actual code, just wanted to point out that the release notes for [v2.13.0](https://github.com/GoogleContainerTools/skaffold/releases/tag/v2.13.0) have a small typo with an extra `v` in there:

![image](https://github.com/user-attachments/assets/c591cb1b-11d6-47d8-b69a-9078caee1ea4)

Easy enough for someone experienced on Github to figure out, but does lead to a dead link https://github.com/GoogleContainerTools/skaffold/compare/vv2.12.0...v2.13.0 :

![image](https://github.com/user-attachments/assets/0df659c5-6aad-4d44-9f7a-64ac27876cfc)

Would fix with a PR, but Github release notes aren't in the source.

**Comment by ericzzzzzzz** [comment] 2024-07-18 15:35
thank you. The issue is fixed now

**Closed by ericzzzzzzz** 2024-07-18 15:35 UTC
