### ISSUE TITLE
FR: Add .IMAGE_TAG template variable

### ISSUE THREAD

**Issue by InsOpDe** [GoogleContainerTools/skaffold#3549] opened 2020-01-21 19:01 UTC
### Expected behavior
There should be a way to retrieve the `image-tag` somehow in order to correctly insert it into the `skaffold.yaml`

According to https://skaffold.dev/docs/environment/templating/ `{{.IMAGE_NAME}}` is usable but not `{{.IMAGE_TAG}}`

### Actual behavior
Kubernetes reports the Error `Back-off pulling image "example.azurecr.io/example/cloud/social/rating"`
Clearly here's missing the image-tag. 

### Information

- Skaffold version: v1.2.0
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: example-social-cloud-rating-service
build:
  artifacts:
  - image: example.azurecr.io/example/cloud/social/rating
    jib: {}
  local: {}
deploy:
  helm:
    flags:
      upgrade: ["-i"]
    releases:
    - name: example-social-cloud-rating-service
      chartPath: helm
      namespace: example-socialcloud-dev
      setValueTemplates:
        "web.image": example.azurecr.io/example/cloud/social/rating
        "web.imageTag": "{{ .IMAGE_TAG }}"
        "web.name": example-social-cloud-rating-service
        "web.host": rating.social.cloud.example.com
```

With the `deployment.yaml`:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.web.name }}
    namespace: {{ .Release.Namespace }}
    labels:
        app: {{ .Values.web.name }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ .Values.web.name }}
    template:
        metadata:
            labels:
                app: {{ .Values.web.name }}
        spec:
            containers:
                -
                    image: "{{ .Values.web.image }}"
                    imagePullPolicy: Always
                    name: {{ .Values.web.name }}
                    ports:
                        -
                            containerPort: 8080
                    livenessProbe:
                        httpGet:
                            path: /healthz/ready
                            port: 8080
                    readinessProbe:
                        httpGet:
                            path: /healthz/ready
                            port: 8080

```

**Comment by InsOpDe** [comment] 2020-01-21 19:01
I believe this might be related to https://github.com/GoogleContainerTools/skaffold/issues/3497

**Comment by kylewolfe** [comment] 2020-02-19 21:13
I opened #3343 for this reason as well.

**Comment by dkirrane** [comment] 2020-03-02 12:49
+1 it looks like there is no way to get the image tag from the tagPolicy to use later in helm.

```
  tagPolicy:
    dateTime:
      format: "2006-01-02_15-04-05.999_MST"
      timezone: "Local"
```

There is no way to get the image and tag and pass it to helm
```
  helm:
    releases:
    - name: my-app
      chartPath: ./helm
      skipBuildDependencies: true
      setValueTemplates:
        image.repository: '{{.IMAGE_NAME}}'
        image.tag: '{{.IMAGE_TAG}}'
```

**Comment by Romeh** [comment] 2020-03-04 23:17
+1 for this as well !

**Comment by joberdick** [comment] 2020-03-05 01:48
I have found a workaround that helps, but still not flexible enough if you need image tag by itself.

I found this in debug output
`level=debug msg="EnvVarMap: map[DIGEST:988737991187.dkr.ecr.us-east-2.amazonaws.com/sandbox-999999-titanium:latest@sha256:8f68c8204660819340f81c94001ce651bfe87e83ab1598eb5e91bd861a39831f DIGEST_ALGO:988737991187.dkr.ecr.us-east-2.amazonaws.com/sandbox-999999-titanium DIGEST_HEX:latest@sha256:8f68c8204660819340f81c94001ce651bfe87e83ab1598eb5e91bd861a39831f IMAGE_NAME:988737991187.dkr.ecr.us-east-2.amazonaws.com/sandbox-999999-titanium]`

I was able to get image+tag with this in my skaffold config:

```
     setValueTemplates:
        global.deployment.image.repository: "{{.DIGEST}}"
```

**Comment by tstromberg** [comment] 2020-04-24 19:50
I think this seems reasonable. PR's welcome!

**Comment by nkubala** [comment] 2020-04-24 21:14
I'm going to close this as a dupe of #3343 so we can keep the conversation to one issue, I think that one covers what's being asked here.

**Closed by nkubala** 2020-04-24 21:14 UTC
Labels: area/templating, fixit, kind/feature-request, priority/p1
