### ISSUE TITLE
Feature: Support executing arbitrary commands before build/deploy steps etc

### ISSUE THREAD

**Issue by bitsofinfo** [GoogleContainerTools/skaffold#3688] opened 2020-02-14 20:21 UTC
I have a need to run a custom command just prior to my `build:` declaration. Would be great to have support to execute one or more arbitrary commands prior to the build and deploy steps. 

https://kubernetes.slack.com/archives/CABQMSZA6/p1581538776128400

#3681

**Comment by dgageot** [comment] 2020-02-20 09:36
Closing as a duplicate of #1441. It's a feature that we have on the roadmap. We understand that it would be very useful

**Closed by dgageot** 2020-02-20 09:36 UTC
