### ISSUE TITLE
Add support for "kubectl apply -k" in addition to "kustomize"

### ISSUE THREAD

**Issue by poikilotherm** [GoogleContainerTools/skaffold#2431] opened 2019-07-08 14:14 UTC
This is a feature request, not a bug report.

Currently, with v0.33.0 you can use either `kubectl` or `kustomize` deployer. 
When a `kustomization.yaml` file is present, the `kubectl` deployer fails, as validation is failing (see also kubernetes-sigs/kustomize#738).

On the other hand, I need to install standalone `kustomize` binary for kustomize deployer, when I could as well use `kubectl apply -k`. These days, `kustomize` has been integrated into `kubectl` and should be available.

I request a feature that Skaffold is able to use `kubectl apply -k`, so less tools need to be installed to get people started. This might be safeguarded by looking at the kubectl version, giving a gracefull error message when an upgraded version or standalone installation is necessary.

Thank you!

**Comment by priyawadhwa** [comment] 2019-07-08 17:38
Hey @poikilotherm thanks for opening this feature request, you make some good points and I definitely agree it's an important feature to add.  We have an open issue for this (#1781) and we are planning on getting to this soon! I'm going to close this issue as a dupe of the other one, but until we add this feature in you can work around it by specifying `-k` as an additional flag to pass to kubectl:

```yaml
kubectl:
  flags:
    apply:
      - -
      - k
```
Here's the skaffold config [reference](https://skaffold.dev/docs/references/yaml/) for more info about specifying additional `kubectl apply` flags.

**Closed by priyawadhwa** 2019-07-08 17:38 UTC
Labels: deploy/kubectl, deploy/kustomize, kind/feature-request

**Comment by poikilotherm** [comment] 2019-07-08 21:58
Sorry for the noise... I tried to search the issues for this but did not find that issue, maybe just overlooked it. Thx for pointing it out and adding the workaround :+1:

**Comment by franxois** [comment] 2019-09-19 08:38
> Hey @poikilotherm thanks for opening this feature request, you make some good points and I definitely agree it's an important feature to add. We have an open issue for this (#1781) and we are planning on getting to this soon! I'm going to close this issue as a dupe of the other one, but until we add this feature in you can work around it by specifying `-k` as an additional flag to pass to kubectl:
> 
> ```yaml
> kubectl:
>   flags:
>     apply:
>       - -
>       - k
> ```
> 
> Here's the skaffold config [reference](https://skaffold.dev/docs/references/yaml/) for more info about specifying additional `kubectl apply` flags.

Hi,
Thanks for the workaround, but for me ["-","k"] did works. I had to use

```yaml
  kubectl:
    flags:
      global:
        - -k
```

Cleanup doesn't work, ends with : 
`error: only one of -f or -k can be specified`
