### ISSUE TITLE
Get build timeout on local concurrent build

### ISSUE THREAD

**Issue by kvokka** [GoogleContainerTools/skaffold#3695] opened 2020-02-18 17:13 UTC
### Actual behavior

with `skaffold dev` i rarely get this sort of error:

```
Sending build context to Docker daemon  9.742MB
Step 1/10 : FROM node:10.15
FATA[1032] failed to build: build failed: building [us.gcr.io/replay-gaming/poker-api]: build artifact: unable to stream build output: Get https://registry-1.docker.io/v2/library/node/manifests/10.15: net/http: TLS handshake timeout
make[1]: *** [dependencies] Error 1
make: *** [init] Error 2
```

Keep in mind, that building of all images takes more than 15 minutes

### Information

- Skaffold version: 1.3.1
- Operating system: MacOs 10.15
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2alpha3
kind: Config
build:
  local:
    concurrency: 0
  tagPolicy:
    sha256: {}
  artifacts:
  - image: us.gcr.io/replay-gaming/rails
    docker:
      dockerfile: docker/development/Dockerfile
    context: rails
    sync:
      infer:
      - 'app/**/*'
      - 'bin/**/*'
      - 'db/**/*'
      - 'lib/**/*'
      - 'public/**/*'
      - 'script/**/*'
      - 'spec/**/*'
  - image: us.gcr.io/replay-gaming/poker-core
    docker:
      dockerfile: docker/development/Dockerfile
    context: core
    sync:
      infer:
        - 'bin/**/*'
        - 'db/**/*'
        - 'lib/**/*'
        - 'system/**/*'
        - 'schemas/**/*'
        - 'spec/**/*'
  - image: us.gcr.io/replay-gaming/poker-api
    docker:
      dockerfile: docker/development/Dockerfile
    context: api
    sync:
      infer:
        - 'bin/**/*'
        - 'src/**/*'
        - 'tests/**/*'
  - image: us.gcr.io/replay-gaming/poker-client
    docker:
      dockerfile: docker/development/Dockerfile
    context: client
    sync:
      infer:
        - 'bin/**/*'
        - 'public/**/*'
        - 'src/**/*'
  - image: us.gcr.io/replay-gaming/poker-scheduler
    docker:
      dockerfile: docker/development/Dockerfile
    context: scheduler
    sync:
      infer:
        - 'src/**/*'
  - image: us.gcr.io/replay-gaming/go-eventsource
    context: es
```

I assume that the root of the problem is in `concurrency` setting.

### Steps to reproduce the behavior

`skaffold dev`

This is flaky!

**Comment by dgageot** [comment] 2020-02-20 09:28
Hi @kvokka! Can you give us more details about which version of Docker you are using? Also could you share the output of `skaffold build -vdebug`?

**Comment by kvokka** [comment] 2020-02-20 13:23
```bash
$ docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      true
```

Will try to catch the error once more time today with `-debug` flag.

**Comment by kvokka** [comment] 2020-02-21 21:11
```bash
$ skaffold build -vdebug                                                                                       
INFO[0000] Skaffold &{Version:v1.3.1 ConfigVersion:skaffold/v2alpha3 GitVersion: GitCommit:6ba887a42438d1da578a005cf550e618fee6dfb8 GitTreeState:clean BuildDate:2020-01-31T19:55:18Z GoVersion:go1.13.4 Compiler:gc Platform:darwin/amd64}
INFO[0000] Activated kube-context "minikube"
DEBU[0000] validating yamltags of struct SkaffoldConfig
DEBU[0000] validating yamltags of struct Metadata
DEBU[0000] validating yamltags of struct Pipeline
DEBU[0000] validating yamltags of struct BuildConfig
DEBU[0000] validating yamltags of struct Artifact
DEBU[0000] validating yamltags of struct Sync
DEBU[0000] validating yamltags of struct ArtifactType
DEBU[0000] validating yamltags of struct DockerArtifact
DEBU[0000] validating yamltags of struct Artifact
DEBU[0000] validating yamltags of struct Sync
DEBU[0000] validating yamltags of struct ArtifactType
DEBU[0000] validating yamltags of struct DockerArtifact
DEBU[0000] validating yamltags of struct Artifact
DEBU[0000] validating yamltags of struct Sync
DEBU[0000] validating yamltags of struct ArtifactType
DEBU[0000] validating yamltags of struct DockerArtifact
DEBU[0000] validating yamltags of struct Artifact
DEBU[0000] validating yamltags of struct Sync
DEBU[0000] validating yamltags of struct ArtifactType
DEBU[0000] validating yamltags of struct DockerArtifact
DEBU[0000] validating yamltags of struct Artifact
DEBU[0000] validating yamltags of struct Sync
DEBU[0000] validating yamltags of struct ArtifactType
DEBU[0000] validating yamltags of struct DockerArtifact
DEBU[0000] validating yamltags of struct Artifact
DEBU[0000] validating yamltags of struct ArtifactType
DEBU[0000] validating yamltags of struct DockerArtifact
DEBU[0000] validating yamltags of struct TagPolicy
DEBU[0000] validating yamltags of struct ShaTagger
DEBU[0000] validating yamltags of struct BuildType
DEBU[0000] validating yamltags of struct LocalBuild
DEBU[0000] validating yamltags of struct DeployConfig
DEBU[0000] validating yamltags of struct DeployType
DEBU[0000] validating yamltags of struct HelmDeploy
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmDeployFlags
DEBU[0000] validating yamltags of struct Profile
DEBU[0000] validating yamltags of struct Pipeline
DEBU[0000] validating yamltags of struct BuildConfig
DEBU[0000] validating yamltags of struct TagPolicy
DEBU[0000] validating yamltags of struct BuildType
DEBU[0000] validating yamltags of struct DeployConfig
DEBU[0000] validating yamltags of struct DeployType
DEBU[0000] validating yamltags of struct HelmDeploy
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmRelease
DEBU[0000] validating yamltags of struct HelmOverrides
DEBU[0000] validating yamltags of struct HelmImageStrategy
DEBU[0000] validating yamltags of struct HelmImageConfig
DEBU[0000] validating yamltags of struct HelmDeployFlags
DEBU[0000] validating yamltags of struct KubectlDeploy
DEBU[0000] validating yamltags of struct KubectlFlags
INFO[0000] Using kubectl context: minikube
DEBU[0000] Using builder: local
DEBU[0000] Running command: [minikube docker-env --shell none]
DEBU[0000] Command output: [DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://192.168.64.8:2376
DOCKER_CERT_PATH=/Users/mike/.minikube/certs
MINIKUBE_ACTIVE_DOCKERD=minikube
]
DEBU[0000] setting Docker user agent to skaffold-v1.3.1
DEBU[0000] push value not present, defaulting to false because localCluster is true
Generating tags...
 - us.gcr.io/replay-gaming/rails -> us.gcr.io/replay-gaming/rails:latest
 - us.gcr.io/replay-gaming/poker-core -> us.gcr.io/replay-gaming/poker-core:latest
 - us.gcr.io/replay-gaming/poker-api -> us.gcr.io/replay-gaming/poker-api:latest
 - us.gcr.io/replay-gaming/poker-client -> us.gcr.io/replay-gaming/poker-client:latest
 - us.gcr.io/replay-gaming/poker-scheduler -> us.gcr.io/replay-gaming/poker-scheduler:latest
 - us.gcr.io/replay-gaming/go-eventsource -> us.gcr.io/replay-gaming/go-eventsource:latest
INFO[0000] Tags generated in 482.038µs
Checking cache...
DEBU[0002] Found dependencies for dockerfile: [{docker/entrypoint /app/docker/entrypoint false} {package-lock.json /app true} {package.json /app true} {Gemfile /app true} {Gemfile.lock /app true} {build.json /app false} {.eslintrc.js /app false} {webpack.config.js /app false} {config.ru /app false} {Rakefile /app/Rakefile false} {bin /app/bin false} {chrome_store /app/chrome_store false} {vendor/assets /app/vendor/assets false} {db /app/db false} {public /app/public false} {script /app/script false} {config /app/config false} {lib /app/lib false} {app /app/app false}]
DEBU[0002] Skipping excluded path: public/assets
DEBU[0002] Skipping excluded path: public/assets/assets2
DEBU[0003] Skipping excluded path: config/database.yml
DEBU[0007] Found dependencies for dockerfile: [{yarn.lock /yarn.lock false} {package.json /package.json false} {. /app false}]
DEBU[0007] Found dependencies for dockerfile: [{yarn.lock /yarn.lock false} {package.json /package.json false} {. /app true}]
DEBU[0007] Found dependencies for dockerfile: [{Gemfile /app true} {Gemfile.lock /app true} {Rakefile /app true} {bin /app/bin false} {system /app/system false} {schemas /app/schemas false} {db /app/db false} {lib /app/lib false} {spec /app/spec false}]
DEBU[0007] Found dependencies for dockerfile: [{yarn.lock /yarn.lock false} {package.json /package.json false} {. /app false}]
DEBU[0007] Found dependencies for dockerfile: [{go.sum /src true} {go.mod /src true} {event.go /src true} {eventsource.go /src true} {eventsource_test.go /src true} {log_metrics.go /src true} {logging.go /src true} {stackdriver_metrics.go /src true}]
DEBU[0007] Skipping excluded path: node_modules/is-plain-obj
DEBU[0007] Skipping excluded path: node_modules/write

[ ... CUT ...]

 ---> Running in 2278e45c4b56
 ---> f6568ffae084
Step 7/9 : RUN yarn install
 ---> Running in cc60e4363b99
yarn install v1.13.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
Done in 73.03s.
 ---> d65130087979
Step 8/9 : WORKDIR /app
 ---> Running in 699aa70a6beb
 ---> 846f4d7562ee
Step 9/9 : ADD . /app
 ---> efa2a9520118
Successfully built efa2a9520118
Successfully tagged us.gcr.io/replay-gaming/poker-scheduler:latest
Building [us.gcr.io/replay-gaming/go-eventsource]...
Sending build context to Docker daemon  25.09kB
Step 1/9 : FROM golang:1.13-alpine AS build_base
1.13-alpine: Pulling from library/golang
c9b1b535fdd9: Pulling fs layer
cbb0d8da1b30: Pulling fs layer
d909eff28200: Pulling fs layer
c9b1b535fdd9: Waiting
cbb0d8da1b30: Waiting
568dff2a5e9e: Pulling fs layer
0aed2559ef8d: Pulling fs layer
d909eff28200: Waiting
568dff2a5e9e: Waiting
0aed2559ef8d: Waiting
c9b1b535fdd9: Verifying Checksum
c9b1b535fdd9: Download complete
c9b1b535fdd9: Pull complete
cbb0d8da1b30: Download complete
cbb0d8da1b30: Pull complete
d909eff28200: Verifying Checksum
d909eff28200: Pull complete
0aed2559ef8d: Verifying Checksum
0aed2559ef8d: Download complete
568dff2a5e9e: Download complete
568dff2a5e9e: Pull complete
0aed2559ef8d: Pull complete
Digest: sha256:1ff752199f17b70e5f4dc2ad7f3e7843c456eb7e1407ed158ed8c237dbf1476a
Status: Downloaded newer image for golang:1.13-alpine
 ---> e1fd9820be16
Step 2/9 : WORKDIR /src
 ---> Running in 3ee3659d459d
 ---> 4fa54d5f9962
Step 3/9 : COPY go.sum go.mod ./
 ---> 3de7c30cc08a
Step 4/9 : COPY *.go ./
 ---> 2f0712739068
Step 5/9 : RUN go build -o /out .
 ---> Running in 968f2f4e8eda
go: downloading github.com/replaygaming/eventsource v1.0.0
go: downloading google.golang.org/genproto v0.0.0-20170214170613-dee11a626cb8
go: downloading golang.org/x/net v0.0.0-20170218080159-6b27048ae5e6
go: downloading cloud.google.com/go v0.6.0
go: downloading github.com/replaygaming/consumer v0.0.0-20170207112044-33f730ad2bd4
go: downloading github.com/golang/protobuf v0.0.0-20170217234432-69b215d01a56
go: extracting github.com/replaygaming/eventsource v1.0.0
go: extracting github.com/replaygaming/consumer v0.0.0-20170207112044-33f730ad2bd4
go: downloading google.golang.org/api v0.0.0-20170214011559-bc20c61134e1
go: downloading golang.org/x/oauth2 v0.0.0-20170214231824-b9780ec78894
go: extracting golang.org/x/oauth2 v0.0.0-20170214231824-b9780ec78894
go: extracting github.com/golang/protobuf v0.0.0-20170217234432-69b215d01a56
go: extracting cloud.google.com/go v0.6.0
go: downloading google.golang.org/grpc v1.0.6-0.20170221215214-20633fa172ac
go: extracting golang.org/x/net v0.0.0-20170218080159-6b27048ae5e6
go: downloading github.com/googleapis/gax-go v0.0.0-20161107002406-da06d194a00e
go: extracting google.golang.org/grpc v1.0.6-0.20170221215214-20633fa172ac
go: extracting google.golang.org/genproto v0.0.0-20170214170613-dee11a626cb8
go: extracting github.com/googleapis/gax-go v0.0.0-20161107002406-da06d194a00e
go: extracting google.golang.org/api v0.0.0-20170214011559-bc20c61134e1
go: finding github.com/golang/protobuf v0.0.0-20170217234432-69b215d01a56
go: finding github.com/replaygaming/consumer v0.0.0-20170207112044-33f730ad2bd4
go: finding golang.org/x/net v0.0.0-20170218080159-6b27048ae5e6
go: finding cloud.google.com/go v0.6.0
go: finding github.com/replaygaming/eventsource v1.0.0
go: finding google.golang.org/genproto v0.0.0-20170214170613-dee11a626cb8
go: finding github.com/googleapis/gax-go v0.0.0-20161107002406-da06d194a00e
go: finding google.golang.org/api v0.0.0-20170214011559-bc20c61134e1
go: finding golang.org/x/oauth2 v0.0.0-20170214231824-b9780ec78894
go: finding google.golang.org/grpc v1.0.6-0.20170221215214-20633fa172ac
 ---> 7e2718d9135a
Step 6/9 : FROM alpine:3.9
FATA[1023] build failed: building [us.gcr.io/replay-gaming/go-eventsource]: build artifact: unable to stream build output: Get https://registry-1.docker.io/v2/library/alpine/manifests/3.9: net/http: TLS handshake timeout
```
Had to cut the middle because of github limitation

with skaffold version 1.3.1

**Comment by kvokka** [comment] 2020-02-21 22:06
By the way, it was resolved after upgrade to skaffold 1.4.0 (rebuild twice)

**Comment by kvokka** [comment] 2020-02-24 03:55
Occasionally got the same error with skaffold 1.4.0

**Comment by nkubala** [comment] 2020-02-29 02:13
hmm, have you tried using a remote cluster (e.g. not minikube)? I wonder if your minikube is having trouble reaching out to the outside world.

**Comment by dgageot** [comment] 2020-07-15 09:19
I'm going to close this issue because we have no way to reproduce right now.

**Closed by dgageot** 2020-07-15 09:19 UTC
Labels: area/build, kind/bug, priority/awaiting-more-evidence
