### ISSUE TITLE
Kpt deployer for kpt v1

### ISSUE THREAD

**Issue by irvifa** [GoogleContainerTools/skaffold#6791] opened 2021-11-02 05:43 UTC
### Expected behavior

Since kpt v1 is already beta is it possible that Skaffold support kpt v1 as a deployer.

### Actual behavior

```
$ skaffold dev
...
you are using kpt "v1.0.0-beta.7"
Please install kpt v0.38.1 <= version < v1.0.0-alpha.1
See kpt installation: https://googlecontainertools.github.io/kpt/installation/
```

### Information

- Skaffold version: v1.34.0
- Installed via: skaffold.dev

**Comment by tejal29** [comment] 2021-11-02 17:02
@irvifa, There are changes in kpt v1 to kpt v2 which are backward incompatible. Skaffold team and kpt team are working on a feature branch to consume kpt v2.

The ETA for the release is Early Jan. 

Closing this as duplicate of #5673

**Closed by tejal29** 2021-11-02 17:02 UTC
Labels: kind/feature-request, area/V2
