### ISSUE TITLE
Skaffold not using specified namespace

### ISSUE THREAD

**Issue by TheYkk** [GoogleContainerTools/skaffold#5338] opened 2021-02-03 10:52 UTC
### Expected behavior
Skaffold should deploy helm chart to specified namespace.

### Actual behavior
Skaffold gets namespace from my kubeconfig and its trying to deploy that namespace not my specified namespace.
I was using skaffold v1.17.2 and I upgraded v1.19.0 then skaffold is not worked.
I used `skaffold fix`
### Information

- Skaffold version: v1.19.0
- Operating system: ubuntu:20.04
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: project
build:
  artifacts:
    - image: myimage
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: project-dev
        chartPath: project
        artifactOverrides:
          image: myimage
        namespace: "mynamespace"
        wait: true
    flags:
      install:
        - --timeout=3m
        - --debug
      upgrade:
        - --timeout=3m
        - --install
        - --debug
```

### Steps to reproduce the behavior

1. skaffold fix
2. skaffold dev

**Comment by AManMustHaveACode** [comment] 2021-02-05 11:11
you cloud remove namespace from kubeconfig and try it again

**Comment by MarlonGamez** [comment] 2021-02-05 20:05
Thanks for opening this issue @TheYkk, It looks like skaffold is using your kubectl namespace over the namespace specified in the skaffold.yaml. I'll discuss this issue with the team and see what we want to do about this. In the meantime, can you try what @AManMustHaveACode suggested and see if that helps with your issue?

**Comment by TheYkk** [comment] 2021-02-05 20:09
Yes @AManMustHaveACode suggestion is worked. But skaffold should overwrite this

**Comment by briandealwis** [comment] 2021-05-30 01:44
I think this has the same cause as #5339.

**Comment by briandealwis** [comment] 2021-07-05 20:45
I can't reproduce this issue.  Closing: can re-open if it can be reproduced in the latest version.

**Closed by briandealwis** 2021-07-05 20:45 UTC
Labels: area/deploy, deploy/helm, good first issue, help wanted, kind/bug, priority/p2
