### ISSUE TITLE
File sync & Port forward didn't work

### ISSUE THREAD

**Issue by oo00spy00oo** [GoogleContainerTools/skaffold#4814] opened 2020-09-22 17:40 UTC
### Expected behavior
- Portforward working.
- Fie sync & hot reload feature work with MIcronaut and Jib.

### Actual behavior
- I am using Micronaut and Jib
- Feature port forward is not working for me.
- And when I made some change in my code all the file are sync already but the hot reload feature didn't work

### Information

- Skaffold version: v1.14.0
- Operating system: MacOSX 10.15.6
- Gradle: 6.6.1
- Jib: 2.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: <REDACTED>
build:
  artifacts:
    - image: <REDACTED>
      jib:
        type: gradle
        args:
          - -Psync
          - -Djib.from.image=adoptopenjdk:11-jre-openj9
      sync:
        auto: {}

deploy:
  kustomize: {}

portForward:
  - resourceType: deployment
    resourceName: <REDACTED>
    port: 8080
```

### Steps to reproduce the behavior
skaffold dev

**Comment by oo00spy00oo** [comment] 2020-09-23 11:34
UPDATE: With port forward, I missed the `--port-forward` flag. And only remain the issue with file sync feature.

**Comment by briandealwis** [comment] 2020-09-29 19:53
Hi @oo00spy00oo.  Auto-sync on Jib requires container-side support, such as through the use of Spring Boot Dev Tools or a web server that supports class reloading.  There's some detail in the docs at:

    https://skaffold.dev/docs/pipeline-stages/filesync/#auto-sync-mode

Could you include your pom.xml?

**Comment by tejal29** [comment] 2020-10-28 15:39
Removing needs-reproduction since we don't have enough data to reproduce. 
@oo00spy00oo Can you please share your pom.xml?

**Comment by briandealwis** [comment] 2020-10-29 03:49
Also the log output from running with `-v debug` would be helpful too.

**Comment by gsquared94** [comment] 2020-11-30 21:30
Closing due to insufficient repro steps. @oo00spy00oo if you can provide the `pom.xml` we can revisit this.

**Closed by gsquared94** 2020-11-30 21:30 UTC
Labels: area/sync, build/jib, kind/question
