### ISSUE TITLE
Provide a way of disabling image building during dev profile

### ISSUE THREAD

**Issue by amirsamary** [GoogleContainerTools/skaffold#5180] opened 2020-12-22 21:55 UTC
Hi! 

First of all: Great tool! I am evaluating it to use on an important project in my company and share it with our community of developers as a suggestion of tool for using our tech on Kubernetes.

### Expected behavior

Some technologies provide their own way of synching changes from the host machine into the container. For example, when using InterSystems IRIS and its VSCode plugin, one can save source code using VSCode and see it immediately applied to the running instance inside the cluster. Other features such as remote debugging are also available which make VSCode synch and debugging the most efficient way of developing with this backend.

I am using Angular as the frontend and Skaffold sync functionality is working great. 

The expected behavior is to be able to disable "watching for changes" for my backend image while leaving the normal behavior for my angular frontend.

Ideally, I should be able to have a patch under my **patches** section under my **dev** profile to set **sync.disabled=true** so that I could continue using skaffold run and build normally.

### Actual behavior

Skaffold will rebuild my backend image no matter what during the dev profile. This is very annoying since every time I am saving a file in VSCode a new build starts. 

### Information

- Skaffold version: v1.17.2
- Operating system: Mac
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta10
kind: Config

# Standard build used by both "dev" and "run" profiles bellow
build:
  insecureRegistries: 
    - local-registry

  local:
    tryImportMissing: true
    push: true
    useBuildkit: true
    concurrency: 2
  
  tagPolicy:
    envTemplate:
      template: "latest"

  artifacts:
    - image: cp_frontend
      context: services/cp/cp_frontend
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
        - '**/*'
      requires:
        - image: base_angularcli
          alias: BASE_ANGULAR_IMAGE

    - image: base_angularcli
      context: base-images/base_angularcli

    # Right now, skaffold will rebuild this image during dev profile every time we save a file using VSCode.
    # There is no way to disable this. I have filing an enhancement request at https://github.com/GoogleContainerTools/skaffold/issues/new
    # to see if we can have a flag we could use here. Idealy, we should be able to use a patch operator to add a sync.disable=true here.
    - image: cp_backend
      context: services/cp/cp_backend
      requires:
        - image: base_iris
          alias: BASE_IRIS_IMAGE

    - image: base_iris
      context: base-images/base_iris


# Definitions of the "dev" and "run" profiles
profiles:
  
  # DEV Profile
  # Used when developping. 
  # We will just be using the standard build above without changes
  - name: dev
    activation:
      - command: dev

    deploy:

      kubectl:
        manifests:
          - ./services/cp/k8s/cp_frontend_deployment.yaml  
          - ./services/cp/k8s/cp_frontend_ingress.yaml  

          - ./services/cp/k8s/cp_backend_configmap_dev.yaml
          - ./services/cp/k8s/cp_backend_deployment.yaml

  # RUN Profile
  # Used when deploying (production). 
  # We will be patching "build" in order to remove synchronization of files 
  # and use production images where appropiate.
  - name: run
    activation:
      - command: run
    deploy:
      kubectl:
        manifests:
          - ./services/cp/k8s/cp_frontend_deployment.yaml
          - ./services/cp/k8s/cp_frontend_ingress.yaml  

          - ./services/cp/k8s/cp_backend_configmap_run.yaml
          - ./services/cp/k8s/cp_backend_deployment.yaml

    patches:
      # cp_frontend patches
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: run.Dockerfile
    
      - op: remove
        path: /build/artifacts/0/sync
```

### Steps to reproduce the behavior

I can't share this repository. But the behavior is easily reproducible. It is actually, so far, unavoidable. I am seeking for a way to stop reproducing it. I mean: stop building an image when files change. :)

**Comment by gsquared94** [comment] 2020-12-22 23:55
> Skaffold will rebuild my backend image no matter what during the dev profile. This is very annoying since every time I am saving a file in VSCode a new build starts.

Are you saying that Skaffold is rebuilding the backend image when you're only making non-backend related code changes? Or is it detecting the right changes and rebuilding it but you'd like to turn that off, even during `skaffold dev`?

Ideally if you're only making scoped changes to the frontend app then Skaffold should not rebuild backend everytime it rebuilds frontend. If that's happening it could be a bug.

**Comment by amirsamary** [comment] 2020-12-23 04:02
No. Everything works great with the frontend. Synchronization is just perfect and we enjoy it pretty much. It does not trigger the rebuild of the backend.

I just wanted to explain that we are making good use of Skaffold and we enjoy it a lot. 

But there is this other piece of the application (the backend) where the synchronization feature is just not needed **during the dev profile**. When we are done changing code, we will certainly trigger a build and/or a run to get a new image built with the final source code. But during the dev process, the specific combination of VSCode and IRIS will take care of it. I believe there are other tools out there that will probably have the same we are having?

I wish I could contribute myself. But I don't know Go. I am starting to learn it so I can be more helpful and contribute and I will push my team to do so as well in the future as we keep diving in this journey. But right now all I can do is ask. 

I admire your work very much. Thank you for any help you can provide.

**Comment by gsquared94** [comment] 2020-12-23 05:15
Got it. Glad you're finding the tool useful. We currently don't have a way to selectively disable file change monitoring per artifact. You could try running multiple instances - `skaffold dev` against the `frontend` service and `skaffold dev --autoBuild=false --autoSync=false` against the `backend` service.

I'll close this issue as a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/4368

**Closed by gsquared94** 2020-12-23 05:15 UTC

**Comment by amirsamary** [comment] 2020-12-23 13:43
Is it at least in the roadmap? 

I will try the autoBuild=false flag. Seems to be what I need since I don’t need any building whatsoever while running on the dev profile. I can build it with the build profile first, then start the dev profile with autoBuild=false. 

But I would like to know if you think such a feature is ever coming to Skaffold?

Kind regards,
AS

**Comment by amirsamary** [comment] 2020-12-23 15:34
Interesting. I can not find this flag: --autoBuild=false 

Which version are you referring to?

I think that would be just perfect for me right now. I do hope though, that you guys consider adding a flag to the build.image API to prevent auto builds during dev.

Kind regards,
Amir Samary

**Comment by gsquared94** [comment] 2020-12-24 01:35
Oops! the flag is `--auto-build` and `--auto-sync`

**Comment by gsquared94** [comment] 2020-12-24 01:42
> But I would like to know if you think such a feature is ever coming to Skaffold?

We do intend to have this feature eventually.
