### ISSUE TITLE
Skaffold build fails via run/dev on M1 but works with build

### ISSUE THREAD

**Issue by BramMeerten** [GoogleContainerTools/skaffold#7584] opened 2022-06-24 09:49 UTC
### Problem
When trying to execute `skaffold run` (or `dev`) on Mac with M1 chip, I get the following error during build:
```bash
$ skaffold run -f skaffold-example.yaml
```
```
Generating tags...
 - my-app -> my-app:latest
Checking cache...
 - my-app: Not found. Building
Starting build...
Building [my-app]...
Target platforms: [linux/arm64]
build [my-app] failed: builder for artifact "my-app" doesn't support building for target platforms: "linux/arm64". Supported platforms are "linux/amd64"
```

However if I run `skaffold build` manually, everything works:
```bash
$ skaffold build -f skaffold-example.yaml
```
```
Generating tags...
 - my-app -> my-app:latest
Checking cache...
 - my-app: Not found. Building
Starting build...
Building [my-app]...
v1: Pulling from buildpacks/builder
Digest: sha256:8c1b577d79319fdf1e5948175a5dcd6afdc40108eee26aedd3434b9766c516a4
Status: Image is up to date for gcr.io/buildpacks/builder:v1
v1: Pulling from buildpacks/gcp/run
Digest: sha256:cadd899b2ffc67b43e5ed3b61386e23b1be90ca1b5ccc792ca4ed7b59f4ee226
Status: Image is up to date for gcr.io/buildpacks/gcp/run:v1
...
```

### Information

- Skaffold version: 1.38.0
- Operating system: MacOS ARM
- Installed via: Homebrew
- Contents of skaffold-example.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: example
build:
  local:
    push: false
  artifacts:
  - image: my-app
    context: ./
    sync:
      auto: false
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
      trustBuilder: true
      env:
      - GOOGLE_RUNTIME_VERSION=17
      - GOOGLE_CLEAR_SOURCE=true
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - deployment.yaml
```

The folder contains a very simple maven project.

**Comment by gsquared94** [comment] 2022-07-09 12:04
Are you trying to deploy to a kubernetes cluster containing `linux/arm64` nodes? This happens for `run` and not for `build` because in `run` Skaffold checks the target cluster nodes' platform, and chooses that for the build.

You can force skaffold to build for `linux/amd64` by running:
```
skaffold run -f skaffold-example.yaml --platform=linux/amd64
```

**Comment by gsquared94** [comment] 2022-10-06 00:50
We've now changed the behavior to `warn` and build with the builder supported platform anyways so it should not fail even when the platform isn't specified. Closing, as working as intended.

**Closed by gsquared94** 2022-10-06 00:50 UTC
Labels: kind/bug, priority/p2, area/dev, area/arm64, area/cross-platform
