### ISSUE TITLE
How to deploy render result by `skaffold render`

### ISSUE THREAD

**Issue by StarpTech** [GoogleContainerTools/skaffold#4861] opened 2020-10-06 10:14 UTC
### Expected behavior

I want to practice GitOps with skaffold.
`skaffold deploy` should provide an argument to deploy the output of `skaffold render`

For example:

```sh
skaffold build --file-output=build.out
skaffold render --build-artifacts=build.out
skaffold deploy --build-artifacts=build.out --render-artifacts=/render-result
```

### Actual behavior

`skaffold deploy` only allows deploying a build artifact. The rendering process is triggered a second time and I have no chance to manipulate/validate the manifests before they are deployed.

```sh
skaffold build --file-output=build.out
skaffold deploy --build-artifacts=build.out
```

### Information

- Skaffold version: v1.15.0
- Operating system: Windows

**Comment by StarpTech** [comment] 2020-10-06 10:46
Do I understand correctly that I need to do this:

```sh
skaffold build --file-output=build.out
skaffold render --build-artifacts=build.out | validate | manipulate > ./render-result/release.yaml
# render-result profile points to manifests ./render-result/release.yaml
skaffold deploy -p render-result --build-artifacts=build.out --skip-render
```

**Comment by briandealwis** [comment] 2020-10-07 16:30
I thought `render` was considered a terminal operation and that you'd use `kubectl apply -f render-result/release.yaml`. Thoughts @GoogleContainerTools/skaffold-team ?

**Comment by briandealwis** [comment] 2020-10-07 17:20
We had some discussion about this, and we think this is similar to #4856.

Duplicate of #4856

**Closed by briandealwis** 2020-10-07 17:20 UTC
Labels: area/deploy, area/render, kind/question
