### ISSUE TITLE
default repo does not behave as expected

### ISSUE THREAD

**Issue by r2d4** [GoogleContainerTools/skaffold#1242] opened 2018-11-06 19:35 UTC
**default repo:** gcr.io/default
**skaffold yaml:** gcr.io/explicit/test

**expected:** gcr.io/default/test
**actual:** gcr.io/default/gcr.io/explicit/test

**Comment by dlorenc** [comment] 2018-11-06 19:48
cc @nkubala

I thought this was actually how default repo was supposed to work for gcr. (It's basically what ko does as well).

**Comment by nkubala** [comment] 2018-11-06 19:59
yeah this is expected behavior. if the provided image name has the default-repo as a prefix, e.g. 

**default repo**: `gcr.io/default`
**skaffold yaml**: `gcr.io/default/test`
**result**: `gcr.io/default/test`

then nothing will happen, but otherwise skaffold will simply concatenate the default repo onto the provided image name. this is how we can solve running the examples without changing any config.

**default repo**: `gcr.io/my-repo`
**skaffold yaml**: `gcr.io/k8s-skaffold/example`
**result**: `gcr.io/my-repo/gcr.io/k8s-skaffold/example` <- this will be valid for the user, and the example will run successfully

**Comment by r2d4** [comment] 2018-11-06 20:05
That is only valid on GCR, most registries don't accept nested image names. Why not just take the path.Base of it?

**Comment by nkubala** [comment] 2018-11-06 20:10
For registries that aren't GCR, we escape the base image name to make it valid, e.g.

**default repo**: `aws_account_id.dkr.ecr.region.amazonaws.com`
**skaffold yaml**: `gcr.io/k8s-skaffold/skaffold-example`
**result**: `aws_account_id.dkr.ecr.region.amazonaws.com/gcr_io_k8s-skaffold_skaffold-example`

If we took the path.Base, we could potentially end up with collisions.

**Comment by r2d4** [comment] 2018-11-06 23:33
skaffold tags with git metadata by default so there shouldn't be any collisions

in fact, you actually want collisions sometimes. user intent is to have an identifier for the image, not to nest registry/project.

The analogy is a fork of a repository on github. 
It's not `github.com/r2d4/github.com/GoogleContainerTools/skaffold`, its `github.com/r2d4/skaffold`

**Comment by dlorenc** [comment] 2018-11-07 00:03
Would the following collide?

**Two images in the skaffold yaml:**
gcr.io/app1/frontend
gcr.io/app2/frontend

**default repo:**
gcr.io/project

Can you elaborate on what you mean about user intent and identifier? I personally like the nesting because it shows the full context of where the image came from originally.

**Comment by balopat** [comment] 2018-11-13 23:17
This is how the feature was designed, so I'm going to go ahead and close this.

**Closed by balopat** 2018-11-13 23:17 UTC
Labels: area/config, bug
