### ISSUE TITLE
"error checking for color support" seems to fail build

### ISSUE THREAD

**Issue by iamnoah** [GoogleContainerTools/skaffold#7525] opened 2022-06-08 18:16 UTC
### Expected behavior

When run in [Github Actions](https://github.com/iamnoah/skaffold-tput-colors-bug/actions/runs/2463260647/workflow), `skaffold build` does not fail with a valid configuration, or fails with a clear error.

### Actual behavior

In the GitHub Actions runner *only* `skaffold build` fails with no clear cause. Turning on debug logging shows an error from a `tput colors` exec.

### Information

- Skaffold version: 1.38.0
- Operating system: ubuntu-latest
- Installed via: skaffold.dev (see workflow)
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: demo
build:
  artifacts:
    - image: ghcr.io/iamnoah/skaffold-tput-colors-bug/baz
      ko:
        main: ./foo
      hooks:
        before:
          - command: [go, mod, vendor]
          - command: [sleep, "3"]
    - image: ghcr.io/iamnoah/skaffold-tput-colors-bug/foo
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: [go, mod, vendor]
          - command: [sleep, "3"]
    - image: ghcr.io/iamnoah/skaffold-tput-colors-bug/bar
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command: [go, mod, vendor]
          - command: [sleep, "3"]
```

### Steps to reproduce the behavior

[Repo](https://github.com/iamnoah/skaffold-tput-colors-bug/). I've struggled with this minimal test case. Sometimes it will fail and sometimes pass. Seemingly arbitrary changes in the private repo this originated from will get to a pass, but I have not found a consistent workaround.

**All of these failures only occur in the Github Action runners. The same build commands succeed when I run them locally**

See the run [here](https://github.com/iamnoah/skaffold-tput-colors-bug/runs/6798763578?check_suite_focus=true). Only error I see (other than spurious gcloud output, which appears with success or failure) is:

```shell
time="2022-06-08T17:28:42Z" level=debug msg="Running command: [tput colors]" subtask=-1 task=DevLoop
[457](https://github.com/iamnoah/skaffold-tput-colors-bug/runs/6798763578?check_suite_focus=true#step:5:458)
time="2022-06-08T17:28:42Z" level=debug msg="error checking for color support: checking terminal colors: running [tput colors]\n - stdout: \"\"\n - stderr: \"tput: No value for $TERM and no -T specified\\n\"\n - cause: exit status 2" subtask=-1 task=DevLoop
[458](https://github.com/iamnoah/skaffold-tput-colors-bug/runs/6798763578?check_suite_focus=true#step:5:459)
{"builds":null}
[459](https://github.com/iamnoah/skaffold-tput-colors-bug/runs/6798763578?check_suite_focus=true#step:5:460)
exit status 1
```

The `go mod vendor` pre-hook seems to be crucial, so I suspect some kind of error there is being suppressed, but the only consistent error I see when the build fails is this tput error. Without `-vdebug` there was no error output.

**Comment by shipperizer** [comment] 2022-11-29 11:35
having the very same issue, just with skaffold `v2.0.2`

log example below
```
time="2022-11-29T11:27:50Z" level=debug msg="Running command: [docker build . --file /home/runner/work/***-experiments-api/***-experiments-api/Dockerfile -t discovery-***-docker-releases.jfrog.io/***-api-kafka:v1.29.0-34-g28827c4_linux_amd64 --build-arg app_name=kafka --platform linux/amd64]" subtask=***-api-kafka task=Build
time="2022-11-29T11:27:50Z" level=debug msg="Running command: [tput colors]" subtask=-1 task=DevLoop
time="2022-11-29T11:27:50Z" level=debug msg="error checking for color support: checking terminal colors: running [tput colors]\n - stdout: \"\"\n - stderr: \"tput: No value for $TERM and no -T specified\\n\"\n - cause: exit status 2" subtask=-1 task=DevLoop
exit status 1. Docker build ran into internal error. Please retry.
If this keeps happening, please open an issue..
null
```

**Comment by aizam6066** [comment] 2023-01-06 23:26
Is there an update on this issue? Having the exact same problem. Thanks!

**Comment by ericzzzzzzz** [comment] 2023-01-30 21:29
Hi, the ``tput`` issue from debug log doesn't cause skaffold to fail, it's just an informational log. However, it occurs along with the real issue if $TERM is empty(usually non-interactive terminals),  So @shipperizer @iamnoah may have different  issues. I'm happy to help you to fix any issues you encountered, but it would require more information, such as os, skaffold version, skaffold config , debug log and if you can provide an reproducible project that would be great.

**Comment by shipperizer** [comment] 2023-06-05 21:24
@ericzzzzzzz apologies, lost the ball on this

Turned out that we had an error while building for one of the platforms that was "hidden", simply disabling that architecture made the whole build work

so even though the issue for skaffold stays we managed to achieve what we needed.

**Comment by cristifalcas** [comment] 2024-01-25 15:52
we are hitting this issue as well, in buildkite with skaffold 2.8

```
time="2024-01-25T15:49:50Z" level=debug msg="Running command: [bazel build --noannounce_rc @//apps/sre_tools/switchboard/api:api_docker.tar --color=no]" subtask=switchboard-api-0xC0DEA5CF task=Build
--
  | time="2024-01-25T15:49:50Z" level=warning msg="failed to list images: Get \"http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json?filter=update-configmap-0xC0DEA5CF\": context canceled" subtask=update-configmap-0xC0DEA5CF task=Build
  | time="2024-01-25T15:49:50Z" level=debug msg="Running command: [bazel build --noannounce_rc @//lib/kubernetes/configs/configmap:update_configmap_docker.tar --color=no]" subtask=update-configmap-0xC0DEA5CF task=Build
  | time="2024-01-25T15:49:50Z" level=debug msg="Running command: [tput colors]" subtask=-1 task=DevLoop
  | time="2024-01-25T15:49:50Z" level=debug msg="error checking for color support: checking terminal colors: running [tput colors]\n - stdout: \"\"\n - stderr: \"tput: No value for $TERM and no -T specified\\n\"\n - cause: exit status 2" subtask=-1 task=DevLoop
  | build [switchboard-gui-0xC0DEA5CF] failed: running command: exit status 1
  | time="2024-01-25T15:49:50Z" level=debug msg="exporting metrics disabled" subtask=-1 task=DevLoop
```

**Comment by cristifalcas** [comment] 2024-01-25 15:56
oh, it works when I connect to the agent and start the same command
But the complain from skaffold doesn't sound critical, maybe it shouldn't fail hard because of that

**Comment by ipv1337** [comment] 2024-02-08 07:24
I've been battling this issue also running this on Cloud Build but not local.  This is with skaffold 2.10.0.
```
Step #1 - "skaffold_test": 2024-02-08 07:11:57 Running custom test command: "go test . -v" with timeout 120 s
Step #1 - "skaffold_test": time="2024-02-08T07:11:57Z" level=debug msg="Running command: [sh -c go test . -v]" subtask=-1 task=Test
Step #1 - "skaffold_test": 2024-02-08 07:12:12 === RUN   TestMinIntBasic
Step #1 - "skaffold_test": Running Basic test.
Step #1 - "skaffold_test": --- PASS: TestMinIntBasic (0.00s)
Step #1 - "skaffold_test": === RUN   TestMinIntTableDriven
Step #1 - "skaffold_test": Running Table driven test.
Step #1 - "skaffold_test": === RUN   TestMinIntTableDriven/TestMinInt():_0,0
Step #1 - "skaffold_test": time="2024-02-08T07:12:12Z" level=debug msg="Running command: [tput colors]" subtask=-1 task=DevLoop
Step #1 - "skaffold_test": time="2024-02-08T07:12:12Z" level=debug msg="error checking for color support: checking terminal colors: running [tput colors]\n - stdout: \"\"\n - stderr: \"tput: No value for $TERM and no -T specified\\n\"\n - cause: exit status 2" subtask=-1 task=DevLoop
Step #1 - "skaffold_test": error running cmd: invalid write result
Step #1 - "skaffold_test": time="2024-02-08T07:12:12Z" level=debug msg="exporting metrics disabled" subtask=-1 task=DevLoop
Finished Step #1 - "skaffold_test"
ERROR
ERROR: build step 1 "gcr.io/cloud-builders/docker" failed: step exited with non-zero status: 1
```

**Comment by ericzzzzzzz** [comment] 2024-02-08 15:05
Hi @ipv1337 , this issue should have been closed as explained here https://github.com/GoogleContainerTools/skaffold/issues/7525#issuecomment-1409369502

**Closed by ericzzzzzzz** 2024-02-08 15:05 UTC
Labels: help wanted, kind/feature-request, priority/p3, bugbash/q4-2022

**Comment by ipv1337** [comment] 2024-02-09 06:17
I did manage to find a workaround even if it's not pretty.  For anyone else that stumbles into this here's what I applied as a workaround while still keeping the test results functional:
```
...
test:
  - image: examples/hellotest
    context: ./src
    custom:
      - command: 'go test . 2>&1 >test_output.txt' # Workaround
        timeoutSeconds: 60
        dependencies:
          paths:
          -  "./*_test.go"
          -  "./test.sh"
...
```
