### ISSUE TITLE
Skaffold dev does not run Go tests correctly

### ISSUE THREAD

**Issue by F21** [GoogleContainerTools/skaffold#337] opened 2018-04-05 06:51 UTC
I want to use `skaffold dev` to implement a build run loop that runs my tests while developing.

A sample project demonstrating the problem is available here: https://github.com/F21/skaffold

### Expected behavior
Skaffold should run the tests (executed in the `CMD` stanza of the dockerfile) correctly.

### Actual behavior
Skaffold produces this error: 
```
[skaffold-5fdbb4dc79-fzkrj app] can't load package: package github.com/F21/skaffold: found packages main (generator\generate.go) and skaffold (something.go) in /go/src/github.com/F21/skaffold
```

### Information
In the sample project the tests run correctly in these scenarios:
- Running `go test`.
- Building the docker image and then running it using `docker run skaffold`.
- Building the docker image and using `deployment.yaml` to deploy it to a kubernetes cluster ( I tried minikube).

If I use skaffold with minikube, I get this error:
```
[skaffold-5fdbb4dc79-fzkrj app] can't load package: package github.com/F21/skaffold: found packages main (generator\generate.go) and skaffold (something.go) in /go/src/github.com/F21/skaffold
```
The strange thing is that my packages are in different directories, so this is not a problem.

In addition, this only happens when using `skaffold dev`. All the other methods demonstrate that the project builds correctly and the tests run correctly.
```
Skaffold version: version master 7349a0f3bc97926c5a894bb1e0af7c63e254a373
Operating system: Windows 10 64-bit with Minikube 0.25.2 and latest version of docker edge. Virtualization is Hyper-V
```

Content of skaffold.yaml:
```
apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: skaffold
    workspace: .
  local: {}
deploy:
  kubectl:
    manifests:
```

### Steps to reproduce the behavior

  1. Clone https://github.com/F21/skaffold
  2. `cd` into the repository and run `skaffold dev`.

**Comment by dgageot** [comment] 2018-04-05 15:29
Hi @F21, thanks for the report! I tried to reproduce and failed. (I'm using Docker for Desktop though)
Skaffold seems to do its job

**Comment by F21** [comment] 2018-04-05 22:17
@dgageot Are you using Docker for Windows (edge)?

**Comment by F21** [comment] 2018-04-09 23:49
Still seeing the same issue with Skaffold master (0f6c48adfbac8a1a3353288372350b2247dec3f3).

Docker was upgraded to latest RC:
```
Version 18.04.0-ce-rc2-win61 (17070)
Channel: edge
f3c9ab6
```

Minikube is still 0.25.2 running on Hyper-V

**Comment by dgageot** [comment] 2018-06-05 13:40
@F21 Can you check that everything is working ok with master? I see the tests passing.

**Comment by dgageot** [comment] 2018-09-07 12:10
Sorry @F21 I'm going to close this one because we've never been able to reproduce the issue. Please feel free to reopen with another way to reproduce.

**Closed by dgageot** 2018-09-07 12:10 UTC
Labels: area/build, bug, cmd/dev, priority/p2, question
