### ISSUE TITLE
exclude subdirectories from being watched

### ISSUE THREAD

**Issue by ekimia** [GoogleContainerTools/skaffold#825] opened 2018-07-17 00:41 UTC
### Expected behavior
I can specify (somehow) certain subfolders to exclude from the watch list.
### Actual behavior
I can't. Or can't find out how.

### Information
Idea is to exclude a directory from being watched, as that directory will be mounted for super super fast local development.

**Comment by ekimia** [comment] 2018-07-17 06:04
After forking I found this:
`https://github.com/GoogleContainerTools/skaffold/blob/e6f37af6eac07da071070c432760d4bdce47d442/pkg/skaffold/watch/files.go#L31`

Recommend a yaml sequence specifying the folders to exclude. Would do it myself but unfortunately too tied up at the moment.

**Comment by taylorKonigsmark** [comment] 2018-07-17 21:22
This could be something that i'd be interested working on.

Would the appropriate configuration be something along the lines of:

```
build:
  watchPolicy:
    ignoredDirectories:
      - /path/to/ignored/dir
    ignoredFiles:
      - /path/to/ignored/file.txt
```

**Comment by ekimia** [comment] 2018-07-18 05:43
@r2d4 totally. Our use case us using Django's hot reloading. In this scenario, a watchPolicy where you can explicitly list directories and files to watch would be sweet. Totally think having different policy types would be the best approach.

Example:
- I modify some application code. Skaffold doesn't rebuild.
- I modify requirements.txt, which will cause Skaffold to rebuild.

**Comment by taylorKonigsmark** [comment] 2018-07-18 12:56
Sure,

so something along the lines of:

```
ignore:
    - pattern: /relative/glob/to/ignore/*.txt
    - pattern: /another/relative/to/specific/file.txt
```

**Comment by taylorKonigsmark** [comment] 2018-07-18 19:44
would like to confirm with @r2d4 since he is one of the maintainers

**Comment by ekimia** [comment] 2018-07-18 20:35
@taylorKonigsmark one important thing to add here is exclusion if glob doesn't account for this already (not super familiar with it). Back to my django example, i'd want something like this which is relevant for other setups as well:

```
ignore:
    - pattern: *.py
    - pattern: !/base/settings.py
```

Something that states "ignore all the python files except settings.py"

Not familar with glob, but the ! came from the syntax in `.gitignore` to exclude a directory with the exception of specific files in that directory.

**Comment by tejal29** [comment] 2019-04-09 01:27
Moving this to Upcoming as  don't think anyone is working on this. This would be a small change but a large impact. We can have a design-proposal for it.

**Comment by ekimia** [comment] 2019-04-10 17:26
sweet!

**Comment by tejal29** [comment] 2019-04-10 18:14
@ekimia, Design proposals welcomed! :+1:  Feel free to submit one as per https://github.com/GoogleContainerTools/skaffold/tree/master/docs/design_proposals

**Comment by dgageot** [comment] 2019-07-11 16:27
Duplicate of https://github.com/GoogleContainerTools/skaffold/issues/20

**Closed by dgageot** 2019-07-11 16:27 UTC
Labels: area/watch, cmd/dev, kind/feature-request, needs-design-proposal
