### ISSUE TITLE
skaffold  helm flags : unable to connect to Kubernetes: getting client config for Kubernetes client:..

### ISSUE THREAD

**Issue by uchenxy** [GoogleContainerTools/skaffold#6808] opened 2021-11-06 04:07 UTC
![image](https://user-images.githubusercontent.com/40748300/140597391-6582560d-9907-437f-964e-817a9b3342c5.png)

![image](https://user-images.githubusercontent.com/40748300/140597405-3921073c-712c-4942-9136-3e3ac0b70096.png)

**Comment by briandealwis** [comment] 2021-11-11 03:57
Duplicate of #6806

**Closed by briandealwis** 2021-11-11 03:57 UTC
