### ISSUE TITLE
profile deploy.kubeContext not used in run

### ISSUE THREAD

**Issue by dthomastx** [GoogleContainerTools/skaffold#6434] opened 2021-08-13 15:03 UTC
### Expected behavior
context provided in deploy.kubeContext should be observed

### Actual behavior
kubectl current-context is used

### Information

- Skaffold version: 1.29.0
- Operating system: Win 10
- Installed via: Chocolatey
- Contents of skaffold.yaml:

```yaml
- name: qa-kaniko
  build:
    tagPolicy: *tagPolicy
    artifacts:
    - image: *image
      kaniko:
    cluster:
  deploy:
    kubeContext: qa
    kustomize: 
      paths:
      - ./kustomize/overlays/qa
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

`time="2021-08-13T09:54:59-05:00" level=info msg="Using kubectl context: admin"`

```
CURRENT   NAME      CLUSTER   AUTHINFO        NAMESPACE
*         admin     dev   dev-admin
           qa          qa     qa-admin
```

switching kubectl current config switches config used

using --kube-context=qa works correctly

**Comment by gsquared94** [comment] 2021-08-16 04:47
this should be fixed in https://github.com/GoogleContainerTools/skaffold/releases/tag/v1.30.0
Can you please try that version?

**Comment by dthomastx** [comment] 2021-08-16 16:14
@gsquared94 thanks, I just saw 1.30 was available in chocolatey so I upgraded, will try again later today

**Comment by dthomastx** [comment] 2021-08-16 16:33
@gsquared94 same result, current-context is used

in skaffold.yaml:
`deploy.kubeContext = qa`

in the first stage (before a 'blue' header);

`time="2021-08-16T11:25:38-05:00" level=info msg="Using kubectl context: dev"`

**current-context = dev**

and in the following stages the kubeContext reports blank:

**Checking for kaniko secret:**

`time="2021-08-16T11:26:35-05:00" level=debug msg="getting client config for kubeContext: ``"`

**Creating docker config secret:**

`time="2021-08-16T11:26:35-05:00" level=debug msg="getting client config for kubeContext: ``"`

**Building:**

`time="2021-08-16T11:26:35-05:00" level=debug msg="getting client config for kubeContext: ``"`

**Comment by briandealwis** [comment] 2021-10-01 20:57
We seem to have a race condition of some kind as it sometimes works for me.

**Comment by gsquared94** [comment] 2021-12-28 17:59
the `deploy.kubeContext` property only sets kubernetes context for the deploy phase. It cannot override the kubernetes context selected for the kaniko builder. We are having some discussions about making `kubeContext` a top-level property in the `skaffold.yaml` config but until that happens this is working as intended. You should be able to specify the cluster for the builder using the flag `--kube-context=qa`

**Closed by gsquared94** 2021-12-28 17:59 UTC
Labels: kind/bug, deploy/kubectl, priority/p2, area/dev
