### ISSUE TITLE
Add possibility to run custom command after deploy to k8s

### ISSUE THREAD

**Issue by absent1706** [GoogleContainerTools/skaffold#2618] opened 2019-08-08 07:36 UTC
It will be very useful to have a possibility to execute some script after deploying to cluster.
It cah be achieved by adding a section to `skaffold.yaml` like:

```
deploy:
  # ....
 after_deploy:
     my-custom-command arg1 arg2
```
For example, I would like to run [kubefwd](https://kubefwd.com/) command after deploy, so, my services will always be available on fixed URLs like `http://<service_name>` even after re-deploy (I know skaffold has port-forwarding feature, but it's really buggy now and doesn't work on my machine).
So I will have
```
deploy:
  # ....
 after_deploy:
     sudo kubefwd svc
```

Thanks in advance!

**Comment by priyawadhwa** [comment] 2019-08-08 19:20
Hey @absent1706 I've been working on improving port-forwarding in skaffold; would you mind opening up another issue about the port forward bugs you've been seeing so I can take a look? Also, what version of skaffold are you running?

In regards to this issue, this is a dupe of #1441, so you can find updates on this topic there! I'm going to go ahead and close this issue as a dupe.

**Closed by priyawadhwa** 2019-08-08 19:20 UTC
