### ISSUE TITLE
Skaffold wrongly treats Helm's stderr output as YAML

### ISSUE THREAD

**Issue by dqsully** [GoogleContainerTools/skaffold#7796] opened 2022-08-23 14:23 UTC
### Expected behavior
Skaffold parses only stdout from the `helm template ...` command, ignoring any warnings.

### Actual behavior
Skaffold treats both stdout and stderr as YAML, causing parsing errors when Helm outputs warnings to stderr.

### Information

- Skaffold version: `v2.0.0-beta1`
- Operating system: Ubuntu 22.04
- Installed via: `curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64`
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta21
kind: Config

build:
  artifacts: []

deploy:
  helm:
    releases:
    - name: example
      remoteChart: my-org/my-chart
      upgradeOnChange: true
      valuesFiles:
        - values.yaml
```

### Steps to reproduce the behavior

1. Run `chmod 664 ~/.kube/config`
2. `skaffold run` on any Skaffold project deploying with Helm

```
Starting test...
INFO[0000] Test completed in 14.122µs                    subtask=-1 task=Test
INFO[0000] Starting render...                            subtask=-1 task=DevLoop
INFO[0000] rendering using helm                          subtask=0 task=Render
DEBU[0000] Executing template &{envTemplate 0xc001583440 0xc000ea01e0  } with environment (hidden)
DEBU[0001] Executing template &{envTemplate 0xc000fecea0 0xc0012c25f0  } with environment (hidden)
DEBU[0001] Executing template &{envTemplate 0xc000fedc20 0xc0012c2640  } with environment (hidden)
DEBU[0001] Executing template &{envTemplate 0xc000f20a20 0xc0012c2690  } with environment (hidden)
DEBU[0001] Running command: [helm template example my-org/my-chart --post-renderer /usr/bin/skaffold -f values.yaml]  subtask=0 task=Render
DEBU[0001] Running command: [tput colors]                subtask=-1 task=DevLoop
DEBU[0001] Command output: [256
]                        subtask=-1 task=DevLoop
setting labels in manifests: reading Kubernetes YAML: yaml: mapping values are not allowed in this context
```

After digging around, I was able to determine that the issue is caused by this line: https://github.com/GoogleContainerTools/skaffold/blob/f6aafdf9eaf158166a668b91fb73143075996085/pkg/skaffold/helm/bin.go#L127 When the output of Helm is being parsed as YAML, it should ignore stderr, or maybe pipe it to Skaffold's stderr directly.

Also, the latest version of Skaffold available for download is `2.0.0-beta1`, is that intended? This issue just started happening for us this week even though that version of Skaffold was released on GitHub over 2 weeks ago.

**Comment by tejal29** [comment] 2022-08-23 20:57
Is this duplicate of #7793 ?

**Comment by dqsully** [comment] 2022-08-23 22:20
@tejal29 No, this is a separate bug, although we have run into that one as well.

**Comment by aaron-prindle** [comment] 2022-08-30 19:39
@dqsully, the `2.0.0-beta1` was accidentally pushed to the `skaffold:latest` tag but this has since been fixed (should now be the latest stable release `v1.39.2`

**Comment by charlesg99** [comment] 2023-05-07 22:37
I'm getting this exact error since [v2.4.0](https://github.com/GoogleContainerTools/skaffold/releases/tag/v2.4.0), works correctly using [v2.0.10](https://github.com/GoogleContainerTools/skaffold/releases/tag/v2.0.10)

**Comment by renzodavid9** [comment] 2023-05-08 13:53
It looks like [#8754](https://github.com/GoogleContainerTools/skaffold/issues/8754) is related with this

**Closed** 2023-05-08 17:19 UTC
