### ISSUE TITLE
Add final pod status to STATUSCHECK_POD_INITIALIZING output

### ISSUE THREAD

**Issue by tstromberg** [GoogleContainerTools/skaffold#4668] opened 2020-08-14 17:55 UTC
As noted by @russwolf:

```
Status check started
Resource pod/nodejs-guestbook-backend-76c5c46f9c-bbdcn status failed with
Resource pod/nodejs-guestbook-frontend-f748c9d67-cjxs9 status updated to In Progress
Resource pod/nodejs-guestbook-mongodb-6f8b7fd56d-9gskl status completed successfully
Resource deployment/nodejs-guestbook-frontend status updated to In Progress
Resource deployment/nodejs-guestbook-frontend status updated to In Progress
Resource pod/nodejs-guestbook-mongodb-6f8b7fd56d-9gskl status updated to In Progress
Resource deployment/nodejs-guestbook-mongodb status updated to In Progress
Resource deployment/nodejs-guestbook-mongodb status updated to In Progress
Resource deployment/nodejs-guestbook-backend status failed with could not stabilize within 2m0s: context deadline exceeded
Resource deployment/nodejs-guestbook-frontend status failed with could not stabilize within 2m0s: context deadline exceeded
Resource deployment/nodejs-guestbook-mongodb status failed with could not stabilize within 2m0s: context deadline exceeded
Status check failed
 
DevInit Iteration 0 failed with error code STATUSCHECK_POD_INITIALIZING
exiting dev mode because first deploy failed: 3/3 deployment(s) failed
```

This error message does not provide enough detail for post-mortem analysis. At a minimum, it needs to show the resulting pod states. Here is my naive suggestion. Instead of:

```
Resource deployment/nodejs-guestbook-backend status failed with could not stabilize within 2m0s: context deadline exceeded
Resource deployment/nodejs-guestbook-frontend status failed with could not stabilize within 2m0s: context deadline exceeded
Resource deployment/nodejs-guestbook-mongodb status failed with could not stabilize within 2m0s: context deadline exceeded
Status check failed
 ```

Show something like the output of `kubectl get` and `kubectl descr`

```
3 of 3 deployments to <kubectl context name> did not complete within the 2m0s timeout: deployment/nodejs-guestbook-backend, deployment/nodejs-guestbook-frontend, deployment/nodejs-guestbook-mongodb

Final state of resources:

deployment/nodejs-guestbook-mongodb: 1/1 ready (18s)
pod/xxx: Running  (12s)
pod/xy: Failed (Evicted): The node was low on resource: memory. 
pod/xy: <.Status> (<.Reason>): <.Message>
```

FWIW, I'd rather get something in ASAP and worry about the exact UX later. This information is critical for users.

**Comment by tejal29** [comment] 2020-08-17 21:08
This might be dupe of #4658 
I will look into why events are are fetched when pods are initializing.

**Closed** 2020-08-28 19:13 UTC
Labels: area/status-check, ide, kind/feature-request, priority/p0
