### ISSUE TITLE
Existing explicit progressdeadline in deployment spec of 600 seconds ignored and replaced with 120 seconds/2minutes

### ISSUE THREAD

**Issue by frejsoya** [GoogleContainerTools/skaffold#4763] opened 2020-09-08 09:19 UTC
Title says it all ;) 

During an upgrade of skaffold to 1.14.0 we hit an issue with deployment status check timeout consistently being 2 minutes. Even when the deployment spec progressdeadline was *explicitly* set to 600. Trying to enforce the same value in skaffold.yaml, it was still 2 minutes

The issue is that whenever the deployment deadline is 600 seconds, no matter how explicit. Skaffold chooses to replace it with 2 minutes.

I find this behavior pretty strange. If the default behavior in k8s is 10 minutes, follow that. Skaffold should not have its own default, and it should definitely not magically replace explicitly values in deployment specs.

:)

**Comment by briandealwis** [comment] 2020-09-08 14:39
Hi @frejsoya — the status-check time is governed by the [`skaffold.yaml`'s `statusCheckDeadlineSeconds:` value](https://skaffold.dev/docs/references/yaml/#deploy-statusCheckDeadlineSeconds).  We're planning to change it to reflect the Kubernetes defaults (#4669).

Duplicate of #4669

**Closed by briandealwis** 2020-09-08 14:39 UTC
Labels: area/status-check, kind/feature-request, triage/duplicate

**Comment by frejsoya** [comment] 2020-09-08 14:43
Yeah i am aware. I even tried 600 seconds there, to no effect as it is magicallly replace by 2 minutes. I ended up putting in 599 :)
