### ISSUE TITLE
[Docs fixit] [HaTS feedback] Make yaml configuration schema collapsible

### ISSUE THREAD

**Issue by gsquared94** [GoogleContainerTools/skaffold#6483] opened 2021-08-20 18:09 UTC
Make the yaml config schema collapsible at the various keys
https://skaffold.dev/docs/references/yaml/

**Comment by aaron-prindle** [comment] 2022-11-26 20:17
Dupe of #4502

**Closed by aaron-prindle** 2022-11-26 20:17 UTC
Labels: help wanted, kind/documentation, kind/todo, area/docs, docs-fixit, planning/H1-2022
