### ISSUE TITLE
Port forwarding not work when pods recreated

### ISSUE THREAD

**Issue by cheung-chifung** [GoogleContainerTools/skaffold#2408] opened 2019-07-04 15:28 UTC
I'm making a simple golang app and trying to use skaffold for local development with`skaffold dev --port-forward`.

However, it only works for the first time, then fails to open ports again when files changed and pods recreated. I even tried v0.33.0 and the latest version `2f2a6f4`, neither works.

I checked issue  #1594 #1815 and tried v0.29.0, and it works as I expected.

I notice that when I use v0.33.0, every time I changed files, skaffold will start a new pod then exit (delete?) the old one, but when I use v0.29.0, only the new one starts, and there is no exit log. So I guess is the old one blocks port-forward somehow since v0.29.0

### Expected behavior

Recreate port forwarding correctly just like v0.29.0 did.

### Actual behavior

Only successful for the first time.

### Information

- Skaffold version: v0.33.0
- Operating system: MacOSX 10.14.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta10
kind: Config
build:
  artifacts:
    - image: api
      context: ./api/
deploy:
  kubectl:
    manifests:
      - ./manifests/*
profiles:
  - name: minikube
    activation:
      - kubeContext: minikube
        command: dev
```

### Steps to reproduce the behavior

1. use minikube and v0.33.0, checkout a minimal app with service and deployment only.
2. run `skaffold dev --port-forward`, can see port-forward works for the first time.
3. change the source codes, trigger the pod recreate.
4. from the logs, you can see skaffold starts a new pod with a different name with the old one, which will be deleted after the new one started listening on the port.
5. stop skaffold and rerun the same command `skaffold dev --port-forward`, it works again.

**Comment by cmoad** [comment] 2019-07-08 16:52
I'm seeing this exact issue after upgrading from 0.32.0 to 0.33.0.

Skaffold command:
```
skaffold dev --cleanup=false --no-prune --port-forward --toot
```

**Comment by priyawadhwa** [comment] 2019-07-08 18:26
Hey @cmoad -- so I merged #2215 recently which changed the functionality of port-forward for `skaffold dev`. Skaffold should now only automatically port forward _services_ upon `skaffold dev` (previously it was pods). If you need to port forward pods as well, you can define them specifically in the skaffold config, as described [here](https://skaffold.dev/docs/how-tos/portforward/). Does that solve your issue?

**Comment by japsen** [comment] 2019-07-09 16:09
for me it looks like the port-forwarding is initiated while the pods that are linked to the service are still "terminating". Once the new pod is initiated, the port-forward command which is already/still running will not be updated to link to the new pod. 

Maybe this could be solved by re-initiating the port-forward when the kubectl port-forward gives "No such container" or "Timeout occured" errors.

**Comment by priyawadhwa** [comment] 2019-07-09 17:18
Hey @japsen so we currently poll `kubectl port-forward` for one minute, waiting for it to connect successfully. How long does it typically take for your service to connect to a new pod?

**Comment by japsen** [comment] 2019-07-10 08:38
@priyawadhwa In my case I have some simple k8s deployments consisting of 4 deployments (redis, elastic, postgres, our product) All 1 replica; having a service that exposes the ports (ClusterIP). 
I'm using local useDockerCli build; after pushing to the repo it almost instantly shows the following.
It looks like "Waiting for the deployments to stabilize" doesn't do anything.

```
Starting deploy...
kubectl client version: 1.12+
deployment.extensions/elasticsearch created
service/elasticsearch created
deployment.extensions/productname created
service/productname created
deployment.extensions/postgres created
service/postgres created
deployment.extensions/redis created
service/redis created
Deploy complete in 1.461292015s
Waiting for deployments to stabilize
Watching for changes every 1s...
Port Forwarding service/elasticsearch 9200 -> 9200
etc..
```

At that moment, the pods are still on "ContainerCreating". On the _initial_ deployment on an empty cluster it takes about 110 seconds for all pods to be 1/1 Running. 

If I trigger a rebuild by altering a file outside of the "sync" folders (file sync works OK!) then after pushing to the repo, the product pod will be on 1/1 Terminating for about 30 seconds. After that 0/1 Terminating and after about 10 seconds the new pod will be on 1/1 Running. In the meantime the port-forward was already established towards the service/productname during the 1/1 Terminating phase. It looks like it doesn't get updated or reset once the pod reaches it's 1/1 Running phase.

If I manually trigger the following bash script at that moment, then the port forwarding works OK.
```
#!/usr/bin/env bash

ps -ef | grep 'service/productname' | grep -v grep | awk '{print $2}' | xargs kill -9

kubectl port-forward service/productname 7000:7000 &
kubectl port-forward service/productname 8000:8000 &
etc...
```

I'm running skaffold v0.33.0 on mac.

**Comment by cmoad** [comment] 2019-07-10 13:50
@priyawadhwa On first run I can see the services getting successfully forwarded:
```
Port Forwarding service/abbott-v2 3001 -> 3001
Port Forwarding service/zeppo-v2 5000 -> 5000
```
However, if the underlying pods change during a deployment update the service port forward becomes unresponsive.
```
# first run of skaffold dev
% curl http://localhost:3001/health
ok

# after deployment update from a file change
% curl http://localhost:3001/health
curl: (52) Empty reply from server
```

**Comment by priyawadhwa** [comment] 2019-07-10 20:09
@japsen -- thanks for your detailed explanation, I'll take a look at it more closely and let you know what next steps would be.

@cmoad -- this is currently expected behavior. skaffold only establishes a connection after deploy and doesn't continuously check if the connection is valid. So, if a user manually changes the pod underneath the service that is being port-forwarded, skaffold won't pick up on that change, and the connection won't work anymore.

**Comment by priyawadhwa** [comment] 2019-07-11 19:25
@japsen I think this issue should be fixed with #2359 -- the healthcheck will wait until deployments have stabilized, and then port forwarding will start, so the pods should be ready by the time port forwarding starts.

cc @tejal29

**Comment by priyawadhwa** [comment] 2019-07-12 00:40
Hey @japsen  -- #2359 was just merged! Could you check and see if this solves your issue?

To download the latest bleeding edge binary, see instructions [here](https://skaffold.dev/docs/getting-started/#installing-skaffold)

**Comment by japsen** [comment] 2019-07-12 09:08
hi @priyawadhwa thanks for being on this!

I just tested the bleeding edge bin. 
On initial run on an empty cluster; after pushing it works as expected. It waits and creates the forwards once pods are ready. 

Two breaking problems that occur:

- If I change a file, then file sync seems to be stuck in a loop. I changed a README.md file and it keeps syncing. 
```
Syncing 1 files for eu.gcr.io......
Syncing 1 files for eu.gcr.io......
Syncing 1 files for eu.gcr.io......
Syncing 1 files for eu.gcr.io......
etc..... it doesn't stop.
```

- If I change my skaffold.yaml, I would expect it to start a rebuild. However it prints out the following and doesn't continue. This does break the faulty file sync loop though. 
```
Watching for changes every 1s...
time="2019-07-12T11:06:17+02:00" level=error msg="error running dev loop: configuration changed"
```

**Comment by priyawadhwa** [comment] 2019-07-12 16:56
@japsen thanks for testing this out! Since both of these bugs seem unrelated to port forwarding, would you mind opening new issues for them? And if the port forwarding bug is fixed, we can go ahead and close this issue.

**Comment by demisx** [comment] 2019-07-12 18:53
Same issue here. Had to roll back to v0.31 for it to work.

**Comment by demisx** [comment] 2019-07-12 19:05
Just tried it with the latest version `4c144df` and it didn't make any difference. Once skaffold rebuilds the image and restarts container, the previously working port times out.

**Comment by priyawadhwa** [comment] 2019-07-12 21:35
@demisx could you please provide logs for the bug you're seeing?

**Comment by demisx** [comment] 2019-07-12 23:07
@priyawadhwa Hmm... There is really nothing different in the logs I am seeing. It's just, as others mentioned, the app no longer works on its port after skaffold updates the docker image and launches a new pod. The port is still open and listening, but any request to it simply times out. Again, this happens after the first update that requires skaffold to build a new image and launch it in  a new pod. Works fine in v0.31.

**Comment by cmoad** [comment] 2019-07-15 13:34
@priyawadhwa It seems like port forwarding the deployment has the same effect in v0.33.0. Is there any way to produce a reliable port forward as seen in v0.32.0? Thanks.

**Comment by priyawadhwa** [comment] 2019-07-15 19:57
I was able to reproduce the issue and have found a few different bugs -- I got started fixing them in #2477 which should being to improve port forwarding.

**Comment by priyawadhwa** [comment] 2019-07-15 20:00
Hey @cmoad @demisx  I found some bugs in port forwarding and just opened #2477, once it's merged can you let me know if it fixes your issue?

**Comment by prokher** [comment] 2019-07-25 08:53
@priyawadhwa I am using `v0.34.0` which seems to have #2477 inside, but an issues is still here. I run `skaffold dev --port-forward` and when pod gets restarted (after changing a source file) browser is not longer able to connect to the forwarded port .(Actually, the connection is timed out.)

**Comment by prokher** [comment] 2019-07-25 08:54
Could there be some workaround for this issue?

**Comment by demisx** [comment] 2019-07-25 13:46
My workaround so far was to roll back to v0.31. The last version that just works for me.

**Comment by priyawadhwa** [comment] 2019-07-25 17:18
@prokher @demisx we have a PR open to fix some more bugs in port forwarding (#2543) -- once that's in I'll comment here and we can see if it fixes your issues.

**Comment by priyawadhwa** [comment] 2019-07-25 21:04
Hey @prokher @demisx the PR was just merged -- could you try again with skaffold @ master? Instructions for downloading the latest bleeding edge binary are [here](https://skaffold.dev/docs/getting-started/#installing-skaffold)

**Comment by prokher** [comment] 2019-07-26 09:21
@priyawadhwa Triedthe latest bleeding edge binary, it seems to work. Thank you  very much!

**Comment by demisx** [comment] 2019-07-26 15:34
@priyawadhwa I've been using the latest bleeding edge binary `a1efe8c` and it's been working pretty good so far. Some issues I've noticed that may not be related to this one:

1. The first time I've started it, one of the ports for downloaded image wasn't forwarded, though I have port forwarding set up in `skaffold.yaml` (see below). However, subsequent runs seem to be OK so far. I'll keep an eye and report this separately, if I notice a pattern.
   ```sh
   portForward:
         - resourceType: service
           resourceName: postgres
           port: 5432
         - resourceType: service
           resourceName: elasticsearch
           port: 9200
   ```

1. When I change any file that matches any of the sync patterns, skaffold also tries to sync this file to a completed `init-db`  job container(log: `INFO[1182] Skipping sync with pod init-db-7klrh because it's not running`), even though I have no sync set up for this resource.

1. Hitting `[Ctrl+C]` does not clean up after itself anymore. It stops port forwarding, but all resources remain running in the cluster. I have to run `skaffold delete -p dev` manually to clean things up.

**Comment by GavinOsborn** [comment] 2019-07-29 07:08
@priyawadhwa I too have this issue.
**Environment**
 - OS: Windows
 - Environment: Minikube (v1.2.0 & virtual box)
 - K8s Versions Tried: 1.12.8 1.15.0
   (with corresponding kubectl versions)
 - Skaffold Versions: 0.34.0 and 0.34.1
   (installed using chocolaty)

Have recreated using several of the sample applications.

**Observed Behaviour**
 - `skaffold dev --port-forward` successfully opens ports for the initial build.
 - When I make a change the hot-reload is successful 
 - Connection to the new pod is never established
   - Despite the logs often report success
   - Occasionally logs report a new port # assigned (and still no actual connectivity)

If I can provide any further details please let me know.

**Comment by demisx** [comment] 2019-07-29 21:28
I've been testing with the latest bleeding version `4ba3d06` today and [all issues reported earlier](https://github.com/GoogleContainerTools/skaffold/issues/2408#issuecomment-515499548) still exist. The port forwarding seems got worse, though. I can't start `skaffold dev` with all of ports forwarded properly. Something is missing each time and I have to forward manually.

**Comment by balopat** [comment] 2019-07-30 17:59
@demisx - I'm sorry to see this and thank you for persisting in testing with us, we are focused on getting this stabilized asap. The `kubectl port-forward` issues were not calculated in the redesign of our port forwarding, we might have to move to yet another different design to get around them. 

Can you share a bit more info? Are you on minikube? On linux/mac/windows? 
It is surprising to hear it doesn't work the first time either. Can you share logs with `-v trace`?

**Comment by balopat** [comment] 2019-07-30 22:21
@demisx  - master contains one more port-forward fix, it should be all good now. After a couple of refreshes (while the new pod is coming up, and potentially `kubectl portforward` being restarted after a failed connection), it should work. 

We noticed today a bug with the latest minikube - if you are on minikube 1.2.0 - make sure to wait until https://github.com/GoogleContainerTools/skaffold/pull/2577 is merged.

**Comment by demisx** [comment] 2019-07-31 03:57
@balopat I am happy to help where I can as Skaffold is one cool project that makes our development more efficient daily. I've been using the latest `cdffdad` bleeding version today and, indeed, the port forwarding issue seems to be resolved. Haven't had any problems yet. The other issues I've reported  earlier still exist, but probably are out of scope here.

Here is my environment:

* **OS:** 10.14.5 Mojave
* **Local K8S:** Docker for Desktop 2.0.0.3 (K8S Server: 1.10.11)
* **K8S Client**: 1.15.1

Please let me know if you need any other info.

**Comment by nkubala** [comment] 2019-07-31 22:00
@demisx thanks for the info, and glad to hear you're seeing the issue fixed with the latest commits! this has obviously been a pain for us recently so any progress is good progress :) since this particular issue seems to be resolved I'm gonna close this issue, but if you are still seeing the other problems you reported here, please open them up in separate issues so we can track them :+1:

**Closed by nkubala** 2019-07-31 22:00 UTC
Labels: area/portforward, kind/bug, priority/p1

**Comment by demisx** [comment] 2019-07-31 22:31
@nkubala Got it. So, is it OK to create new GitHub issues for problems I am seeing in the latest `master` or should I report against the releases only?

**Comment by nkubala** [comment] 2019-07-31 22:36
yes thats fine! the sooner we catch the issues the better :) just be sure and include the commit if you're seeing them at `HEAD`

**Comment by haje01** [comment] 2023-03-27 05:59
I guess this issue is still happening. I installed bitnami/minio via Helm, deployed it and do `skaffold deploy --port-forward`, and got the following error message:
```
Waiting for deployments to stabilize...
Deployments stabilized in 9.074142ms
port forwarding service-minio-default-9001 got terminated: output: error: unable to forward port because pod is not running. Current status=Pending
```

Port forwarding failed. It seems to happen when the deployment is stable but the pods is not running.
