### ISSUE TITLE
panic on cleanup after Ctrl+C during pushing large image

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#2208] opened 2019-06-02 17:22 UTC
### Expected behavior

clean exit on Ctrl + C 

### Actual behavior

Skaffold panics. 

### Information

- Skaffold version: master
- Operating system: MacOSX
- Contents of skaffold.yaml:

  - one docker artifact 
  - one job that uses that artifact

### Steps to reproduce the behavior

Not sure how reproducible it is, might be a weird race condition, but wanted to make a not of it: 

1. I ran a `skaffold dev --no-prune --trigger notify`
2. image is built, and it's waiting for a long time to push the layers to GCR 
3. pressed Ctrl + C

log extract: 

```
...
4460daec2786: Pushed
^CCleaning up...
job.batch "bq-cirq-xmon" deleted
Cleanup complete in 3.018025022s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4f355ce]

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.doDev(0x551fca0, 0xc00004e580, 0x54e8080, 0xc0000ea000, 0x0, 0x0)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/dev.go:90 +0x1de
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.cancelWithCtrlC.func1(0x54e8080, 0xc0000ea000, 0x0, 0x0)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/signals.go:33 +0xba
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/commands.(*cmdBuilder).NoArgs.func1(0xc000429690, 0xc000335680, 0x0, 0x3, 0x0, 0x0)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd/commands/commands.go:73 +0x3a
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).execute(0xc000429690, 0xc0003355f0, 0x3, 0x3, 0xc000429690, 0xc0003355f0)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000428780, 0xc0000ea000, 0x54e8080, 0xc0000ea008)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:852 +0x2c0
github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/vendor/github.com/spf13/cobra/command.go:800
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app.Run(0x54e8080, 0xc0000ea000, 0x54e8080, 0xc0000ea008, 0xc000507f88, 0x400830f)
        /ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/skaffold.go:27 +0x58
main.main()
        /ext-go/src/github.com/GoogleContainerTools/skaffold/cmd/skaffold/skaffold.go:30 +0x4e

```

**Comment by corneliusweig** [comment] 2019-06-03 11:12
What kind of artifact is that? With a docker artifact, I could not reproduce this on Linux.

**Comment by balopat** [comment] 2019-06-03 17:43
It's a docker artifact - it did not happen consistently, but definitely ran into it multiple times.

**Comment by dgageot** [comment] 2019-07-02 13:00
I'm going to close this one because I'm almost sure it's a duplicate of #2281 that's been fixed with https://github.com/GoogleContainerTools/skaffold/commit/ee24699e931b30ae03aee74b7e9659fc11e14e01.

**Closed by dgageot** 2019-07-02 13:00 UTC
Labels: area/dev, kind/bug
