### ISSUE TITLE
TestBuildKanikoInsecureRegistry is flaky

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/skaffold#4564] opened 2020-07-24 14:07 UTC
```
/integration/TestBuildKanikoInsecureRegistry
time="2020-07-24T13:51:15Z" level=info msg="Namespace: skaffoldkqw5g"
time="2020-07-24T13:51:15Z" level=info msg="[skaffold run --namespace skaffoldkqw5g --default-repo gcr.io/k8s-skaffold -p deploy-insecure-registry]"
time="2020-07-24T13:51:26Z" level=info msg="Ran in 11.07928446s"
time="2020-07-24T13:51:57Z" level=info msg="[skaffold build --namespace skaffoldkqw5g --default-repo 35.223.165.161:5000 --insecure-registry 35.223.165.161:5000 -p build-artifact]"
    TestBuildKanikoInsecureRegistry: build_cluster_test.go:47: skaffold build: exit status 1, Generating tags...
         - kaniko-insecure -> 35.223.165.161:5000/kaniko-insecure:v1.12.0-107-gd0f11aa
        Checking cache...
         - kaniko-insecure: Not found. Building
        Checking for kaniko secret [default/e2esecret]...
        Building [kaniko-insecure]...
        E0724 13:52:03.149493       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
        	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
        E0724 13:52:03.161097       1 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
        E0724 13:52:03.165827       1 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
        error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "35.223.165.161:5000/kaniko-insecure:v1.12.0-107-gd0f11aa": creating push check transport for 35.223.165.161:5000 failed: Get "http://35.223.165.161:5000/v2/": dial tcp 35.223.165.161:5000: connect: connection refused
    TestBuildKanikoInsecureRegistry: panic.go:617: time="2020-07-24T13:51:58Z" level=warning msg="Assuming the secret e2esecret is mounted inside Kaniko pod with the filename kaniko-secret. If your secret is mounted at different path, please specify using config key `pullSecretPath`.\nSee https://skaffold.dev/docs/references/yaml/#build-cluster-pullSecretPath"
        couldn't build "kaniko-insecure": pod has failed
--- FAIL: TestBuildKanikoInsecureRegistry (48.79s)
```

**Comment by tejal29** [comment] 2020-10-05 20:14
we haven't seen this recently. Keeping it open!

**Comment by briandealwis** [comment] 2021-03-08 19:30
Had this last week:
```
/integration/TestBuildKanikoInsecureRegistry
time="2021-03-04T04:46:47Z" level=info msg="Namespace: skaffoldxlgf8"
time="2021-03-04T04:46:47Z" level=info msg="Running [skaffold run --namespace skaffoldxlgf8 --default-repo gcr.io/k8s-skaffold -p deploy-insecure-registry] in testdata/kaniko-insecure-registry"
time="2021-03-04T04:47:14Z" level=info msg="Ran [skaffold run --namespace skaffoldxlgf8 --default-repo gcr.io/k8s-skaffold -p deploy-insecure-registry] in 26.276 seconds"
time="2021-03-04T04:47:40Z" level=info msg="Running [skaffold build --namespace skaffoldxlgf8 --default-repo 35.184.98.139:5000 --insecure-registry 35.184.98.139:5000 -p build-artifact] in testdata/kaniko-insecure-registry"
    build_cluster_test.go:47: skaffold build: exit status 1, Generating tags...
         - kaniko-insecure -> 35.184.98.139:5000/kaniko-insecure:v1.20.0-30-gd50d89463
        Checking cache...
         - kaniko-insecure: Not found. Building
        Checking for kaniko secret [default/e2esecret]...
        Building [kaniko-insecure]...
        E0304 04:47:45.542704       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
        	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
        E0304 04:47:45.559362       1 metadata.go:154] while reading 'google-dockercfg' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg
        E0304 04:47:45.563784       1 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
        error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "35.184.98.139:5000/kaniko-insecure:v1.20.0-30-gd50d89463": creating push check transport for 35.184.98.139:5000 failed: Get "http://35.184.98.139:5000/v2/": dial tcp 35.184.98.139:5000: connect: connection refused
    panic.go:617: time="2021-03-04T04:47:41Z" level=warning msg="Assuming the secret e2esecret is mounted inside Kaniko pod with the filename kaniko-secret. If your secret is mounted at different path, please specify using config key `pullSecretPath`.\nSee https://skaffold.dev/docs/references/yaml/#build-cluster-pullSecretPath"
        pod has failed
--- FAIL: TestBuildKanikoInsecureRegistry (59.25s)
```

**Comment by briandealwis** [comment] 2021-03-08 19:58
Seems to me that the registry may actually take some time to startup.

**Comment by briandealwis** [comment] 2021-07-13 19:01
Still happening
```
=== RUN   TestBuildKanikoInsecureRegistry
time="2021-07-12T20:37:51Z" level=info msg="Namespace: skaffoldslg77"
time="2021-07-12T20:37:51Z" level=info msg="Running [skaffold run --namespace skaffoldslg77 --default-repo gcr.io/k8s-skaffold -p deploy-insecure-registry] in testdata/kaniko-insecure-registry"
time="2021-07-12T20:38:12Z" level=info msg="Ran [skaffold run --namespace skaffoldslg77 --default-repo gcr.io/k8s-skaffold -p deploy-insecure-registry] in 21.431 seconds"
time="2021-07-12T20:39:14Z" level=info msg="Running [skaffold build --namespace skaffoldslg77 --default-repo 34.71.134.178:5000 --insecure-registry 34.71.134.178:5000 -p build-artifact] in testdata/kaniko-insecure-registry"
    build_cluster_test.go:47: skaffold build: exit status 1, Generating tags...
         - kaniko-insecure -> 34.71.134.178:5000/kaniko-insecure:v1.27.0-35-g0429d1275
        Checking cache...
         - kaniko-insecure: Not found. Building
        Starting build...
        Checking for kaniko secret [default/e2esecret]...
        Building [kaniko-insecure]...
        INFO[0000] GET KEYCHAIN
        INFO[0000] running on kubernetes ....
        E0712 20:39:18.351476       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
        	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
        E0712 20:39:18.374608       1 metadata.go:166] while reading 'google-dockercfg-url' metadata: http status code: 404 while fetching url http://metadata.google.internal./computeMetadata/v1/instance/attributes/google-dockercfg-url
        error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "34.71.134.178:5000/kaniko-insecure:v1.27.0-35-g0429d1275": creating push check transport for 34.71.134.178:5000 failed: Get "https://34.71.134.178:5000/v2/": dial tcp 34.71.134.178:5000: connect: connection refused; Get "http://34.71.134.178:5000/v2/": dial tcp 34.71.134.178:5000: connect: connection refused
    panic.go:617: time="2021-07-12T20:39:15Z" level=warning msg="Assuming the secret e2esecret is mounted inside Kaniko pod with the filename kaniko-secret. If your secret is mounted at different path, please specify using config key `pullSecretPath`.\nSee https://skaffold.dev/docs/references/yaml/#build-cluster-pullSecretPath"
        pod has failed
--- FAIL: TestBuildKanikoInsecureRegistry (88.88s)
```

**Comment by dgageot** [comment] 2021-07-13 19:11
Some things never change :-)

**Comment by tejal29** [comment] 2022-03-02 21:25
dupe of #7092

**Closed by tejal29** 2022-03-02 21:25 UTC
Labels: priority/p0, meta/test-flake, kind/todo
