### ISSUE TITLE
docker.pkg.github.com: unable to pull images with @sha256 tag in image name

### ISSUE THREAD

**Issue by StarpTech** [GoogleContainerTools/skaffold#4388] opened 2020-06-24 09:26 UTC
# Expected behavior

`skaffold run` produces an invalid image tag that can't be pulled on Kubernetes. I use Github Packages as docker registry.

```
docker.pkg.github.com/foo/bar/service:latest@sha256:c05bbd85b060818016b36bfe456f57f54051485d36a2811442b8167ce93560f1
```

### Actual behavior

Produced error:

```
 - development:deployment/foo-dev: waiting for rollout to finish: 1 out of 2 new replicas have been updated...
    - development:pod/foo-dev-58f4b5677f-sljfs: container service is waiting to start: docker.pkg.github.com/foo/bar/service:latest@sha256:c05bbd85b060818016b36bfe456f57f54051485d36a2811442b8167ce93560f1 can't be pulled
    - development:pod/foo-dev-58f4b5677f-t8hvh: container service is waiting to start: docker.pkg.github.com/foo/bar/service:latest@sha256:c05bbd85b060818016b36bfe456f57f54051485d36a2811442b8167ce93560f1 can't be pulled
```

After removing the part `@sha256:` my deployments work and all images are pulled correctly.

### Information

- Skaffold version: v1.11.0
- Operating system: Ubuntu
- Contents of skaffold.yaml:

```
apiVersion: skaffold/v2beta5
kind: Config

build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: docker.pkg.github.com/foo/bar/webapp
    context: frontpage
  - image: docker.pkg.github.com/foo/bar/service
    context: service
```

Related:
https://github.com/GoogleContainerTools/skaffold/issues/3269

**Comment by tstromberg** [comment] 2020-06-24 16:55
This is unfortunately a restriction of docker.pkg.github.com:

https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages

Marking as dupe of #4218

**Closed by tstromberg** 2020-06-24 16:55 UTC
