### ISSUE TITLE
Cannot get job redeployed using helm

### ISSUE THREAD

**Issue by rlotufo** [GoogleContainerTools/skaffold#1706] opened 2019-02-28 16:14 UTC
This issue is similar to https://github.com/GoogleContainerTools/skaffold/pull/940

The only difference is that the problem still occurs if using helm instead of kubectl. The problem seems to be that it is not possible to update a Job with a different image, so a solution might be to use `--force` when calling helm upgrade, similar to what was done to solve issue #940

https://codecov.io/gh/GoogleContainerTools/skaffold/pull/940/diff

### Expected behavior

Redeploying a Job should work when using helm, but instead I get an "immutable field" error thrown by kubectl.

**Comment by balopat** [comment] 2019-02-28 20:00
What version of kubectl are you using?

**Comment by rlotufo** [comment] 2019-02-28 21:05
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-04T04:48:55Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by corneliusweig** [comment] 2019-03-16 13:14
Should be fixed by #1568

**Comment by tejal29** [comment] 2019-05-07 17:36
This should be fixed.

**Closed by tejal29** 2019-05-07 17:36 UTC
Labels: area/deploy, deploy/helm

**Comment by demisx** [comment] 2020-02-08 19:23
I am experiencing a similar problem if I am trying to run skaffold when local cluster has deployed releases running from the previous skaffold run:

```
Starting deploy...
Error: UPGRADE FAILED: failed to replace object: Service "elasticsearch-master" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```

I have to manually `helm del` all releases for it to work. Here are my versions on MacOs 10.15.3:

```sh
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:54Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

$ skaffold version
v1.3.1

$ helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.7"}
```

```yaml
# In skaffold.yaml
apiVersion: skaffold/v2alpha1
kind: Config
deploy:
  kubeContext: docker-for-desktop
  helm:
    flags:
      upgrade: ['-i']
    releases:
    ...
```

**Comment by corneliusweig** [comment] 2020-02-11 20:15
@demisx This looks like an unrelated problem. Can you open a separate issue with a minimal example to reproduce the problem?

My guess is that in the second skaffold run helm tries to patch the resource created by the first run. But to be sure, we need reproduction.
