### ISSUE TITLE
Setting imageStrategy.helm (instead of using FQN default) does not work for .image nested under a parent key

### ISSUE THREAD

**Issue by smoll** [GoogleContainerTools/skaffold#1156] opened 2018-10-13 16:45 UTC
### Expected behavior

Changed my helm chart

```diff
-image: puckel/docker-airflow:1.9.0-4
-imagePullPolicy: IfNotPresent
airflow:
+  image:
+    repository: puckel/docker-airflow
+    tag: 1.9.0-4
+    pull_policy: IfNotPresent
```

and updated my config

```diff
apiVersion: skaffold/v1alpha4
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: airflow-tmp
deploy:
  helm:
    releases:
    - name: airflow
      namespace: airflow
      chartPath: charts/airflow
      valuesFiles:
      - values/local-values.yaml
      values:
-        image: airflow-tmp
+        airflow.image.repository: airflow-tmp
      setValues:
-        imagePullPolicy: IfNotPresent
+        airflow.image.pull_policy: IfNotPresent
+      imageStrategy:
+        helm: {}
```

which should have just been a pure refactor and `skaffold run` should have continued to succeed.

### Actual behavior

When I run `skaffold run` I get the following:

```
Update Complete. ⎈Happy Helming!⎈
Saving 2 charts
Downloading postgresql from repo https://kubernetes-charts.storage.googleapis.com/
Downloading redis from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
k8s.io/helm/pkg/strvals.(*parser).key(0xc000872680, 0xc00075da10, 0xc00080d390, 0x5)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/pkg/strvals/parser.go:211 +0xedf
k8s.io/helm/pkg/strvals.(*parser).key(0xc000872680, 0xc00075d9b0, 0xc00080d5c8, 0x7)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/pkg/strvals/parser.go:215 +0x1b0
k8s.io/helm/pkg/strvals.(*parser).key(0xc000872680, 0xc00075cde0, 0x1e8252d, 0x2158b60)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/pkg/strvals/parser.go:215 +0x1b0
k8s.io/helm/pkg/strvals.(*parser).parse(0xc000872680, 0xc00075cde0, 0x0)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/pkg/strvals/parser.go:133 +0x38
k8s.io/helm/pkg/strvals.ParseInto(0x7fff5fbff9fc, 0x54, 0xc00075cde0, 0x1fb95c0, 0xc00000e958)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/pkg/strvals/parser.go:85 +0xbe
main.vals(0xc0003b28d0, 0x1, 0x1, 0xc0005f2c60, 0x2, 0x2, 0x33234a8, 0x0, 0x0, 0x33234a8, ...)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/cmd/helm/install.go:386 +0x276
main.(*upgradeCmd).run(0xc0001be780, 0x0, 0x2463ce0)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/cmd/helm/upgrade.go:238 +0x2d4
main.newUpgradeCmd.func2(0xc00082b900, 0xc0001163c0, 0x2, 0xc, 0x0, 0x0)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/cmd/helm/upgrade.go:145 +0x12e
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc00082b900, 0xc000116300, 0xc, 0xc, 0xc00082b900, 0xc000116300)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:756 +0x473
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f4280, 0xc000073900, 0xc000073b80, 0xc0003de000)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:846 +0x2fd
k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0000f4280, 0xd, 0xd)
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/private/tmp/kubernetes-helm-20180927-91593-13a8zwt/src/k8s.io/helm/cmd/helm/helm.go:167 +0x79
FATA[0003] deploy step: deploying airflow: exit status 2
```

Could this be because `image` / `repository` are specified under a parent key (`airflow`)... I used the `imageStrategy.helm` value as described in https://github.com/GoogleContainerTools/skaffold/issues/360 so I think that should be fine.

### Information

- Skaffold version: v0.16.0
- Operating system: macOS Sierra 10.12.6
- Contents of skaffold.yaml: see diff above

**Comment by smoll** [comment] 2018-10-16 11:43
Looks like it works if the image name is defined at a top level `image`, e.g.

```yml
image:
  repository: somename
  tag: sometag
```

but not if under some `parent`, e.g.

```yml
parent:
  image:
    repository: somename
    tag: sometag
```

I don't know any Go but the code looks straightforward, so I'm going to try to take a crack at making this configurable, such that you can specify an arbitrary key mapping in `skaffold.yml`:

```yml
imageStrategy:
  helm:
    repositoryKey: parent.image.repository # defaults to image.repository
    tagKey: parent.image.tag # defaults to image.tag
```

**Comment by michaelbeaumont** [comment] 2019-05-12 16:16
I can't reproduce this bug anymore, if I write the following it works:

```
      values:
-        airflow.image.repository: airflow-tmp
+        airflow.image: airflow-tmp
```

**Comment by nkubala** [comment] 2019-06-04 17:30
going to close this one for now, please feel free and reopen if you're still seeing the issue.

**Closed by nkubala** 2019-06-04 17:30 UTC
Labels: area/deploy, deploy/helm, kind/bug

**Comment by lboclboc** [comment] 2020-02-06 17:01
I still see this error with bleeding edge skaffold version 7b4da99.
I am trying to deploy jenkins with helm and it has its image specified as key master.image, like:
      values:
        master.image: registry2:443/atlas-ssvjenkins
      imageStrategy:
        helm: {}


I get the exact same error as the original reporter.

**Comment by nkubala** [comment] 2020-04-10 22:20
@lboclboc you're still seeing skaffold panic on the latest version?

can you give me contents of your skaffold.yaml and some version info (skaffold, helm, etc.)?
