### ISSUE TITLE
Image Repository Handling

### ISSUE THREAD

**Issue by blaggacao** [GoogleContainerTools/skaffold#4858] opened 2020-10-05 20:01 UTC
### Expected behavior

`--default-repo='x.y.z'` would transform `z.y.x/image-name` into `x.y.z/image-name`.

### Actual behavior
`--default-repo='x.y.z'` transforms `z.y.x/image-name` into `x.y.z/z.y.x_image-name`.

### Information

While this is ok if one's entire deployment workflow is managed through skaffold, it starts to break things once one wants to use skaffold during dev and up until shit-left style artifact build but use different tooling for deployment.

In an air-gapped environment, I would distribute images to mirrors and register registry mirrors with containerd in the style of:
`z.y.x -> x.y.z`. So the current transformation breaks any distribution strategy which involves host mirrors.

The problem is that I could not re-use any `./deploy` blueprint without also applying this skaffold-specific transformation downstream, while handling distribution (`skaffold build`) in upstream repositories. To work arround this, I would have to execute a specific skaffold render in downstream repositories to map for the `x.y.z/z.y.x_image-name` distributed names or make a somewhat hard to maintain manual kustomization image replacement.

Ok why not simply avoid `--default-repo` altogether? It would come handy if could provide quick switches between a `x.y.z:5000` and a `x.y.z` repo deployment and similar, mainly for different dev _or staging_ environments (local, k3d, remote, vm, etc) without needing to touch the manifests themselves.

**Comment by tejal29** [comment] 2020-10-05 20:59
@blaggacao We are aware of this issue. 
We have a PR #4150 in progress to address this. 
We will try to get this in ASAP.

**Comment by blaggacao** [comment] 2020-10-05 21:07
@tejal29 Oh nice, I was thinking of ways to abstractly reproduce, so non-withstanding here is my take:

- Have deployment registry on authoritative.registry.example.com
- construe deployments with `image: authoritative.registry.example.com/my-image` - the canonical way
- Manage a temporary host entry with (e.g. with `hostctl`) so that `authoritative.registry.example.com` -> `169.254.0.5` (link-local test net!!)
- Circumstantially, not having neither `:80` nor `:443` available, we need to resort to `:5000`
- `skaffold --default-repo='authoritative.registry.example.com:5000' build` would break
- downstream apply of manifests `image: authoritative.registry.example.com/my-image` when configured with a containerd mirror:
`authoritative.registry.example.com -> authoritative.registry.example.com:5000`

**Comment by briandealwis** [comment] 2020-10-07 17:30
Closing — we'll continue discussion on #4150.
Duplicate of #4150

**Closed** 2020-10-07 18:01 UTC
Labels: area/default-repo, kind/friction, priority/p2
