### ISSUE TITLE
skaffold build hangs when pushing to docker hub

### ISSUE THREAD

**Issue by kahunacohen** [GoogleContainerTools/skaffold#6292] opened 2021-07-26 16:05 UTC
### Expected behavior
Running `skaffold build` with skaffold.yaml's `build.local.push` set to `true` should push to the image repo as specified in default-repo.

### Actual behavior
skaffold hangs when trying to push.

### Information

- Skaffold version: 1.28.1
- Operating system: Mac OSX
- Installed via: skaffold.dev

### Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: hello-k8s
build:
  artifacts:
  - image: hello-k8s
    docker:
      dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - manifests/web-configmap.yaml
    - manifests/web-service.yaml
    - manifests/web-deployment.yaml
   ```

### Contents of web-deployment.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-pod
  template:
    metadata:
      labels:
        app: web-pod
    spec:
      containers:
      - name: web
        image: kahunacohen/hello-k8s
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: web-configmap
        ports:
        - containerPort: 3000
          protocol: TCP
```

### Steps to reproduce the behavior

1. https://github.com/kahunacohen/hello-k8s/tree/tutorial
2. Running minikube, do `skaffold build`

### Config

```
$ skaffold config list
skaffold config: 
kube-context: minikube
default-repo: docker.io/kahunacohen
```

### Output from `skaffold build -vdebug`

```
$ skaffold build -vdebug 
INFO[0000] Skaffold &{Version:v1.28.1 ConfigVersion:skaffold/v2beta19 GitVersion: GitCommit:7b855e136dc0f9cc5544ed2808c9d5feb767118c BuildDate:2021-07-20T17:51:49Z GoVersion:go1.14.14 Compiler:gc Platform:darwin/amd64 User:} 
INFO[0000] Loaded Skaffold defaults from "/Users/acohen/.skaffold/config" 
DEBU[0000] found config for context "minikube"          
DEBU[0000] parsed 1 configs from configuration file /Users/acohen/kahunacohen/hello-k8s/skaffold.yaml 
INFO[0000] Using kubectl context: minikube              
DEBU[0000] Running command: [minikube version --output=json] 
DEBU[0000] Command output: [{"commit":"a03fbcf166e6f74ef224d4a63be4277d017bb62e","minikubeVersion":"v1.22.0"}
] 
DEBU[0000] Running command: [/usr/local/bin/minikube docker-env --shell none -p minikube --user=skaffold] 
DEBU[0001] Command output: [DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://127.0.0.1:49781
DOCKER_CERT_PATH=/Users/acohen/.minikube/certs
MINIKUBE_ACTIVE_DOCKERD=minikube
] 
DEBU[0001] setting Docker user agent to skaffold-v1.28.1 
INFO[0001] Using minikube docker daemon at tcp://127.0.0.1:49781 
DEBU[0001] Using builder: local                         
INFO[0001] build concurrency first set to 1 parsed from *local.Builder[0] 
INFO[0001] final build concurrency value is 1           
Generating tags...
 - hello-k8s -> DEBU[0001] Running command: [git describe --tags --always] 
DEBU[0001] Command output: [3089c6b
]                   
DEBU[0001] Running command: [git status . --porcelain]  
DEBU[0001] Command output: [?? skaffold
?? x.sh
]       
INFO[0001] Using default-repo=docker.io/kahunacohen from config 
docker.io/kahunacohen/hello-k8s:3089c6b-dirty
INFO[0001] Tags generated in 26.317582ms                
Checking cache...
DEBU[0001] Found dependencies for dockerfile: [{package.json /code true} {server.js /code true}] 
 - hello-k8s: Not found. Building
INFO[0003] Cache check completed in 2.102 seconds       
Starting build...
Found [minikube] context, using local docker daemon.
Building [hello-k8s]...
DEBU[0003] Running docker build: context: ., dockerfile: Dockerfile 
Sending build context to Docker daemon  4.608kB
Step 1/8 : from node:14.17.3
 ---> 813e282b6d18
Step 2/8 : RUN useradd -ms /bin/bash appuser && mkdir /code && chown -R appuser /code
 ---> Using cache
 ---> e2cb91b0799d
Step 3/8 : COPY package.json /code/
 ---> Using cache
 ---> 5cc9d901bb33
Step 4/8 : WORKDIR /code
 ---> Using cache
 ---> 52711d91a409
Step 5/8 : RUN npm install
 ---> Using cache
 ---> 15b9f1b506a6
Step 6/8 : COPY server.js /code/
 ---> Using cache
 ---> e8ddeefadf29
Step 7/8 : USER appuser
 ---> Using cache
 ---> f62153fa4268
Step 8/8 : CMD ["node", "server.js"]
 ---> Using cache
 ---> 51c286922370
Successfully built 51c286922370
Successfully tagged kahunacohen/hello-k8s:3089c6b-dirty
The push refers to repository [docker.io/kahunacohen/hello-k8s]
ff3fc28d603a: Preparing
5baa891edc28: Preparing
83c575748d30: Preparing
6c61e14f8d44: Preparing
14b4c05157aa: Preparing
988cf964c9c1: Preparing
b58ea2e80417: Preparing
d7aef11e5baf: Preparing
2c6cd9a0820c: Preparing
50c78a431907: Preparing
cccb1829e343: Preparing
14ce51dbae6e: Preparing
3125b578849a: Preparing
d7aef11e5baf: Waiting
2c6cd9a0820c: Waiting
50c78a431907: Waiting
cccb1829e343: Waiting
14ce51dbae6e: Waiting
3125b578849a: Waiting
988cf964c9c1: Waiting
b58ea2e80417: Waiting
6c61e14f8d44: Layer already exists
14b4c05157aa: Layer already exists
ff3fc28d603a: Layer already exists
83c575748d30: Layer already exists
5baa891edc28: Layer already exists
988cf964c9c1: Layer already exists
d7aef11e5baf: Layer already exists
cccb1829e343: Layer already exists
14ce51dbae6e: Layer already exists
```
Script hangs in this last step. Network is fine. I can push using docker OK.

If I set my image in skaffold to include username (kahunacohen) and set my default repo to not include the username I get: `denied: requested access to the resource is denied` when running build, when it's trying to push.

**Comment by aaron-prindle** [comment] 2021-07-27 19:47
I am able to reproduce the error `denied: requested access to the resource is denied` with a setup specifying the repo in the images (eg: aaronprindle/hello-k8s:tag).  I was however able to get this setup working correctly though using `--default-repo=aaronprindle` and I did not get the hang mentioned:
```
skaffold build --default-repo=aaronprindle
```

Full logs with successful build and push:
https://gist.github.com/aaron-prindle/c93e1e66e34e37338b9fa19d302cefb8

Dockerhub UI showing image was pushed:
![image](https://user-images.githubusercontent.com/1951658/127218041-e90f3456-ac21-4a82-8410-990a3548e1d7.png)

**Comment by aaron-prindle** [comment] 2021-07-27 20:00
I am not sure what might be different in our setups/steps-here but I did notice that the push seemed to take a longer using skaffold.  Perhaps it was not hanging but there was a large slowdown?  Can you verify that this is hanging on your setup vs takes X minutes?

**Comment by kahunacohen** [comment] 2021-07-28 06:19
@aaron-prindle thank you. Yes this also works for me when I set the default repo via the command line.

Questions:

1. I thought the repo meant docker.io, but I guess it really means the docker username, in my case kahunacohen. Is the default place it pushes docker hub? If you want to push it to another place like google's container registry, is that a different setting than default-repo?
2. What is suggested? Leaving the repo and tags out of the yamls? So deployment.yaml should list simply "hello-k8s" and skaffold.yaml also "hello-k8s"?

**Comment by kahunacohen** [comment] 2021-07-28 13:00
OK I think you can close this. I guess it was a slow connection on my machine.  I had other tags of this image up there, but for some reason the first time building with skaffold it seemed to take a long time to push, maybe there are some layers that go in to the skaffold tagged image?

Anyway, now it works as expected. I just let it push for >5 mins and it worked.

**Comment by aaron-prindle** [comment] 2021-07-28 17:36
> "kahunacohen" is not a repo is it? Isn't that my username? A repo would be k8s, so kahunacohen/k8s represents a namespace + repo. So when we set a default repo, what are we referring to?

It is a repo because the docker specification is that any path without a url prefix is by default the `docker.io` registry, some more information here - https://docs.docker.com/registry/introduction/#understanding-image-naming

> How does skaffold know to push to docker hub? Is that the default image repo? If you want to use another one, you have to explicitly name it in the image field?

Similar to the above, the the docker spec is that the default image registry is `docker.io` so it is prefixed on images w/ no registry specified.  To use another registry, for example `gcr.io` you specifiy the prefix explicitly - eg: `skaffold build --default-registry=gcr.io/aaronprindle/hello-k8s`.  For dockerhub, both `--default-registry=docker.io/aaronprindle/hello-k8s` and `--default-registr=aaronprindle/hello-k8s` due to the defaulting in the docker spec.

Closing for now, please re-open if there is some addition issues here.  Thanks

**Closed by aaron-prindle** 2021-07-28 17:36 UTC
Labels: area/build, build/docker, kind/bug, priority/p2
