### ISSUE TITLE
Latest built jar not picked up

### ISSUE THREAD

**Issue by tvanhees** [GoogleContainerTools/skaffold#1069] opened 2018-10-01 06:26 UTC
Hello,

I am trying to use Skaffold for my Java (Spring Boot) project. Whenever I do a "mvn package" Skaffold starts a new deploy, but when building the Docker image, a jar from the cache is used in stead of the latest version in my target folder.

I am aware that this might be a Docker issue, however, I am not able (or I don't know how) to manipulate the fact it should not cache my jars. When using Docker Compose, the jar is always the one that has been built the last time.

### Expected behavior
When a new jar is built, it is used to build the Docker image
When building with Docker Compose:
```
Step 1/4 : FROM openjdk:8-jdk-alpine
 ---> 5801f7d008e5
Step 2/4 : ENV TZ Europe/Brussels
 ---> Using cache
 ---> 8308fc77978b
Step 3/4 : COPY target/myapp.jar /usr/local/
 ---> cdff1ee95c08
Step 4/4 : ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000",             "-Djava.security.egd=file:/dev/./urandom", "-Xdebug",             "-jar", "/usr/local/myapp.jar"]
 ---> Running in 9aa789ad623b
Removing intermediate container 9aa789ad623b
 ---> 2f01dca6e782
Successfully built 2f01dca6e782
```

### Actual behavior
The Docker image is built using the jar from the cache (of Docker)

```
Step 1/4 : FROM openjdk:8-jdk-alpine
 ---> 5801f7d008e5
Step 2/4 : ENV TZ Europe/Brussels
 ---> Using cache
 ---> 8308fc77978b
Step 3/4 : COPY target/myapp.jar /usr/local/
 ---> Using cache
 ---> ee3d0e7fd529
Step 4/4 : ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000",             "-Djava.security.egd=file:/dev/./urandom", "-Xdebug",             "-jar", "/usr/local/myapp.jar"]
 ---> Using cache
 ---> b0f0270a3240
Successfully built b0f0270a3240
```

### Information
My noteworthy to tell is that I've put my helm config in a totally different folder than where my application is sitting.

- Skaffold version: version v0.15.0
- Operating system: Win10
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
  - imageName: location_to_my_image
    workspace: ./../workspace-folder/my-app-folder/
deploy:
  helm:
    releases:
    - name: my-app-release
      chartPath: ./../kubernetes-helm-config
      valuesFiles:
      - ./../kubernetes-helm-config/values.yaml
      namespace: ""
      version: ""
      setValues: {}
      setValueTemplates: {}
      wait: false
      recreatePods: false
      overrides: {}
      packaged: null
      imageStrategy:
        fqn: null
        helm: null
```

### Steps to reproduce the behavior

1. Run skaffold dev
2. Skaffold sets up a release and deploys it
3. Make a code changes and run 'mvn clean package'
4. (Skaffold crashed because it can't find a jar, but that's for another ticket if find the time)
5. run skaffold dev again
6. skaffold (Docker) builds and image using a jar from the cache (so the changes are not effective)

The work around is to build the jar and docker image and push it to our docker container registry on our build system. But that defeats the purpuse of Skaffold.

**Comment by dgageot** [comment] 2018-12-03 18:23
@tvanhees have you tried with Skaffold 0.19? It would be good to know if this is still there.

**Comment by dgageot** [comment] 2019-01-20 16:06
I'm going to close this one. @tvanhees feel free to reopen in case the issue is still there.

**Closed by dgageot** 2019-01-20 16:06 UTC
Labels: area/build, area/watch, bug, platform/windows
