### ISSUE TITLE
Add new `--out` parameter to `skaffold build`

### ISSUE THREAD

**Issue by pepjo** [GoogleContainerTools/skaffold#2261] opened 2019-06-12 12:20 UTC
### Actual behavior
This is a feature request.
`skaffold build --quite > build.out` generates the docker images and an output file used by `skaffold deploy`. This methodology however prevents displaying the normal console output and makes it difficult to debug, especially if this command runs in a CI.

### Expected behavior
It would be amazing if, instead of using the output to generate the `build.out` file, we could use an extra option that does not erase the default output of `skaffold build`. Such option could be something like this: `skaffold build --out build.out` and there would be no change to the normal console output.

**Comment by alnr** [comment] 2019-06-12 16:24
Duplicate of #2249

**Comment by dgageot** [comment] 2019-06-20 13:07
Closing as a duplicate of #2249

**Closed by dgageot** 2019-06-20 13:07 UTC
