### ISSUE TITLE
"UNAUTHORIZED: authentication required" error after upgrade to v0.32

### ISSUE THREAD

**Issue by demisx** [GoogleContainerTools/skaffold#2314] opened 2019-06-21 18:10 UTC
After upgrading to 0.32.0 `skaffold dev` can no longer start. It errors out with the following error(see below). Please note I am only building local images - not using any registry of any kind for my docker images.  

```sh
> skaffold dev -v=info --port-forward=false

INFO[0000] Skaffold &{Version:v0.32.0 ConfigVersion:skaffold/v1beta11 GitVersion: GitCommit:6ed7aad5e8a36052ee5f6079fc91368e362121f7 GitTreeState:clean BuildDate:2019-06-20T23:34:55Z GoVersion:go1.12.6 Compiler:gc Platform:darwin/amd64} 
INFO[0000] applying profile: dev                        
INFO[0000] no values found in profile for field TagPolicy, using original config values 
INFO[0000] no config entry found for kube-context docker-for-desktop 
INFO[0000] Using kubectl context: docker-for-desktop    
INFO[0000] no config entry found for kube-context docker-for-desktop 
INFO[0000] no config entry found for kube-context docker-for-desktop 
INFO[0000] no config entry found for kube-context docker-for-desktop 
INFO[0000] starting gRPC server on port 50051           
INFO[0000] starting gRPC HTTP server on port 50052      
FATA[0004] watching files for artifact dl-web: listing files: listing files: listing copied files: retrieving image config: getting image: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/base Type:repository]] 
```

### Information

- Skaffold version: 0.32
- Operating system: MacOs 10.14.5
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubectl:
        manifests:
          - web/k8s/dev/web-k8s.yaml
    build:
      local:
        useDockerCLI: true
      artifacts:
        - image: dl-web
          context: .
          docker:
            dockerfile: web/Dockerfile
            target: dev-env
```

### Steps to reproduce the behavior

1. Run `skaffold dev -v=info --port-forward=false`

**Comment by braderhart** [comment] 2019-06-21 20:48
This has to do with targets, please see:

https://github.com/GoogleContainerTools/skaffold/issues/2315

I tried warning @dgageot about this yesterday on Slack.

**Comment by dgageot** [comment] 2019-06-26 08:08
@demisx Can you confirm you have a multi-stage build? If the answer is yes, then this is a duplicate of #2315

**Comment by michaelkruglos** [comment] 2019-06-26 11:17
Here's what I get after the upgrade:

```
WARN[0000] Could not get minikube docker env, falling back to local docker daemon: getting minikube env: Running [minikube docker-env --shell none]: stdout , stderr: X The docker host is currently not running
, err: exit status 69: exit status 69
FATA[0004] watching files for artifact agogos: listing files: listing files: listing copied files: retrieving image config: getting image: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/base Type:repository]]
```

**Comment by dgageot** [comment] 2019-06-26 13:54
@michaelbeaumont Can you share your Dockerfile?

**Comment by demisx** [comment] 2019-06-26 14:12
@dgageot This is correct. I have multi-stage Dockerfile. Once I make it a single-stage the error goes away.

**Comment by dgageot** [comment] 2019-06-26 14:25
@demisx Thanks a lot for your feedback!
Closing as a duplicate of #2315

**Closed by dgageot** 2019-06-26 14:25 UTC
Labels: build/dockerfile, kind/bug
