### ISSUE TITLE
The deployed pod did not deleted in 'dev' option

### ISSUE THREAD

**Issue by jaredbark** [GoogleContainerTools/skaffold#2412] opened 2019-07-05 07:01 UTC
### Expected behavior
The deployed pod should be deleted when stopping the process which launched in 'dev' option

### Actual behavior
The deployed pod did not deleted from the cluster.

Log
DEBU[0025] Running command: [helm --kube-context eks-dev-cluster delete configmgmt --purge]
release "configmgmt" deleted
Cleanup complete in 3.989216938s
FATA[0029] exiting dev mode because first deploy failed: deploying configmgmt: exit status 1

### Information

- Skaffold version: a43cf56
- Operating system: CentOS 7
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:0.1"
  artifacts:
  - image: XXX
    jibMaven:
      args:
      - -DskipTests=true
deploy:
  helm:
    releases:
    - name: configmgmt
      namespace: devel
      version: 0.1
      chartPath: pod
      valuesFiles:
      - ./pod/values.yaml
      - ../../globalvalues/globalvalues.yaml
      values:
        image: XXX
    flags:
      install: ["--name=configmgmt", "--tiller-namespace=devel", "--namespace=devel"]
```

### Steps to reproduce the behavior

1. Set flags with contents of skaffold.yaml above.
2. Execute 'skaffold dev -f skaffold.yaml'.
3. Stop the process by Ctrl-C.
4. The deployed pod did not deleted from the cluster.

**Comment by priyawadhwa** [comment] 2019-07-09 22:09
Hey @jaredbark, could you please provide a small project so that we can reproduce this bug?

**Comment by jaredbark** [comment] 2019-07-10 00:01
@priyawadhwa , I cannot provide it. But the root cause of this issue is that the 'helm delete --purge' command not work with the helm release that installed with custom namespace of tiller. Because the default namespace of tiller is 'kube-system' and I've installed my release with '--tiller-namespace=devel' option. So, the helm cannot delete the release, and Skaffold has to provide an option to delete the helm release, in my opinion.

For example:
deploy:
  helm:
    flags:
        install: ["--name=configmgmt", "--tiller-namespace=devel", "--namespace=devel"]
        _delete: ["--tiller-namespace=devel"]_

**Comment by dgageot** [comment] 2019-07-10 19:04
You can use
```
flags:
  global: ["--tiller-namespace=devel"]
```

I'm going to close this one as a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/1183

**Closed by dgageot** 2019-07-10 19:04 UTC
Labels: deploy/helm, kind/bug
