### ISSUE TITLE
Cannot connect to the Docker Damon via /var/run/docker. sock

### ISSUE THREAD

**Issue by lucidlips** [GoogleContainerTools/skaffold#7985] opened 2022-10-26 12:08 UTC
### Expected behavior
Skaffold is able to connect to the docker daemon

### Actual behavior
Skaffold cant connect.

### Information
This is an issue with Docker but its affecting scaffold so I thought I would post here. A recent update to docker desktop for mac v4.13.0 does not add the required sym link to access to docker daemon at `/var/run/docker.sock`. I tested this with a clean install of v4.12.0 and verified this.

Creating the sym manually or rolling back to docker desktop v4.12.0 does resolve the issue. 

Docker issue is here: [Cannot connect to the Docker Damon via /var/run/docker. sock](https://github.com/docker/for-mac/issues/6536)

**Comment by aariacarterweir** [comment] 2022-10-27 02:05
Just pasting the super quick workaround for affected users:

```
sudo ln -s "$HOME/.docker/run/docker.sock" /var/run/docker.sock
```

**Comment by aaron-prindle** [comment] 2022-10-31 22:51
Closing as dupe of #7981

**Closed by aaron-prindle** 2022-10-31 22:51 UTC
Labels: priority/p1, platform/mac, area/arm64
