### ISSUE TITLE
Fail to deploy helm on Minikube after upgrading Skaffold, Helm and Minikube to the latest version

### ISSUE THREAD

**Issue by mraliagha** [GoogleContainerTools/skaffold#3500] opened 2020-01-11 13:08 UTC
Since I have upgraded helm, Skaffold and Minikube to the latest version, my local project has been failed to get deployed to minikube with the following warning:

    Listing files to watch...
     - tect-cicd
    Generating tags...
     - tect-cicd -> tect-cicd:2.2.19-5-gfb14eb3-dirty
    Checking cache...
     - tect-cicd: Found Locally
    Tags used in deployment:
     -tect-cicd -> tect-cicd:ce2c8b21a565fc96d3e2c8f9821e7a9b3364fe0c06bc4611d63e64c1332f43a3
       local images can't be referenced by digest. They are tagged and referenced by a unique ID instead
    Starting deploy...
    WARN[0003] image [tect-cicd:ce2c8b21a565fc96d3e2c8f9821e7a9b3364fe0c06bc4611d63e64c1332f43a3] is not used. 
    WARN[0003] image [tect-cicd] is used instead.    
    WARN[0003] See helm sample for how to replace image names with their actual tags: https://github.com/GoogleContainerTools/skaffold/blob/master/examples/helm-deployment/skaffold.yaml 
    Error: UPGRADE FAILED: "test-cicd" has no deployed releases
    Cleaning up...
    Error: unknown flag: --purge
    FATA[0003] exiting dev mode because first deploy failed: deploying test-cicd: exit status 1 

My skaffold.yml

    apiVersion: skaffold/v2alpha1
    kind: Config
    profiles:
    - name: dev
      activation:
      - kubeContext: minikube
        command: dev
      build:
        tagPolicy:
          gitCommit: {}
        artifacts:
        - image: tect-cicd
          jib:
            type: maven
            args:
            - -Dmaven.test.skip
            - clean
        local:
          push: false
      deploy:
        helm:
          releases:
          - name: test-cicd
            chartPath: deployment/helm
            setValues: # listing the env variables here for secrets according to secrets.yaml file
              secret.db.password: ${DB_PASSWORD}
            valuesFiles:
            - deployment/helm/values/values-default.yaml
            - deployment/helm/values/secrets.yaml
            - deployment/helm/values/values-dev.yaml

I am not sure if I am missing something or this is just a bug I am hitting.

- Skaffold version: 1.1.0
- Helm version: 3.0.2
- Minikube version: 1.6.2
- Operating system: MacOs 10.15.2

**Comment by KhaledSakr** [comment] 2020-01-14 10:37
This seems to be a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/3386
As a workaround you can:
```yaml
deploy:
   ...
    flags:
      upgrade:
        - --install
```

**Comment by balopat** [comment] 2020-01-14 23:44
Yes, this is a duplicate. Thank you for opening, finding the workaround and posting it here!

**Closed** 2020-01-14 23:45 UTC
Labels: deploy/helm3, kind/bug, priority/p1, triage/duplicate
