### ISSUE TITLE
Debugging With Skaffold

### ISSUE THREAD

**Issue by coolyrat** [GoogleContainerTools/skaffold#3934] opened 2020-04-10 09:08 UTC
How to set up a debug environment in Goland?

info:
I am using cloud code plugin in goland to play.
```bash
~ » skaffold version
v1.7.0
```

skaffold.yaml
```yaml
apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: app
build:
  local: {}
  artifacts:
    - image: app
      custom:
        buildCommand: "make dev_docker"
        dependencies:
          paths:
            - cmd/app
            - sdk
            - internal

deploy:
  kubectl:
    manifests:
      - ./k8s/k8s-deployment.yaml

```
makefile
```makefile
dev_docker:
	go build -gcflags='all=-N -l' -o ./tmp/app ./cmd/app/main.go
	docker build -t app -f Dockerfile ./tmp
```

```Dockerfile
FROM gcr.io/distroless/base
ENV GOTRACEBACK=all
COPY app /app
EXPOSE 3000 3001

CMD ["./app"]
```

I could start up the server, but I am expecting the output below when I  run the "develop on kubernetes" in the debug mode provided by the cloud code plugin.
```
[app-577bc59f76-n9w4w install-go-support] Installing runtime debugging support files in /dbg
[app-577bc59f76-n9w4w install-go-support] Installation complete
```

**Comment by nkubala** [comment] 2020-04-10 18:20
@coolyrat can you give a little more info on what happens when you use the "debug" functionality in cloud code?

is there any reason why you're building using the `custom` builder? you should be able to use the `docker` builder and move your `go build` command inside of your Dockerfile.

**Comment by coolyrat** [comment] 2020-04-11 01:44
@nkubala thanks for the response.

> can you give a little more info on what happens when you use the "debug" functionality in cloud code?

1. when I press the debug button, the debug panel run the command below to start the skaffold workflow
![image](https://user-images.githubusercontent.com/1881159/79031993-86eab280-7bd5-11ea-9ac0-479a1348e082.png)
```bash
/usr/local/bin/skaffold debug --filename skaffold.yaml --label ide=GoLand --label ideVersion=2020.1.0.0 --label ijPluginVersion=unknown --rpc-port 50051 --port-forward=true --enable-rpc=true
```

2. the server started without any warning or error
3. adding a breakpoint
4. fire a request

> is there any reason why you're building using the custom builder? you should be able to use the docker builder and move your go build command inside of your Dockerfile.

I am just trying out different approaches supported by skaffold. I will use local docker daemon + buildkit after.

**Comment by briandealwis** [comment] 2020-04-13 22:05
Hi @coolyrat.  Your Dockerfile looks ideal: the use of `GOTRACEBACK` should be enough for Cloud Code and Skaffold to configure your container for debugging.  Could you please try running that `skaffold` command with `-v debug` and copy the logs here?

**Comment by coolyrat** [comment] 2020-04-18 17:15
Hi, @briandealwis I've upgraded my environment to following:

> ![image](https://user-images.githubusercontent.com/1881159/79644116-69bb7280-81d9-11ea-9d1d-221630516fc9.png)
> skaffold version v1.8.0
> docker for k8s v1.15.5

I finally see the initContainers were injected during the runtime. But there are two problems. 

1. running debug,  the output from the cloud code:
```
/usr/local/bin/skaffold debug --filename skaffold.yaml --label ide=GoLand --label ideVersion=2020.1.0.0 --label ijPluginVersion=unknown --rpc-port 50051 --port-forward=true --status-check=true --enable-rpc=true --verbosity trace
......ignore some output....
Successfully tagged skaffold-test:latest
time="2020-04-19T01:07:16+08:00" level=info msg="Build complete in 2.792145613s"
time="2020-04-19T01:07:16+08:00" level=info msg="Test complete in 418ns"
time="2020-04-19T01:07:16+08:00" level=debug msg="Running command: [kubectl version --client -ojson]"
Tags used in deployment:
 - skaffold-test -> skaffold-test:d9ea4371e99550b83c029b8d63b10fabaff79051030be31e2c5488fae5958728
   local images can't be referenced by digest. They are tagged and referenced by a unique ID instead
Starting deploy...
time="2020-04-19T01:07:16+08:00" level=debug msg="Command output: [{\n  \"clientVersion\": {\n    \"major\": \"1\",\n    \"minor\": \"15\",\n    \"gitVersion\": \"v1.15.5\",\n    \"gitCommit\": \"20c265fef0741dd71a66480e35bd69f18351daea\",\n    \"gitTreeState\": \"clean\",\n    \"buildDate\": \"2019-10-15T19:16:51Z\",\n    \"goVersion\": \"go1.12.10\",\n    \"compiler\": \"gc\",\n    \"platform\": \"darwin/amd64\"\n  }\n}\n]"
time="2020-04-19T01:07:16+08:00" level=debug msg="Running command: [kubectl --context docker-desktop create --dry-run -oyaml -f /Users/luis/go/src/test/skaffold-test/k8s-deployment.yaml]"
Cleaning up...
```
  
2. so I decided to run the command below in the terminal
```
skaffold debug --label ide=GoLand --label ideVersion=2020.1.0.0 --label ijPluginVersion=unknown --rpc-port 50051 --port-forward=true --enable-rpc=true
```

```shell
...ignore the build...
Waiting for deployments to stabilize...
DEBU[0002] getting client config for kubeContext: ``    
DEBU[0002] checking status deployment/skaffold-test     
DEBU[0002] Running command: [kubectl --context docker-desktop rollout status deployment skaffold-test --namespace default --watch=false] 
DEBU[0002] Command output: [Waiting for deployment "skaffold-test" rollout to finish: 0 of 1 updated replicas are available...
] 
DEBU[0009] Running command: [kubectl --context docker-desktop rollout status deployment skaffold-test --namespace default --watch=false] 
DEBU[0009] Command output: [Waiting for deployment "skaffold-test" rollout to finish: 0 of 1 updated replicas are available...
] 
```

the last two lines kept repeating forever.

**Comment by briandealwis** [comment] 2020-04-20 02:44
@coolyrat can you confirm that your app works in the "Run on Kubernetes" (the non-Debug variant)?

Your log from within Cloud Code seems to be missing oodles of statements: at `trace` level, the transformed k8s manifest would be logged shown the debugging support files being mounted on the pod.  When I run `skaffold debug -v info` from [Skaffold's `examples/getting-started`](https://github.com/GoogleContainerTools/skaffold/tree/master/examples/getting-started) I see the following:

```
Tags used in deployment:
 - skaffold-example -> skaffold-example:d05d1b526b77c30ecbeca5bd654662717b9fb3e73aa1b846bcc6693c96c4c43b
   local images can't be referenced by digest. They are tagged and referenced by a unique ID instead
Starting deploy...
INFO[0032] Configuring "getting-started" for Go/Delve debugging 
INFO[0032] "getting-started" requires debugging support image "go" 
INFO[0032] Configuring installation of debugging support files 
 - pod/getting-started created
INFO[0033] Deploy complete in 1.264976085s              
Waiting for deployments to stabilize...
Deployments stabilized in 31.780208ms
Watching for changes...
INFO[0035] Streaming logs from pod: getting-started container: install-go-support 
[getting-started install-go-support] Installing runtime debugging support files in /dbg
[getting-started install-go-support] Installation complete
INFO[0036] Streaming logs from pod: getting-started container: getting-started 
Port forwarding pod/getting-started in namespace default, remote port 56268 -> address 127.0.0.1 port 56268
[getting-started] API server listening at: 127.0.0.1:56268
[getting-started] Hello world!
```

Could you please attach the full log?

You can instruct Skaffold to ignore the deployment status by running `skaffold debug ... --status-check=false`.

**Comment by coolyrat** [comment] 2020-04-20 09:58
> can you confirm that your app works in the "Run on Kubernetes" (the non-Debug variant)?

I used the getting-started example, and It doesn't work. [see the full output](https://gist.github.com/coolyrat/eec39bcacece7b67e88276dc6197ecde). 

![image](https://user-images.githubusercontent.com/1881159/79737481-f5deae80-832d-11ea-8a55-035bd869179d.png)

so I go back to my project and run the command in the terminal. [See the output](https://gist.github.com/coolyrat/f95ef161d6f7fd5bc98a30596a9aafb6).

**Comment by briandealwis** [comment] 2020-04-21 03:54
@coolyrat I should have asked this before but are you developing on macOS?  It would explain why you're encountering the following error:

```
Port forwarding pod/skaffold-test-77d5fc666b-7bbc8 in namespace default, remote port 56268 -> address 127.0.0.1 port 56268
[skaffold-test-77d5fc666b-7bbc8 skaffold-test] API server listening at: 127.0.0.1:56268
[skaffold-test-77d5fc666b-7bbc8 skaffold-test] could not launch process: fork/exec /app: exec format error
```

You can cross-compile a Linux binary with Go, but you need to set `GOOS` like as follows:

	GOOS=linux go build -gcflags='all=-N -l' -o ./tmp/app ./cmd/app/main.go

**Comment by coolyrat** [comment] 2020-04-21 04:07
@briandealwis thank you so much, it worked!

I could start the server, and I started a dlv, I can now debug the application. But when I change the code, It doesn't rebuild.

**Comment by briandealwis** [comment] 2020-04-21 04:20
That's by design as redeploying-on-save has a nasty side-effect of terminating existing pods, and thus kills any debug sessions in progress.  #3272 requests incorporating some hidden options from  `dev` to allow more user control over rebuilds and redeploys.

Closing as this issue is solved.

**Closed by briandealwis** 2020-04-21 04:20 UTC
Labels: area/debug, kind/question
