### ISSUE TITLE
Trigger customised script after Deployment

### ISSUE THREAD

**Issue by kooyear** [GoogleContainerTools/skaffold#2960] opened 2019-09-30 01:50 UTC
### Expected behavior
Is it possible for me to run some scripts after the Deployment step with kubestl. The problem I have is I try to deploy `Replicaset` with Skaffold. But it seems that the `Replicaset` doesn't support rolling update, so I want to delete the old Pods with my script and make sure the pods are created by the latest `Replicaset`, or any better solution I can apply?
### Information

- Skaffold version: version...
- Operating system: ...
- Contents of skaffold.yaml:

```yaml
<paste your skaffold.yaml here>
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>`
3. ...

**Comment by priyawadhwa** [comment] 2019-09-30 17:56
Hey @kooyear -- this is related to #1441. Right now, we don't have any support for scripts after deploy, but we are currently looking into it.

Is there any reason you are using a `ReplicaSet` instead of a `Deployment`? A`Deployment` can do a rolling update. From the Kubernetes docs [here](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/):

**To update Pods to a new spec in a controlled way, use a Deployment, as ReplicaSets do not support a rolling update directly.**

I'm going to close this issue as a dupe of #1441, please comment on that thread with your use case. It would be helpful as we decide how best to proceed with that feature request.

**Closed by priyawadhwa** 2019-09-30 17:56 UTC
