### ISSUE TITLE
v 2.0.4 fails with "unable to decode \"STDIN\": Object 'Kind' is missing" if manifest uses CRLF 

### ISSUE THREAD

**Issue by hellgrenj** [GoogleContainerTools/skaffold#8316] opened 2023-01-12 14:04 UTC
I have a .yaml file that contains this config-map-manifest (with CRLF line endings):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings
data:
  appsettings.k8s.json: |-
   {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "SndSettings": {
        "ApiKey": "",
        "BaseAddress": "REMOVED",
        "AcceptHeaderContentType": "application/json"
      },
      "IdentityServer": {
        "Authority": "REMOVED",
        "Audience": "REMOVED",
        "RequireHttpsMetadata ": false
      }
   }
```
When I run ``skaffold run``  in Powershell in Windows 10 i get the following error:

```
waiting for deletion: running [kubectl --context docker-desktop get -f - --ignore-not-found -ojson]
 - stdout: ""
 - stderr: "error: unable to decode \"STDIN\": Object 'Kind' is missing in '{\"data\":{\"appsettings.k8s.json\":\"{\\n   \\\"Logging\\\": {\\n     \\\"LogLevel\\\": {\\n       \\\"Default\\\": \\\"Information\\\",\\n       \\\"Microsoft.AspNetCore\\\": \\\"Warning\\\"\\n     }\\n   },\\n   \\\"SndSettings\\\": {\\n     \\\"ApiKey\\\": \\\"\\\",\\n     \\\"BaseAddress\\\": \\\"REMOVED\\\",\\n     \\\"AcceptHeaderContentType\\\": \\\"application/json\\\"\\n   },\\n   \\\"IdentityServer\\\": {\\n     \\\"Authority\\\": \\\"REMOVED\\\",\\n     \\\"Audience\\\": \\\"REMOVED\\\",\\n     \\\"RequireHttpsMetadata \\\": false\\n   }\\n}\"}}'\n"
 - cause: exit status 1
 ```

If i just change line endings to LF (I am doing it in VS Code) without changing anything else I dont get this error and everything spins up as expected. I can reproduce this on Ubuntu (WSL2) as well, i.e if i switch to CRLF i get the same error.

If i revert back to v 1.39.4 (and revert the skaffold yaml to the v1 format..) the config-map-manifest above works with CRLF line endings on Windows. 

### Expected behavior

That our config-map-manifest should work with CRLF in v2.0.4 as it does in v.1.39.4 (i.e skaffold run should not fail)

### Actual behavior
skaffold run fails with error:

```
waiting for deletion: running [kubectl --context docker-desktop get -f - --ignore-not-found -ojson]
 - stdout: ""
 - stderr: "error: unable to decode \"STDIN\": Object 'Kind' is missing in '{\"data\":{\"appsettings.k8s.json\":\"{\\n   \\\"Logging\\\": {\\n     \\\"LogLevel\\\": {\\n       \\\"Default\\\": \\\"Information\\\",\\n       \\\"Microsoft.AspNetCore\\\": \\\"Warning\\\"\\n     }\\n   },\\n   \\\"SndSettings\\\": {\\n     \\\"ApiKey\\\": \\\"\\\",\\n     \\\"BaseAddress\\\": \\\"REMOVED\\\",\\n     \\\"AcceptHeaderContentType\\\": \\\"application/json\\\"\\n   },\\n   \\\"IdentityServer\\\": {\\n     \\\"Authority\\\": \\\"REMOVED\\\",\\n     \\\"Audience\\\": \\\"REMOVED\\\",\\n     \\\"RequireHttpsMetadata \\\": false\\n   }\\n}\"}}'\n"
 - cause: exit status 1
 ```
 
### Information

- Skaffold version: v2.0.4 (and 2.0.2)
- Operating system: Windows 10  (and Ubuntu 20.04 in WSL2)
- Installed via: tried both Chocolatey  and by placing .exe in PATH (i.e both version 2.0.2 and 2.04)
- Contents of skaffold.yaml: 

```yaml
apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: api
    context: ./Src/SOMEPROJECT.Api
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
      - ./devops/k8s/local/*.yaml
```

### Steps to reproduce the behavior

1. clone this repo: https://github.com/hellgrenj/hejhopp
2. try locally:

skaffold version 2.0.4
set end of line for manifest.yaml to LF and run skaffold run (and it works)
set end of line for manifest.yaml to CRLF and run skaffold run (and it fails)

skaffold version 1.39.4
set end of line for manifest.yaml to LF and run skaffold run (and it works)
set end of line for manifest.yaml to CRLF and run skaffold run (and it works)

**Comment by aaron-prindle** [comment] 2023-01-12 18:50
related: #8299

**Comment by aaron-prindle** [comment] 2023-01-30 19:24
Thank you for flagging this, closing as a dupe of #8299 (same underlying issue).  We are working on this issue in our `v2.2.0` milestone so this should be fixed next release.

**Closed by aaron-prindle** 2023-01-30 19:24 UTC
Labels: kind/bug, platform/windows, priority/p1, area/render
