### ISSUE TITLE
skaffold init shouldn't leave the user in an infinite loop of suggestions

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#3678] opened 2020-02-11 20:51 UTC
### Expected behavior

* `skaffold init` shouldn't leave the user in an infinite loop of suggestions
* `skaffold init` should have a clearly documented way of operating in a prompt-free way 

### Actual behavior

`skaffold init` leaves the user in an infinite loop of suggestions

- skaffold.yaml exists
- skaffold init 
FATA[0000] pre-existing skaffold.yaml found (you may continue with --force)
- skaffold init --force 
FATA[0001] unable to automatically resolve builder/image pairs; run `skaffold init` without `--force` to manually resolve ambiguities

`skaffold init --force` is currently the prompt-free mode, however: 
- `--force=false: Force the generation of the Skaffold config` is the documentation

**Comment by balopat** [comment] 2020-02-11 20:54
Implementation suggestion: 

Limit `--force` to only file overriding behavior, introduce `--quiet` == `--force + no prompts` - which would behave the same as `--force` today.

**Comment by tstromberg** [comment] 2020-04-30 17:25
Clarifying title, but I'm honestly a bit confused by this issue - it sounds like two issues rolled into one.

**Comment by MarlonGamez** [comment] 2020-11-10 17:39
Closing this as the root cause here is better captured by https://github.com/GoogleContainerTools/skaffold/issues/4912

Feel free to reopen if you feel otherwise!

**Closed by MarlonGamez** 2020-11-10 17:39 UTC
Labels: area/init, kind/feature-request, priority/p2
