### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by osbornk** [GoogleContainerTools/skaffold#7617] opened 2022-06-30 22:18 UTC
### Expected behavior

This should run skaffold without error.

### Actual behavior

I get an index out of range issue whenever I make any non-committed change to a branch and try to skaffold it. I am on v1.39.1, which I believe fixes a similar issue. Downgrading to 1.37.2 solved my problem for now.

### Information

- Skaffold version: 1.39.1
- Operating system: MacOS 12.4
- Installed via: Homebrew
- Contents of skaffold.yaml:

### Steps to reproduce the behavior

2. `skaffold dev`
```
Listing files to watch...
 - xxx.dkr.ecr.us-east-2.amazonaws.com/rails-ruby27
 - xxx.dkr.ecr.us-east-2.amazonaws.com/components
Generating tags...
 - xxx.dkr.ecr.us-east-2.amazonaws.com/rails-ruby27 -> xxx.dkr.ecr.us-east-2.amazonaws.com/rails-ruby27:v2021.03.24-8449-g120ed4eb4e-dirty
 - xxx.dkr.ecr.us-east-2.amazonaws.com/components -> xxx.dkr.ecr.us-east-2.amazonaws.com/components:v2021.03.24-8449-g120ed4eb4e-dirty
Checking cache...
 - xxx.dkr.ecr.us-east-2.amazonaws.com/rails-ruby27: Found. Tagging
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.needsRemoteTagging.Tag({{0xc001004740, 0x40}, {0xc0014aa000, 0x5c}, {0xc0011abe00, 0x47}}, {0x78e1478, 0xc000555e00}, 0xc000b16100, {0xc000718c90})
	/private/tmp/skaffold-20220625-10976-1ij4m21/pkg/skaffold/build/cache/details.go:94 +0x285
github.com/GoogleContainerTools/skaffold/pkg/skaffold/build/cache.(*cache).Build(0xc000b16100, {0x78e13d0, 0xc000316a80}, {0x788cf60, 0xc000181a40}, 0xc000554db0, {0xc000d9bff0, 0x2, 0x2}, {0xc000718c90}, ...)
	/private/tmp/skaffold-20220625-10976-1ij4m21/pkg/skaffold/build/cache/retrieve.go:85 +0x117d
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner.(*Builder).Build(0xc000aae000, {0x78e1478, 0xc000554d50}, {0x788cf60, 0xc000181a40}, {0xc000d9bff0, 0x2, 0x2})
	/private/tmp/skaffold-20220625-10976-1ij4m21/pkg/skaffold/runner/build.go:105 +0xa26
github.com/GoogleContainerTools/skaffold/pkg/skaffold/runner/v1.(*SkaffoldRunner).Dev(0xc000aae000, {0x78e13d0, 0xc0001d2000}, {0x788cf60, 0xc000384050}, {0xc000d9bff0, 0x2, 0x2})
	/private/tmp/skaffold-20220625-10976-1ij4m21/pkg/skaffold/runner/v1/dev.go:306 +0x16e8
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev.func5({0x792f100, 0xc000aae000}, {0xc000f88320, 0x1, 0x1})
	/private/tmp/skaffold-20220625-10976-1ij4m21/cmd/skaffold/app/cmd/dev.go:71 +0x16f
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.withRunner({0x78e13d0, 0xc0001d2000}, {0x788cf60, 0xc000384050}, 0xc0005b5560)
	/private/tmp/skaffold-20220625-10976-1ij4m21/cmd/skaffold/app/cmd/runner.go:55 +0x20d
github.com/GoogleContainerTools/skaffold/cmd/skaffold/app/cmd.runDev({0x78e13d0, 0xc0001d2000}, {0x788cf60, 0xc000384050})
```

**Comment by gsquared94** [comment] 2022-07-01 17:31
There seems to be some issue installing skaffold with brew. Can you try installing the binary directly. See https://github.com/GoogleContainerTools/skaffold/issues/7587#issuecomment-1172566078

**Comment by gsquared94** [comment] 2022-07-01 17:32
Closing as duplicate of https://github.com/GoogleContainerTools/skaffold/issues/7587

**Closed by gsquared94** 2022-07-01 17:32 UTC
