### ISSUE TITLE
Skaffold debug fails with: debug requires at least Helm 3.1 (current: 3.9.0)

### ISSUE THREAD

**Issue by wollowizard** [GoogleContainerTools/skaffold#7583] opened 2022-06-24 04:34 UTC
### Expected behavior
the app is deployed

### Actual behavior
Getting error:
`deploying "xxx": debug requires at least Helm 3.1 (current: 3.9.0)`

### Information

- Skaffold version: 
1.39.0
- Operating system: 
macos monterey 12.4
- Installed via: 
`curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.39.0/skaffold-darwin-arm64 && chmod +x skaffold && sudo mv skaffold /usr/local/bin
`
- Contents of skaffold.yaml:

```yaml
any
```

### Steps to reproduce the behavior

1. a clonable repository with the sample skaffold project
2. `skaffold <command>` skaffold debug
3. ...

**Comment by aaron-prindle** [comment] 2022-06-24 19:15
Dupe of https://github.com/GoogleContainerTools/skaffold/issues/7582, follow that issue for updates.  Closing

**Closed by aaron-prindle** 2022-06-24 19:15 UTC
