### ISSUE TITLE
Feature request: allow default-repo to be set in skaffold.yaml

### ISSUE THREAD

**Issue by ekuefler** [GoogleContainerTools/skaffold#5856] opened 2021-05-17 19:23 UTC
### Expected behavior

I should be able to ask developers to check out my repository and then start working using `skaffold dev` with no further configuration.

### Actual behavior

I have to tell each developer to set `default-repo` according to the instrucitons at https://skaffold.dev/docs/environment/image-registries/. We set `default-repo` the same for each developer, so there's no advantage to making everyone do this.

### Information

- Skaffold version: v1.23.0
- Operating system: Linux
- Installed via: skaffold.dev

**Comment by tejal29** [comment] 2021-05-17 19:56
@ekuefler 
you define the repository as part of your image name in skaffold.yaml.  It will solve half of your problems but not all 
It won't solve the issue for when you want to apply a new default repo per profile. 
We have another issues related to specifying default repo per profile basis.  #2317 

Adding this for our planned work in H2. #5857

**Comment by ekuefler** [comment] 2021-05-17 21:09
Thanks - I think #2317 probably covers what I want. Our manifests and skaffold.yaml currently specify the repository as it appears in production. Developers don't have write access to that repo, so we want to use a separate dev repo for local development.

**Comment by irvifa** [comment] 2021-11-08 08:55
Is this still blocked?

**Comment by gsquared94** [comment] 2021-11-19 15:49
I added this to our triage discussion list

**Comment by tejal29** [comment] 2022-01-10 19:22
removing the triage/discuss. As part of v2 config re-design, an engineer will look into it

**Comment by aaron-prindle** [comment] 2022-11-27 00:22
Marking as dupe of #2317, we'll use that issue to track the discussion/progress on this item.  Closing (dupe)

**Closed by aaron-prindle** 2022-11-27 00:22 UTC
Labels: kind/feature-request, priority/blocked, source/partnerships, planning/Q4-21
