### ISSUE TITLE
Autoload docker machine for minikube profile

### ISSUE THREAD

**Issue by woodcockjosh** [GoogleContainerTools/skaffold#4483] opened 2020-07-16 13:11 UTC
### Feature request
Please lets give the option to autoload a minikube profile. Everytime I open up a new terminal session I have to run
```bash
eval $(minikube docker-env -p trk8s)
```
And I often forget

### Expected behavior
```bash
skaffold run
```
It just works

### Actual behavior
```bash
skaffold run
```
It uses the host's docker machine

```bash
eval $(minikube docker-env -p trk8s)
skaffold run
```
It works

### Information

Example yaml
```yaml
deploy:
  minikube:
    autoload: true
    profile: trk8s
```

**Comment by woodcockjosh** [comment] 2020-07-16 13:14
@tstromberg what are your thoughts on this?

**Comment by briandealwis** [comment] 2020-07-28 03:35
I think this is a duplicate of #3668, which requests support for minikube profiles.

**Closed by briandealwis** 2020-07-28 03:35 UTC
Labels: kind/feature-request, platform/minikube
