### ISSUE TITLE
skaffold labels erroneously added to CRD validation schema metadata field

### ISSUE THREAD

**Issue by andsens** [GoogleContainerTools/skaffold#1737] opened 2019-03-06 16:15 UTC
I am trying to get cert-manager up and running with skaffold+kustomize, but am running into an issue with skaffold adding labels to a CRD manifest. `kustomize build . | kubectl apply -f -` works fine, so I 
think this is skaffold itself. Either it modifies the manifest or kustomize gets some additional flags.

### Expected behavior

The manifest validates.

### Actual behavior

skaffold errors out with:
```
error: error validating "STDIN": error validating data: ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.metadata): unknown field "labels" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
```

### Information

- Skaffold version: v0.24.0
- Operating system: MacOS 10.14.3
- Contents of skaffold.yaml:

```yaml
apiVersion: skaffold/v1beta6
kind: Config
deploy:
  kustomize:
    path: .
```

### Steps to reproduce the behavior

1. `skaffold run` [this gist](https://gist.github.com/andsens/19a7485b753bf303fb3a9d768e457ee4).

### Full log

```
$ skaffold run
Starting build...
Build complete in 40.014µs
Starting test...
Test complete in 7.814µs
Starting deploy...
kubectl client version: 1.13
error: error validating "STDIN": error validating data: ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.metadata): unknown field "labels" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
Deploy complete in 644.45351ms
You can also run [skaffold run --tail] to get the logs
```

**Comment by andsens** [comment] 2019-03-06 16:20
I'm having trouble figuring out what the actual manifest looks like. Is there a way to do a dry-run with skaffold and retrieve the generated manifest?

**Comment by tejal29** [comment] 2019-03-06 18:33
@andsens. Right now, there isnt. But this is good feature to have.
However, you can run `skaffold deploy -v=debug` to see the generated manifests on the command line.

**Comment by andsens** [comment] 2019-03-08 09:41
Yup, found the issue with `-v=debug`:
```
[...]
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          labels:
            cleanup: \"true\"
            skaffold-builder: local
            skaffold-deployer: kustomize
            skaffold-tag-policy: git-commit
            tail: \"true\"
          type: object
        spec:
[...]
```

In the original it looks like this:
```
[...]
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
[...]
```

[Full debug output](https://gist.github.com/andsens/d97f368c3c8b3bea05405339f311574a).

**Comment by nkubala** [comment] 2019-03-11 19:00
yeah, we probably shouldn't be doing this. we're using the k8s dynamic client to apply labels to all k8s objects created with skaffold, but this won't work for CRDs. we'll need to figure out a way to determine if an object was created with a CRD and skip labeling if it was.

**Comment by briandealwis** [comment] 2019-03-13 17:05
I think the code that's doing this is [`ManifestList`'s `SetLabels()`](https://github.com/GoogleContainerTools/skaffold/blob/master/pkg/skaffold/deploy/kubectl/labels.go#L25), which is called from Kustomize:

https://github.com/GoogleContainerTools/skaffold/blob/163f2e893148b8e66be1ab503831f7d334799279/pkg/skaffold/deploy/kustomize.go#L133

This isn't the same as the labeller used in Helm.

**Comment by daniyalj** [comment] 2019-04-24 22:28
running into the same issue. Im deploying rbac-manager with skaffold with the following:

```
$ cat skaffold.yaml 
apiVersion: skaffold/v1beta8
kind: Config
deploy:
  kubectl:
    manifests:
      - manifests/rbac-manager/01-rbac-manager.yaml
```

01-rbac-manager.yaml is [here](https://github.com/reactiveops/rbac-manager/blob/master/deploy/all.yaml)

error is:
```
clusterrole.rbac.authorization.k8s.io/rbac-manager unchanged
clusterrolebinding.rbac.authorization.k8s.io/rbac-manager unchanged
error: error validating "STDIN": error validating data: ValidationError(CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.metadata): unknown field "labels" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
FATA[0000] deploy failed: kubectl apply: exit status 1 
```

**Comment by daniyalj** [comment] 2019-04-24 22:29
Skaffold is creating labels in my crd:

```
kind: CustomResourceDefinition
metadata:
  labels:
    app: rbac-manager
    cleanup: "true"
    docker-api-version: "1.39"
    skaffold-builder: local
    skaffold-deployer: kubectl
    skaffold-tag-policy: git-commit
    tail: "true"
  name: rbacdefinitions.rbacmanager.reactiveops.io
spec:
  group: rbacmanager.reactiveops.io
  names:
    kind: RBACDefinition
    plural: rbacdefinitions
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          labels:
            cleanup: "true"
            docker-api-version: "1.39"
            skaffold-builder: local
            skaffold-deployer: kubectl
            skaffold-tag-policy: git-commit
            tail: "true"
          type: object
        rbacBindings:
          items:
            properties:

```

**Comment by adrienjt** [comment] 2019-05-16 04:37
FWIW, this is a regression. No problem with v0.14.0.

(I've had no reason to upgrade for a long time, decided to upgrade to v0.29.0 to avoid too many changes at once when I do need to upgrade... no luck, I'm going to stick with v0.14.0 a little longer.)

**Comment by nkubala** [comment] 2019-05-21 21:56
turns out this is happening because skaffold is adding labels to **all** sections in any manifest that use `metadata` as the key, including those in the `validation` section for a CRD. obviously this is bad because we should never be touching the CRD validation section.

a fix for this would be checking for `validation` sections when we're recursively parsing the manifest, and skipping those sections outright since we shouldn't be modifying them. PRs welcome as this should be a pretty easy fix, or else I'll try and get to it next week.

**Comment by tejal29** [comment] 2019-05-22 19:02
I have a PR out for this which is in draft right now. https://github.com/GoogleContainerTools/skaffold/pull/2060

**Comment by afirth** [comment] 2019-06-28 15:31
borks kubebuilder :(

**Comment by chainlink** [comment] 2019-08-08 01:45
Looks like this is stalled

**Comment by tejal29** [comment] 2019-09-03 22:13
@chainlink yes. i will try to resurrect this this week.

**Comment by tejal29** [comment] 2019-09-11 16:13
re-opening,
Since implementation is not yet done.

**Comment by zmarouf** [comment] 2019-09-20 10:13
Hitting the same issue. Is there a way to just not add skaffold labels at all?

**Comment by kunickiaj** [comment] 2019-12-19 19:49
Is this coming any closer to resolution?

**Comment by mgoltzsche** [comment] 2019-12-27 18:16
With the logic that is currently in place a `Replacer` could be added that excludes object's containing `kind: CustomResourceDefinition` using a corresponding `Matcher`. However this allows only to exclude CRDs from the transformation completely - not only some parts of it - while I think that it should still be labeled. Also the `Matcher` must be added to every `Replacer` although so far the `Replacer`s are more general and there does not seem to be a need to implement exclusion/preservation rules specific to a particular `Replacer` but to the resource type instead.
Hence I suggest to move the exclusion functionality into a resource type dependent traversal strategy. This would allow the precise definition of exclusions rules. Parts that should be kept untouched would not be traversed. Besides the default implementation (that would not change the current behaviour) a CRD-specialized implementation could be added that only traverses the first-level fields or rather does no recursion. (Having this functionality separated would also allow to simplify the `Replacer` interface which is actually also used as namespace collector currently.)

**Closed** 2020-01-15 05:13 UTC
Labels: CRDs, area/deploy, deploy-labeller, kind/bug, priority/p2

**Comment by rmmcnulty9** [comment] 2020-03-05 20:51
On v1.4.0 I am still seeing this problem when trying to deploy KEDA ScaledObjects (https://keda.sh/scalers/rabbitmq-queue/). Their CRD structure has a `metadata` tag that Skaffold wants to put `labels` on which is invalid for the CRD. 

The skaffold error message is:

```
 - spec.triggers.metadata.labels in body must be of type string: "object"
```

**Comment by rmmcnulty9** [comment] 2020-03-10 13:23
Update: This also happens on v1.5.0

Should this issue be reopened or should I submit a new issue?

**Comment by mgoltzsche** [comment] 2020-03-13 16:49
Currently, in case the resource is not a CRD, the transforming FieldVisitor is wrapped into a decorator that applies it recursively.
To make this more reliable it should be wrapped/recursive only when the resource's kind matches one of a predefined set of kinds that require the recursive transformations.

**Comment by mgoltzsche** [comment] 2020-03-17 00:24
@rmmcnulty9 I've created a corresponding PR #3833.
