### ISSUE TITLE
[v2] skaffold delete followed by skaffold run does not work.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7054] opened 2022-01-25 12:23 UTC
Skaffold v2:

`skaffold delete` does not work after `skaffold run` on the v2 branch.

Steps to reproduce.
1) Run `skaffold run` on v2 branch
```
DEBU[0001] v2 runner invoked                             subtask=-1 task=DevLoop
INFO[0001] manifests hydration will take place in /Users/tejaldesai/workspace/skaffold/integration/examples/getting-started/.kpt-pipeline  subtask=-1 task=DevLoop
```

2)  Run `../../../out/skaffold delete`
```
Cleaning up...
WARN[0001] /Users/tejaldesai/workspace/skaffold/integration/examples/getting-started/.kpt-pipeline/* did not match any file  subtask=-1 task=DevLoop
 - No resources found
 ```

3) There are no files in the kpt hydration directory. 
```
 ls -al .kpt-pipeline
total 0
drwxr-xr-x  2 tejaldesai  primarygroup   64 Jan 25 17:38 .
drwxr-xr-x  8 tejaldesai  primarygroup  256 Jan 25 17:40 ..
```

The pod is getting deployed. 
```
kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
getting-started               1/1     Running   0          12m
```

**Comment by aaron-prindle** [comment] 2022-04-12 21:00
Not sure if something was changed recently but I am currently unable to repro this using `integration/examples/getting-started` (as done in the initial issue text):
```
aprindle@aprindle ~/skaffold/integration/examples/getting-started  [v2-v1.37.0]$ skaff run
Generating tags...
 - skaffold-example -> skaffold-example:v1.37.0-110-g3c097ec44
Checking cache...
 - skaffold-example: Found Locally
Starting test...
Tags used in deployment:
 - skaffold-example -> skaffold-example:716aa26dfba5604cd7d6bc4dbcbcb2821dbf520ed51401b392ed075df490a81d
Starting deploy...
WARN[0002] `deploy.kubectl.manifests` (DEPRECATED) are given, skaffold will skip the `manifests` field. If you expect skaffold to render the resources from the `manifests`, please delete the `deploy.kubectl.manifests` field.  subtask=0 task=Deploy
 - pod/getting-started created
Waiting for deployments to stabilize...
 - pods is ready.
Deployments stabilized in 3.107 seconds
You can also run [skaffold run --tail] to get the logs

aprindle@aprindle ~/skaffold/integration/examples/getting-started  [v2-v1.37.0]$ kubectl get po
NAME              READY   STATUS    RESTARTS   AGE
getting-started   1/1     Running   0          12s
aprindle@aprindle ~/skaffold/integration/examples/getting-started  [v2-v1.37.0]$ skaff delete
Cleaning up...
WARN[0000] `deploy.kubectl.manifests` (DEPRECATED) are given, skaffold will skip the `manifests` field. If you expect skaffold to render the resources from the `manifests`, please delete the `deploy.kubectl.manifests` field.  subtask=-1 task=DevLoop
 - pod "getting-started" deleted
aprindle@aprindle ~/skaffold/integration/examples/getting-started  [v2-v1.37.0]$ kubectl get po
No resources found in default namespace.
```

**Comment by aaron-prindle** [comment] 2022-04-12 21:06
@tejal29 do you have a link to the logs for the failing run?  Currently getting a yaml conversion issue attempting to run the integration test locally
```
aprindle@aprindle ~/skaffold  [v2-v1.37.0]$ INTEGRATION_TEST_ARGS="-run=TestDeployTailDefaultNamespace$" make integration
GOOS=linux GOARCH=amd64 CGO_ENABLED=1 \
    go build -gcflags="all=-N -l" -tags "osusergo netgo static_build release " -ldflags "-X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.version=v1.37.0-110-g3c097ec44-dirty -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.buildDate=2022-04-12T14:05:11Z -X github.com/GoogleContainerTools/skaffold/pkg/skaffold/version.gitCommit=3c097ec4492f456c9f2a75c0e74d053450e3c168 -s -w -extldflags \"-static\"" -o out/skaffold github.com/GoogleContainerTools/skaffold/cmd/skaffold
mkdir -p /usr/local/google/home/aprindle/go/bin
rm -f /usr/local/google/home/aprindle/go/bin/skaffold
cp ./out/skaffold /usr/local/google/home/aprindle/go/bin/skaffold
go test -v github.com/GoogleContainerTools/skaffold/integration/binpack github.com/GoogleContainerTools/skaffold/integration -timeout 50m -run=TestDeployTailDefaultNamespace$
testing: warning: no tests to run
PASS
ok  	github.com/GoogleContainerTools/skaffold/integration/binpack	(cached) [no tests to run]
=== RUN   TestDeployTailDefaultNamespace
    deploy_test.go:153: Running [skaffold deploy --default-repo gcr.io/k8s-skaffold --tail --images busybox:latest --default-repo=] in testdata/deploy-hello-tail
panic: interface conversion: util.VersionedConfig is *v2.SkaffoldConfig, not *v1.SkaffoldConfig


```

**Comment by aaron-prindle** [comment] 2022-04-12 21:19
I am able to repro using the command in the test but actually doing a vanilla `skaffold run` + `skaffold delete` seems to work.  Should likely update the bug title, will dig in more to see what is happening

**Comment by aaron-prindle** [comment] 2022-04-12 21:21
This bug is related to the fact that some kind of yaml defaults, must have changed from v1 -> v2.  Currently the test yaml is:

```
apiVersion: skaffold/v3alpha2
kind: Config
```

Changing this to:
```
apiVersion: skaffold/v3alpha2
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s/pod.yaml
```

resolves this error

**Comment by aaron-prindle** [comment] 2022-04-12 21:26
The current test yaml is from a very old skaffold version:
```
aprindle@aprindle ~/skaffold/integration/testdata/deploy-hello-tail  [main]$ cat skaffold.yaml 
apiVersion: skaffold/v1beta16
kind: Config
```

Is it intended that this should work w/o specifying the manifest(s)?

**Comment by tejal29** [comment] 2022-04-12 21:27
The old style deploy manifests should be removed. I think I have an issue open to delete it. We now have a `kubectl` renderer. 
```
deploy:
  kubectl:
     manifests:

```

The expectation is the below manifest should work.
```
apiVersion: skaffold/v3alpha2
kind: Config
manifests:
   rawYaml:
      - k8s/pod.yaml

```

**Comment by aaron-prindle** [comment] 2022-04-12 21:30
Ah yes I see.  It is broken currently for the new style manifest.  I will see what is happening

**Comment by aaron-prindle** [comment] 2022-04-12 22:15
The issue I saw is that `skaffold run` and `skaffold deploy` do not actually do any rendering.  As such the .kpt-pipeline directory is empty when running both of these commands and the commands do not behave as expected when used in v1.  

I have made the following issues from these observations which are the root cause of this issue:
- #7295 
- #7296

**Comment by aaron-prindle** [comment] 2022-04-19 18:18
`TestDeployTailDefaultNamespace` failing because logs not correctly found (even w/ render phase added):
```
aprindle@aprindle ~/skaffold/integration/testdata/deploy-hello-tail  [v2-fix-7054]$ skaffold deploy --tail
Starting render...
Tags used in deployment:
Starting deploy...
 - pod/busybox-hello created
Waiting for deployments to stabilize...
Deployments stabilized in 414.974841ms
Press Ctrl+C to exit
```
^^ hangs forever w/ no logs even though logs coming from Pod:
```
aprindle@aprindle ~/verify-test $ kubectl logs busybox-hello
Hello world!
Hello world!
Hello world!
Hello world!
Hello world!
Hello world!
Hello world!
Hello world!
Hello world!
Hello world!
Hello world!

```

**Comment by aaron-prindle** [comment] 2022-04-20 19:14
This error was not related to deploy + delete but a combination of:
- #7296 
- #7325 

Closing as this issue is actually encapsulated in those issues

**Closed by aaron-prindle** 2022-04-20 19:14 UTC
Labels: kind/bug, priority/p0, triage/discuss, 2.0.0
