### ISSUE TITLE
skaffold dev - bootstrap scripts

### ISSUE THREAD

**Issue by sasso** [GoogleContainerTools/skaffold#2400] opened 2019-07-03 16:57 UTC
I am working with Skaffold and there are a couple of things that need to be set up in minikube or remote cluster before you can start developing (helm, CRDs, local routes, ...). Would it make sense to extend the skaffold config and add support to execute some custom scripts to bootstrap the development environment when calling `skaffold dev`?

Example:
```
apiVersion: skaffold/v1beta11
kind: Config
dev:
  bootstrapScripts:
    - /usr/local/bin/bootstrap-minikube
    - /usr/local/bin/bootstrap-helm
    - /usr/local/bin/bootstrap-routes
    - ...
```

**Comment by sgammon** [comment] 2019-11-19 19:07
either this or the ability to push manifests as bootstrap items would be great

**Comment by nkubala** [comment] 2020-03-05 00:01
closing as a dupe of https://github.com/GoogleContainerTools/skaffold/issues/1441

**Closed by nkubala** 2020-03-05 00:01 UTC
Labels: area/dev, kind/feature-request, priority/p2
