### ISSUE TITLE
Allow deploy steps to use a configurable context for K8s clusters

### ISSUE THREAD

**Issue by viglesiasce** [GoogleContainerTools/skaffold#104] opened 2018-02-26 21:39 UTC
When deploying, you may want to define a specific cluster to use rather than the one that is configured on the local host.

**Comment by balopat** [comment] 2018-08-21 22:46
closing as a dupe of https://github.com/GoogleContainerTools/skaffold/issues/511

**Closed by balopat** 2018-08-21 22:46 UTC
Labels: area/deploy, feature-request, kubectl, priority/p2
