### ISSUE TITLE
Sample for using skaffold in a CD system.

### ISSUE THREAD

**Issue by dlorenc** [GoogleContainerTools/skaffold#139] opened 2018-03-07 05:39 UTC
We should show how to setup a trigger in GCB or a Jenkins job to do a basic "skaffold run"

**Comment by shravanpn7** [comment] 2018-05-03 17:47
+1

**Comment by bhack** [comment] 2018-07-09 11:48
See also https://github.com/GoogleContainerTools/skaffold/issues/346

**Comment by dgageot** [comment] 2019-01-19 23:50
Duplicate of #346

**Closed by dgageot** 2019-01-19 23:50 UTC
Labels: cloud-builder, documentation, priority/p1
