### ISSUE TITLE
make gcr.io/gcp-dev-tools/duct-tape/go configurable

### ISSUE THREAD

**Issue by coolyrat** [GoogleContainerTools/skaffold#4059] opened 2020-04-30 06:43 UTC
`skaffold debug` is using `gcr.io/gcp-dev-tools/duct-tape/go` in the init container. Is there a way to make this image configurable? The cloud provider I'm using can't pull this image down. I need to smuggle the image and change it into a pullable registry.

**Comment by coolyrat** [comment] 2020-04-30 07:18
I asked my cloud provider, there's no way they can get around the law to pull the image😂

**Comment by dgageot** [comment] 2020-04-30 07:56
This is a duplicate of https://github.com/GoogleContainerTools/skaffold/issues/2679

**Closed by dgageot** 2020-04-30 07:56 UTC
