### ISSUE TITLE
Feature: General deployment plugin

### ISSUE THREAD

**Issue by mumoshu** [GoogleContainerTools/skaffold#170] opened 2018-03-09 05:30 UTC
An alternative approach to #169 would be a more versatile "command" deployment plugin which allows us to glue skaffold with any tool by writing a bash snippet.

We have a bunch of k8s deployment tools these days and each of those have their own sweet spots.
Certainly we won't like to bloat up skaffold's code-base by adding a direct integration for each tool...

**Comment by r2d4** [comment] 2018-03-09 19:09
**tl;dr** We're going to have some deep integrations with a few tools for now, see how it goes, and as the APIs become more stable we can look at adding the bash or external binary escape hatch.

This is definitely something I've thought about and I want to hold off until we have more of an idea of how the builders and deployers are actually going to look. Some of our deploy integration is pretty shallow right now, but our builders have deeper integration (local docker and google cloud builder) and thats the level of integration we're targeting for the implementations we include.

**Comment by balopat** [comment] 2019-09-20 23:34
Closing this as a dupe of https://github.com/GoogleContainerTools/skaffold/issues/2277 where we will track this feature request.

**Closed by balopat** 2019-09-20 23:34 UTC
Labels: area/deploy, kind/feature-request
